{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connected","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/connected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/connected"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"connected","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusConnected"}],"symbolKind":"case","modules":[{"name":"ConnectSDK"}],"title":"PGCloudConnectionStatus.connected","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGCloudConnectionStatus@PGCloudConnectionStatusConnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"connected","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/connected":{"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/connected","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connected"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusConnected"}],"abstract":[],"role":"symbol","title":"PGCloudConnectionStatus.connected","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCloudConnectionStatus"}],"type":"topic","navigatorTitle":[{"text":"PGCloudConnectionStatus","kind":"identifier"}],"abstract":[{"text":"Connection status to Insight portal","type":"text"}],"role":"symbol","title":"PGCloudConnectionStatus","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PGCloudConnectionStatusConnected","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGCloudConnectionStatusConnected"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGCloudConnectionStatusConnected"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connected\/title","value":"PGCloudConnectionStatusConnected","op":"replace"},{"op":"replace","value":[{"text":"PGCloudConnectionStatusConnected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connected\/fragments"},{"value":"PGCloudConnectionStatus","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}