{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connecting"},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"PGCloudConnectionStatusConnecting","kind":"identifier"}],"role":"symbol","title":"PGCloudConnectionStatus.connecting","externalID":"c:@M@ConnectSDK@E@PGCloudConnectionStatus@PGCloudConnectionStatusConnecting","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connecting","kind":"identifier"}],"symbolKind":"case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/connecting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/connecting"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connecting"}],"languages":["swift"]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/connecting":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"type":"topic","abstract":[],"title":"PGCloudConnectionStatus.connecting","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusConnecting"}],"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/connecting","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCloudConnectionStatus","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus","abstract":[{"type":"text","text":"Connection status to Insight portal"}],"navigatorTitle":[{"text":"PGCloudConnectionStatus","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","title":"PGCloudConnectionStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"PGCloudConnectionStatusConnecting","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"PGCloudConnectionStatusConnecting","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PGCloudConnectionStatusConnecting","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"PGCloudConnectionStatusConnecting","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connecting\/title"},{"value":[{"kind":"identifier","text":"PGCloudConnectionStatusConnecting"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connecting\/fragments","op":"replace"},{"op":"replace","value":"PGCloudConnectionStatus","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/fragments","value":[{"text":"PGCloudConnectionStatus","kind":"identifier"}]}]}]}