{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/disconnected"},"metadata":{"roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGCloudConnectionStatus@PGCloudConnectionStatusDisconnected","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusDisconnected"}],"role":"symbol","title":"PGCloudConnectionStatus.disconnected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnected","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/disconnected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/disconnected"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/disconnected":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusDisconnected"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/disconnected","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/disconnected","title":"PGCloudConnectionStatus.disconnected","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnected"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCloudConnectionStatus","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus","abstract":[{"type":"text","text":"Connection status to Insight portal"}],"navigatorTitle":[{"text":"PGCloudConnectionStatus","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","title":"PGCloudConnectionStatus"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGCloudConnectionStatusDisconnected","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionStatusDisconnected"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"PGCloudConnectionStatusDisconnected","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"PGCloudConnectionStatusDisconnected","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1disconnected\/title"},{"value":[{"kind":"identifier","text":"PGCloudConnectionStatusDisconnected"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1disconnected\/fragments","op":"replace"},{"op":"replace","value":"PGCloudConnectionStatus","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}