{"sections":[],"metadata":{"modules":[{"name":"ConnectSDK"}],"symbolKind":"case","title":"PGCloudConnectionStatus.error","externalID":"c:@M@ConnectSDK@E@PGCloudConnectionStatus@PGCloudConnectionStatusError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"role":"symbol","navigatorTitle":[{"text":"PGCloudConnectionStatusError","kind":"identifier"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus"]]},"variants":[{"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus\/error"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/error"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus":{"abstract":[{"text":"Connection status to Insight portal","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatus"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus","title":"PGCloudConnectionStatus","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudConnectionStatus","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/error":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"title":"PGCloudConnectionStatus.error","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusError"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/error","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/error"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"PGCloudConnectionStatusError","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"PGCloudConnectionStatusError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"PGCloudConnectionStatusError","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"PGCloudConnectionStatus","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionStatus"}]},{"value":"PGCloudConnectionStatusError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1error\/title"},{"value":[{"text":"PGCloudConnectionStatusError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1error\/fragments","op":"replace"}]}]}