{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorMissingData","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"PGConfigurationApiError.apiErrorMissingData","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorApiErrorMissingData","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"apiErrorMissingData","kind":"identifier"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorApiErrorMissingData","kind":"identifier"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiErrorMissingData","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"No data at given path."}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/apierrormissingdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/apierrormissingdata"]}],"kind":"symbol","sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"navigatorTitle":[{"text":"PGConfigurationApiError","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"PG configuration api error codes"}],"title":"PGConfigurationApiError","url":"\/documentation\/connectsdk\/pgconfigurationapierror","type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGConfigurationApiError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/apiErrorMissingData":{"abstract":[{"type":"text","text":"No data at given path."}],"role":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/apierrormissingdata","navigatorTitle":[{"text":"PGConfigurationApiErrorApiErrorMissingData","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorMissingData","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiErrorMissingData","kind":"identifier"}],"kind":"symbol","title":"PGConfigurationApiError.apiErrorMissingData"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PGConfigurationApiErrorApiErrorMissingData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PGConfigurationApiErrorApiErrorMissingData","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PGConfigurationApiErrorApiErrorMissingData","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGConfigurationApiError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGConfigurationApiError"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorMissingData\/title","value":"PGConfigurationApiErrorApiErrorMissingData","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorMissingData\/fragments","value":[{"text":"PGConfigurationApiErrorApiErrorMissingData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}