{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiErrorFailToParse"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/apierrorfailtoparse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/apierrorfailtoparse"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"abstract":[{"type":"text","text":"Fail to parse data into Wapi object."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorFailToParse"},"kind":"symbol","sections":[],"metadata":{"title":"PGConfigurationApiError.apiErrorFailToParse","externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorApiErrorFailToParse","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"apiErrorFailToParse","kind":"identifier"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorApiErrorFailToParse","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/apiErrorFailToParse":{"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorApiErrorFailToParse"}],"title":"PGConfigurationApiError.apiErrorFailToParse","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorFailToParse","abstract":[{"text":"Fail to parse data into Wapi object.","type":"text"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/apierrorfailtoparse","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiErrorFailToParse"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"role":"symbol","navigatorTitle":[{"text":"PGConfigurationApiError","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"PG configuration api error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationApiError"}],"title":"PGConfigurationApiError","url":"\/documentation\/connectsdk\/pgconfigurationapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGConfigurationApiErrorApiErrorFailToParse","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiErrorApiErrorFailToParse"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PGConfigurationApiErrorApiErrorFailToParse","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorFailToParse\/title","op":"replace","value":"PGConfigurationApiErrorApiErrorFailToParse"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorFailToParse\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiErrorApiErrorFailToParse"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","value":"PGConfigurationApiError","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiError"}],"op":"replace"}]}]}