{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"abstract":[{"type":"text","text":"Configuration id nil."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idNil","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/idNil"},"kind":"symbol","variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/idnil"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/idnil"]}],"metadata":{"externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorIdNil","symbolKind":"case","title":"PGConfigurationApiError.idNil","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idNil","kind":"identifier"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorIdNil"}]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationApiError"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiError"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror","title":"PGConfigurationApiError","abstract":[{"type":"text","text":"PG configuration api error codes"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/idNil":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idNil"}],"title":"PGConfigurationApiError.idNil","abstract":[{"type":"text","text":"Configuration id nil."}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/idnil","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/idNil","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PGConfigurationApiErrorIdNil","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGConfigurationApiErrorIdNil"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PGConfigurationApiErrorIdNil","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"PGConfigurationApiErrorIdNil"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","op":"replace","value":"PGConfigurationApiError"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","op":"replace","value":[{"text":"PGConfigurationApiError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1idNil\/title","value":"PGConfigurationApiErrorIdNil","op":"replace"},{"value":[{"kind":"identifier","text":"PGConfigurationApiErrorIdNil"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1idNil\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}