{"abstract":[{"type":"text","text":"Missing profile id."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingProfileId"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorMissingProfileId","role":"symbol","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ConnectSDK"}],"title":"PGConfigurationApiError.missingProfileId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingProfileId"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorMissingProfileId","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfileId"},"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofileid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofileid"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingProfileId":{"type":"topic","navigatorTitle":[{"text":"PGConfigurationApiErrorMissingProfileId","kind":"identifier"}],"title":"PGConfigurationApiError.missingProfileId","abstract":[{"text":"Missing profile id.","type":"text"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofileid","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfileId","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingProfileId"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"role":"symbol","navigatorTitle":[{"text":"PGConfigurationApiError","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"PG configuration api error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationApiError"}],"title":"PGConfigurationApiError","url":"\/documentation\/connectsdk\/pgconfigurationapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"PGConfigurationApiErrorMissingProfileId","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PGConfigurationApiErrorMissingProfileId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PGConfigurationApiErrorMissingProfileId","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfileId\/title","op":"replace","value":"PGConfigurationApiErrorMissingProfileId"},{"value":[{"text":"PGConfigurationApiErrorMissingProfileId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfileId\/fragments"},{"value":"PGConfigurationApiError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","value":[{"text":"PGConfigurationApiError","kind":"identifier"}]}]}]}