{"kind":"symbol","abstract":[{"type":"text","text":"Configuration manifest not present in the configuration file."}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingManifest","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingmanifest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingmanifest"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingManifest"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingManifest"}],"role":"symbol","title":"PGConfigurationApiError.missingManifest","externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorMissingManifest"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingManifest"}],"languages":["swift"]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"title":"PGConfigurationApiError","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiError"}],"abstract":[{"type":"text","text":"PG configuration api error codes"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationApiError"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingManifest":{"abstract":[{"type":"text","text":"Configuration manifest not present in the configuration file."}],"type":"topic","title":"PGConfigurationApiError.missingManifest","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingManifest"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorMissingManifest","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingManifest","role":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingmanifest","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGConfigurationApiErrorMissingManifest"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"PGConfigurationApiErrorMissingManifest","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingManifest"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGConfigurationApiError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","value":[{"text":"PGConfigurationApiError","kind":"identifier"}]},{"value":"PGConfigurationApiErrorMissingManifest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingManifest\/title","op":"replace"},{"op":"replace","value":[{"text":"PGConfigurationApiErrorMissingManifest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingManifest\/fragments"}]}]}