{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingDefaultProfile"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingdefaultprofile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingdefaultprofile"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingDefaultProfile","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration missing default profile."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingDefaultProfile"}],"title":"PGConfigurationApiError.missingDefaultProfile","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorMissingDefaultProfile","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingDefaultProfile"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"role":"symbol","title":"PGConfigurationApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationApiError"}],"abstract":[{"type":"text","text":"PG configuration api error codes"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiError"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingDefaultProfile":{"role":"symbol","title":"PGConfigurationApiError.missingDefaultProfile","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingDefaultProfile"}],"abstract":[{"type":"text","text":"Configuration missing default profile."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingDefaultProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingDefaultProfile"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingdefaultprofile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGConfigurationApiErrorMissingDefaultProfile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingDefaultProfile"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingDefaultProfile"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","value":"PGConfigurationApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingDefaultProfile\/title","value":"PGConfigurationApiErrorMissingDefaultProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingDefaultProfile\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingDefaultProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}