{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"missingProfile","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofile"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofile"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfile"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The configuration profile not found.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"metadata":{"title":"PGConfigurationApiError.missingProfile","externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorMissingProfile","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingProfile"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"missingProfile","kind":"identifier"}]},"kind":"symbol","sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingProfile":{"title":"PGConfigurationApiError.missingProfile","type":"topic","abstract":[{"text":"The configuration profile not found.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingProfile"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofile","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingProfile"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfile"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationApiError"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiError"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror","title":"PGConfigurationApiError","abstract":[{"type":"text","text":"PG configuration api error codes"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"PGConfigurationApiErrorMissingProfile","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingProfile"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingProfile"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfile\/title","op":"replace","value":"PGConfigurationApiErrorMissingProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfile\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingProfile"}]},{"value":"PGConfigurationApiError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGConfigurationApiError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}