{"metadata":{"externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError@PGConfigurationApiErrorProfileMissingDocument","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"profileMissingDocument","kind":"identifier"}],"role":"symbol","symbolKind":"case","title":"PGConfigurationApiError.profileMissingDocument","roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorProfileMissingDocument","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/profilemissingdocument"]},{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror\/profilemissingdocument"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileMissingDocument"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Configuration profile missing document.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/profileMissingDocument"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"navigatorTitle":[{"text":"PGConfigurationApiError","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"PG configuration api error codes"}],"title":"PGConfigurationApiError","url":"\/documentation\/connectsdk\/pgconfigurationapierror","type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGConfigurationApiError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/profileMissingDocument":{"title":"PGConfigurationApiError.profileMissingDocument","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/profilemissingdocument","kind":"symbol","abstract":[{"type":"text","text":"Configuration profile missing document."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/profileMissingDocument","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileMissingDocument"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorProfileMissingDocument","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGConfigurationApiErrorProfileMissingDocument"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"PGConfigurationApiErrorProfileMissingDocument","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"PGConfigurationApiErrorProfileMissingDocument"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","op":"replace","value":"PGConfigurationApiError"},{"value":[{"text":"PGConfigurationApiError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1profileMissingDocument\/title","op":"replace","value":"PGConfigurationApiErrorProfileMissingDocument"},{"op":"replace","value":[{"text":"PGConfigurationApiErrorProfileMissingDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1profileMissingDocument\/fragments"}]}]}