{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pglogflag\/verbose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pglogflag\/verbose"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/verbose","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Verbose log flag - used for very verbose debugging"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"title":"PGLogFlag.verbose","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGLogFlag@PGLogFlagVerbose","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogFlagVerbose"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/verbose":{"role":"symbol","title":"PGLogFlag.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[{"type":"text","text":"Verbose log flag - used for very verbose debugging"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGLogFlagVerbose"}],"url":"\/documentation\/connectsdk\/pglogflag\/verbose"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag":{"role":"symbol","title":"PGLogFlag","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGLogFlag"}],"abstract":[{"type":"text","text":"Log flags, used to determine the severity of a log message"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGLogFlag"}],"url":"\/documentation\/connectsdk\/pglogflag"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGLogFlagVerbose"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGLogFlagVerbose"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGLogFlagVerbose"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1verbose\/title","value":"PGLogFlagVerbose"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1verbose\/fragments","value":[{"kind":"identifier","text":"PGLogFlagVerbose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/title","value":"PGLogFlag"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/fragments","value":[{"kind":"identifier","text":"PGLogFlag"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}