{"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/warning","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pglogflag\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pglogflag\/warning"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"warning","kind":"identifier"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Warning log flag - used for less severe, recoverable problems"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGLogFlag@PGLogFlagWarning","modules":[{"name":"ConnectSDK"}],"role":"symbol","roleHeading":"Case","title":"PGLogFlag.warning","symbolKind":"case","navigatorTitle":[{"text":"PGLogFlagWarning","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/warning":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogFlagWarning"}],"abstract":[{"type":"text","text":"Warning log flag - used for less severe, recoverable problems"}],"title":"PGLogFlag.warning","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/warning","type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pglogflag\/warning"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag":{"navigatorTitle":[{"kind":"identifier","text":"PGLogFlag"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGLogFlag","kind":"identifier"}],"kind":"symbol","title":"PGLogFlag","abstract":[{"type":"text","text":"Log flags, used to determine the severity of a log message"}],"url":"\/documentation\/connectsdk\/pglogflag","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGLogFlagWarning"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGLogFlagWarning"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGLogFlagWarning"}]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1warning\/title","op":"replace","value":"PGLogFlagWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1warning\/fragments","value":[{"text":"PGLogFlagWarning","kind":"identifier"}]},{"op":"replace","value":"PGLogFlag","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/fragments","value":[{"text":"PGLogFlag","kind":"identifier"}]}]}]}