{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"managerDidUpdateState","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"manager"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGManager"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"manager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The manager whose state has changed."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Invoked whenever the manager’s state has been updated. Commands should only be issued when the state is","type":"text"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn"},{"text":". A state below ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn","type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"implies that scanning has stopped and any connected peripherals have been disconnected. If the state moves below"},{"type":"text","text":" "},{"type":"text","text":"PGCentral"},{"text":" objects obtained from this","type":"text"},{"text":" ","type":"text"},{"text":"manager become invalid and must be retrieved or discovered again.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"See: "},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","type":"reference","isActive":true}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate\/managerDidUpdateState(_:)"},"variants":[{"paths":["\/documentation\/connectsdk\/pgmanagerdelegate\/managerdidupdatestate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgmanagerdelegate\/managerdidupdatestate(_:)"]}],"kind":"symbol","metadata":{"externalID":"c:@M@ConnectSDK@objc(pl)PGManagerDelegate(im)managerDidUpdateState:","roleHeading":"Instance Method","required":true,"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"managerDidUpdateState:","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"managerDidUpdateState","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGManager","kind":"typeIdentifier","text":"PGManager"},{"text":")","kind":"text"}],"title":"managerDidUpdateState(_:)"},"abstract":[{"text":"centralManagerDidUpdateState:","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGManager"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PGManager","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanager","title":"PGManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","kind":"symbol","abstract":[{"type":"text","text":"PGManager"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerDelegate/managerDidUpdateState(_:)":{"type":"topic","title":"managerDidUpdateState(_:)","required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"managerDidUpdateState"},{"kind":"text","text":"("},{"text":"PGManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGManager"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"managerDidUpdateState:","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerdelegate\/managerdidupdatestate(_:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate\/managerDidUpdateState(_:)","abstract":[{"type":"text","text":"centralManagerDidUpdateState:"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/poweredOn":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn","abstract":[{"text":"Bluetooth is currently powered on and available to use.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"poweredOn","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGManagerStatePoweredOn"}],"title":"PGManagerState.poweredOn","url":"\/documentation\/connectsdk\/pgmanagerstate\/poweredon"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGManagerDelegate","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerdelegate","navigatorTitle":[{"text":"PGManagerDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PGManagerDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","abstract":[{"text":"The delegate of a {@link PGManager} object must adopt the ","type":"text"},{"type":"text","text":"PGManagerDelegate"},{"type":"text","text":" protocol. The"},{"type":"text","text":" "},{"text":"single required method indicates the availability of the manager.","type":"text"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate","abstract":[{"text":"Represents the current state of a PGManager.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","kind":"symbol","type":"topic","title":"PGManagerState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGManagerState","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"managerDidUpdateState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"managerDidUpdateState:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"managerDidUpdateState:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGManager","text":"PGManager"},{"text":" *) ","kind":"text"},{"text":"manager","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/title","value":"PGManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/fragments","value":[{"kind":"identifier","text":"PGManager"}]},{"op":"replace","value":"managerDidUpdateState:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate~1managerDidUpdateState(_:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate~1managerDidUpdateState(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"managerDidUpdateState:","kind":"identifier"}],"op":"replace"},{"value":"PGManagerStatePoweredOn","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOn\/title"},{"value":[{"kind":"identifier","text":"PGManagerStatePoweredOn"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOn\/fragments","op":"replace"},{"value":"PGManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/title"},{"value":[{"kind":"identifier","text":"PGManagerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title","value":"PGManagerState","op":"replace"},{"op":"replace","value":[{"text":"PGManagerState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}