{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/error"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback\/error"]},{"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"]]},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedbackError"}],"externalID":"c:@M@ConnectSDK@E@PGPredefinedFeedback@PGPredefinedFeedbackError","title":"PGPredefinedFeedback.error"},"abstract":[{"type":"text","text":"A negative Feedback."}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/error":{"type":"topic","url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/error","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"title":"PGPredefinedFeedback.error","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/error","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedbackError"}],"abstract":[{"text":"A negative Feedback.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"type":"topic","title":"PGPredefinedFeedback","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","url":"\/documentation\/connectsdk\/pgpredefinedfeedback","abstract":[{"type":"text","text":"Feedback enum"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPredefinedFeedback"}],"navigatorTitle":[{"text":"PGPredefinedFeedback","kind":"identifier"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGPredefinedFeedbackError","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPredefinedFeedbackError"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGPredefinedFeedbackError"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGPredefinedFeedbackError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1error\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGPredefinedFeedbackError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1error\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title","value":"PGPredefinedFeedback"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPredefinedFeedback"}]}]}]}