{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Special Feedback (Purple)."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"special2","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special2","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback\/special2"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback\/special2"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"]]},"kind":"symbol","metadata":{"modules":[{"name":"ConnectSDK"}],"roleHeading":"Case","navigatorTitle":[{"text":"PGPredefinedFeedbackSpecial2","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGPredefinedFeedback@PGPredefinedFeedbackSpecial2","role":"symbol","title":"PGPredefinedFeedback.special2","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"special2"}]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/special2":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special2","navigatorTitle":[{"text":"PGPredefinedFeedbackSpecial2","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/special2","title":"PGPredefinedFeedback.special2","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"special2"}],"kind":"symbol","abstract":[{"text":"Special Feedback (Purple).","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"title":"PGPredefinedFeedback","url":"\/documentation\/connectsdk\/pgpredefinedfeedback","abstract":[{"text":"Feedback enum","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPredefinedFeedback","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"PGPredefinedFeedbackSpecial2","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial2"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PGPredefinedFeedbackSpecial2","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"PGPredefinedFeedbackSpecial2","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special2\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special2\/fragments","value":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial2"}],"op":"replace"},{"op":"replace","value":"PGPredefinedFeedback","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments","value":[{"kind":"identifier","text":"PGPredefinedFeedback"}]}]}]}