{"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"PGPredefinedFeedbackSpecial1","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGPredefinedFeedback@PGPredefinedFeedbackSpecial1","modules":[{"name":"ConnectSDK"}],"title":"PGPredefinedFeedback.special1","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"special1","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback\/special1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback\/special1"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"]]},"abstract":[{"type":"text","text":"Special Feedback (Yellow)."}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special1","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"special1"}]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPredefinedFeedback"}],"navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","role":"symbol","type":"topic","title":"PGPredefinedFeedback","url":"\/documentation\/connectsdk\/pgpredefinedfeedback","abstract":[{"text":"Feedback enum","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/special1":{"abstract":[{"text":"Special Feedback (Yellow).","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special1","role":"symbol","url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/special1","title":"PGPredefinedFeedback.special1","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"special1"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGPredefinedFeedbackSpecial1","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial1"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"PGPredefinedFeedbackSpecial1","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGPredefinedFeedback","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments","value":[{"text":"PGPredefinedFeedback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special1\/title","value":"PGPredefinedFeedbackSpecial1","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special1\/fragments","value":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial1"}],"op":"replace"}]}]}