{"abstract":[{"type":"text","text":"All log level - All messages will be logged"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ConnectSDK@E@PGLogLevel@PGLogLevelAll","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"all"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGLogLevelAll"}],"modules":[{"name":"ConnectSDK"}],"symbolKind":"case","title":"PGLogLevel.all"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/all","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pgloglevel\/all"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgloglevel\/all"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"all","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogLevel"}],"url":"\/documentation\/connectsdk\/pgloglevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/all":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgloglevel\/all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"all","kind":"identifier"}],"abstract":[{"text":"All log level - All messages will be logged","type":"text"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/all","title":"PGLogLevel.all","role":"symbol","navigatorTitle":[{"text":"PGLogLevelAll","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PGLogLevelAll","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGLogLevelAll","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGLogLevelAll"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title","op":"replace","value":"PGLogLevel"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1all\/title","value":"PGLogLevelAll"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1all\/fragments","value":[{"text":"PGLogLevelAll","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}