{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/error","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ConnectSDK@E@PGLogLevel@PGLogLevelError","modules":[{"name":"ConnectSDK"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGLogLevelError"}],"title":"PGLogLevel.error","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Error log level - only errors will be logged","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgloglevel\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgloglevel\/error"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/error":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Error log level - only errors will be logged"}],"title":"PGLogLevel.error","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/error","navigatorTitle":[{"text":"PGLogLevelError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"url":"\/documentation\/connectsdk\/pgloglevel\/error","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGLogLevel","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgloglevel","navigatorTitle":[{"kind":"identifier","text":"PGLogLevel"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"PGLogLevelError","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"PGLogLevelError"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGLogLevelError"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1error\/title","value":"PGLogLevelError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1error\/fragments","value":[{"kind":"identifier","text":"PGLogLevelError"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title","op":"replace","value":"PGLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments","value":[{"text":"PGLogLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}