{"metadata":{"modules":[{"name":"ConnectSDK"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PGLogLevelInfo"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGLogLevel@PGLogLevelInfo","title":"PGLogLevel.info"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgloglevel\/info"]},{"paths":["\/documentation\/connectsdk\/pgloglevel\/info"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/info"},"abstract":[{"type":"text","text":"Info log level - errors, warnings and info will be logged"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGLogLevel","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pgloglevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}],"navigatorTitle":[{"text":"PGLogLevel","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/info":{"role":"symbol","navigatorTitle":[{"text":"PGLogLevelInfo","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Info log level - errors, warnings and info will be logged"}],"url":"\/documentation\/connectsdk\/pgloglevel\/info","title":"PGLogLevel.info","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/info"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"PGLogLevelInfo","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGLogLevelInfo","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PGLogLevelInfo","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title","value":"PGLogLevel"},{"op":"replace","value":[{"text":"PGLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1info\/title","op":"replace","value":"PGLogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1info\/fragments","value":[{"text":"PGLogLevelInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}