{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgloglevel\/off"]},{"paths":["\/documentation\/connectsdk\/pgloglevel\/off"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/off","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ConnectSDK"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"off"}],"navigatorTitle":[{"text":"PGLogLevelOff","kind":"identifier"}],"title":"PGLogLevel.off","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGLogLevel@PGLogLevelOff"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Off log level - no messages will be logged"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGLogLevel","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgloglevel","navigatorTitle":[{"kind":"identifier","text":"PGLogLevel"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/off":{"type":"topic","url":"\/documentation\/connectsdk\/pgloglevel\/off","role":"symbol","abstract":[{"text":"Off log level - no messages will be logged","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"off"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogLevelOff"}],"title":"PGLogLevel.off","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/off","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGLogLevelOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"PGLogLevelOff"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"PGLogLevelOff","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGLogLevel","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments","value":[{"kind":"identifier","text":"PGLogLevel"}]},{"op":"replace","value":"PGLogLevelOff","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1off\/title"},{"value":[{"text":"PGLogLevelOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1off\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}