{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"verbose","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Verbose log level - errors, warnings, info, debug and verbose will be logged","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/verbose"},"metadata":{"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"PGLogLevel.verbose","navigatorTitle":[{"text":"PGLogLevelVerbose","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGLogLevel@PGLogLevelVerbose","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verbose","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgloglevel\/verbose"]},{"paths":["\/documentation\/connectsdk\/pgloglevel\/verbose"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/verbose":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGLogLevelVerbose"}],"type":"topic","abstract":[{"type":"text","text":"Verbose log level - errors, warnings, info, debug and verbose will be logged"}],"url":"\/documentation\/connectsdk\/pgloglevel\/verbose","title":"PGLogLevel.verbose","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"verbose","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/verbose"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGLogLevel","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pgloglevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}],"navigatorTitle":[{"text":"PGLogLevel","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGLogLevelVerbose"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGLogLevelVerbose"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGLogLevelVerbose"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"PGLogLevelVerbose","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1verbose\/title"},{"value":[{"kind":"identifier","text":"PGLogLevelVerbose"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1verbose\/fragments","op":"replace"},{"value":"PGLogLevel","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title","op":"replace"},{"value":[{"text":"PGLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}