{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/warning"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgloglevel\/warning"]},{"paths":["\/documentation\/connectsdk\/pgloglevel\/warning"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"ConnectSDK"}],"title":"PGLogLevel.warning","role":"symbol","externalID":"c:@M@ConnectSDK@E@PGLogLevel@PGLogLevelWarning","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"warning","kind":"identifier"}],"navigatorTitle":[{"text":"PGLogLevelWarning","kind":"identifier"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]}]}],"abstract":[{"text":"Warning log level - errors and warnings will be logged","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGLogLevel","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgloglevel","navigatorTitle":[{"kind":"identifier","text":"PGLogLevel"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/warning":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/warning","kind":"symbol","abstract":[{"type":"text","text":"Warning log level - errors and warnings will be logged"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGLogLevelWarning"}],"title":"PGLogLevel.warning","url":"\/documentation\/connectsdk\/pgloglevel\/warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGLogLevelWarning"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"PGLogLevelWarning"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGLogLevelWarning"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PGLogLevel","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title"},{"value":[{"text":"PGLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments","op":"replace"},{"value":"PGLogLevelWarning","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1warning\/title"},{"value":[{"kind":"identifier","text":"PGLogLevelWarning"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1warning\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}