{"abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorCorrectionLevel","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel","text":"PGPairingQRGeneratorErrorCorrectionLevel","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default value is PGPairingQRGeneratorErrorCorrectionLevelM"}]}]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/errorcorrectionlevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/errorcorrectionlevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/errorCorrectionLevel","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ConnectSDK"}],"title":"errorCorrectionLevel","externalID":"c:@M@ConnectSDK@objc(cs)PGPairingQRGeneratorOptions(py)errorCorrectionLevel","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCorrectionLevel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"navigatorTitle":[{"text":"errorCorrectionLevel","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"abstract":[{"text":"The PG Pairing QR error correction level","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"title":"PGPairingQRGeneratorErrorCorrectionLevel","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"type":"topic","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/errorCorrectionLevel":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/errorCorrectionLevel","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/errorcorrectionlevel","title":"errorCorrectionLevel","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCorrectionLevel"},{"text":": ","kind":"text"},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel"}],"navigatorTitle":[{"text":"errorCorrectionLevel","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions","title":"PGPairingQRGeneratorOptions","abstract":[{"type":"text","text":"Options for generating QR pairing image"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"errorCorrectionLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"errorCorrectionLevel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCorrectionLevel"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title","value":"PGPairingQRGeneratorErrorCorrectionLevel"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"op":"replace"},{"value":"errorCorrectionLevel","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1errorCorrectionLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"errorCorrectionLevel"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1errorCorrectionLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/title","value":"PGPairingQRGeneratorOptions"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/fragments","op":"replace","value":[{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}