{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullDiscoveryHandshakeEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Default value is true.","type":"text"},{"type":"text","text":" "},{"text":"If set to false the indicator can’t be longer than 8 characters.","type":"text"}]}]}],"metadata":{"navigatorTitle":[{"text":"fullDiscoveryHandshakeEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fullDiscoveryHandshakeEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGPairingQRGeneratorOptions(py)fullDiscoveryHandshakeEnabled","role":"symbol","title":"fullDiscoveryHandshakeEnabled","symbolKind":"property","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/fulldiscoveryhandshakeenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/fulldiscoveryhandshakeenabled"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/fullDiscoveryHandshakeEnabled"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions"]]},"sections":[],"abstract":[{"text":"Enable full discover handshake","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/fullDiscoveryHandshakeEnabled":{"navigatorTitle":[{"kind":"identifier","text":"fullDiscoveryHandshakeEnabled"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/fulldiscoveryhandshakeenabled","abstract":[{"text":"Enable full discover handshake","type":"text"}],"type":"topic","title":"fullDiscoveryHandshakeEnabled","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/fullDiscoveryHandshakeEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullDiscoveryHandshakeEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions":{"title":"PGPairingQRGeneratorOptions","abstract":[{"text":"Options for generating QR pairing image","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"fullDiscoveryHandshakeEnabled"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"fullDiscoveryHandshakeEnabled"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"fullDiscoveryHandshakeEnabled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1fullDiscoveryHandshakeEnabled\/title","value":"fullDiscoveryHandshakeEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1fullDiscoveryHandshakeEnabled\/fragments","value":[{"kind":"identifier","text":"fullDiscoveryHandshakeEnabled"}],"op":"replace"},{"op":"replace","value":"PGPairingQRGeneratorOptions","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/fragments","value":[{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}