{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default size is width: 300, height: 300"}]}]}],"metadata":{"externalID":"c:@M@ConnectSDK@objc(cs)PGPairingQRGeneratorOptions(py)imageSize","navigatorTitle":[{"kind":"identifier","text":"imageSize"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"ConnectSDK"}],"role":"symbol","symbolKind":"property","title":"imageSize"},"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The PG Pairing QR image size"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/imagesize"]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/imagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/imageSize":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/imagesize","role":"symbol","abstract":[{"text":"The PG Pairing QR image size","type":"text"}],"type":"topic","kind":"symbol","title":"imageSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageSize","navigatorTitle":[{"text":"imageSize","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions":{"role":"symbol","title":"PGPairingQRGeneratorOptions","url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions","abstract":[{"type":"text","text":"Options for generating QR pairing image"}],"type":"topic","navigatorTitle":[{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"imageSize"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"imageSize","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1imageSize\/title","value":"imageSize"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1imageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"imageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/title","value":"PGPairingQRGeneratorOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/fragments","value":[{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}