{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/init(feedback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used to initiate PGFeedbackRequest with a predefined feedback."}],"variants":[{"paths":["\/documentation\/connectsdk\/pgfeedbackrequest\/init(feedback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgfeedbackrequest\/init(feedback:)"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest"]]},"metadata":{"externalID":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest(im)initWithFeedback:","modules":[{"name":"ConnectSDK"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"feedback"},{"text":": ","kind":"text"},{"text":"PGPredefinedFeedback","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback"},{"kind":"text","text":")"}],"title":"init(feedback:)","navigatorTitle":[{"text":"initWithFeedback:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"feedback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback","text":"PGPredefinedFeedback","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"PGFeedbackRequest object"}],"type":"paragraph"}],"name":"feedback"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackRequest"}],"navigatorTitle":[{"kind":"identifier","text":"PGFeedbackRequest"}],"url":"\/documentation\/connectsdk\/pgfeedbackrequest","title":"PGFeedbackRequest","abstract":[{"text":"Model representing PGFeedback Request","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPredefinedFeedback"}],"navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"url":"\/documentation\/connectsdk\/pgpredefinedfeedback","title":"PGPredefinedFeedback","abstract":[{"text":"Feedback enum","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest/init(feedback:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"feedback"},{"text":": ","kind":"text"},{"text":"PGPredefinedFeedback","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFeedback:"}],"abstract":[{"type":"text","text":"Used to initiate PGFeedbackRequest with a predefined feedback."}],"url":"\/documentation\/connectsdk\/pgfeedbackrequest\/init(feedback:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/init(feedback:)","title":"init(feedback:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFeedback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFeedback:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFeedback:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback","text":"PGPredefinedFeedback","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"feedback","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/title","value":"PGFeedbackRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/fragments","op":"replace","value":[{"text":"PGFeedbackRequest","kind":"identifier"}]},{"op":"replace","value":"PGPredefinedFeedback","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1init(feedback:)\/title","value":"initWithFeedback:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFeedback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1init(feedback:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}