{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"predefinedFeedback","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback","text":"PGPredefinedFeedback"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"predefinedFeedback"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"predefinedFeedback","kind":"identifier"},{"kind":"text","text":": "},{"text":"PGPredefinedFeedback","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback"}],"roleHeading":"Instance Property","modules":[{"name":"ConnectSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest(py)predefinedFeedback","title":"predefinedFeedback"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/predefinedFeedback"},"abstract":[{"type":"text","text":"Predefined feedback id."}],"variants":[{"paths":["\/documentation\/connectsdk\/pgfeedbackrequest\/predefinedfeedback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgfeedbackrequest\/predefinedfeedback"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest":{"title":"PGFeedbackRequest","abstract":[{"text":"Model representing PGFeedback Request","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PGFeedbackRequest","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackRequest"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","url":"\/documentation\/connectsdk\/pgfeedbackrequest"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest/predefinedFeedback":{"url":"\/documentation\/connectsdk\/pgfeedbackrequest\/predefinedfeedback","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/predefinedFeedback","role":"symbol","title":"predefinedFeedback","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"predefinedFeedback","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGPredefinedFeedback","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback"}],"navigatorTitle":[{"kind":"identifier","text":"predefinedFeedback"}],"kind":"symbol","abstract":[{"text":"Predefined feedback id.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPredefinedFeedback"}],"navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","role":"symbol","type":"topic","title":"PGPredefinedFeedback","url":"\/documentation\/connectsdk\/pgpredefinedfeedback","abstract":[{"text":"Feedback enum","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"predefinedFeedback","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"predefinedFeedback","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPredefinedFeedback","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"},{"text":" ","kind":"text"},{"text":"predefinedFeedback","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/title","op":"replace","value":"PGFeedbackRequest"},{"value":[{"text":"PGFeedbackRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/fragments"},{"value":"predefinedFeedback","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1predefinedFeedback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1predefinedFeedback\/fragments","value":[{"text":"predefinedFeedback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title","value":"PGPredefinedFeedback"},{"value":[{"text":"PGPredefinedFeedback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}