{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralstate\/discovering"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralstate\/discovering"]}],"metadata":{"externalID":"c:@M@ConnectSDK@E@PGPeripheralState@PGPeripheralStateDiscovering","modules":[{"name":"ConnectSDK"}],"title":"PGPeripheralState.discovering","role":"symbol","navigatorTitle":[{"text":"PGPeripheralStateDiscovering","kind":"identifier"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"discovering","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState"]]},"abstract":[{"text":"The peripheral is currently being interrogated by the central manager","type":"text"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/discovering","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"discovering"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralState"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","type":"topic","title":"PGPeripheralState","abstract":[{"text":"Values representing the current connection state of the peripheral","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipheralstate","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralState"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/discovering":{"kind":"symbol","navigatorTitle":[{"text":"PGPeripheralStateDiscovering","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/discovering","title":"PGPeripheralState.discovering","url":"\/documentation\/connectsdk\/pgperipheralstate\/discovering","role":"symbol","abstract":[{"type":"text","text":"The peripheral is currently being interrogated by the central manager"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discovering"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"PGPeripheralStateDiscovering"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"PGPeripheralStateDiscovering","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"PGPeripheralStateDiscovering","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/title","value":"PGPeripheralState"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralState"}]},{"value":"PGPeripheralStateDiscovering","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1discovering\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralStateDiscovering"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1discovering\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}