{"kind":"symbol","metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnecting"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateDisconnecting"}],"title":"PGPeripheralState.disconnecting","externalID":"c:@M@ConnectSDK@E@PGPeripheralState@PGPeripheralStateDisconnecting","modules":[{"name":"ConnectSDK"}],"roleHeading":"Case","role":"symbol"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnecting","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralstate\/disconnecting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralstate\/disconnecting"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnecting","kind":"identifier"}]}]}],"abstract":[{"text":"The peripheral is currently in the process of connecting to the central manager.","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Values representing the current connection state of the peripheral","type":"text"}],"title":"PGPeripheralState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheralState","kind":"identifier"}],"navigatorTitle":[{"text":"PGPeripheralState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheralstate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/disconnecting":{"title":"PGPeripheralState.disconnecting","navigatorTitle":[{"text":"PGPeripheralStateDisconnecting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"disconnecting","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnecting","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralstate\/disconnecting","abstract":[{"text":"The peripheral is currently in the process of connecting to the central manager.","type":"text"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PGPeripheralStateDisconnecting"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralStateDisconnecting"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PGPeripheralStateDisconnecting","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"PGPeripheralState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/fragments","op":"replace","value":[{"text":"PGPeripheralState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1disconnecting\/title","value":"PGPeripheralStateDisconnecting"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1disconnecting\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralStateDisconnecting"}]}]}]}