{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"The peripheral is ready to be used","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralstate\/ready"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralstate\/ready"]}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ready","kind":"identifier"}],"role":"symbol","title":"PGPeripheralState.ready","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGPeripheralState@PGPeripheralStateReady","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"PGPeripheralStateReady","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState"]]},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/ready","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ready","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralState"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","type":"topic","title":"PGPeripheralState","abstract":[{"text":"Values representing the current connection state of the peripheral","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipheralstate","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralState"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/ready":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/ready","abstract":[{"type":"text","text":"The peripheral is ready to be used"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ready"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/ready","type":"topic","navigatorTitle":[{"text":"PGPeripheralStateReady","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PGPeripheralState.ready"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralStateReady"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateReady"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"PGPeripheralStateReady"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PGPeripheralState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/title"},{"value":[{"kind":"identifier","text":"PGPeripheralState"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/fragments"},{"op":"replace","value":"PGPeripheralStateReady","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1ready\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1ready\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateReady"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}