{"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralstate\/systemconnected"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralstate\/systemconnected"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/systemConnected"},"abstract":[{"type":"text","text":"The peripheral is currently connected to the system, but not the App’s central manager."}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState"]]},"kind":"symbol","metadata":{"externalID":"c:@M@ConnectSDK@E@PGPeripheralState@PGPeripheralStateSystemConnected","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateSystemConnected"}],"title":"PGPeripheralState.systemConnected","modules":[{"name":"ConnectSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemConnected","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"systemConnected","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralState"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","type":"topic","title":"PGPeripheralState","abstract":[{"text":"Values representing the current connection state of the peripheral","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipheralstate","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralState"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/systemConnected":{"kind":"symbol","navigatorTitle":[{"text":"PGPeripheralStateSystemConnected","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"systemConnected"}],"title":"PGPeripheralState.systemConnected","abstract":[{"text":"The peripheral is currently connected to the system, but not the App’s central manager.","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/systemconnected","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/systemConnected"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"PGPeripheralStateSystemConnected","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PGPeripheralStateSystemConnected","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"PGPeripheralStateSystemConnected","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"PGPeripheralState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/title"},{"value":[{"text":"PGPeripheralState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/fragments","op":"replace"},{"op":"replace","value":"PGPeripheralStateSystemConnected","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1systemConnected\/title"},{"value":[{"text":"PGPeripheralStateSystemConnected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1systemConnected\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}