{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"screenDataRequest"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScreenData","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","text":"PGScreenData"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams"},{"text":" = PGCommandParams())","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"}],"type":"paragraph"}],"name":"screenDataRequest"},{"name":"params","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"init(screenDataRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"screenDataRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGScreenData","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScreenData"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"params"},{"text":": ","kind":"text"},{"text":"PGCommandParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithScreenDataRequest:params:","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGCommand(im)initWithScreenDataRequest:params:","symbolKind":"init","role":"symbol","roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(screenDataRequest:params:)"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Initialize with Screen Data request"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcommand\/init(screendatarequest:params:)"]},{"paths":["\/documentation\/connectsdk\/pgcommand\/init(screendatarequest:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"symbol","role":"symbol","abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"title":"PGCommand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(screenDataRequest:params:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Initialize with Screen Data request"}],"title":"init(screenDataRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"screenDataRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGScreenData","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScreenData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithScreenDataRequest:params:"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(screendatarequest:params:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(screenDataRequest:params:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"title":"PGScreenData","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGScreenData"}],"url":"\/documentation\/connectsdk\/pgscreendata","type":"topic","role":"symbol","navigatorTitle":[{"text":"PGScreenData","kind":"identifier"}],"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"title":"PGCommandParams","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommandParams","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcommandparams","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"abstract":[{"type":"text","text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithScreenDataRequest:params:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithScreenDataRequest:params:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithScreenDataRequest:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScreenData","text":"PGScreenData","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"},{"kind":"text","text":" *) "},{"text":"screenDataRequest","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"text":"(","kind":"text"},{"text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"params"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","value":"PGCommand"},{"value":[{"text":"PGCommand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(screenDataRequest:params:)\/title","value":"initWithScreenDataRequest:params:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithScreenDataRequest:params:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(screenDataRequest:params:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title","value":"PGScreenData","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","value":[{"text":"PGScreenData","kind":"identifier"}],"op":"replace"},{"value":"PGCommandParams","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","value":[{"text":"PGCommandParams","kind":"identifier"}],"op":"replace"}]}]}