{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(displayOrientationRequest:params:)"},"variants":[{"paths":["\/documentation\/connectsdk\/pgcommand\/init(displayorientationrequest:params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcommand\/init(displayorientationrequest:params:)"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"displayOrientationRequest","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGSetDisplayOrientationRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams"},{"text":")","kind":"text"}],"title":"init(displayOrientationRequest:params:)","navigatorTitle":[{"text":"initWithDisplayOrientationRequest:params:","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGCommand(im)initWithDisplayOrientationRequest:params:","modules":[{"name":"ConnectSDK"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init"},"abstract":[{"type":"text","text":"Initialize with Display Orientation Request"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayOrientationRequest"},{"text":": ","kind":"text"},{"text":"PGSetDisplayOrientationRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams","kind":"typeIdentifier"},{"text":" = PGCommandParams())","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","isActive":true}]}],"name":"displayOrientationRequest"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","isActive":true,"type":"reference"}]}],"name":"params"}],"kind":"parameters"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(displayOrientationRequest:params:)":{"navigatorTitle":[{"text":"initWithDisplayOrientationRequest:params:","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(displayorientationrequest:params:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"displayOrientationRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest","text":"PGSetDisplayOrientationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"text":": ","kind":"text"},{"text":"PGCommandParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Initialize with Display Orientation Request"}],"role":"symbol","title":"init(displayOrientationRequest:params:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(displayOrientationRequest:params:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"type":"topic","title":"PGCommand","abstract":[{"type":"text","text":"A PGCommand is used to send a command to a connected device through Connect SDK."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest":{"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest","kind":"symbol","abstract":[{"type":"text","text":"This object holds the data for updating a screen orientation on a ProGlove display device."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"navigatorTitle":[{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"type":"topic","title":"PGSetDisplayOrientationRequest","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"type":"topic","abstract":[{"type":"text","text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour."}],"title":"PGCommandParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGCommandParams","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcommandparams","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDisplayOrientationRequest:params:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDisplayOrientationRequest:params:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDisplayOrientationRequest:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","text":"PGSetDisplayOrientationRequest"},{"text":" *) ","kind":"text"},{"text":"displayOrientationRequest","kind":"internalParam"},{"kind":"text","text":" "},{"text":"params:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCommandParams","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":" *) "},{"text":"params","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(displayOrientationRequest:params:)\/title","value":"initWithDisplayOrientationRequest:params:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDisplayOrientationRequest:params:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(displayOrientationRequest:params:)\/fragments"},{"value":"PGCommand","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGCommand"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments"},{"value":"PGSetDisplayOrientationRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/fragments"},{"value":"PGCommandParams","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGCommandParams"}]}]}]}