{"variants":[{"paths":["\/documentation\/connectsdk\/pgcommand\/init(deviceinforequest:params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcommand\/init(deviceinforequest:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"]]},"kind":"symbol","metadata":{"title":"init(deviceInfoRequest:params:)","modules":[{"name":"ConnectSDK"}],"symbolKind":"init","externalID":"c:@M@ConnectSDK@objc(cs)PGCommand(im)initWithDeviceInfoRequest:params:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceInfoRequest"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformationRequest","text":"PGDeviceInformationRequest"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PGCommandParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithDeviceInfoRequest:params:","kind":"identifier"}],"role":"symbol","roleHeading":"Initializer"},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(deviceInfoRequest:params:)","interfaceLanguage":"swift"},"abstract":[{"text":"Initilaze with device information request","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"deviceInfoRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGDeviceInformationRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformationRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"},{"kind":"text","text":" = PGCommandParams())"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","isActive":true}]}],"name":"deviceInfoRequest"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","isActive":true}],"type":"paragraph"}],"name":"params"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"title":"PGCommand","url":"\/documentation\/connectsdk\/pgcommand","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommand","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(deviceInfoRequest:params:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"deviceInfoRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformationRequest","kind":"typeIdentifier","text":"PGDeviceInformationRequest"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(deviceInfoRequest:params:)","abstract":[{"type":"text","text":"Initilaze with device information request"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(deviceinforequest:params:)","navigatorTitle":[{"kind":"identifier","text":"initWithDeviceInfoRequest:params:"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(deviceInfoRequest:params:)","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformationRequest":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDeviceInformationRequest","kind":"identifier"}],"navigatorTitle":[{"text":"PGDeviceInformationRequest","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgdeviceinformationrequest","title":"PGDeviceInformationRequest","abstract":[{"text":"Request used for retreiving Device information","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"abstract":[{"text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour.","type":"text"}],"url":"\/documentation\/connectsdk\/pgcommandparams","title":"PGCommandParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommandParams","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithDeviceInfoRequest:params:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDeviceInfoRequest:params:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDeviceInfoRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformationRequest","kind":"typeIdentifier","text":"PGDeviceInformationRequest"},{"kind":"text","text":" *) "},{"text":"deviceInfoRequest","kind":"internalParam"},{"kind":"text","text":" "},{"text":"params:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCommandParams","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGCommand","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title"},{"value":[{"text":"PGCommand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(deviceInfoRequest:params:)\/title","op":"replace","value":"initWithDeviceInfoRequest:params:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDeviceInfoRequest:params:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(deviceInfoRequest:params:)\/fragments"},{"value":"PGDeviceInformationRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest\/fragments","value":[{"kind":"identifier","text":"PGDeviceInformationRequest"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title","value":"PGCommandParams"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","value":[{"text":"PGCommandParams","kind":"identifier"}],"op":"replace"}]}]}