{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"feedbackRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest","kind":"typeIdentifier","text":"PGFeedbackRequest"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","text":"PGCommandParams"},{"kind":"text","text":" = PGCommandParams())"}],"languages":["swift"]}]},{"parameters":[{"name":"feedbackRequest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest"}]}]},{"name":"params","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcommand\/init(feedbackrequest:params:)"]},{"paths":["\/documentation\/connectsdk\/pgcommand\/init(feedbackrequest:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"init(feedbackRequest:params:)","roleHeading":"Initializer","externalID":"c:@M@ConnectSDK@objc(cs)PGCommand(im)initWithFeedbackRequest:params:","navigatorTitle":[{"kind":"identifier","text":"initWithFeedbackRequest:params:"}],"modules":[{"name":"ConnectSDK"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"feedbackRequest"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGFeedbackRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(feedbackRequest:params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize with feedback request"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackRequest"}],"navigatorTitle":[{"kind":"identifier","text":"PGFeedbackRequest"}],"url":"\/documentation\/connectsdk\/pgfeedbackrequest","title":"PGFeedbackRequest","abstract":[{"text":"Model representing PGFeedback Request","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(feedbackRequest:params:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"feedbackRequest"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest","text":"PGFeedbackRequest"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams"},{"kind":"text","text":")"}],"title":"init(feedbackRequest:params:)","kind":"symbol","abstract":[{"text":"Initialize with feedback request","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFeedbackRequest:params:"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(feedbackRequest:params:)","url":"\/documentation\/connectsdk\/pgcommand\/init(feedbackrequest:params:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"abstract":[{"text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour.","type":"text"}],"url":"\/documentation\/connectsdk\/pgcommandparams","title":"PGCommandParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommandParams","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"title":"PGCommand","url":"\/documentation\/connectsdk\/pgcommand","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommand","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithFeedbackRequest:params:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFeedbackRequest:params:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithFeedbackRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGFeedbackRequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"feedbackRequest"},{"text":" ","kind":"text"},{"text":"params:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGCommandParams","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGFeedbackRequest","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/fragments","value":[{"kind":"identifier","text":"PGFeedbackRequest"}]},{"value":"initWithFeedbackRequest:params:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(feedbackRequest:params:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(feedbackRequest:params:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFeedbackRequest:params:"}]},{"value":"PGCommandParams","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","value":[{"kind":"identifier","text":"PGCommandParams"}]},{"value":"PGCommand","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments","value":[{"kind":"identifier","text":"PGCommand"}]}]}]}