{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configurationProfileRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","text":"PGConfigurationProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams"},{"kind":"text","text":" = PGCommandParams())"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"configurationProfileRequest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile"}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgcommand\/init(configurationprofilerequest:params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcommand\/init(configurationprofilerequest:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(configurationProfileRequest:params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize with Configuration Profile Request"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configurationProfileRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"title":"init(configurationProfileRequest:params:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ConnectSDK@objc(cs)PGCommand(im)initWithConfigurationProfileRequest:params:","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfigurationProfileRequest:params:"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationProfile":{"role":"symbol","title":"PGConfigurationProfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationProfile"}],"abstract":[{"type":"text","text":"Configuration profile model class."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationProfile"}],"url":"\/documentation\/connectsdk\/pgconfigurationprofile"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"role":"symbol","title":"PGCommandParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommandParams"}],"abstract":[{"type":"text","text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"url":"\/documentation\/connectsdk\/pgcommandparams"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(configurationProfileRequest:params:)":{"role":"symbol","title":"init(configurationProfileRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configurationProfileRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with Configuration Profile Request"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(configurationProfileRequest:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfigurationProfileRequest:params:"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(configurationprofilerequest:params:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"role":"symbol","title":"PGCommand","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"abstract":[{"type":"text","text":"A PGCommand is used to send a command to a connected device through Connect SDK."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfigurationProfileRequest:params:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfigurationProfileRequest:params:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfigurationProfileRequest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","text":"PGConfigurationProfile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configurationProfileRequest"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/title","value":"PGConfigurationProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/fragments","value":[{"kind":"identifier","text":"PGConfigurationProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title","value":"PGCommandParams"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","value":[{"kind":"identifier","text":"PGCommandParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(configurationProfileRequest:params:)\/title","value":"initWithConfigurationProfileRequest:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(configurationProfileRequest:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfigurationProfileRequest:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","value":"PGCommand"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments","value":[{"kind":"identifier","text":"PGCommand"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}