{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcommand\/init(captureimagerequest:params:)"]},{"paths":["\/documentation\/connectsdk\/pgcommand\/init(captureimagerequest:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(captureImageRequest:params:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Initialize with Capture Image Request","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"captureImageRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGCaptureImageRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCaptureImageRequest"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","text":"PGCommandParams"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCaptureImageRequest:params:"}],"modules":[{"name":"ConnectSDK"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(captureImageRequest:params:)","externalID":"c:@M@ConnectSDK@objc(cs)PGCommand(im)initWithCaptureImageRequest:params:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"captureImageRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCaptureImageRequest","text":"PGCaptureImageRequest"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"},{"text":" = PGCommandParams())","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"captureImageRequest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest"}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","isActive":true}]}]}],"kind":"parameters"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"type":"topic","title":"PGCommand","abstract":[{"type":"text","text":"A PGCommand is used to send a command to a connected device through Connect SDK."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest":{"abstract":[{"type":"text","text":"PGCaptureImageRequest"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCaptureImageRequest"}],"url":"\/documentation\/connectsdk\/pgcaptureimagerequest","navigatorTitle":[{"text":"PGCaptureImageRequest","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PGCaptureImageRequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(captureImageRequest:params:)":{"type":"topic","kind":"symbol","title":"init(captureImageRequest:params:)","abstract":[{"text":"Initialize with Capture Image Request","type":"text"}],"navigatorTitle":[{"text":"initWithCaptureImageRequest:params:","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(captureImageRequest:params:)","url":"\/documentation\/connectsdk\/pgcommand\/init(captureimagerequest:params:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"captureImageRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCaptureImageRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCaptureImageRequest"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PGCommandParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"type":"topic","abstract":[{"type":"text","text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour."}],"title":"PGCommandParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGCommandParams","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcommandparams","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithCaptureImageRequest:params:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCaptureImageRequest:params:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithCaptureImageRequest:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","kind":"typeIdentifier","text":"PGCaptureImageRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCaptureImageRequest"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"captureImageRequest"},{"kind":"text","text":" "},{"text":"params:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","text":"PGCommandParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGCommand","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title"},{"value":[{"kind":"identifier","text":"PGCommand"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/title","value":"PGCaptureImageRequest","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/fragments","value":[{"text":"PGCaptureImageRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(captureImageRequest:params:)\/title","op":"replace","value":"initWithCaptureImageRequest:params:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCaptureImageRequest:params:"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(captureImageRequest:params:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title","value":"PGCommandParams","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","op":"replace","value":[{"text":"PGCommandParams","kind":"identifier"}]}]}]}