{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipherallockstate\/disabled"]},{"paths":["\/documentation\/connectsdk\/pgperipherallockstate\/disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState"]]},"metadata":{"title":"PGPeripheralLockState.disabled","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGPeripheralLockState@PGPeripheralLockStateDisabled","roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"navigatorTitle":[{"text":"PGPeripheralLockStateDisabled","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"Indicates that the scanner locking is disabled"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/disabled"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/disabled":{"abstract":[{"text":"Indicates that the scanner locking is disabled","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/disabled","url":"\/documentation\/connectsdk\/pgperipherallockstate\/disabled","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"navigatorTitle":[{"text":"PGPeripheralLockStateDisabled","kind":"identifier"}],"title":"PGPeripheralLockState.disabled"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralLockState","kind":"identifier"}],"abstract":[{"text":"The lock status of the scanner","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","type":"topic","title":"PGPeripheralLockState","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralLockState"}],"url":"\/documentation\/connectsdk\/pgperipherallockstate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGPeripheralLockStateDisabled","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"PGPeripheralLockStateDisabled"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGPeripheralLockStateDisabled"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1disabled\/title","op":"replace","value":"PGPeripheralLockStateDisabled"},{"op":"replace","value":[{"text":"PGPeripheralLockStateDisabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1disabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/title","value":"PGPeripheralLockState"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralLockState"}]}]}]}