{"sections":[],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralLockStateLocked"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"locked"}],"modules":[{"name":"ConnectSDK"}],"title":"PGPeripheralLockState.locked","externalID":"c:@M@ConnectSDK@E@PGPeripheralLockState@PGPeripheralLockStateLocked","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/locked"},"abstract":[{"text":"Indicates that the scanner is locked and expecting the validation barcode to be scanned.","type":"text"},{"type":"text","text":" "},{"text":"All scanner functions are suspended until the scanner gets unlocked, or changes to a configuration","type":"text"},{"type":"text","text":" "},{"text":"which has authentication disabled","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locked"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipherallockstate\/locked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipherallockstate\/locked"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPeripheralLockState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralLockState"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","type":"topic","abstract":[{"text":"The lock status of the scanner","type":"text"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipherallockstate","title":"PGPeripheralLockState"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/locked":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"locked","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/locked","role":"symbol","url":"\/documentation\/connectsdk\/pgperipherallockstate\/locked","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralLockStateLocked"}],"title":"PGPeripheralLockState.locked","abstract":[{"text":"Indicates that the scanner is locked and expecting the validation barcode to be scanned.","type":"text"},{"type":"text","text":" "},{"text":"All scanner functions are suspended until the scanner gets unlocked, or changes to a configuration","type":"text"},{"text":" ","type":"text"},{"text":"which has authentication disabled","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGPeripheralLockStateLocked","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PGPeripheralLockStateLocked"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"PGPeripheralLockStateLocked","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/title","value":"PGPeripheralLockState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/fragments","value":[{"kind":"identifier","text":"PGPeripheralLockState"}]},{"op":"replace","value":"PGPeripheralLockStateLocked","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1locked\/title"},{"value":[{"text":"PGPeripheralLockStateLocked","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1locked\/fragments"}]}]}