{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/unlocked"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unlocked","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipherallockstate\/unlocked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipherallockstate\/unlocked"]}],"metadata":{"title":"PGPeripheralLockState.unlocked","roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unlocked"}],"modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"PGPeripheralLockStateUnlocked","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGPeripheralLockState@PGPeripheralLockStateUnlocked"},"abstract":[{"text":"Indicates that the scanner has been unlocked with validation barcode","type":"text"}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState":{"type":"topic","abstract":[{"text":"The lock status of the scanner","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgperipherallockstate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPeripheralLockState","kind":"identifier"}],"title":"PGPeripheralLockState","navigatorTitle":[{"text":"PGPeripheralLockState","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/unlocked":{"navigatorTitle":[{"text":"PGPeripheralLockStateUnlocked","kind":"identifier"}],"abstract":[{"text":"Indicates that the scanner has been unlocked with validation barcode","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipherallockstate\/unlocked","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/unlocked","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unlocked","kind":"identifier"}],"title":"PGPeripheralLockState.unlocked","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"PGPeripheralLockStateUnlocked","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPeripheralLockStateUnlocked"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PGPeripheralLockStateUnlocked","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"PGPeripheralLockState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/title"},{"op":"replace","value":[{"text":"PGPeripheralLockState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1unlocked\/title","op":"replace","value":"PGPeripheralLockStateUnlocked"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1unlocked\/fragments","value":[{"kind":"identifier","text":"PGPeripheralLockStateUnlocked"}],"op":"replace"}]}]}