{"kind":"symbol","variants":[{"paths":["\/documentation\/connectsdk\/pgimageresolution\/res1280_960"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgimageresolution\/res1280_960"]}],"metadata":{"navigatorTitle":[{"text":"PGImageResolutionRes1280_960","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ConnectSDK@E@PGImageResolution@PGImageResolutionRes1280_960","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"title":"PGImageResolution.res1280_960","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"res1280_960","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res1280_960"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"res1280_960"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/res1280_960":{"url":"\/documentation\/connectsdk\/pgimageresolution\/res1280_960","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"res1280_960"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGImageResolutionRes1280_960"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res1280_960","title":"PGImageResolution.res1280_960"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution":{"title":"PGImageResolution","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGImageResolution"}],"navigatorTitle":[{"kind":"identifier","text":"PGImageResolution"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","abstract":[],"url":"\/documentation\/connectsdk\/pgimageresolution","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGImageResolutionRes1280_960","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PGImageResolutionRes1280_960","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGImageResolutionRes1280_960"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res1280_960\/title","value":"PGImageResolutionRes1280_960"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res1280_960\/fragments","value":[{"kind":"identifier","text":"PGImageResolutionRes1280_960"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/title","value":"PGImageResolution","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGImageResolution"}]}]}]}