{"variants":[{"paths":["\/documentation\/connectsdk\/pgimageresolution\/res320_240"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgimageresolution\/res320_240"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"res320_240","kind":"identifier"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution"]]},"metadata":{"modules":[{"name":"ConnectSDK"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGImageResolution@PGImageResolutionRes320_240","navigatorTitle":[{"text":"PGImageResolutionRes320_240","kind":"identifier"}],"title":"PGImageResolution.res320_240","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"res320_240","kind":"identifier"}],"symbolKind":"case"},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res320_240","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/res320_240":{"url":"\/documentation\/connectsdk\/pgimageresolution\/res320_240","type":"topic","role":"symbol","navigatorTitle":[{"text":"PGImageResolutionRes320_240","kind":"identifier"}],"title":"PGImageResolution.res320_240","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"res320_240","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res320_240"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution":{"navigatorTitle":[{"kind":"identifier","text":"PGImageResolution"}],"url":"\/documentation\/connectsdk\/pgimageresolution","abstract":[],"title":"PGImageResolution","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImageResolution"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"PGImageResolutionRes320_240","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PGImageResolutionRes320_240","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PGImageResolutionRes320_240","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"PGImageResolutionRes320_240","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res320_240\/title"},{"value":[{"kind":"identifier","text":"PGImageResolutionRes320_240"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res320_240\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/title","value":"PGImageResolution"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/fragments","value":[{"kind":"identifier","text":"PGImageResolution"}]}]}]}