{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/fullRefresh","interfaceLanguage":"swift"},"metadata":{"title":"PGRefreshType.fullRefresh","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullRefresh","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"PGRefreshTypeFullRefresh","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@ConnectSDK@E@PGRefreshType@PGRefreshTypeFullRefresh"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullRefresh","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgrefreshtype\/fullrefresh"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgrefreshtype\/fullrefresh"]}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType/fullRefresh":{"role":"symbol","navigatorTitle":[{"text":"PGRefreshTypeFullRefresh","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullRefresh","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/fullRefresh","url":"\/documentation\/connectsdk\/pgrefreshtype\/fullrefresh","title":"PGRefreshType.fullRefresh"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGRefreshType","kind":"identifier"}],"abstract":[{"type":"text","text":"The refresh type, the display should be using when setting a screen."}],"title":"PGRefreshType","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","url":"\/documentation\/connectsdk\/pgrefreshtype","navigatorTitle":[{"text":"PGRefreshType","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PGRefreshTypeFullRefresh"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGRefreshTypeFullRefresh"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PGRefreshTypeFullRefresh","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1fullRefresh\/title","value":"PGRefreshTypeFullRefresh"},{"op":"replace","value":[{"text":"PGRefreshTypeFullRefresh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1fullRefresh\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/title","value":"PGRefreshType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/fragments","value":[{"kind":"identifier","text":"PGRefreshType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}