{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/durationms"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/durationms"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]]},"sections":[],"abstract":[{"type":"text","text":"The duration for how long the notification should be displayed."},{"text":" ","type":"text"},{"type":"text","text":"Only used when sent with NotificationScreen, must be >0 in that case."},{"type":"text","text":" "},{"text":"An automatic transition back to the previous screen will take place after this time. A notification can be replaced by any other notification and by a new screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Depending on your implementation, this is thus only an upper limit on the time this notification will be shown."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationMs"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ConnectSDK@objc(cs)PGScreenData(py)durationMs","title":"durationMs","modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"durationMs","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"durationMs"}]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/durationMs","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"url":"\/documentation\/connectsdk\/pgscreendata","title":"PGScreenData","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGScreenData"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGScreenData","kind":"identifier"}],"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/durationMs":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/durationMs","url":"\/documentation\/connectsdk\/pgscreendata\/durationms","navigatorTitle":[{"text":"durationMs","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"durationMs","type":"topic","abstract":[{"text":"The duration for how long the notification should be displayed.","type":"text"},{"type":"text","text":" "},{"text":"Only used when sent with NotificationScreen, must be >0 in that case.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"An automatic transition back to the previous screen will take place after this time. A notification can be replaced by any other notification and by a new screen."},{"text":" ","type":"text"},{"type":"text","text":"Depending on your implementation, this is thus only an upper limit on the time this notification will be shown."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"durationMs","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"durationMs","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"durationMs","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t","text":"uint32_t"},{"text":" ","kind":"text"},{"text":"durationMs","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGScreenData","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","value":[{"text":"PGScreenData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1durationMs\/title","op":"replace","value":"durationMs"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1durationMs\/fragments","op":"replace","value":[{"text":"durationMs","kind":"identifier"}]}]}]}