{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"templateId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"templateFields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"PGTemplateField","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField"},{"text":"])","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The id of the template to be used to construct the screen."}],"type":"paragraph"}],"name":"templateId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of PGTemplateField which hold the data for header and content for each field in the template"}]}],"name":"templateFields"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Convenience initializer for creating PGScreenData model class. Refresh type will default to PGDefault and durationMs will default to 0."}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]]},"metadata":{"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGScreenData(im)initWithTemplateId:templateFields:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"templateId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"templateFields","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PGTemplateField","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"kind":"text","text":"])"}],"modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTemplateId:templateFields:"}],"roleHeading":"Initializer","title":"init(templateId:templateFields:)","symbolKind":"init"},"kind":"symbol","sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGScreenData","kind":"identifier"}],"navigatorTitle":[{"text":"PGScreenData","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgscreendata","title":"PGScreenData","abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/init(templateId:templateFields:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithTemplateId:templateFields:"}],"type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"templateId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateFields"},{"text":": [","kind":"text"},{"text":"PGTemplateField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"text":"])","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:)","title":"init(templateId:templateFields:)","abstract":[{"text":"Convenience initializer for creating PGScreenData model class. Refresh type will default to PGDefault and durationMs will default to 0.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGTemplateField":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGTemplateField"}],"navigatorTitle":[{"text":"PGTemplateField","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgtemplatefield","title":"PGTemplateField","abstract":[{"type":"text","text":"This class represents the data, that should be displayed in a template field."}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithTemplateId:templateFields:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTemplateId:templateFields:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithTemplateId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"templateId"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateFields:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<PGTemplateField *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"templateFields"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title","value":"PGScreenData","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGScreenData"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:)\/title","op":"replace","value":"initWithTemplateId:templateFields:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTemplateId:templateFields:"}]},{"value":"PGTemplateField","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/title"},{"op":"replace","value":[{"text":"PGTemplateField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/fragments"}]}]}