{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateFields"},{"text":": [","kind":"text"},{"text":"PGTemplateField","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"text":"], ","kind":"text"},{"text":"refreshType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType","text":"PGRefreshType","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"templateId","content":[{"inlineContent":[{"text":"The id of the template to be used to construct the screen.","type":"text"}],"type":"paragraph"}]},{"name":"templateFields","content":[{"inlineContent":[{"text":"A list of PGTemplateField which hold the data for header and content for each field in the template","type":"text"}],"type":"paragraph"}]},{"name":"refreshType","content":[{"inlineContent":[{"text":"The PGRefreshType type to be used while setting this screen.","type":"text"}],"type":"paragraph"}]},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The duration for how long the notification should be displayed."}]}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"templateId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"templateFields","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"PGTemplateField","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"refreshType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGRefreshType","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTemplateId:templateFields:refreshType:duration:"}],"symbolKind":"init","title":"init(templateId:templateFields:refreshType:duration:)","externalID":"c:@M@ConnectSDK@objc(cs)PGScreenData(im)initWithTemplateId:templateFields:refreshType:duration:","roleHeading":"Initializer","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:refreshtype:duration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:refreshtype:duration:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]]},"abstract":[{"type":"text","text":"Designated initializer for creating PGScreenData model class."}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:refreshType:duration:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"url":"\/documentation\/connectsdk\/pgscreendata","title":"PGScreenData","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGScreenData"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGScreenData","kind":"identifier"}],"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgrefreshtype","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGRefreshType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGRefreshType"}],"abstract":[{"text":"The refresh type, the display should be using when setting a screen.","type":"text"}],"title":"PGRefreshType"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGTemplateField":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGTemplateField"}],"abstract":[{"text":"This class represents the data, that should be displayed in a template field.","type":"text"}],"url":"\/documentation\/connectsdk\/pgtemplatefield","role":"symbol","navigatorTitle":[{"text":"PGTemplateField","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField","type":"topic","title":"PGTemplateField"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/init(templateId:templateFields:refreshType:duration:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithTemplateId:templateFields:refreshType:duration:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Designated initializer for creating PGScreenData model class.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"templateFields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"PGTemplateField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"refreshType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGRefreshType","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:refreshType:duration:)","url":"\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:refreshtype:duration:)","title":"init(templateId:templateFields:refreshType:duration:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithTemplateId:templateFields:refreshType:duration:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithTemplateId:templateFields:refreshType:duration:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithTemplateId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"templateId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templateFields:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<PGTemplateField *>"},{"text":" *) ","kind":"text"},{"text":"templateFields","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"refreshType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType","text":"PGRefreshType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"refreshType"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t","text":"uint32_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"duration"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"PGScreenData","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title"},{"op":"replace","value":[{"text":"PGScreenData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments"},{"op":"replace","value":"PGRefreshType","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/fragments","value":[{"kind":"identifier","text":"PGRefreshType"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/title","op":"replace","value":"PGTemplateField"},{"value":[{"text":"PGTemplateField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:refreshType:duration:)\/title","value":"initWithTemplateId:templateFields:refreshType:duration:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTemplateId:templateFields:refreshType:duration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:refreshType:duration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}