{"sections":[],"abstract":[{"type":"text","text":"The PGRefreshType type to be used while setting this screen."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/refreshType"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"refreshType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType","text":"PGRefreshType","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/refreshtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/refreshtype"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"refreshType","kind":"identifier"}],"title":"refreshType","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"refreshType","kind":"identifier"},{"kind":"text","text":": "},{"text":"PGRefreshType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType"}],"symbolKind":"property","externalID":"c:@M@ConnectSDK@objc(cs)PGScreenData(py)refreshType","roleHeading":"Instance Property"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"title":"PGScreenData","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGScreenData"}],"url":"\/documentation\/connectsdk\/pgscreendata","type":"topic","role":"symbol","navigatorTitle":[{"text":"PGScreenData","kind":"identifier"}],"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/refreshType":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshType"},{"text":": ","kind":"text"},{"text":"PGRefreshType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/refreshType","url":"\/documentation\/connectsdk\/pgscreendata\/refreshtype","navigatorTitle":[{"text":"refreshType","kind":"identifier"}],"kind":"symbol","title":"refreshType","role":"symbol","type":"topic","abstract":[{"text":"The PGRefreshType type to be used while setting this screen.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType":{"type":"topic","title":"PGRefreshType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGRefreshType"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","abstract":[{"type":"text","text":"The refresh type, the display should be using when setting a screen."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGRefreshType"}],"url":"\/documentation\/connectsdk\/pgrefreshtype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"refreshType"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"refreshType","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGRefreshType","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"refreshType","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title","value":"PGScreenData"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGScreenData"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1refreshType\/title","value":"refreshType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1refreshType\/fragments","value":[{"text":"refreshType","kind":"identifier"}]},{"value":"PGRefreshType","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/fragments","op":"replace","value":[{"text":"PGRefreshType","kind":"identifier"}]}]}]}