{"variants":[{"paths":["\/documentation\/connectsdk\/pgscreendata\/templatefields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgscreendata\/templatefields"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ConnectSDK"}],"title":"templateFields","symbolKind":"property","externalID":"c:@M@ConnectSDK@objc(cs)PGScreenData(py)templateFields","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"templateFields","kind":"identifier"},{"kind":"text","text":": ["},{"text":"PGTemplateField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"templateFields"}]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateFields","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]]},"abstract":[{"type":"text","text":"A list of PGTemplateField which hold the data for header and content for each field in the template."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField","kind":"typeIdentifier","text":"PGTemplateField"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGTemplateField":{"type":"topic","url":"\/documentation\/connectsdk\/pgtemplatefield","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGTemplateField"}],"abstract":[{"type":"text","text":"This class represents the data, that should be displayed in a template field."}],"title":"PGTemplateField","navigatorTitle":[{"kind":"identifier","text":"PGTemplateField"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/templateFields":{"type":"topic","url":"\/documentation\/connectsdk\/pgscreendata\/templatefields","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templateFields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField","text":"PGTemplateField"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"A list of PGTemplateField which hold the data for header and content for each field in the template."}],"title":"templateFields","navigatorTitle":[{"kind":"identifier","text":"templateFields"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateFields"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"title":"PGScreenData","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGScreenData"}],"url":"\/documentation\/connectsdk\/pgscreendata","type":"topic","role":"symbol","navigatorTitle":[{"text":"PGScreenData","kind":"identifier"}],"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"templateFields","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"templateFields"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<PGTemplateField *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"templateFields"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"PGTemplateField","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/fragments","value":[{"kind":"identifier","text":"PGTemplateField"}]},{"op":"replace","value":"templateFields","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1templateFields\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1templateFields\/fragments","value":[{"text":"templateFields","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title","value":"PGScreenData"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","value":[{"kind":"identifier","text":"PGScreenData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}