{"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager(im)changeActiveProfile:completionHandler:","title":"changeActiveProfile(_:completionHandler:)","required":true,"role":"symbol","navigatorTitle":[{"text":"changeActiveProfile:completionHandler:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"changeActiveProfile","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/changeActiveProfile(_:completionHandler:)"},"sections":[],"abstract":[{"type":"text","text":"Use this method to set an active configuration profile."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeActiveProfile"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"profileCommand","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PGCommand","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PGCommand"},{"text":" with a profile.","type":"text"}],"type":"paragraph"}],"name":"profileCommand"},{"content":[{"inlineContent":[{"type":"text","text":"The handler containing error indicating if the information is stored locally. The result if configuration profile is applied to a connected device will be sent via "},{"type":"codeVoice","code":"PGPeripheralDelegate"},{"text":" delegate methods ","type":"text"},{"code":"peripheral:didSetConfigurationProfile:","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"peripheral:didFailToSetConfigurationProfile:error","type":"codeVoice"}],"type":"paragraph"}],"name":"completionHandler"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Method will store the information about new active profile locally"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will try to apply the configuration profile to a connected device immediately."}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager"]]},"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/changeactiveprofile(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/changeactiveprofile(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"symbol","role":"symbol","abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"title":"PGCommand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager":{"role":"symbol","title":"PGConfigurationManager","kind":"symbol","navigatorTitle":[{"text":"PGConfigurationManager","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationManager"}],"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/changeActiveProfile(_:completionHandler:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/changeActiveProfile(_:completionHandler:)","role":"symbol","title":"changeActiveProfile(_:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeActiveProfile"},{"kind":"text","text":"("},{"text":"PGCommand","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","required":true,"url":"\/documentation\/connectsdk\/pgconfigurationmanager\/changeactiveprofile(_:completionhandler:)","abstract":[{"text":"Use this method to set an active configuration profile.","type":"text"}],"navigatorTitle":[{"text":"changeActiveProfile:completionHandler:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"changeActiveProfile:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"changeActiveProfile:completionHandler:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"changeActiveProfile:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCommand","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":" *) "},{"text":"profileCommand","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"PGCommand","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","op":"replace"},{"op":"replace","value":[{"text":"PGCommand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments"},{"value":"PGConfigurationManager","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/fragments","value":[{"text":"PGConfigurationManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1changeActiveProfile(_:completionHandler:)\/title","value":"changeActiveProfile:completionHandler:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeActiveProfile:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1changeActiveProfile(_:completionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}