{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getActiveConfigurationProfile(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/getactiveconfigurationprofile(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/getactiveconfigurationprofile(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getActiveConfigurationProfile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","text":"PGConfigurationProfile","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The handler containing the active profile if available."}],"type":"paragraph"}],"name":"completionHandler"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getActiveConfigurationProfile"},{"text":"((","kind":"text"},{"text":"PGConfigurationProfile","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager(im)getActiveConfigurationProfile:","title":"getActiveConfigurationProfile(_:)","symbolKind":"method","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"getActiveConfigurationProfile:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol"},"abstract":[{"type":"text","text":"Use this method to retrieve the current active profile. The active profile is the profile that will be applied to a scanner on each successful connection."},{"type":"text","text":" "},{"type":"text","text":"In case no active profile is set, nil will be returned."}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/getActiveConfigurationProfile(_:)":{"abstract":[{"type":"text","text":"Use this method to retrieve the current active profile. The active profile is the profile that will be applied to a scanner on each successful connection."},{"type":"text","text":" "},{"type":"text","text":"In case no active profile is set, nil will be returned."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getActiveConfigurationProfile(_:)","required":true,"url":"\/documentation\/connectsdk\/pgconfigurationmanager\/getactiveconfigurationprofile(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getActiveConfigurationProfile","kind":"identifier"},{"text":"((","kind":"text"},{"text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"getActiveConfigurationProfile(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getActiveConfigurationProfile:"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGConfigurationManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PGConfigurationManager","kind":"identifier"}],"abstract":[],"url":"\/documentation\/connectsdk\/pgconfigurationmanager","title":"PGConfigurationManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationProfile":{"url":"\/documentation\/connectsdk\/pgconfigurationprofile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGConfigurationProfile","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","type":"topic","role":"symbol","kind":"symbol","title":"PGConfigurationProfile","navigatorTitle":[{"text":"PGConfigurationProfile","kind":"identifier"}],"abstract":[{"text":"Configuration profile model class.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"getActiveConfigurationProfile:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"getActiveConfigurationProfile:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"getActiveConfigurationProfile:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@ConnectSDK@objc(cs)PGConfigurationProfile)","kind":"typeIdentifier","text":"void (^)(PGConfigurationProfile *)"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"getActiveConfigurationProfile:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getActiveConfigurationProfile(_:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getActiveConfigurationProfile(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getActiveConfigurationProfile:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/title","op":"replace","value":"PGConfigurationManager"},{"op":"replace","value":[{"text":"PGConfigurationManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/fragments"},{"value":"PGConfigurationProfile","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/title"},{"value":[{"kind":"identifier","text":"PGConfigurationProfile"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}