{"abstract":[{"text":"Method will return an array of all the previously loaded configuration profiles.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAllConfigurationProfiles"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"The completion handler containing the array of all the previously loaded configurations."}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getAllConfigurationProfiles(completionHandler:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/getallconfigurationprofiles(completionhandler:)"]},{"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/getallconfigurationprofiles(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager"]]},"metadata":{"required":true,"roleHeading":"Instance Method","title":"getAllConfigurationProfiles(completionHandler:)","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAllConfigurationProfiles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"text":": ([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","text":"PGConfigurationProfile"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"getAllConfigurationProfilesWithCompletionHandler:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager(im)getAllConfigurationProfilesWithCompletionHandler:"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","type":"topic","role":"symbol","title":"PGConfigurationManager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManager"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationManager"}],"kind":"symbol","abstract":[],"url":"\/documentation\/connectsdk\/pgconfigurationmanager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/getAllConfigurationProfiles(completionHandler:)":{"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanager\/getallconfigurationprofiles(completionhandler:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getAllConfigurationProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","text":"PGConfigurationProfile"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"getAllConfigurationProfilesWithCompletionHandler:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Method will return an array of all the previously loaded configuration profiles."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getAllConfigurationProfiles(completionHandler:)","title":"getAllConfigurationProfiles(completionHandler:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationProfile":{"type":"topic","kind":"symbol","title":"PGConfigurationProfile","role":"symbol","navigatorTitle":[{"text":"PGConfigurationProfile","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgconfigurationprofile","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","abstract":[{"text":"Configuration profile model class.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationProfile"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"getAllConfigurationProfilesWithCompletionHandler:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getAllConfigurationProfilesWithCompletionHandler:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"getAllConfigurationProfilesWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray)","text":"void (^)(NSArray<PGConfigurationProfile *> *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/title","value":"PGConfigurationManager","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/fragments","op":"replace","value":[{"text":"PGConfigurationManager","kind":"identifier"}]},{"value":"getAllConfigurationProfilesWithCompletionHandler:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getAllConfigurationProfiles(completionHandler:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getAllConfigurationProfiles(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getAllConfigurationProfilesWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"value":"PGConfigurationProfile","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/title"},{"value":[{"text":"PGConfigurationProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}