{"abstract":[{"type":"text","text":"This method will load configuration using a file at given path."},{"type":"text","text":" "},{"text":"One configuration at the time is supported, previously loaded configuration will be deleted.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The file name must be proglove.proconfig"}],"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadConfigurationFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atPath"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"loadConfigurationFileAtPath:completionHandler:","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager(im)loadConfigurationFileAtPath:completionHandler:","role":"symbol","title":"loadConfigurationFile(atPath:completionHandler:)","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ConnectSDK"}]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/loadConfigurationFile(atPath:completionHandler:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/loadconfigurationfile(atpath:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanager\/loadconfigurationfile(atpath:completionhandler:)"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadConfigurationFile","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"atPath"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configurationPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"A path to a configuration file.","type":"text"}],"type":"paragraph"}],"name":"configurationPath"},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler containing error if encountered during configuration load."}]}]}],"kind":"parameters"}],"kind":"symbol","sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/loadConfigurationFile(atPath:completionHandler:)":{"required":true,"url":"\/documentation\/connectsdk\/pgconfigurationmanager\/loadconfigurationfile(atpath:completionhandler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadConfigurationFile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadConfigurationFileAtPath:completionHandler:"}],"role":"symbol","title":"loadConfigurationFile(atPath:completionHandler:)","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/loadConfigurationFile(atPath:completionHandler:)","abstract":[{"type":"text","text":"This method will load configuration using a file at given path."},{"type":"text","text":" "},{"text":"One configuration at the time is supported, previously loaded configuration will be deleted.","type":"text"},{"text":" ","type":"text"},{"text":"The file name must be proglove.proconfig","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGConfigurationManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PGConfigurationManager","kind":"identifier"}],"abstract":[],"url":"\/documentation\/connectsdk\/pgconfigurationmanager","title":"PGConfigurationManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"loadConfigurationFileAtPath:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadConfigurationFileAtPath:completionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"loadConfigurationFileAtPath:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configurationPath"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1loadConfigurationFile(atPath:completionHandler:)\/title","value":"loadConfigurationFileAtPath:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1loadConfigurationFile(atPath:completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"loadConfigurationFileAtPath:completionHandler:","kind":"identifier"}]},{"op":"replace","value":"PGConfigurationManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/fragments","value":[{"kind":"identifier","text":"PGConfigurationManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}