{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleTrigger"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/doubleTrigger","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The double button trigger event type"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgbuttontriggereventtype\/doubletrigger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgbuttontriggereventtype\/doubletrigger"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"case","title":"PGButtonTriggerEventType.doubleTrigger","navigatorTitle":[{"kind":"identifier","text":"PGButtonTriggerEventTypeDoubleTrigger"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"doubleTrigger","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGButtonTriggerEventType@PGButtonTriggerEventTypeDoubleTrigger","modules":[{"name":"ConnectSDK"}]},"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGButtonTriggerEventType","kind":"identifier"}],"navigatorTitle":[{"text":"PGButtonTriggerEventType","kind":"identifier"}],"title":"PGButtonTriggerEventType","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType","type":"topic","abstract":[{"type":"text","text":"The button trigger event types"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType/doubleTrigger":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"doubleTrigger","kind":"identifier"}],"navigatorTitle":[{"text":"PGButtonTriggerEventTypeDoubleTrigger","kind":"identifier"}],"title":"PGButtonTriggerEventType.doubleTrigger","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/doubleTrigger","role":"symbol","abstract":[{"type":"text","text":"The double button trigger event type"}],"type":"topic","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype\/doubletrigger","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PGButtonTriggerEventTypeDoubleTrigger","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGButtonTriggerEventTypeDoubleTrigger"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PGButtonTriggerEventTypeDoubleTrigger","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"PGButtonTriggerEventType","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/title","op":"replace"},{"value":[{"text":"PGButtonTriggerEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType~1doubleTrigger\/title","value":"PGButtonTriggerEventTypeDoubleTrigger","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType~1doubleTrigger\/fragments","value":[{"text":"PGButtonTriggerEventTypeDoubleTrigger","kind":"identifier"}],"op":"replace"}]}]}