{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pgLog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"asynchronous"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag","preciseIdentifier":"c:@M@ConnectSDK@E@PGLogFlag","text":"PGLogFlag"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"line"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"asynchronous","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", this log message can be handled asynchronously"}]}]},{"name":"flag","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The log flag"}]}]},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A context for the message, if provided"}]}]},{"name":"file","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file that the log occurred in"}]}]},{"name":"function","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The function that the log occurred in"}]}]},{"name":"line","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The line that the log occurred on"}]}]},{"name":"tag","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A tag for the message, if provided"}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message to log"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgloggingdelegate\/pglog(_:flag:context:file:function:line:tag:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgloggingdelegate\/pglog(_:flag:context:file:function:line:tag:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate\/pgLog(_:flag:context:file:function:line:tag:message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method notifies the delegate of new log messages when they occur"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"pgLog:flag:context:file:function:line:tag:message:"}],"role":"symbol","title":"pgLog(_:flag:context:file:function:line:tag:message:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pgLog"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGLogFlag","preciseIdentifier":"c:@M@ConnectSDK@E@PGLogFlag"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"line"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ConnectSDK@objc(pl)PGLoggingDelegate(im)pgLog:flag:context:file:function:line:tag:message:","required":true,"modules":[{"name":"ConnectSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLoggingDelegate":{"role":"symbol","title":"PGLoggingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGLoggingDelegate"}],"abstract":[{"type":"text","text":"The logging class delegate protocol"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGLoggingDelegate"}],"url":"\/documentation\/connectsdk\/pgloggingdelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag":{"role":"symbol","title":"PGLogFlag","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGLogFlag"}],"abstract":[{"type":"text","text":"Log flags, used to determine the severity of a log message"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGLogFlag"}],"url":"\/documentation\/connectsdk\/pglogflag"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLoggingDelegate/pgLog(_:flag:context:file:function:line:tag:message:)":{"navigatorTitle":[{"kind":"identifier","text":"pgLog:flag:context:file:function:line:tag:message:"}],"role":"symbol","title":"pgLog(_:flag:context:file:function:line:tag:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pgLog"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGLogFlag","preciseIdentifier":"c:@M@ConnectSDK@E@PGLogFlag"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"line"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method notifies the delegate of new log messages when they occur"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate\/pgLog(_:flag:context:file:function:line:tag:message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgloggingdelegate\/pglog(_:flag:context:file:function:line:tag:message:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pgLog:flag:context:file:function:line:tag:message:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pgLog:flag:context:file:function:line:tag:message:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"pgLog:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"asynchronous"},{"kind":"text","text":" "},{"kind":"identifier","text":"flag:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag","preciseIdentifier":"c:@M@ConnectSDK@E@PGLogFlag","text":"PGLogFlag"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flag"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"file:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"file"},{"kind":"text","text":" "},{"kind":"identifier","text":"function:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"function"},{"kind":"text","text":" "},{"kind":"identifier","text":"line:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"line"},{"kind":"text","text":" "},{"kind":"identifier","text":"tag:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tag"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate\/title","value":"PGLoggingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate\/fragments","value":[{"kind":"identifier","text":"PGLoggingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/title","value":"PGLogFlag"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/fragments","value":[{"kind":"identifier","text":"PGLogFlag"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate~1pgLog(_:flag:context:file:function:line:tag:message:)\/title","value":"pgLog:flag:context:file:function:line:tag:message:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate~1pgLog(_:flag:context:file:function:line:tag:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pgLog:flag:context:file:function:line:tag:message:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}