{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poweredOff"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate\/poweredoff"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate\/poweredoff"]}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poweredOff"}],"navigatorTitle":[{"text":"PGManagerStatePoweredOff","kind":"identifier"}],"role":"symbol","modules":[{"name":"ConnectSDK"}],"roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGManagerState@PGManagerStatePoweredOff","title":"PGManagerState.poweredOff"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOff","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Bluetooth is currently powered off."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate","abstract":[{"text":"Represents the current state of a PGManager.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","kind":"symbol","type":"topic","title":"PGManagerState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGManagerState","kind":"identifier"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/poweredOff":{"abstract":[{"type":"text","text":"Bluetooth is currently powered off."}],"type":"topic","title":"PGManagerState.poweredOff","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGManagerStatePoweredOff"}],"url":"\/documentation\/connectsdk\/pgmanagerstate\/poweredoff","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poweredOff"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOff"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"PGManagerStatePoweredOff","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGManagerStatePoweredOff"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGManagerStatePoweredOff"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"PGManagerState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments","value":[{"text":"PGManagerState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOff\/title","value":"PGManagerStatePoweredOff"},{"value":[{"kind":"identifier","text":"PGManagerStatePoweredOff"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOff\/fragments"}]}]}