{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGManagerState@PGManagerStatePoweredOn","navigatorTitle":[{"kind":"identifier","text":"PGManagerStatePoweredOn"}],"title":"PGManagerState.poweredOn","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"poweredOn","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn"},"abstract":[{"text":"Bluetooth is currently powered on and available to use.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"poweredOn","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate\/poweredon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate\/poweredon"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/poweredOn":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn","abstract":[{"text":"Bluetooth is currently powered on and available to use.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"poweredOn","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGManagerStatePoweredOn"}],"title":"PGManagerState.poweredOn","url":"\/documentation\/connectsdk\/pgmanagerstate\/poweredon"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate","abstract":[{"text":"Represents the current state of a PGManager.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","kind":"symbol","type":"topic","title":"PGManagerState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGManagerState","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGManagerStatePoweredOn"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"PGManagerStatePoweredOn"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"PGManagerStatePoweredOn","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOn\/title","value":"PGManagerStatePoweredOn","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOn\/fragments","value":[{"text":"PGManagerStatePoweredOn","kind":"identifier"}],"op":"replace"},{"value":"PGManagerState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments","value":[{"kind":"identifier","text":"PGManagerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}