{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unauthorized","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGManagerState@PGManagerStateUnauthorized","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"PGManagerStateUnauthorized","kind":"identifier"}],"role":"symbol","title":"PGManagerState.unauthorized"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unauthorized"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The application is not authorized to use the Bluetooth Low Energy role."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate\/unauthorized"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate\/unauthorized"]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unauthorized","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGManagerState","kind":"identifier"}],"navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate","title":"PGManagerState","abstract":[{"text":"Represents the current state of a PGManager.","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/unauthorized":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unauthorized","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The application is not authorized to use the Bluetooth Low Energy role."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unauthorized","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGManagerStateUnauthorized"}],"type":"topic","title":"PGManagerState.unauthorized","url":"\/documentation\/connectsdk\/pgmanagerstate\/unauthorized"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGManagerStateUnauthorized"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGManagerStateUnauthorized"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGManagerStateUnauthorized"}]}],"kind":"declarations"}},{"op":"replace","value":"PGManagerState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGManagerState"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments"},{"op":"replace","value":"PGManagerStateUnauthorized","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unauthorized\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unauthorized\/fragments","value":[{"kind":"identifier","text":"PGManagerStateUnauthorized"}],"op":"replace"}]}]}