{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgmanagerstate\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgmanagerstate\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unknown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"State unknown, update imminent."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"PGManagerState.unknown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGManagerState@PGManagerStateUnknown","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGManagerStateUnknown"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"role":"symbol","title":"PGManagerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGManagerState"}],"abstract":[{"type":"text","text":"Represents the current state of a PGManager."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGManagerState"}],"url":"\/documentation\/connectsdk\/pgmanagerstate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/unknown":{"role":"symbol","title":"PGManagerState.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"State unknown, update imminent."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGManagerStateUnknown"}],"url":"\/documentation\/connectsdk\/pgmanagerstate\/unknown"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGManagerStateUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGManagerStateUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGManagerStateUnknown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title","value":"PGManagerState"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments","value":[{"kind":"identifier","text":"PGManagerState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unknown\/title","value":"PGManagerStateUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unknown\/fragments","value":[{"kind":"identifier","text":"PGManagerStateUnknown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}