{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/connectsdk\/pgmanagerstate\/unsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgmanagerstate\/unsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupported","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unsupported","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState"]]},"abstract":[{"type":"text","text":"The platform doesn’t support the Bluetooth Low Energy Central\/Client role."}],"metadata":{"symbolKind":"case","title":"PGManagerState.unsupported","role":"symbol","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGManagerState@PGManagerStateUnsupported","roleHeading":"Case","navigatorTitle":[{"text":"PGManagerStateUnsupported","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupported","kind":"identifier"}]},"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGManagerState","kind":"identifier"}],"navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate","title":"PGManagerState","abstract":[{"text":"Represents the current state of a PGManager.","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/unsupported":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unsupported","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The platform doesn’t support the Bluetooth Low Energy Central\/Client role.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unsupported","role":"symbol","navigatorTitle":[{"text":"PGManagerStateUnsupported","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate\/unsupported","title":"PGManagerState.unsupported","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGManagerStateUnsupported","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"PGManagerStateUnsupported","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PGManagerStateUnsupported","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PGManagerState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments","value":[{"kind":"identifier","text":"PGManagerState"}]},{"value":"PGManagerStateUnsupported","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unsupported\/title"},{"value":[{"text":"PGManagerStateUnsupported","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unsupported\/fragments"}]}]}