{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The current update progress expressed in percentage."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didchangefirmwareupdateprogress(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didchangefirmwareupdateprogress(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeFirmwareUpdateProgress","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"percentage","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The firmware update completed percentage.","type":"text"}]}],"name":"percentage"}]}],"sections":[],"metadata":{"title":"didChangeFirmwareUpdateProgress(_:)","navigatorTitle":[{"text":"didChangeFirmwareUpdateProgress:","kind":"identifier"}],"roleHeading":"Instance Method","required":true,"modules":[{"name":"ConnectSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didChangeFirmwareUpdateProgress","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManagerDelegate(im)didChangeFirmwareUpdateProgress:","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didChangeFirmwareUpdateProgress(_:)"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"navigatorTitle":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate","title":"PGFirmwareUpdateManagerDelegate","abstract":[{"text":"PGFirmwareUpdateManagerDelegate","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The delegate protocol for the PGFirmwareUpdateManager. The delegate must adopt the PGFirmwareUpdateManagerDelegate protocol."},{"text":" ","type":"text"},{"text":"The methods will provide the firmware update state information.","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didChangeFirmwareUpdateProgress(_:)":{"title":"didChangeFirmwareUpdateProgress(_:)","required":true,"type":"topic","abstract":[{"type":"text","text":"The current update progress expressed in percentage."}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didchangefirmwareupdateprogress(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeFirmwareUpdateProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didChangeFirmwareUpdateProgress(_:)","navigatorTitle":[{"kind":"identifier","text":"didChangeFirmwareUpdateProgress:"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"didChangeFirmwareUpdateProgress:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didChangeFirmwareUpdateProgress:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didChangeFirmwareUpdateProgress:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"percentage"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"PGFirmwareUpdateManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/fragments","value":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didChangeFirmwareUpdateProgress(_:)\/title","value":"didChangeFirmwareUpdateProgress:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didChangeFirmwareUpdateProgress(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didChangeFirmwareUpdateProgress:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}