{"metadata":{"modules":[{"name":"ConnectSDK"}],"required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCompleteFirmwareUpdate","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"didCompleteFirmwareUpdate"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManagerDelegate(im)didCompleteFirmwareUpdate","roleHeading":"Instance Method","role":"symbol","title":"didCompleteFirmwareUpdate()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteFirmwareUpdate"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didCompleteFirmwareUpdate()","interfaceLanguage":"swift"},"abstract":[{"text":"The firmware update is successfully completed.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didcompletefirmwareupdate()"]},{"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didcompletefirmwareupdate()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didCompleteFirmwareUpdate()":{"required":true,"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didcompletefirmwareupdate()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCompleteFirmwareUpdate","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"The firmware update is successfully completed."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didCompleteFirmwareUpdate"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didCompleteFirmwareUpdate()","title":"didCompleteFirmwareUpdate()","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate":{"title":"PGFirmwareUpdateManagerDelegate","navigatorTitle":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"abstract":[{"text":"PGFirmwareUpdateManagerDelegate","type":"text"},{"text":" ","type":"text"},{"text":"The delegate protocol for the PGFirmwareUpdateManager. The delegate must adopt the PGFirmwareUpdateManagerDelegate protocol.","type":"text"},{"text":" ","type":"text"},{"text":"The methods will provide the firmware update state information.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"didCompleteFirmwareUpdate","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didCompleteFirmwareUpdate","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didCompleteFirmwareUpdate"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didCompleteFirmwareUpdate()\/title","value":"didCompleteFirmwareUpdate","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"didCompleteFirmwareUpdate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didCompleteFirmwareUpdate()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/title","value":"PGFirmwareUpdateManagerDelegate"},{"value":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/fragments"}]}]}