{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFailToUpdateFirmwareWithError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error which occurred."}]}],"name":"error"}]}],"abstract":[{"text":"The firmware update failed.","type":"text"}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"didFailToUpdateFirmwareWithError:","kind":"identifier"}],"title":"didFailToUpdateFirmwareWithError(_:)","externalID":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManagerDelegate(im)didFailToUpdateFirmwareWithError:","role":"symbol","required":true,"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didFailToUpdateFirmwareWithError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didfailtoupdatefirmwarewitherror(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didfailtoupdatefirmwarewitherror(_:)"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didFailToUpdateFirmwareWithError(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didFailToUpdateFirmwareWithError(_:)":{"type":"topic","abstract":[{"text":"The firmware update failed.","type":"text"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didFailToUpdateFirmwareWithError(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didFailToUpdateFirmwareWithError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"didFailToUpdateFirmwareWithError:","kind":"identifier"}],"title":"didFailToUpdateFirmwareWithError(_:)","role":"symbol","url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didfailtoupdatefirmwarewitherror(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"title":"PGFirmwareUpdateManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"PGFirmwareUpdateManagerDelegate"},{"type":"text","text":" "},{"text":"The delegate protocol for the PGFirmwareUpdateManager. The delegate must adopt the PGFirmwareUpdateManagerDelegate protocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The methods will provide the firmware update state information."}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"didFailToUpdateFirmwareWithError:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailToUpdateFirmwareWithError:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didFailToUpdateFirmwareWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didFailToUpdateFirmwareWithError(_:)\/title","op":"replace","value":"didFailToUpdateFirmwareWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didFailToUpdateFirmwareWithError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didFailToUpdateFirmwareWithError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/title","value":"PGFirmwareUpdateManagerDelegate"},{"value":[{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/fragments"}]}]}