{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate"]]},"abstract":[{"type":"text","text":"The firmware update has begun."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didStartFirmwareUpdate","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didStartFirmwareUpdate()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didstartfirmwareupdate()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didstartfirmwareupdate()"]}],"sections":[],"metadata":{"symbolKind":"method","required":true,"title":"didStartFirmwareUpdate()","externalID":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManagerDelegate(im)didStartFirmwareUpdate","modules":[{"name":"ConnectSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didStartFirmwareUpdate","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"didStartFirmwareUpdate","kind":"identifier"}],"roleHeading":"Instance Method"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didStartFirmwareUpdate()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didStartFirmwareUpdate","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didstartfirmwareupdate()","title":"didStartFirmwareUpdate()","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didStartFirmwareUpdate()","role":"symbol","abstract":[{"type":"text","text":"The firmware update has begun."}],"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didStartFirmwareUpdate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"title":"PGFirmwareUpdateManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"PGFirmwareUpdateManagerDelegate"},{"type":"text","text":" "},{"text":"The delegate protocol for the PGFirmwareUpdateManager. The delegate must adopt the PGFirmwareUpdateManagerDelegate protocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The methods will provide the firmware update state information."}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"didStartFirmwareUpdate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didStartFirmwareUpdate"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didStartFirmwareUpdate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"didStartFirmwareUpdate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didStartFirmwareUpdate()\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didStartFirmwareUpdate()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didStartFirmwareUpdate","kind":"identifier"}],"op":"replace"},{"value":"PGFirmwareUpdateManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}