{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Create-the-Central-Manager-object","level":2,"type":"heading","text":"Create the Central Manager object"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To initiate and set the delegate to the central manager object, confirm "},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","isActive":true,"type":"reference"},{"text":" and use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/init(delegate:enableRestoration:)"},{"type":"text","text":" method."}]},{"level":3,"anchor":"Initiate-new-connections","type":"heading","text":"Initiate new connections"},{"inlineContent":[{"type":"text","text":"To initiate a new connection, create a connection QR code by invoking the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"},{"text":" method ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnection(withImageSize:)","isActive":true},{"type":"text","text":" (make sure Bluetooth is on by checking the PGCentralManager "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/state"},{"type":"text","text":")."}],"type":"paragraph"},{"level":4,"type":"heading","text":"Swift","anchor":"Swift"},{"syntax":"swift","code":["import ConnectSDK","...","class ViewController: UIViewController, PGCentralManagerDelegate {","...","var central: PGCentralManager?","...","func setup() {","    central = PGCentralManager(delegate: self, enableRestoration: false)","}"],"type":"codeListing"},{"level":4,"text":"Objective-C","type":"heading","anchor":"Objective-C"},{"type":"codeListing","code":["#import <ConnectSDK\/ConnectSDK.h>","...","@interface ViewController () <PGCentralManagerDelegate>","@property PGCentralManager *central;","...","- (void)setup {","   self.central = [[PGCentralManager alloc] initWithDelegate:self enableRestoration:NO];","}"],"syntax":"objc"}]}],"kind":"article","metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"ConnectSDK"}],"title":"Initiate Connection"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/initate-connection","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/initate-connection"]},{"paths":["\/documentation\/connectsdk\/initate-connection"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/initiateScannerConnection(withImageSize:)":{"title":"initiateScannerConnection(withImageSize:)","abstract":[{"type":"text","text":"This method generates an identifier which is embedded in a QR code for the Scanner to Scan, which the Scanner will advertise with."},{"type":"text","text":" "},{"text":"The central begins scanning for a Scanner advertising the generated identifier, and on discovering will connect to the Scanner.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"After Scanner interrogation, the scanner will become ready and "},{"type":"codeVoice","code":"-centralManager:scannerDidBecomeReady:"},{"type":"text","text":" will be called."},{"text":" ","type":"text"},{"type":"text","text":"This method is a convenience method which calls "},{"type":"codeVoice","code":"-initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale"},{"text":" ","type":"text"},{"text":"with correction level Q (appropriate for dirty environments such as a warehouse) and the scale factor of the main screen","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnection(withImageSize:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initiateScannerConnectionWithImageSize:"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnection(withimagesize:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initiateScannerConnection","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","role":"symbol","title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCentralManagerDelegate"}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","title":"PGCentralManagerDelegate","abstract":[{"text":"PGCentralManagerDelegate","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/init(delegate:enableRestoration:)":{"url":"\/documentation\/connectsdk\/pgcentralmanager\/init(delegate:enablerestoration:)","abstract":[{"text":"Init the central manager with a delegate and optionally enable restoration","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:enableRestoration:"}],"title":"init(delegate:enableRestoration:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCentralManagerDelegate","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate"},{"text":", ","kind":"text"},{"text":"enableRestoration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/init(delegate:enableRestoration:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager/state":{"url":"\/documentation\/connectsdk\/pgmanager\/state","abstract":[{"text":"State of the PGManager","type":"text"}],"navigatorTitle":[{"text":"state","kind":"identifier"}],"title":"state","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGManagerState","preciseIdentifier":"c:@M@ConnectSDK@E@PGManagerState"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/state"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnection(withImageSize:)\/title","op":"replace","value":"initiateScannerConnectionWithImageSize:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initiateScannerConnectionWithImageSize:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnection(withImageSize:)\/fragments"},{"value":"PGCentralManager","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGCentralManager"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments"},{"op":"replace","value":"PGCentralManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGCentralManagerDelegate"}],"op":"replace"},{"value":"initWithDelegate:enableRestoration:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1init(delegate:enableRestoration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDelegate:enableRestoration:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1init(delegate:enableRestoration:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager~1state\/title","op":"replace","value":"state"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager~1state\/fragments","op":"replace","value":[{"kind":"identifier","text":"state"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}