{"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType"},"variants":[{"paths":["\/documentation\/connectsdk\/pgbuttontriggereventtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgbuttontriggereventtype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/doubleTrigger"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/RawRepresentable-Implementations"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"The button trigger event types","type":"text"}],"metadata":{"externalID":"c:@M@ConnectSDK@E@PGButtonTriggerEventType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGButtonTriggerEventType","kind":"identifier"}],"role":"symbol","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGButtonTriggerEventType"}],"title":"PGButtonTriggerEventType","symbolKind":"enum","roleHeading":"Enumeration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGButtonTriggerEventType"}]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType/doubleTrigger":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"doubleTrigger","kind":"identifier"}],"navigatorTitle":[{"text":"PGButtonTriggerEventTypeDoubleTrigger","kind":"identifier"}],"title":"PGButtonTriggerEventType.doubleTrigger","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/doubleTrigger","role":"symbol","abstract":[{"type":"text","text":"The double button trigger event type"}],"type":"topic","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype\/doubletrigger","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType/Equatable-Implementations":{"kind":"article","role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/Equatable-Implementations","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype\/equatable-implementations","title":"Equatable Implementations"},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGButtonTriggerEventType","kind":"identifier"}],"navigatorTitle":[{"text":"PGButtonTriggerEventType","kind":"identifier"}],"title":"PGButtonTriggerEventType","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType","type":"topic","abstract":[{"type":"text","text":"The button trigger event types"}]},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType/RawRepresentable-Implementations":{"url":"\/documentation\/connectsdk\/pgbuttontriggereventtype\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/init(rawValue:)","abstract":[],"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.proglove.Mark2SDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"PGButtonTriggerEventType","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"PGButtonTriggerEventType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGButtonTriggerEventType"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType\/doubleTrigger"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGButtonTriggerEventType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType~1doubleTrigger\/title","value":"PGButtonTriggerEventTypeDoubleTrigger","op":"replace"},{"value":[{"text":"PGButtonTriggerEventTypeDoubleTrigger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType~1doubleTrigger\/fragments"},{"value":"PGButtonTriggerEventType","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/title"},{"value":[{"text":"PGButtonTriggerEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}