{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCaptureImageRequest"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Used to retrieve "},{"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","isActive":true}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcaptureimagerequest"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcaptureimagerequest"]}],"metadata":{"modules":[{"name":"ConnectSDK"}],"roleHeading":"Class","title":"PGCaptureImageRequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCaptureImageRequest"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@ConnectSDK@objc(cs)PGCaptureImageRequest","navigatorTitle":[{"kind":"identifier","text":"PGCaptureImageRequest"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"kind":"relationships","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/init(_:resolution:timeout:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/jpegQuality","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/resolution","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/timeout"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest"},"abstract":[{"type":"text","text":"PGCaptureImageRequest"}],"references":{"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest":{"abstract":[{"type":"text","text":"PGCaptureImageRequest"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCaptureImageRequest"}],"url":"\/documentation\/connectsdk\/pgcaptureimagerequest","navigatorTitle":[{"text":"PGCaptureImageRequest","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PGCaptureImageRequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","type":"topic"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImage":{"url":"\/documentation\/connectsdk\/pgimage","abstract":[{"type":"text","text":"Object containing image data and image options"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","title":"PGImage","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGImage","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGImage"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest/resolution":{"abstract":[{"type":"text","text":"Resolution of the image"}],"navigatorTitle":[{"text":"resolution","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcaptureimagerequest\/resolution","role":"symbol","title":"resolution","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/resolution","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution","text":"PGImageResolution","kind":"typeIdentifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest/jpegQuality":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/jpegQuality","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"jpegQuality","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"jpegQuality"}],"type":"topic","abstract":[{"type":"text","text":"Quality of the image"}],"title":"jpegQuality","kind":"symbol","url":"\/documentation\/connectsdk\/pgcaptureimagerequest\/jpegquality","role":"symbol"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest/init(_:resolution:timeout:)":{"navigatorTitle":[{"text":"init:resolution:timeout:","kind":"identifier"}],"title":"init(_:resolution:timeout:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"resolution","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution","text":"PGImageResolution","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/init(_:resolution:timeout:)","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgcaptureimagerequest\/init(_:resolution:timeout:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest/timeout":{"abstract":[{"type":"text","text":"Timeout in miliseconds"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/connectsdk\/pgcaptureimagerequest\/timeout","navigatorTitle":[{"kind":"identifier","text":"timeout"}],"kind":"symbol","role":"symbol","title":"timeout","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/timeout","type":"topic"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"PGCaptureImageRequest","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PGCaptureImageRequest"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PGCaptureImageRequest","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/jpegQuality","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/resolution","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/timeout"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/init(_:resolution:timeout:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PGCaptureImageRequest","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PGCaptureImageRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGCaptureImageRequest"}]},{"op":"replace","value":"PGImage","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/fragments","value":[{"text":"PGImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1resolution\/title","op":"replace","value":"resolution"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1resolution\/fragments","value":[{"kind":"identifier","text":"resolution"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1jpegQuality\/title","value":"jpegQuality"},{"value":[{"text":"jpegQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1jpegQuality\/fragments"},{"value":"init:resolution:timeout:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1init(_:resolution:timeout:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1init(_:resolution:timeout:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"init:resolution:timeout:","kind":"identifier"}]},{"op":"replace","value":"timeout","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1timeout\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1timeout\/fragments","op":"replace","value":[{"kind":"identifier","text":"timeout"}]}]}]}