{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"PGCentralManagerDelegate"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCentralManagerDelegate"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","text":"PGManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGManagerDelegate"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate of a {@link PGCentralManager} object must adopt the "},{"text":"PGCentralManagerDelegate","type":"text"},{"type":"text","text":" protocol."},{"type":"text","text":" "},{"text":"The optional methods allow for the discovery and connection of peripherals.","type":"text"}]}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:connectingToScanner:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didDisconnectFromScanner:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didFailToConnectToScanner:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didFailToInitiateConnection:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didLostConnectionAndReconnectingToScanner:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didStartSearchingForIndicator:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidBecomeReady:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidConnect:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate"]},{"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCentralManagerDelegate"}],"role":"symbol","symbolKind":"protocol","title":"PGCentralManagerDelegate","externalID":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate","roleHeading":"Protocol","modules":[{"name":"ConnectSDK"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGManagerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgmanagerdelegate","navigatorTitle":[{"kind":"identifier","text":"PGManagerDelegate"}],"abstract":[{"type":"text","text":"The delegate of a {@link PGManager} object must adopt the "},{"text":"PGManagerDelegate","type":"text"},{"type":"text","text":" protocol. The"},{"type":"text","text":" "},{"text":"single required method indicates the availability of the manager.","type":"text"}],"title":"PGManagerDelegate","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:scannerDidConnect:)":{"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidConnect:)","title":"centralManager(_:scannerDidConnect:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"centralManager:scannerDidConnect:"}],"abstract":[{"type":"text","text":"Scanner is connected but still not ready for use."}],"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"text":", ","kind":"text"},{"text":"scannerDidConnect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":")"}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidconnect:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:didDisconnectFromScanner:error:)":{"title":"centralManager(_:didDisconnectFromScanner:error:)","navigatorTitle":[{"kind":"identifier","text":"centralManager:didDisconnectFromScanner:error:"}],"required":true,"kind":"symbol","abstract":[{"type":"text","text":"The central disconnected from the Scanner."}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:diddisconnectfromscanner:error:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","kind":"typeIdentifier","text":"PGCentralManager"},{"text":", ","kind":"text"},{"text":"didDisconnectFromScanner","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didDisconnectFromScanner:error:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:didFailToInitiateConnection:)":{"navigatorTitle":[{"text":"centralManager:didFailToInitiateConnection:","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didfailtoinitiateconnection:)","abstract":[{"text":"The central manager failed to initiate Scanner connection.","type":"text"}],"title":"centralManager(_:didFailToInitiateConnection:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didFailToInitiateConnection:)","required":true,"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"kind":"text","text":", "},{"text":"didFailToInitiateConnection","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"role":"symbol","title":"PGCentralManagerDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","navigatorTitle":[{"text":"PGCentralManagerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"PGCentralManagerDelegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:didStartSearchingForIndicator:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","text":"PGCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didStartSearchingForIndicator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didstartsearchingforindicator:)","role":"symbol","navigatorTitle":[{"text":"centralManager:didStartSearchingForIndicator:","kind":"identifier"}],"title":"centralManager(_:didStartSearchingForIndicator:)","abstract":[{"type":"text","text":"The central is searching for a peripheral scanner with an indicator."}],"required":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didStartSearchingForIndicator:)","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:didFailToConnectToScanner:error:)":{"required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didfailtoconnecttoscanner:error:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didFailToConnectToScanner:error:)","abstract":[{"text":"The central failed to connect to the Scanner.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","text":"PGCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailToConnectToScanner","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"centralManager:didFailToConnectToScanner:error:","kind":"identifier"}],"title":"centralManager(_:didFailToConnectToScanner:error:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:scannerDidBecomeReady:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidBecomeReady:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","text":"PGCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scannerDidBecomeReady"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"centralManager:scannerDidBecomeReady:"}],"required":true,"title":"centralManager(_:scannerDidBecomeReady:)","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidbecomeready:)","abstract":[{"text":"The Scanner became ready","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:connectingToScanner:)":{"navigatorTitle":[{"text":"centralManager:connectingToScanner:","kind":"identifier"}],"title":"centralManager(_:connectingToScanner:)","abstract":[{"type":"text","text":"Now connecting to a Scanner"}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:connectingtoscanner:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:connectingToScanner:)","required":true,"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"kind":"text","text":", "},{"text":"connectingToScanner","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral"},{"kind":"text","text":")"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:didLostConnectionAndReconnectingToScanner:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","text":"PGCentralManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didLostConnectionAndReconnectingToScanner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"centralManager:didLostConnectionAndReconnectingToScanner:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"The central manager did lost connection to Scanner and trying to reconnect."}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didlostconnectionandreconnectingtoscanner:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didLostConnectionAndReconnectingToScanner:)","kind":"symbol","type":"topic","role":"symbol","title":"centralManager(_:didLostConnectionAndReconnectingToScanner:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PGCentralManagerDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGCentralManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PGCentralManagerDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:connectingToScanner:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didDisconnectFromScanner:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didFailToConnectToScanner:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didFailToInitiateConnection:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didLostConnectionAndReconnectingToScanner:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didStartSearchingForIndicator:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidBecomeReady:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidConnect:)"]}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCentralManagerDelegate"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"PGManagerDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGManagerDelegate"},{"text":">","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/title","value":"PGManagerDelegate"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGManagerDelegate"}]},{"value":"centralManager:scannerDidConnect:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidConnect:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:scannerDidConnect:"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidConnect:)\/fragments"},{"value":"centralManager:didDisconnectFromScanner:error:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didDisconnectFromScanner:error:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"centralManager:didDisconnectFromScanner:error:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didDisconnectFromScanner:error:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didFailToInitiateConnection:)\/title","value":"centralManager:didFailToInitiateConnection:"},{"value":[{"text":"- ","kind":"text"},{"text":"centralManager:didFailToInitiateConnection:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didFailToInitiateConnection:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title","value":"PGCentralManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGCentralManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didStartSearchingForIndicator:)\/title","value":"centralManager:didStartSearchingForIndicator:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didStartSearchingForIndicator:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"centralManager:didStartSearchingForIndicator:","kind":"identifier"}]},{"value":"centralManager:didFailToConnectToScanner:error:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didFailToConnectToScanner:error:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didFailToConnectToScanner:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"centralManager:didFailToConnectToScanner:error:","kind":"identifier"}],"op":"replace"},{"value":"centralManager:scannerDidBecomeReady:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidBecomeReady:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"centralManager:scannerDidBecomeReady:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidBecomeReady:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:connectingToScanner:)\/title","value":"centralManager:connectingToScanner:","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:connectingToScanner:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"centralManager:connectingToScanner:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didLostConnectionAndReconnectingToScanner:)\/title","value":"centralManager:didLostConnectionAndReconnectingToScanner:","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didLostConnectionAndReconnectingToScanner:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"centralManager:didLostConnectionAndReconnectingToScanner:"}]}]}]}