{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"abstract":[{"type":"text","text":"PGCentralManager"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager","modules":[{"name":"ConnectSDK"}],"title":"PGCentralManager","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}]},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/init(delegate:enableRestoration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cloudConnectionDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/configurationManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedScanner","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedToCloud","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/continuousSearchEnabled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/delegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/displayManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/feedbackManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/firmwareUpdateManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/imageManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/isSearching","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/scanningForIndicator"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/add(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cancelScannerConnection(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectToScanner(withIndicator:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnection(withImageSize:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/stopScan()"]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Entry point to the central role. Commands should only be issued when its state is "},{"type":"codeVoice","code":"PGManagerStatePoweredOn"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/connectToScanner(withIndicator:)":{"abstract":[{"text":"Connect to a scanner using a given indicator. Previous connection will be canceled.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectToScanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIndicator"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"connectToScanner(withIndicator:)","navigatorTitle":[{"text":"connectToScannerWithIndicator:","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectToScanner(withIndicator:)","url":"\/documentation\/connectsdk\/pgcentralmanager\/connecttoscanner(withindicator:)","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/firmwareUpdateManager":{"title":"firmwareUpdateManager","abstract":[{"text":"The firmware update manager.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"firmwareUpdateManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGFirmwareUpdateManager","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManager"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanager\/firmwareupdatemanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/firmwareUpdateManager","navigatorTitle":[{"text":"firmwareUpdateManager","kind":"identifier"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/stopScan()":{"abstract":[{"type":"text","text":"Use this method to stop scanning process after initiateScannerConnectionWithImageSize is invoked and before pairing QR code is scanned."},{"type":"text","text":" "},{"type":"text","text":"If connection with Scanner is established use cancelScannerConnection: to cancel the connection."}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"stopScan","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/stopScan()","url":"\/documentation\/connectsdk\/pgcentralmanager\/stopscan()","title":"stopScan()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopScan"},{"text":"()","kind":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/scanningForIndicator":{"navigatorTitle":[{"text":"scanningForIndicator","kind":"identifier"}],"role":"symbol","title":"scanningForIndicator","type":"topic","abstract":[{"type":"text","text":"The indicator the central is scanning for. This is a random string which is included in the QR code generated"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanningForIndicator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/scanningforindicator","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/scanningForIndicator"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/configurationManager":{"title":"configurationManager","navigatorTitle":[{"kind":"identifier","text":"configurationManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/configurationManager","role":"symbol","abstract":[{"type":"text","text":"The configuration manager."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configurationManager"},{"kind":"text","text":": "},{"text":"PGConfigurationManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager\/configurationmanager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/continuousSearchEnabled":{"navigatorTitle":[{"kind":"identifier","text":"continuousSearchEnabled"}],"role":"symbol","title":"continuousSearchEnabled","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"When set to YES (true), continuousSearchEnabled option will enable continuous discovery of scanners, meaning that central manager will continue to search for scanners even when connection is established."},{"type":"text","text":" "},{"type":"text","text":"Common use case is with fixed connection barcode, by scanning connection barcode, the current connection will be dropped and new one established."},{"type":"text","text":" "},{"type":"text","text":"This option does not affect current central state hence will not start or stop searching process."},{"type":"text","text":" "},{"type":"text","text":"When set to NO (false) the searching process will be terminated when connection is established."},{"text":" ","type":"text"},{"type":"text","text":"Default value is NO (false)."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continuousSearchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/continuoussearchenabled","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/continuousSearchEnabled"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/cancelScannerConnection(_:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelScannerConnection:"}],"role":"symbol","title":"cancelScannerConnection(_:)","type":"topic","kind":"symbol","abstract":[{"text":"Use this method to cancel the established connection with Scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelScannerConnection"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"text":")","kind":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/cancelscannerconnection(_:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cancelScannerConnection(_:)"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/add(_:)":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/add(_:)","url":"\/documentation\/connectsdk\/pgcentralmanager\/add(_:)","kind":"symbol","title":"add(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGMockPeripheral","kind":"typeIdentifier","text":"PGMockPeripheral"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"add:"}],"abstract":[{"type":"text","text":"Add a mock peripheral. PGPeripheral must be created from "},{"type":"codeVoice","code":"PGMockPeripheral.init(identifier:)"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/displayManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/displayManager","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"displayManager"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager\/displaymanager","abstract":[{"type":"text","text":"The display manager. Use this manager to configure screen settings."}],"title":"displayManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"displayManager","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGDisplayManager","text":"PGDisplayManager"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","role":"symbol","title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGManager"}],"navigatorTitle":[{"kind":"identifier","text":"PGManager"}],"url":"\/documentation\/connectsdk\/pgmanager","title":"PGManager","abstract":[{"text":"PGManager","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/connectedToCloud":{"url":"\/documentation\/connectsdk\/pgcentralmanager\/connectedtocloud","abstract":[{"type":"text","text":"A Boolean value to check if we are currently connected to Insight Cloud"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedToCloud","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectedToCloud","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"connectedToCloud","kind":"symbol","navigatorTitle":[{"text":"connectedToCloud","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/cloudConnectionDelegate":{"navigatorTitle":[{"kind":"identifier","text":"cloudConnectionDelegate"}],"role":"symbol","title":"cloudConnectionDelegate","type":"topic","abstract":[{"type":"text","text":"A delegate used for insight updates"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cloudConnectionDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCloudConnectionDelegate","text":"PGCloudConnectionDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/cloudconnectiondelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cloudConnectionDelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/imageManager":{"navigatorTitle":[{"text":"imageManager","kind":"identifier"}],"role":"symbol","title":"imageManager","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The image manager. Use this manager to capture a photo using the connected device."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"imageManager","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGImageManager","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGImageManager"},{"text":"?","kind":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/imagemanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/imageManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/isSearching":{"navigatorTitle":[{"text":"isSearching","kind":"identifier"}],"role":"symbol","title":"isSearching","type":"topic","abstract":[{"type":"text","text":"A Boolean indicating whether the search for a scanner is currently in progress."},{"type":"text","text":" "},{"type":"text","text":"The value of this property is set to YES when a search is initiated and remains in that state until the search results (or an appropriate error) are delivered, at which time the property is set to NO."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSearching"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/issearching","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/isSearching"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/delegate":{"abstract":[{"text":"The central delegate","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/delegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/delegate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGCentralManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate"},{"text":"?","kind":"text"}],"title":"delegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)":{"role":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnectionwithqrcorrectionlevel(_:imagesize:scale:)","title":"initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initiateScannerConnectionWithQRCorrectionLevel","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGPairingQRGeneratorErrorCorrectionLevel","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel"},{"text":", ","kind":"text"},{"text":"imageSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"navigatorTitle":[{"text":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","abstract":[{"type":"text","text":"This method generates an identifier which is embedded in a QR code for the Scanner to Scan, which the Scanner will advertise with."},{"type":"text","text":" "},{"text":"The central begins scanning for a Scanner advertising the generated identifier, and on discovering will connect to the Scanner.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"After Scanner interrogation, the scanner will become ready and "},{"code":"-centralManager:scannerDidBecomeReady:","type":"codeVoice"},{"text":" will be called","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/init(delegate:enableRestoration:)":{"url":"\/documentation\/connectsdk\/pgcentralmanager\/init(delegate:enablerestoration:)","abstract":[{"text":"Init the central manager with a delegate and optionally enable restoration","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:enableRestoration:"}],"title":"init(delegate:enableRestoration:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCentralManagerDelegate","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate"},{"text":", ","kind":"text"},{"text":"enableRestoration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/init(delegate:enableRestoration:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/initiateScannerConnection(withImageSize:)":{"title":"initiateScannerConnection(withImageSize:)","abstract":[{"type":"text","text":"This method generates an identifier which is embedded in a QR code for the Scanner to Scan, which the Scanner will advertise with."},{"type":"text","text":" "},{"text":"The central begins scanning for a Scanner advertising the generated identifier, and on discovering will connect to the Scanner.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"After Scanner interrogation, the scanner will become ready and "},{"type":"codeVoice","code":"-centralManager:scannerDidBecomeReady:"},{"type":"text","text":" will be called."},{"text":" ","type":"text"},{"type":"text","text":"This method is a convenience method which calls "},{"type":"codeVoice","code":"-initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale"},{"text":" ","type":"text"},{"text":"with correction level Q (appropriate for dirty environments such as a warehouse) and the scale factor of the main screen","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnection(withImageSize:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initiateScannerConnectionWithImageSize:"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnection(withimagesize:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initiateScannerConnection","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/connectedScanner":{"role":"symbol","title":"connectedScanner","url":"\/documentation\/connectsdk\/pgcentralmanager\/connectedscanner","abstract":[{"type":"text","text":"The connected scanner, if one is connected"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedScanner","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectedScanner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"connectedScanner"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/feedbackManager":{"url":"\/documentation\/connectsdk\/pgcentralmanager\/feedbackmanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/feedbackManager","title":"feedbackManager","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"feedbackManager"}],"abstract":[{"text":"The feedback manager. Use this manager to play feedback sequences on a connected device.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"feedbackManager","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGFeedbackManager","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFeedbackManager","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGCentralManager","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"PGCentralManager","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGCentralManager"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cloudConnectionDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/configurationManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedScanner","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedToCloud","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/continuousSearchEnabled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/delegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/displayManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/feedbackManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/firmwareUpdateManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/imageManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/isSearching","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/scanningForIndicator"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/add(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cancelScannerConnection(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectToScanner(withIndicator:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/init(delegate:enableRestoration:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnection(withImageSize:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/stopScan()"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGManager","text":"PGManager"}]}]},"op":"replace"},{"op":"replace","value":"connectToScannerWithIndicator:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectToScanner(withIndicator:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectToScanner(withIndicator:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"connectToScannerWithIndicator:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1firmwareUpdateManager\/title","op":"replace","value":"firmwareUpdateManager"},{"value":[{"text":"firmwareUpdateManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1firmwareUpdateManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1stopScan()\/title","op":"replace","value":"stopScan"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1stopScan()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopScan"}]},{"value":"scanningForIndicator","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1scanningForIndicator\/title"},{"value":[{"text":"scanningForIndicator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1scanningForIndicator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1configurationManager\/title","value":"configurationManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1configurationManager\/fragments","value":[{"text":"configurationManager","kind":"identifier"}],"op":"replace"},{"value":"continuousSearchEnabled","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1continuousSearchEnabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1continuousSearchEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"continuousSearchEnabled"}]},{"value":"cancelScannerConnection:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1cancelScannerConnection(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"cancelScannerConnection:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1cancelScannerConnection(_:)\/fragments","op":"replace"},{"op":"replace","value":"add:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1add(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"add:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1add(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1displayManager\/title","value":"displayManager","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1displayManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"displayManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","value":[{"text":"PGCentralManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments"},{"value":"PGManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/title","op":"replace"},{"op":"replace","value":[{"text":"PGManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectedToCloud\/title","op":"replace","value":"connectedToCloud"},{"value":[{"kind":"identifier","text":"connectedToCloud"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectedToCloud\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1cloudConnectionDelegate\/title","op":"replace","value":"cloudConnectionDelegate"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1cloudConnectionDelegate\/fragments","value":[{"text":"cloudConnectionDelegate","kind":"identifier"}],"op":"replace"},{"value":"imageManager","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1imageManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1imageManager\/fragments","value":[{"text":"imageManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1isSearching\/title","op":"replace","value":"isSearching"},{"value":[{"text":"isSearching","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1isSearching\/fragments"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1delegate\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)\/title","value":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)\/fragments","op":"replace"},{"value":"initWithDelegate:enableRestoration:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1init(delegate:enableRestoration:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1init(delegate:enableRestoration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:enableRestoration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnection(withImageSize:)\/title","op":"replace","value":"initiateScannerConnectionWithImageSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnection(withImageSize:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initiateScannerConnectionWithImageSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectedScanner\/title","value":"connectedScanner","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectedScanner\/fragments","op":"replace","value":[{"text":"connectedScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1feedbackManager\/title","value":"feedbackManager"},{"value":[{"text":"feedbackManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1feedbackManager\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}