{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCloudConnectionDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgcloudconnectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcloudconnectiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate\/cloudConnectionStatusDidUpdate(_:error:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCloudConnectionDelegate"}],"title":"PGCloudConnectionDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ConnectSDK@objc(pl)PGCloudConnectionDelegate","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionDelegate/cloudConnectionStatusDidUpdate(_:error:)":{"navigatorTitle":[{"kind":"identifier","text":"cloudConnectionStatusDidUpdate:error:"}],"role":"symbol","title":"cloudConnectionStatusDidUpdate(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudConnectionStatusDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGCloudConnectionStatus","preciseIdentifier":"c:@M@ConnectSDK@E@PGCloudConnectionStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Cloud connection status for Insight updated"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate\/cloudConnectionStatusDidUpdate(_:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgcloudconnectiondelegate\/cloudconnectionstatusdidupdate(_:error:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionDelegate":{"role":"symbol","title":"PGCloudConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCloudConnectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionDelegate"}],"url":"\/documentation\/connectsdk\/pgcloudconnectiondelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"PGCloudConnectionDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGCloudConnectionDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate\/cloudConnectionStatusDidUpdate(_:error:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCloudConnectionDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate~1cloudConnectionStatusDidUpdate(_:error:)\/title","value":"cloudConnectionStatusDidUpdate:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate~1cloudConnectionStatusDidUpdate(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cloudConnectionStatusDidUpdate:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/title","value":"PGCloudConnectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}