{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgclouderrordomain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgclouderrordomain"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The Cloud Error Domain"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudErrorDomain","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGCloudErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"PGCloudErrorDomain","kind":"identifier"}],"role":"symbol","roleHeading":"Global Variable","symbolKind":"var","externalID":"c:@PGCloudErrorDomain","modules":[{"name":"ConnectSDK"}],"title":"PGCloudErrorDomain","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"PGCloudErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudErrorDomain":{"url":"\/documentation\/connectsdk\/pgclouderrordomain","title":"PGCloudErrorDomain","abstract":[{"text":"The Cloud Error Domain","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PGCloudErrorDomain"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudErrorDomain","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCloudErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"PGCloudErrorDomain"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"PGCloudErrorDomain","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"PGCloudErrorDomain"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudErrorDomain\/title","value":"PGCloudErrorDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudErrorDomain\/fragments","value":[{"text":"PGCloudErrorDomain","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}