{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus"]},{"paths":["\/documentation\/connectsdk\/pgcloudconnectionstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCloudConnectionStatus"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus"},"abstract":[{"type":"text","text":"Connection status to Insight portal"}],"metadata":{"modules":[{"name":"ConnectSDK"}],"role":"symbol","navigatorTitle":[{"text":"PGCloudConnectionStatus","kind":"identifier"}],"title":"PGCloudConnectionStatus","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudConnectionStatus","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGCloudConnectionStatus","roleHeading":"Enumeration"},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connecting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/disconnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/error"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCloudConnectionStatus","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus","abstract":[{"type":"text","text":"Connection status to Insight portal"}],"navigatorTitle":[{"text":"PGCloudConnectionStatus","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","title":"PGCloudConnectionStatus"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/Equatable-Implementations":{"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/equatable-implementations","abstract":[],"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/RawRepresentable-Implementations","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/disconnected":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusDisconnected"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/disconnected","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/disconnected","title":"PGCloudConnectionStatus.disconnected","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnected"}]},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/connecting":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"type":"topic","abstract":[],"title":"PGCloudConnectionStatus.connecting","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusConnecting"}],"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/connecting","kind":"symbol"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/init(rawValue:)","role":"symbol","kind":"symbol","abstract":[],"title":"init(rawValue:)","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/error":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/error","role":"symbol","title":"PGCloudConnectionStatus.error","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/error","navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatusError"}]},"doc://com.proglove.Mark2SDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus/connected":{"type":"topic","navigatorTitle":[{"text":"PGCloudConnectionStatusConnected","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connected","role":"symbol","kind":"symbol","abstract":[],"title":"PGCloudConnectionStatus.connected","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus\/connected","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PGCloudConnectionStatus","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"PGCloudConnectionStatus"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGCloudConnectionStatus"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/connecting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/disconnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus\/error"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGCloudConnectionStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/title","op":"replace","value":"PGCloudConnectionStatus"},{"value":[{"text":"PGCloudConnectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/fragments"},{"value":"PGCloudConnectionStatusDisconnected","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1disconnected\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGCloudConnectionStatusDisconnected"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1disconnected\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connecting\/title","value":"PGCloudConnectionStatusConnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connecting\/fragments","value":[{"text":"PGCloudConnectionStatusConnecting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1error\/title","value":"PGCloudConnectionStatusError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1error\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionStatusError"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connected\/title","value":"PGCloudConnectionStatusConnected","op":"replace"},{"op":"replace","value":[{"text":"PGCloudConnectionStatusConnected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus~1connected\/fragments"}]}]}