{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManagerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration Delegate"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManagerDelegate"}],"title":"PGConfigurationManagerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManagerDelegate","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didFailToLoadNewConfiguration(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didLoadNewConfiguration(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didFailToSetConfigurationProfile:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didSetConfigurationProfile:)"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate/didFailToLoadNewConfiguration(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didFailToLoadNewConfiguration:"}],"role":"symbol","title":"didFailToLoadNewConfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToLoadNewConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"New configuration has failed to load"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didFailToLoadNewConfiguration(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didfailtoloadnewconfiguration(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate/didLoadNewConfiguration(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didLoadNewConfiguration:"}],"role":"symbol","title":"didLoadNewConfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLoadNewConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"New configuration has been loaded"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didLoadNewConfiguration(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didloadnewconfiguration(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate":{"role":"symbol","title":"PGConfigurationManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManagerDelegate"}],"abstract":[{"type":"text","text":"Configuration Delegate"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}],"url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate/peripheral(_:didFailToSetConfigurationProfile:error:)":{"navigatorTitle":[{"kind":"identifier","text":"peripheral:didFailToSetConfigurationProfile:error:"}],"role":"symbol","title":"peripheral(_:didFailToSetConfigurationProfile:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didFailToSetConfigurationProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The request to set a profile to a device failed."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didFailToSetConfigurationProfile:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/peripheral(_:didfailtosetconfigurationprofile:error:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate/peripheral(_:didSetConfigurationProfile:)":{"navigatorTitle":[{"kind":"identifier","text":"peripheral:didSetConfigurationProfile:"}],"role":"symbol","title":"peripheral(_:didSetConfigurationProfile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSetConfigurationProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The PGPeripheral did successfully set the configuration profile."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didSetConfigurationProfile:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/peripheral(_:didsetconfigurationprofile:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"PGConfigurationManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didFailToLoadNewConfiguration(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didLoadNewConfiguration(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didFailToSetConfigurationProfile:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didSetConfigurationProfile:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManagerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didFailToLoadNewConfiguration(_:)\/title","value":"didFailToLoadNewConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didFailToLoadNewConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailToLoadNewConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didLoadNewConfiguration(_:)\/title","value":"didLoadNewConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didLoadNewConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didLoadNewConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/title","value":"PGConfigurationManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1peripheral(_:didFailToSetConfigurationProfile:error:)\/title","value":"peripheral:didFailToSetConfigurationProfile:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1peripheral(_:didFailToSetConfigurationProfile:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didFailToSetConfigurationProfile:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1peripheral(_:didSetConfigurationProfile:)\/title","value":"peripheral:didSetConfigurationProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1peripheral(_:didSetConfigurationProfile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didSetConfigurationProfile:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}