{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"},"metadata":{"roleHeading":"Class","role":"symbol","title":"PGCommandParams","externalID":"c:@M@ConnectSDK@objc(cs)PGCommandParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCommandParams"}],"symbolKind":"class","navigatorTitle":[{"text":"PGCommandParams","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}]},"abstract":[{"text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/init()"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/replaceQueue"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCommandParams"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgcommandparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcommandparams"]}],"references":{"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/init()","title":"init()","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgcommandparams\/init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}]},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"title":"PGCommandParams","abstract":[{"type":"text","text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PGCommandParams","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgcommandparams","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams/replaceQueue":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"replaceQueue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"replaceQueue","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/replaceQueue","abstract":[{"text":"When set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" this command will clear all queued commands and then queue itself."}],"type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgcommandparams\/replacequeue","title":"replaceQueue"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PGCommandParams"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGCommandParams"}]},{"value":[{"text":"PGCommandParams","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/replaceQueue"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/init()"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommandParams","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams~1init()\/title","op":"replace","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title","value":"PGCommandParams"},{"value":[{"kind":"identifier","text":"PGCommandParams"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","op":"replace"},{"op":"replace","value":"replaceQueue","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams~1replaceQueue\/title"},{"op":"replace","value":[{"text":"replaceQueue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams~1replaceQueue\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}