{"metadata":{"role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGConfigurationApiError","kind":"identifier"}],"navigatorTitle":[{"text":"PGConfigurationApiError","kind":"identifier"}],"title":"PGConfigurationApiError","externalID":"c:@M@ConnectSDK@E@PGConfigurationApiError","modules":[{"name":"ConnectSDK"}]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorFailToParse","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorMissingData","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/idNil","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingDefaultProfile","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingManifest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfile","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfileId","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/notFound","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/profileMissingDocument"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGConfigurationApiError","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"PG configuration api error codes"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationapierror"]},{"paths":["\/documentation\/connectsdk\/pgconfigurationapierror"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"sections":[],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/profileMissingDocument":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorProfileMissingDocument"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/profileMissingDocument","role":"symbol","abstract":[{"type":"text","text":"Configuration profile missing document."}],"title":"PGConfigurationApiError.profileMissingDocument","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"profileMissingDocument"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/profilemissingdocument","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"title":"PGConfigurationApiError","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiError"}],"abstract":[{"type":"text","text":"PG configuration api error codes"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationApiError"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/apiErrorMissingData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorApiErrorMissingData"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorMissingData","role":"symbol","abstract":[{"type":"text","text":"No data at given path."}],"title":"PGConfigurationApiError.apiErrorMissingData","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiErrorMissingData","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/apierrormissingdata","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/apiErrorFailToParse":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorApiErrorFailToParse"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorFailToParse","role":"symbol","abstract":[{"type":"text","text":"Fail to parse data into Wapi object."}],"title":"PGConfigurationApiError.apiErrorFailToParse","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiErrorFailToParse","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/apierrorfailtoparse","kind":"symbol"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingDefaultProfile":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingDefaultProfile"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingDefaultProfile","role":"symbol","abstract":[{"type":"text","text":"Configuration missing default profile."}],"title":"PGConfigurationApiError.missingDefaultProfile","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingDefaultProfile"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingdefaultprofile","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/Equatable-Implementations","abstract":[],"kind":"article","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/equatable-implementations","title":"Equatable Implementations","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/notFound":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notFound"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorNotFound","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/notFound","kind":"symbol","abstract":[{"type":"text","text":"Configuration not loaded."}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/notfound","title":"PGConfigurationApiError.notFound","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingProfileId":{"abstract":[{"text":"Missing profile id.","type":"text"}],"type":"topic","title":"PGConfigurationApiError.missingProfileId","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"missingProfileId","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingProfileId"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfileId","role":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofileid","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingManifest":{"abstract":[{"type":"text","text":"Configuration manifest not present in the configuration file."}],"type":"topic","title":"PGConfigurationApiError.missingManifest","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingManifest"}],"navigatorTitle":[{"text":"PGConfigurationApiErrorMissingManifest","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingManifest","role":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingmanifest","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/rawrepresentable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/missingProfile":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingProfile"}],"type":"topic","kind":"symbol","title":"PGConfigurationApiError.missingProfile","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfile","abstract":[{"text":"The configuration profile not found.","type":"text"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/missingprofile","navigatorTitle":[{"text":"PGConfigurationApiErrorMissingProfile","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror\/init(rawvalue:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://com.proglove.Mark2SDK/SY":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError/idNil":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idNil"}],"type":"topic","kind":"symbol","title":"PGConfigurationApiError.idNil","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/idNil","abstract":[{"text":"Configuration id nil.","type":"text"}],"url":"\/documentation\/connectsdk\/pgconfigurationapierror\/idnil","navigatorTitle":[{"text":"PGConfigurationApiErrorIdNil","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"PGConfigurationApiError","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"text":"PGConfigurationApiError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PGConfigurationApiError","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorFailToParse","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/apiErrorMissingData","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/idNil","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingDefaultProfile","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingManifest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfile","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/missingProfileId","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/notFound","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError\/profileMissingDocument"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGConfigurationApiError","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1profileMissingDocument\/title","value":"PGConfigurationApiErrorProfileMissingDocument"},{"value":[{"kind":"identifier","text":"PGConfigurationApiErrorProfileMissingDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1profileMissingDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","value":"PGConfigurationApiError"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments","value":[{"text":"PGConfigurationApiError","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PGConfigurationApiErrorApiErrorMissingData","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorMissingData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorMissingData\/fragments","value":[{"text":"PGConfigurationApiErrorApiErrorMissingData","kind":"identifier"}]},{"value":"PGConfigurationApiErrorApiErrorFailToParse","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorFailToParse\/title"},{"value":[{"kind":"identifier","text":"PGConfigurationApiErrorApiErrorFailToParse"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1apiErrorFailToParse\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingDefaultProfile\/title","op":"replace","value":"PGConfigurationApiErrorMissingDefaultProfile"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingDefaultProfile\/fragments","value":[{"text":"PGConfigurationApiErrorMissingDefaultProfile","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1notFound\/title","value":"PGConfigurationApiErrorNotFound"},{"value":[{"text":"PGConfigurationApiErrorNotFound","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1notFound\/fragments","op":"replace"},{"op":"replace","value":"PGConfigurationApiErrorMissingProfileId","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfileId\/title"},{"value":[{"text":"PGConfigurationApiErrorMissingProfileId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfileId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingManifest\/title","op":"replace","value":"PGConfigurationApiErrorMissingManifest"},{"op":"replace","value":[{"text":"PGConfigurationApiErrorMissingManifest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingManifest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfile\/title","value":"PGConfigurationApiErrorMissingProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1missingProfile\/fragments","value":[{"kind":"identifier","text":"PGConfigurationApiErrorMissingProfile"}]},{"value":"PGConfigurationApiErrorIdNil","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1idNil\/title"},{"value":[{"text":"PGConfigurationApiErrorIdNil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError~1idNil\/fragments"}]}]}