{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanager"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/changeActiveProfile(_:completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/deleteLoadedConfigurations(completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getActiveConfigurationProfile(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getAllConfigurationProfiles(completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/loadConfigurationFile(atPath:completionHandler:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGConfigurationManager","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager","title":"PGConfigurationManager","symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationManager"}],"modules":[{"name":"ConnectSDK"}]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/getAllConfigurationProfiles(completionHandler:)":{"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanager\/getallconfigurationprofiles(completionhandler:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getAllConfigurationProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","text":"PGConfigurationProfile"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"getAllConfigurationProfilesWithCompletionHandler:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Method will return an array of all the previously loaded configuration profiles."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getAllConfigurationProfiles(completionHandler:)","title":"getAllConfigurationProfiles(completionHandler:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/changeActiveProfile(_:completionHandler:)":{"required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"changeActiveProfile:completionHandler:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationmanager\/changeactiveprofile(_:completionhandler:)","abstract":[{"text":"Use this method to set an active configuration profile.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/changeActiveProfile(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeActiveProfile"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","kind":"typeIdentifier","text":"PGCommand"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"changeActiveProfile(_:completionHandler:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/getActiveConfigurationProfile(_:)":{"required":true,"title":"getActiveConfigurationProfile(_:)","url":"\/documentation\/connectsdk\/pgconfigurationmanager\/getactiveconfigurationprofile(_:)","navigatorTitle":[{"text":"getActiveConfigurationProfile:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getActiveConfigurationProfile","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","kind":"typeIdentifier","text":"PGConfigurationProfile"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getActiveConfigurationProfile(_:)","abstract":[{"type":"text","text":"Use this method to retrieve the current active profile. The active profile is the profile that will be applied to a scanner on each successful connection."},{"type":"text","text":" "},{"type":"text","text":"In case no active profile is set, nil will be returned."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","type":"topic","role":"symbol","title":"PGConfigurationManager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManager"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationManager"}],"kind":"symbol","abstract":[],"url":"\/documentation\/connectsdk\/pgconfigurationmanager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/deleteLoadedConfigurations(completionHandler:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/deleteLoadedConfigurations(completionHandler:)","title":"deleteLoadedConfigurations(completionHandler:)","required":true,"kind":"symbol","type":"topic","abstract":[{"text":"Method will delete all previously loaded configurations.","type":"text"}],"url":"\/documentation\/connectsdk\/pgconfigurationmanager\/deleteloadedconfigurations(completionhandler:)","navigatorTitle":[{"text":"deleteLoadedConfigurationsWithCompletionHandler:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deleteLoadedConfigurations","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/delegate":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGConfigurationManagerDelegate","text":"PGConfigurationManagerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The configuration manager delegate.","type":"text"}],"url":"\/documentation\/connectsdk\/pgconfigurationmanager\/delegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/delegate","title":"delegate","required":true,"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager/loadConfigurationFile(atPath:completionHandler:)":{"type":"topic","title":"loadConfigurationFile(atPath:completionHandler:)","kind":"symbol","abstract":[{"type":"text","text":"This method will load configuration using a file at given path."},{"text":" ","type":"text"},{"type":"text","text":"One configuration at the time is supported, previously loaded configuration will be deleted."},{"type":"text","text":" "},{"text":"The file name must be proglove.proconfig","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/loadConfigurationFile(atPath:completionHandler:)","role":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationmanager\/loadconfigurationfile(atpath:completionhandler:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadConfigurationFile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atPath","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"loadConfigurationFileAtPath:completionHandler:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGConfigurationManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGConfigurationManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PGConfigurationManager","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/changeActiveProfile(_:completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/deleteLoadedConfigurations(completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getActiveConfigurationProfile(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/getAllConfigurationProfiles(completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager\/loadConfigurationFile(atPath:completionHandler:)"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationManager"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"getAllConfigurationProfilesWithCompletionHandler:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getAllConfigurationProfiles(completionHandler:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getAllConfigurationProfiles(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllConfigurationProfilesWithCompletionHandler:"}],"op":"replace"},{"value":"changeActiveProfile:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1changeActiveProfile(_:completionHandler:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"changeActiveProfile:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1changeActiveProfile(_:completionHandler:)\/fragments"},{"value":"getActiveConfigurationProfile:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getActiveConfigurationProfile(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"getActiveConfigurationProfile:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1getActiveConfigurationProfile(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/title","value":"PGConfigurationManager","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/fragments","value":[{"kind":"identifier","text":"PGConfigurationManager"}],"op":"replace"},{"value":"deleteLoadedConfigurationsWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1deleteLoadedConfigurations(completionHandler:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1deleteLoadedConfigurations(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"deleteLoadedConfigurationsWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"loadConfigurationFileAtPath:completionHandler:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1loadConfigurationFile(atPath:completionHandler:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager~1loadConfigurationFile(atPath:completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadConfigurationFileAtPath:completionHandler:"}]}]}]}