{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum number of PGCommands that can be sent to a device at a time is 1."},{"type":"text","text":" "},{"type":"text","text":"The maximum PGCommands that can be queued for sending is 5."},{"type":"text","text":" "},{"type":"text","text":"If PGCommand is requested and queue reached the limit, PGCommand will be droped and failed."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgcommand"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcommand"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A PGCommand is used to send a command to a connected device through Connect SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"title":"PGCommand","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ConnectSDK@objc(cs)PGCommand","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGCommand"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(configurationProfileRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(deviceInfoRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(displayOrientationRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(feedbackRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(screenDataRequest:params:)"]}],"references":{"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(deviceInfoRequest:params:)":{"role":"symbol","title":"init(deviceInfoRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceInfoRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGDeviceInformationRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initilaze with device information request"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(deviceInfoRequest:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDeviceInfoRequest:params:"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(deviceinforequest:params:)"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(feedbackRequest:params:)":{"role":"symbol","title":"init(feedbackRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"feedbackRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGFeedbackRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with feedback request"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(feedbackRequest:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFeedbackRequest:params:"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(feedbackrequest:params:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"role":"symbol","title":"PGCommand","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"abstract":[{"type":"text","text":"A PGCommand is used to send a command to a connected device through Connect SDK."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(configurationProfileRequest:params:)":{"role":"symbol","title":"init(configurationProfileRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configurationProfileRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with Configuration Profile Request"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(configurationProfileRequest:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfigurationProfileRequest:params:"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(configurationprofilerequest:params:)"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(screenDataRequest:params:)":{"role":"symbol","title":"init(screenDataRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"screenDataRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGScreenData","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScreenData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with Screen Data request"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(screenDataRequest:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithScreenDataRequest:params:"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(screendatarequest:params:)"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand/init(displayOrientationRequest:params:)":{"role":"symbol","title":"init(displayOrientationRequest:params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayOrientationRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGSetDisplayOrientationRequest","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommandParams","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommandParams"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with Display Orientation Request"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(displayOrientationRequest:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDisplayOrientationRequest:params:"}],"url":"\/documentation\/connectsdk\/pgcommand\/init(displayorientationrequest:params:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PGCommand"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGCommand"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGCommand"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(configurationProfileRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(deviceInfoRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(displayOrientationRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(feedbackRequest:params:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand\/init(screenDataRequest:params:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(deviceInfoRequest:params:)\/title","value":"initWithDeviceInfoRequest:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(deviceInfoRequest:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDeviceInfoRequest:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(feedbackRequest:params:)\/title","value":"initWithFeedbackRequest:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(feedbackRequest:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFeedbackRequest:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","value":"PGCommand"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments","value":[{"kind":"identifier","text":"PGCommand"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(configurationProfileRequest:params:)\/title","value":"initWithConfigurationProfileRequest:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(configurationProfileRequest:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfigurationProfileRequest:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(screenDataRequest:params:)\/title","value":"initWithScreenDataRequest:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(screenDataRequest:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithScreenDataRequest:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(displayOrientationRequest:params:)\/title","value":"initWithDisplayOrientationRequest:params:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand~1init(displayOrientationRequest:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDisplayOrientationRequest:params:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}