{"metadata":{"symbolKind":"class","title":"PGDeviceInformation","navigatorTitle":[{"text":"PGDeviceInformation","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGDeviceInformation","role":"symbol","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PGDeviceInformation","kind":"identifier"}],"roleHeading":"Class"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/description","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/firmwareRevision","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/serialNumber"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDeviceInformation","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"title":"Models","generated":true,"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdeviceinformation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdeviceinformation"]}],"abstract":[{"type":"text","text":"Model representing device information"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformation/description":{"abstract":[{"type":"text","text":"Device description"}],"kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgdeviceinformation\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/description","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformation/firmwareRevision":{"abstract":[{"type":"text","text":"Firmware revision."}],"kind":"symbol","navigatorTitle":[{"text":"firmwareRevision","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgdeviceinformation\/firmwarerevision","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firmwareRevision"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"firmwareRevision","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/firmwareRevision","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGScreenData"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgscreendata","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGScreenData","kind":"identifier"}],"title":"PGScreenData","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformation":{"abstract":[{"type":"text","text":"Model representing device information"}],"kind":"symbol","navigatorTitle":[{"text":"PGDeviceInformation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgdeviceinformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDeviceInformation"}],"title":"PGDeviceInformation","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformation/serialNumber":{"abstract":[{"type":"text","text":"Serial number."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"serialNumber"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgdeviceinformation\/serialnumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"serialNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"serialNumber","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/serialNumber","type":"topic"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"PGDeviceInformation","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"PGDeviceInformation"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGDeviceInformation"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/description","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/firmwareRevision","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation\/serialNumber"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"]}]},{"value":[{"title":"Models","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDeviceInformation","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation~1description\/title","op":"replace","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation~1firmwareRevision\/title","value":"firmwareRevision","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation~1firmwareRevision\/fragments","op":"replace","value":[{"text":"firmwareRevision","kind":"identifier"}]},{"value":"PGScreenData","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","value":[{"kind":"identifier","text":"PGScreenData"}],"op":"replace"},{"value":"PGDeviceInformation","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/fragments","value":[{"kind":"identifier","text":"PGDeviceInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation~1serialNumber\/title","value":"serialNumber"},{"value":[{"text":"serialNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation~1serialNumber\/fragments"}]}]}