{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"kind":"relationships"}],"abstract":[{"type":"text","text":"Request used for retreiving Device information"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGDeviceInformationRequest","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgdeviceinformationrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdeviceinformationrequest"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest\/init()"]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"PGDeviceInformationRequest","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGDeviceInformationRequest","roleHeading":"Class","role":"symbol","modules":[{"name":"ConnectSDK"}],"title":"PGDeviceInformationRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGDeviceInformationRequest"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformationRequest":{"url":"\/documentation\/connectsdk\/pgdeviceinformationrequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDeviceInformationRequest","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDeviceInformationRequest"}],"abstract":[{"text":"Request used for retreiving Device information","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","title":"PGDeviceInformationRequest","role":"symbol"},"doc://com.proglove.Mark2SDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformationRequest/init()":{"url":"\/documentation\/connectsdk\/pgdeviceinformationrequest\/init()","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest\/init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","kind":"symbol","title":"init()","role":"symbol"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PGDeviceInformationRequest","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGDeviceInformationRequest","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PGDeviceInformationRequest"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest\/init()"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGDeviceInformationRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGDeviceInformationRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest\/fragments","value":[{"kind":"identifier","text":"PGDeviceInformationRequest"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]}]}]}