{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGDeviceLockError","kind":"identifier"}]}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/invalidAuthenticationBarcode","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/unlockFailed"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"sections":[],"metadata":{"externalID":"c:@M@ConnectSDK@E@PGDeviceLockError","modules":[{"name":"ConnectSDK"}],"title":"PGDeviceLockError","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGDeviceLockError","kind":"identifier"}],"navigatorTitle":[{"text":"PGDeviceLockError","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol"},"abstract":[{"type":"text","text":"Scanner lock\/unlock error codes"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdevicelockerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdevicelockerror"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError/unlockFailed":{"url":"\/documentation\/connectsdk\/pgdevicelockerror\/unlockfailed","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockErrorUnlockFailed"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unlockFailed","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/unlockFailed","title":"PGDeviceLockError.unlockFailed","abstract":[{"type":"text","text":"Device unlock failed"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockError"}],"role":"symbol","title":"PGDeviceLockError","type":"topic","abstract":[{"text":"Scanner lock\/unlock error codes","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGDeviceLockError"}],"url":"\/documentation\/connectsdk\/pgdevicelockerror"},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","title":"Swift.RawRepresentable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError/invalidAuthenticationBarcode":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidAuthenticationBarcode","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgdevicelockerror\/invalidauthenticationbarcode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockErrorInvalidAuthenticationBarcode"}],"role":"symbol","title":"PGDeviceLockError.invalidAuthenticationBarcode","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/invalidAuthenticationBarcode","abstract":[{"type":"text","text":"Authentication barcode is invalid"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError/Equatable-Implementations":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/Equatable-Implementations","kind":"article","type":"topic","abstract":[],"title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/connectsdk\/pgdevicelockerror\/equatable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","url":"\/documentation\/connectsdk\/pgdevicelockerror\/rawrepresentable-implementations","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError/init(rawValue:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/init(rawValue:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgdevicelockerror\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGDeviceLockError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGDeviceLockError"}]},{"value":[{"kind":"identifier","text":"PGDeviceLockError"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/invalidAuthenticationBarcode","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/unlockFailed"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGDeviceLockError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1unlockFailed\/title","op":"replace","value":"PGDeviceLockErrorUnlockFailed"},{"value":[{"text":"PGDeviceLockErrorUnlockFailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1unlockFailed\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/title","value":"PGDeviceLockError","op":"replace"},{"value":[{"kind":"identifier","text":"PGDeviceLockError"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1invalidAuthenticationBarcode\/title","value":"PGDeviceLockErrorInvalidAuthenticationBarcode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1invalidAuthenticationBarcode\/fragments","value":[{"kind":"identifier","text":"PGDeviceLockErrorInvalidAuthenticationBarcode"}]}]}]}