{"metadata":{"modules":[{"name":"ConnectSDK"}],"symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","title":"PGDisplayApiError","externalID":"c:@M@ConnectSDK@E@PGDisplayApiError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGDisplayApiError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiError"}]},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/contentTooLong","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/duplicateFieldId","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/emptyTemplateId","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/fieldIdNotInTemplate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/headerTooLong","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/invalidNumberOfFieldsInTemplate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/negativeDuration","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/templateIdNotFound"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGDisplayApiError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror"]},{"paths":["\/documentation\/connectsdk\/pgdisplayapierror"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"PG Display API error codes.","type":"text"}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/contentTooLong":{"url":"\/documentation\/connectsdk\/pgdisplayapierror\/contenttoolong","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"contentTooLong","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/contentTooLong","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The content value is too long."}],"navigatorTitle":[{"text":"PGDisplayApiErrorContentTooLong","kind":"identifier"}],"title":"PGDisplayApiError.contentTooLong"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/emptyTemplateId":{"url":"\/documentation\/connectsdk\/pgdisplayapierror\/emptytemplateid","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"emptyTemplateId","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/emptyTemplateId","role":"symbol","abstract":[{"type":"text","text":"The provided Template id is nil or empty."}],"navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorEmptyTemplateId"}],"title":"PGDisplayApiError.emptyTemplateId"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/templateIdNotFound":{"type":"topic","abstract":[{"type":"text","text":"The provided Template id not found in the list of supported ids."}],"role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgdisplayapierror\/templateidnotfound","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/templateIdNotFound","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorTemplateIdNotFound"}],"title":"PGDisplayApiError.templateIdNotFound","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"templateIdNotFound","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","title":"Swift.RawRepresentable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/duplicateFieldId":{"url":"\/documentation\/connectsdk\/pgdisplayapierror\/duplicatefieldid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duplicateFieldId"}],"title":"PGDisplayApiError.duplicateFieldId","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/duplicateFieldId","role":"symbol","abstract":[{"type":"text","text":"The provided list of fields contain duplicate field id."}],"navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorDuplicateFieldId"}],"type":"topic","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/connectsdk\/pgdisplayapierror\/rawrepresentable-implementations","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/RawRepresentable-Implementations"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"title":"PGDisplayApiError","url":"\/documentation\/connectsdk\/pgdisplayapierror","role":"symbol","navigatorTitle":[{"text":"PGDisplayApiError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","abstract":[{"text":"PG Display API error codes.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDisplayApiError"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/headerTooLong":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"headerTooLong","kind":"identifier"}],"abstract":[{"text":"The header value is too long.","type":"text"}],"navigatorTitle":[{"text":"PGDisplayApiErrorHeaderTooLong","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/headerTooLong","url":"\/documentation\/connectsdk\/pgdisplayapierror\/headertoolong","title":"PGDisplayApiError.headerTooLong"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/Equatable-Implementations":{"type":"topic","url":"\/documentation\/connectsdk\/pgdisplayapierror\/equatable-implementations","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/Equatable-Implementations","kind":"article","role":"collectionGroup"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/negativeDuration":{"url":"\/documentation\/connectsdk\/pgdisplayapierror\/negativeduration","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"negativeDuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/negativeDuration","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The provided duration is negative value."}],"navigatorTitle":[{"text":"PGDisplayApiErrorNegativeDuration","kind":"identifier"}],"title":"PGDisplayApiError.negativeDuration"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/invalidNumberOfFieldsInTemplate":{"abstract":[{"type":"text","text":"There is mismatch in number of fields provided and supported by selected template."}],"type":"topic","title":"PGDisplayApiError.invalidNumberOfFieldsInTemplate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/invalidNumberOfFieldsInTemplate","url":"\/documentation\/connectsdk\/pgdisplayapierror\/invalidnumberoffieldsintemplate","role":"symbol","navigatorTitle":[{"text":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidNumberOfFieldsInTemplate"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/init(rawValue:)":{"abstract":[],"type":"topic","url":"\/documentation\/connectsdk\/pgdisplayapierror\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(rawValue:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/init(rawValue:)","role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/fieldIdNotInTemplate":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldIdNotInTemplate"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/fieldIdNotInTemplate","url":"\/documentation\/connectsdk\/pgdisplayapierror\/fieldidnotintemplate","kind":"symbol","title":"PGDisplayApiError.fieldIdNotInTemplate","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorFieldIdNotInTemplate"}],"abstract":[{"type":"text","text":"The provided field id is not in the list of supported ids. The field id is number beetween 1 and number of supported fields."}],"type":"topic","role":"symbol"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGDisplayApiError"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGDisplayApiError","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PGDisplayApiError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/contentTooLong","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/duplicateFieldId","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/emptyTemplateId","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/fieldIdNotInTemplate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/headerTooLong","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/invalidNumberOfFieldsInTemplate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/negativeDuration","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/templateIdNotFound"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGDisplayApiError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1contentTooLong\/title","value":"PGDisplayApiErrorContentTooLong"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1contentTooLong\/fragments","value":[{"text":"PGDisplayApiErrorContentTooLong","kind":"identifier"}]},{"op":"replace","value":"PGDisplayApiErrorEmptyTemplateId","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1emptyTemplateId\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1emptyTemplateId\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGDisplayApiErrorEmptyTemplateId"}]},{"op":"replace","value":"PGDisplayApiErrorTemplateIdNotFound","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1templateIdNotFound\/title"},{"value":[{"kind":"identifier","text":"PGDisplayApiErrorTemplateIdNotFound"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1templateIdNotFound\/fragments"},{"value":"PGDisplayApiErrorDuplicateFieldId","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1duplicateFieldId\/title"},{"value":[{"text":"PGDisplayApiErrorDuplicateFieldId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1duplicateFieldId\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title","value":"PGDisplayApiError","op":"replace"},{"op":"replace","value":[{"text":"PGDisplayApiError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1headerTooLong\/title","op":"replace","value":"PGDisplayApiErrorHeaderTooLong"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1headerTooLong\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGDisplayApiErrorHeaderTooLong"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1negativeDuration\/title","value":"PGDisplayApiErrorNegativeDuration"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1negativeDuration\/fragments","value":[{"text":"PGDisplayApiErrorNegativeDuration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1invalidNumberOfFieldsInTemplate\/title","value":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1invalidNumberOfFieldsInTemplate\/fragments","value":[{"kind":"identifier","text":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"}]},{"value":"PGDisplayApiErrorFieldIdNotInTemplate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1fieldIdNotInTemplate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PGDisplayApiErrorFieldIdNotInTemplate"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1fieldIdNotInTemplate\/fragments"}]}]}