{"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setDisplayOrientation(_:completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setScreen(_:completionHandler:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdisplaymanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdisplaymanager"]}],"abstract":[{"type":"text","text":"Protocol contains all the display configuration related methods."}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDisplayManager"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ConnectSDK@objc(pl)PGDisplayManager","title":"PGDisplayManager","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDisplayManager"}],"roleHeading":"Protocol","modules":[{"name":"ConnectSDK"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"PGDisplayManager"}]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayManager":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager","abstract":[{"text":"Protocol contains all the display configuration related methods.","type":"text"}],"title":"PGDisplayManager","url":"\/documentation\/connectsdk\/pgdisplaymanager","type":"topic","navigatorTitle":[{"text":"PGDisplayManager","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PGDisplayManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayManager/setScreen(_:completionHandler:)":{"type":"topic","abstract":[{"type":"text","text":"Use this method to set a screen data to a connected device."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","required":true,"navigatorTitle":[{"text":"setScreen:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setScreen(_:completionHandler:)","title":"setScreen(_:completionHandler:)","url":"\/documentation\/connectsdk\/pgdisplaymanager\/setscreen(_:completionhandler:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayManager/setDisplayOrientation(_:completionHandler:)":{"kind":"symbol","role":"symbol","title":"setDisplayOrientation(_:completionHandler:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setDisplayOrientation(_:completionHandler:)","abstract":[{"text":"This method can be used to change the orientation on a connected device.","type":"text"}],"url":"\/documentation\/connectsdk\/pgdisplaymanager\/setdisplayorientation(_:completionhandler:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"setDisplayOrientation:completionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDisplayOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCommand","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"PGDisplayManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"PGDisplayManager"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGDisplayManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setDisplayOrientation(_:completionHandler:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setScreen(_:completionHandler:)"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"PGDisplayManager","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager\/title","value":"PGDisplayManager"},{"value":[{"kind":"identifier","text":"PGDisplayManager"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager~1setScreen(_:completionHandler:)\/title","value":"setScreen:completionHandler:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager~1setScreen(_:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setScreen:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager~1setDisplayOrientation(_:completionHandler:)\/title","value":"setDisplayOrientation:completionHandler:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager~1setDisplayOrientation(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setDisplayOrientation:completionHandler:","kind":"identifier"}],"op":"replace"}]}]}