{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgfeedbackapierrordomain"]},{"paths":["\/documentation\/connectsdk\/pgfeedbackapierrordomain"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"metadata":{"externalID":"c:@PGFeedbackApiErrorDomain","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGFeedbackApiErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"PGFeedbackApiErrorDomain","kind":"identifier"}],"roleHeading":"Global Variable","modules":[{"name":"ConnectSDK"}],"role":"symbol","symbolKind":"var","title":"PGFeedbackApiErrorDomain"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFeedbackApiErrorDomain"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The scanner feedback api error domain."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiErrorDomain"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiErrorDomain":{"url":"\/documentation\/connectsdk\/pgfeedbackapierrordomain","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiErrorDomain","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackApiErrorDomain"}],"kind":"symbol","title":"PGFeedbackApiErrorDomain","role":"symbol","abstract":[{"type":"text","text":"The scanner feedback api error domain."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGFeedbackApiErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"PGFeedbackApiErrorDomain"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"op":"replace","value":[{"text":"PGFeedbackApiErrorDomain","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"PGFeedbackApiErrorDomain","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGFeedbackApiErrorDomain","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiErrorDomain\/title"},{"op":"replace","value":[{"text":"PGFeedbackApiErrorDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiErrorDomain\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}