{"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/init(feedback:)"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/predefinedFeedback"],"title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"abstract":[{"type":"text","text":"Model representing PGFeedback Request"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGFeedbackRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgfeedbackrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgfeedbackrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Class","externalID":"c:@M@ConnectSDK@objc(cs)PGFeedbackRequest","role":"symbol","symbolKind":"class","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGFeedbackRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGFeedbackRequest"}],"title":"PGFeedbackRequest"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest/init(feedback:)":{"abstract":[{"text":"Used to initiate PGFeedbackRequest with a predefined feedback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFeedback:"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/init(feedback:)","title":"init(feedback:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"feedback","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback","text":"PGPredefinedFeedback"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pgfeedbackrequest\/init(feedback:)"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest":{"title":"PGFeedbackRequest","abstract":[{"text":"Model representing PGFeedback Request","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PGFeedbackRequest","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackRequest"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","url":"\/documentation\/connectsdk\/pgfeedbackrequest"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest/predefinedFeedback":{"url":"\/documentation\/connectsdk\/pgfeedbackrequest\/predefinedfeedback","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/predefinedFeedback","role":"symbol","title":"predefinedFeedback","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"predefinedFeedback","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGPredefinedFeedback","preciseIdentifier":"c:@M@ConnectSDK@E@PGPredefinedFeedback"}],"navigatorTitle":[{"kind":"identifier","text":"predefinedFeedback"}],"kind":"symbol","abstract":[{"text":"Predefined feedback id.","type":"text"}]},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PGFeedbackRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"PGFeedbackRequest"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGFeedbackRequest"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/predefinedFeedback"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest\/init(feedback:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PGFeedbackRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1init(feedback:)\/title","value":"initWithFeedback:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFeedback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1init(feedback:)\/fragments"},{"value":"PGFeedbackRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/title","op":"replace"},{"value":[{"text":"PGFeedbackRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1predefinedFeedback\/title","value":"predefinedFeedback"},{"value":[{"text":"predefinedFeedback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest~1predefinedFeedback\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}