{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackApiError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgfeedbackapierror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgfeedbackapierror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/sequenceNotFound"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackApiError"}],"title":"PGFeedbackApiError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ConnectSDK@E@PGFeedbackApiError","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGFeedbackApiError"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError/sequenceNotFound":{"role":"symbol","title":"PGFeedbackApiError.sequenceNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sequenceNotFound"}],"abstract":[{"type":"text","text":"Feedback for sequence id not found."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/sequenceNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackApiErrorSequenceNotFound"}],"url":"\/documentation\/connectsdk\/pgfeedbackapierror\/sequencenotfound"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgfeedbackapierror\/init(rawvalue:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/connectsdk\/pgfeedbackapierror\/equatable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/connectsdk\/pgfeedbackapierror\/rawrepresentable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError":{"role":"symbol","title":"PGFeedbackApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackApiError"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackApiError"}],"url":"\/documentation\/connectsdk\/pgfeedbackapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"PGFeedbackApiError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGFeedbackApiError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGFeedbackApiError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/sequenceNotFound"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackApiError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError~1sequenceNotFound\/title","value":"PGFeedbackApiErrorSequenceNotFound"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError~1sequenceNotFound\/fragments","value":[{"kind":"identifier","text":"PGFeedbackApiErrorSequenceNotFound"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError\/title","value":"PGFeedbackApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError\/fragments","value":[{"kind":"identifier","text":"PGFeedbackApiError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}