{"abstract":[{"type":"text","text":"Protocol contains all the feedback related methods."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager"},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager\/playFeedbackSequence(withFeedbackCommand:completionHandler:)"],"title":"Instance Methods"}],"metadata":{"navigatorTitle":[{"text":"PGFeedbackManager","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGFeedbackManager","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFeedbackManager"}],"modules":[{"name":"ConnectSDK"}],"title":"PGFeedbackManager","roleHeading":"Protocol","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGFeedbackManager","kind":"identifier"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgfeedbackmanager"]},{"paths":["\/documentation\/connectsdk\/pgfeedbackmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager":{"abstract":[{"type":"text","text":"Protocol contains all the feedback related methods."}],"url":"\/documentation\/connectsdk\/pgfeedbackmanager","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFeedbackManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackManager"}],"title":"PGFeedbackManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager/playFeedbackSequence(withFeedbackCommand:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager\/playFeedbackSequence(withFeedbackCommand:completionHandler:)","required":true,"abstract":[{"type":"text","text":"Plays sequence on a connected scanner based on a provided id."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playFeedbackSequence","kind":"identifier"},{"kind":"text","text":"("},{"text":"withFeedbackCommand","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","text":"PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/connectsdk\/pgfeedbackmanager\/playfeedbacksequence(withfeedbackcommand:completionhandler:)","title":"playFeedbackSequence(withFeedbackCommand:completionHandler:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGFeedbackManager","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"PGFeedbackManager"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGFeedbackManager"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager\/playFeedbackSequence(withFeedbackCommand:completionHandler:)"],"title":"Instance Methods"}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFeedbackManager"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGFeedbackManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/title"},{"value":[{"text":"PGFeedbackManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager~1playFeedbackSequence(withFeedbackCommand:completionHandler:)\/title","value":"playFeedbackSequenceWithFeedbackCommand:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager~1playFeedbackSequence(withFeedbackCommand:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}