{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFirmwareUpdateManager"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanager"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateManager"}],"roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGFirmwareUpdateManager","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManager","title":"PGFirmwareUpdateManager"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"The protocol for the PGFirmwareUpdateManager.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager\/delegate"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManager/delegate":{"type":"topic","title":"delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager\/delegate","url":"\/documentation\/connectsdk\/pgfirmwareupdatemanager\/delegate","abstract":[{"type":"text","text":"The firmware update manager delegate."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"PGFirmwareUpdateManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManagerDelegate"},{"kind":"text","text":"?"}],"required":true,"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManager":{"role":"symbol","url":"\/documentation\/connectsdk\/pgfirmwareupdatemanager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGFirmwareUpdateManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager","abstract":[{"type":"text","text":"The protocol for the PGFirmwareUpdateManager."}],"type":"topic","title":"PGFirmwareUpdateManager","navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PGFirmwareUpdateManager","op":"replace"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGFirmwareUpdateManager","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PGFirmwareUpdateManager","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager\/delegate"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFirmwareUpdateManager"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager~1delegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager~1delegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager\/title","value":"PGFirmwareUpdateManager"},{"value":[{"text":"PGFirmwareUpdateManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager\/fragments"}]}]}