{"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didChangeFirmwareUpdateProgress(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didCompleteFirmwareUpdate()","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didFailToUpdateFirmwareWithError(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didStartFirmwareUpdate()"]}],"metadata":{"externalID":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManagerDelegate","roleHeading":"Protocol","navigatorTitle":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"symbolKind":"protocol","title":"PGFirmwareUpdateManagerDelegate","modules":[{"name":"ConnectSDK"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"variants":[{"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate"]}],"kind":"symbol","abstract":[{"type":"text","text":"PGFirmwareUpdateManagerDelegate"},{"type":"text","text":" "},{"text":"The delegate protocol for the PGFirmwareUpdateManager. The delegate must adopt the PGFirmwareUpdateManagerDelegate protocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The methods will provide the firmware update state information."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didChangeFirmwareUpdateProgress(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChangeFirmwareUpdateProgress"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didchangefirmwareupdateprogress(_:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didChangeFirmwareUpdateProgress(_:)","title":"didChangeFirmwareUpdateProgress(_:)","role":"symbol","abstract":[{"text":"The current update progress expressed in percentage.","type":"text"}],"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didChangeFirmwareUpdateProgress:"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didCompleteFirmwareUpdate()":{"role":"symbol","required":true,"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didCompleteFirmwareUpdate()","navigatorTitle":[{"text":"didCompleteFirmwareUpdate","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCompleteFirmwareUpdate","kind":"identifier"},{"kind":"text","text":"()"}],"title":"didCompleteFirmwareUpdate()","kind":"symbol","abstract":[{"type":"text","text":"The firmware update is successfully completed."}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didcompletefirmwareupdate()"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didFailToUpdateFirmwareWithError(_:)":{"type":"topic","abstract":[{"text":"The firmware update failed.","type":"text"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didFailToUpdateFirmwareWithError(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didFailToUpdateFirmwareWithError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"didFailToUpdateFirmwareWithError:","kind":"identifier"}],"title":"didFailToUpdateFirmwareWithError(_:)","role":"symbol","url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didfailtoupdatefirmwarewitherror(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"title":"PGFirmwareUpdateManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"PGFirmwareUpdateManagerDelegate"},{"type":"text","text":" "},{"text":"The delegate protocol for the PGFirmwareUpdateManager. The delegate must adopt the PGFirmwareUpdateManagerDelegate protocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The methods will provide the firmware update state information."}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate/didStartFirmwareUpdate()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didStartFirmwareUpdate","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate\/didstartfirmwareupdate()","title":"didStartFirmwareUpdate()","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didStartFirmwareUpdate()","role":"symbol","abstract":[{"type":"text","text":"The firmware update has begun."}],"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didStartFirmwareUpdate"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","value":"PGFirmwareUpdateManagerDelegate","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didChangeFirmwareUpdateProgress(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didCompleteFirmwareUpdate()","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didFailToUpdateFirmwareWithError(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate\/didStartFirmwareUpdate()"],"title":"Instance Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"didChangeFirmwareUpdateProgress:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didChangeFirmwareUpdateProgress(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didChangeFirmwareUpdateProgress:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didChangeFirmwareUpdateProgress(_:)\/fragments","op":"replace"},{"op":"replace","value":"didCompleteFirmwareUpdate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didCompleteFirmwareUpdate()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCompleteFirmwareUpdate"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didCompleteFirmwareUpdate()\/fragments"},{"value":"didFailToUpdateFirmwareWithError:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didFailToUpdateFirmwareWithError(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didFailToUpdateFirmwareWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didFailToUpdateFirmwareWithError:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PGFirmwareUpdateManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/title"},{"value":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/fragments"},{"value":"didStartFirmwareUpdate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didStartFirmwareUpdate()\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate~1didStartFirmwareUpdate()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didStartFirmwareUpdate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}