{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgimageresolution"]},{"paths":["\/documentation\/connectsdk\/pgimageresolution"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"type":"conformsTo","kind":"relationships"}],"metadata":{"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@ConnectSDK@E@PGImageResolution","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGImageResolution"}],"navigatorTitle":[{"text":"PGImageResolution","kind":"identifier"}],"title":"PGImageResolution"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution"},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res1280_960","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res320_240","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res640_480"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImageResolution"}]}]}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/res1280_960":{"url":"\/documentation\/connectsdk\/pgimageresolution\/res1280_960","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"res1280_960"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGImageResolutionRes1280_960"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res1280_960","title":"PGImageResolution.res1280_960"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/connectsdk\/pgimageresolution\/init(rawvalue:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/init(rawValue:)","title":"init(rawValue:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/connectsdk\/pgimageresolution\/rawrepresentable-implementations","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/res320_240":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res320_240","type":"topic","url":"\/documentation\/connectsdk\/pgimageresolution\/res320_240","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PGImageResolutionRes320_240"}],"title":"PGImageResolution.res320_240","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"res320_240"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/res640_480":{"abstract":[],"title":"PGImageResolution.res640_480","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGImageResolutionRes640_480"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res640_480","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"res640_480"}],"url":"\/documentation\/connectsdk\/pgimageresolution\/res640_480"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","type":"topic","url":"\/documentation\/connectsdk\/pgimageresolution\/equatable-implementations"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution":{"title":"PGImageResolution","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGImageResolution"}],"navigatorTitle":[{"kind":"identifier","text":"PGImageResolution"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","abstract":[],"url":"\/documentation\/connectsdk\/pgimageresolution","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PGImageResolution"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PGImageResolution"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PGImageResolution","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res1280_960","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res320_240","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution\/res640_480"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGImageResolution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"PGImageResolutionRes1280_960","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res1280_960\/title"},{"value":[{"text":"PGImageResolutionRes1280_960","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res1280_960\/fragments","op":"replace"},{"value":"PGImageResolutionRes320_240","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res320_240\/title"},{"value":[{"text":"PGImageResolutionRes320_240","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res320_240\/fragments"},{"op":"replace","value":"PGImageResolutionRes640_480","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res640_480\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGImageResolutionRes640_480"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution~1res640_480\/fragments"},{"op":"replace","value":"PGImageResolution","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/fragments","value":[{"kind":"identifier","text":"PGImageResolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}