{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImageManager"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PGImageManager"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGImageManager","title":"PGImageManager","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImageManager"}],"role":"symbol","symbolKind":"protocol","roleHeading":"Protocol"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgimagemanager"]},{"paths":["\/documentation\/connectsdk\/pgimagemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager"},"abstract":[{"text":"PGImageManager protocol containg the methods and properties for retrieving an image using photo feature","type":"text"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager\/takeImage(_:completionHandler:)"],"title":"Instance Methods"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageManager":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGImageManager","kind":"identifier"}],"abstract":[{"type":"text","text":"PGImageManager protocol containg the methods and properties for retrieving an image using photo feature"}],"url":"\/documentation\/connectsdk\/pgimagemanager","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGImageManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager","title":"PGImageManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageManager/takeImage(_:completionHandler:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager\/takeImage(_:completionHandler:)","abstract":[{"type":"text","text":"Take image function that is used to retrieve the image"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"takeImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","text":"PGCommand"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"PGImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGImage"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"takeImage:completionHandler:","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgimagemanager\/takeimage(_:completionhandler:)","role":"symbol","title":"takeImage(_:completionHandler:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGImageManager","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"PGImageManager"}],"path":"\/metadata\/fragments"},{"value":[{"text":"PGImageManager","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager\/takeImage(_:completionHandler:)"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGImageManager","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/title","op":"replace","value":"PGImageManager"},{"value":[{"text":"PGImageManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/fragments"},{"value":"takeImage:completionHandler:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager~1takeImage(_:completionHandler:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager~1takeImage(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"takeImage:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}