{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/height","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/imageData","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/width"]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgimage"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"PGImage","symbolKind":"class","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGImage"}],"role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGImage","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGImage"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImage"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"type":"conformsTo"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Object containing image data and image options","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImage/height":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"height"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/height","url":"\/documentation\/connectsdk\/pgimage\/height","abstract":[{"type":"text","text":"Height of the image"}],"title":"height"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImage":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"PGImage","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGImage","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","url":"\/documentation\/connectsdk\/pgimage","abstract":[{"type":"text","text":"Object containing image data and image options"}],"title":"PGImage"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImage/width":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"width","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/width","url":"\/documentation\/connectsdk\/pgimage\/width","abstract":[{"type":"text","text":"Width of the image"}],"title":"width"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImage/imageData":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/imageData","kind":"symbol","url":"\/documentation\/connectsdk\/pgimage\/imagedata","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"imageData","kind":"identifier"}],"abstract":[{"text":"Data of the image","type":"text"}],"title":"imageData","role":"symbol"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PGImage"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGImage","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGImage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/height","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/imageData","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage\/width"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImage"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage~1height\/title","value":"height"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage~1height\/fragments"},{"value":"PGImage","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/fragments","value":[{"text":"PGImage","kind":"identifier"}],"op":"replace"},{"value":"width","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage~1width\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage~1width\/fragments","value":[{"kind":"identifier","text":"width"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage~1imageData\/title","value":"imageData"},{"value":[{"kind":"identifier","text":"imageData"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage~1imageData\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}