{"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGLogFlag","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGLogFlag","title":"PGLogFlag","roleHeading":"Enumeration","modules":[{"name":"ConnectSDK"}],"symbolKind":"enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGLogFlag"}]},"abstract":[{"text":"Log flags, used to determine the severity of a log message","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGLogFlag","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGLogFlagError: Error log flag - used for severe problems"}]}]},{"content":[{"inlineContent":[{"text":"PGLogFlagWarning: Warning log flag - used for less severe, recoverable problems","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"PGLogFlagInfo: Info log flag - used for informational purposes","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PGLogFlagDebug: Debug log flag - used to aid debugging","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"PGLogFlagVerbose: Verbose log flag - used for very verbose debugging","type":"text"}],"type":"paragraph"}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pglogflag"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pglogflag"]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"kind":"relationships"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/debug","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/error","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/info","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/verbose","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/warning"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/init(rawValue:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pglogflag\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/verbose":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verbose","kind":"identifier"}],"navigatorTitle":[{"text":"PGLogFlagVerbose","kind":"identifier"}],"abstract":[{"type":"text","text":"Verbose log flag - used for very verbose debugging"}],"title":"PGLogFlag.verbose","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/verbose","type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pglogflag\/verbose"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/RawRepresentable-Implementations":{"type":"topic","kind":"article","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/connectsdk\/pglogflag\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/RawRepresentable-Implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/warning":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogFlagWarning"}],"abstract":[{"type":"text","text":"Warning log flag - used for less severe, recoverable problems"}],"title":"PGLogFlag.warning","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/warning","type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pglogflag\/warning"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/error":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogFlagError"}],"abstract":[{"type":"text","text":"Error log flag - used for severe problems"}],"title":"PGLogFlag.error","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/error","type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pglogflag\/error"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/Equatable-Implementations":{"kind":"article","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/Equatable-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/connectsdk\/pglogflag\/equatable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/info":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/info","role":"symbol","title":"PGLogFlag.info","abstract":[{"type":"text","text":"Info log flag - used for informational purposes"}],"url":"\/documentation\/connectsdk\/pglogflag\/info","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PGLogFlagInfo","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag":{"navigatorTitle":[{"kind":"identifier","text":"PGLogFlag"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGLogFlag","kind":"identifier"}],"kind":"symbol","title":"PGLogFlag","abstract":[{"type":"text","text":"Log flags, used to determine the severity of a log message"}],"url":"\/documentation\/connectsdk\/pglogflag","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag"},"doc://com.proglove.Mark2SDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag/debug":{"abstract":[{"type":"text","text":"Debug log flag - used to aid debugging"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"title":"PGLogFlag.debug","url":"\/documentation\/connectsdk\/pglogflag\/debug","navigatorTitle":[{"text":"PGLogFlagDebug","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/debug"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"PGLogFlag","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGLogFlag","kind":"identifier"}]},{"value":[{"text":"PGLogFlag","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/debug","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/error","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/info","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/verbose","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag\/warning"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGLogFlag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGLogFlagVerbose","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1verbose\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1verbose\/fragments","op":"replace","value":[{"text":"PGLogFlagVerbose","kind":"identifier"}]},{"op":"replace","value":"PGLogFlagWarning","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1warning\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGLogFlagWarning"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1warning\/fragments"},{"value":"PGLogFlagError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1error\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1error\/fragments","value":[{"text":"PGLogFlagError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1info\/title","op":"replace","value":"PGLogFlagInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1info\/fragments","value":[{"kind":"identifier","text":"PGLogFlagInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/title","value":"PGLogFlag"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/fragments","value":[{"text":"PGLogFlag","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1debug\/title","value":"PGLogFlagDebug","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag~1debug\/fragments","value":[{"kind":"identifier","text":"PGLogFlagDebug"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}