{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/connectsdk\/pgloggingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgloggingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The logging class delegate protocol","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate\/pgLog(_:flag:context:file:function:line:tag:message:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGLoggingDelegate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"protocol","modules":[{"name":"ConnectSDK"}],"roleHeading":"Protocol","title":"PGLoggingDelegate","navigatorTitle":[{"kind":"identifier","text":"PGLoggingDelegate"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGLoggingDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGLoggingDelegate","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLoggingDelegate/pgLog(_:flag:context:file:function:line:tag:message:)":{"type":"topic","title":"pgLog(_:flag:context:file:function:line:tag:message:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pgLog","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"flag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGLogFlag","preciseIdentifier":"c:@M@ConnectSDK@E@PGLogFlag","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"function"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"line","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?, ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"text":"This method notifies the delegate of new log messages when they occur","type":"text"}],"required":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate\/pgLog(_:flag:context:file:function:line:tag:message:)","kind":"symbol","url":"\/documentation\/connectsdk\/pgloggingdelegate\/pglog(_:flag:context:file:function:line:tag:message:)","navigatorTitle":[{"text":"pgLog:flag:context:file:function:line:tag:message:","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLoggingDelegate":{"url":"\/documentation\/connectsdk\/pgloggingdelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGLoggingDelegate"}],"title":"PGLoggingDelegate","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate","abstract":[{"text":"The logging class delegate protocol","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGLoggingDelegate","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGLoggingDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PGLoggingDelegate","kind":"identifier"}]},{"value":[{"text":"PGLoggingDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate\/pgLog(_:flag:context:file:function:line:tag:message:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGLoggingDelegate","kind":"identifier"}],"languages":["occ"]}]}},{"value":"pgLog:flag:context:file:function:line:tag:message:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate~1pgLog(_:flag:context:file:function:line:tag:message:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate~1pgLog(_:flag:context:file:function:line:tag:message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"pgLog:flag:context:file:function:line:tag:message:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate\/title","value":"PGLoggingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate\/fragments","value":[{"text":"PGLoggingDelegate","kind":"identifier"}]}]}]}