{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGLogLevel","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGLogLevelOff: Off log level - no messages will be logged"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGLogLevelError: Error log level - only errors will be logged"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGLogLevelWarning: Warning log level - errors and warnings will be logged"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PGLogLevelInfo: Info log level - errors, warnings and info will be logged","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"PGLogLevelDebug: Debug log level - errors, warnings, info and debug will be logged","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"PGLogLevelVerbose: Verbose log level - errors, warnings, info, debug and verbose will be logged"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PGLogLevelAll: All log level - All messages will be logged","type":"text"}]}]}]}]}],"abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgloglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgloglevel"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/all","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/debug","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/error","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/info","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/off","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/verbose","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/RawRepresentable-Implementations"]}],"sections":[],"metadata":{"modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"PGLogLevel","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGLogLevel","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGLogLevel","kind":"identifier"}],"role":"symbol","title":"PGLogLevel"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"type":"topic","url":"\/documentation\/connectsdk\/pgloglevel\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/Equatable-Implementations","role":"collectionGroup"},"doc://com.proglove.Mark2SDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/error":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Error log level - only errors will be logged"}],"title":"PGLogLevel.error","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/error","navigatorTitle":[{"text":"PGLogLevelError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"url":"\/documentation\/connectsdk\/pgloglevel\/error","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/RawRepresentable-Implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/connectsdk\/pgloglevel\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/all":{"navigatorTitle":[{"kind":"identifier","text":"PGLogLevelAll"}],"title":"PGLogLevel.all","abstract":[{"type":"text","text":"All log level - All messages will be logged"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/all","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgloglevel\/all","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"all"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/verbose":{"type":"topic","navigatorTitle":[{"text":"PGLogLevelVerbose","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Verbose log level - errors, warnings, info, debug and verbose will be logged","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/verbose","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verbose"}],"title":"PGLogLevel.verbose","url":"\/documentation\/connectsdk\/pgloglevel\/verbose"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/debug":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogLevelDebug"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/debug","abstract":[{"type":"text","text":"Debug log level - errors, warnings, info and debug will be logged"}],"title":"PGLogLevel.debug","url":"\/documentation\/connectsdk\/pgloglevel\/debug"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/warning":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/warning","kind":"symbol","abstract":[{"type":"text","text":"Warning log level - errors and warnings will be logged"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGLogLevelWarning"}],"title":"PGLogLevel.warning","url":"\/documentation\/connectsdk\/pgloglevel\/warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/info":{"url":"\/documentation\/connectsdk\/pgloglevel\/info","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"navigatorTitle":[{"text":"PGLogLevelInfo","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Info log level - errors, warnings and info will be logged"}],"kind":"symbol","title":"PGLogLevel.info","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/info"},"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/off":{"type":"topic","url":"\/documentation\/connectsdk\/pgloglevel\/off","role":"symbol","abstract":[{"text":"Off log level - no messages will be logged","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"off"}],"navigatorTitle":[{"kind":"identifier","text":"PGLogLevelOff"}],"title":"PGLogLevel.off","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/off","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGLogLevel","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgloglevel","navigatorTitle":[{"kind":"identifier","text":"PGLogLevel"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel/init(rawValue:)":{"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/init(rawValue:)","url":"\/documentation\/connectsdk\/pgloglevel\/init(rawvalue:)","abstract":[],"kind":"symbol","title":"init(rawValue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","value":"PGLogLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGLogLevel"}],"path":"\/metadata\/fragments"},{"value":[{"text":"PGLogLevel","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/all","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/debug","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/error","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/info","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/off","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/verbose","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel\/warning"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGLogLevel","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1error\/title","value":"PGLogLevelError"},{"value":[{"kind":"identifier","text":"PGLogLevelError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1error\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1all\/title","value":"PGLogLevelAll","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1all\/fragments","value":[{"text":"PGLogLevelAll","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1verbose\/title","value":"PGLogLevelVerbose"},{"op":"replace","value":[{"kind":"identifier","text":"PGLogLevelVerbose"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1verbose\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1debug\/title","value":"PGLogLevelDebug"},{"value":[{"kind":"identifier","text":"PGLogLevelDebug"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1debug\/fragments"},{"value":"PGLogLevelWarning","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1warning\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGLogLevelWarning"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1warning\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1info\/title","op":"replace","value":"PGLogLevelInfo"},{"value":[{"kind":"identifier","text":"PGLogLevelInfo"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1info\/fragments","op":"replace"},{"op":"replace","value":"PGLogLevelOff","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1off\/title"},{"value":[{"text":"PGLogLevelOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel~1off\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title","value":"PGLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments","value":[{"text":"PGLogLevel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}