{"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGManagerState"}],"externalID":"c:@M@ConnectSDK@E@PGManagerState","role":"symbol","modules":[{"name":"ConnectSDK"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"PGManagerState"}],"symbolKind":"enum","title":"PGManagerState"},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGManagerState"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOff","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/resetting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unauthorized","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unknown","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unsupported"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/RawRepresentable-Implementations"],"generated":true}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgmanagerstate"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Represents the current state of a PGManager.","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/unknown":{"abstract":[{"text":"State unknown, update imminent.","type":"text"}],"title":"PGManagerState.unknown","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unknown","url":"\/documentation\/connectsdk\/pgmanagerstate\/unknown","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"PGManagerStateUnknown","kind":"identifier"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/poweredOff":{"abstract":[{"type":"text","text":"Bluetooth is currently powered off."}],"type":"topic","title":"PGManagerState.poweredOff","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGManagerStatePoweredOff"}],"url":"\/documentation\/connectsdk\/pgmanagerstate\/poweredoff","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poweredOff"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOff"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/connectsdk\/pgmanagerstate\/rawrepresentable-implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/unauthorized":{"abstract":[{"text":"The application is not authorized to use the Bluetooth Low Energy role.","type":"text"}],"type":"topic","title":"PGManagerState.unauthorized","role":"symbol","navigatorTitle":[{"text":"PGManagerStateUnauthorized","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate\/unauthorized","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unauthorized"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unauthorized"},"doc://com.proglove.Mark2SDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/Equatable-Implementations":{"url":"\/documentation\/connectsdk\/pgmanagerstate\/equatable-implementations","title":"Equatable Implementations","abstract":[],"kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/Equatable-Implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/resetting":{"role":"symbol","title":"PGManagerState.resetting","url":"\/documentation\/connectsdk\/pgmanagerstate\/resetting","abstract":[{"text":"The connection with the system service was momentarily lost, update imminent.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/resetting","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetting"}],"navigatorTitle":[{"text":"PGManagerStateResetting","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/init(rawValue:)","url":"\/documentation\/connectsdk\/pgmanagerstate\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol"},"doc://com.proglove.Mark2SDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanagerstate","abstract":[{"text":"Represents the current state of a PGManager.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","kind":"symbol","type":"topic","title":"PGManagerState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGManagerState","kind":"identifier"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/unsupported":{"url":"\/documentation\/connectsdk\/pgmanagerstate\/unsupported","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unsupported","abstract":[{"text":"The platform doesn’t support the Bluetooth Low Energy Central\/Client role.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unsupported","kind":"identifier"}],"title":"PGManagerState.unsupported","navigatorTitle":[{"text":"PGManagerStateUnsupported","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState/poweredOn":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn","abstract":[{"text":"Bluetooth is currently powered on and available to use.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"poweredOn","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGManagerStatePoweredOn"}],"title":"PGManagerState.poweredOn","url":"\/documentation\/connectsdk\/pgmanagerstate\/poweredon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PGManagerState","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PGManagerState"}],"path":"\/metadata\/fragments"},{"value":[{"text":"PGManagerState","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOff","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/poweredOn","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/resetting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unauthorized","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unknown","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState\/unsupported"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGManagerState"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"PGManagerStateUnknown","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unknown\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unknown\/fragments","value":[{"text":"PGManagerStateUnknown","kind":"identifier"}],"op":"replace"},{"value":"PGManagerStatePoweredOff","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOff\/title","op":"replace"},{"value":[{"text":"PGManagerStatePoweredOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOff\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unauthorized\/title","value":"PGManagerStateUnauthorized","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unauthorized\/fragments","value":[{"kind":"identifier","text":"PGManagerStateUnauthorized"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1resetting\/title","value":"PGManagerStateResetting","op":"replace"},{"op":"replace","value":[{"text":"PGManagerStateResetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1resetting\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title","value":"PGManagerState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments","value":[{"text":"PGManagerState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unsupported\/title","value":"PGManagerStateUnsupported"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1unsupported\/fragments","value":[{"text":"PGManagerStateUnsupported","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOn\/title","value":"PGManagerStatePoweredOn"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState~1poweredOn\/fragments","value":[{"text":"PGManagerStatePoweredOn","kind":"identifier"}],"op":"replace"}]}]}