{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PGManager","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Entry point to the manager role. Commands should only be issued when its state is ","type":"text"},{"type":"text","text":"PGManagerStatePoweredOn"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"PGManager"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"kind":"relationships","type":"conformsTo"}],"metadata":{"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGManager","symbolKind":"class","title":"PGManager","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGManager"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmanager"]},{"paths":["\/documentation\/connectsdk\/pgmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/state"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager/state":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGManagerState","preciseIdentifier":"c:@M@ConnectSDK@E@PGManagerState"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"state","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanager\/state","title":"state","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/state","abstract":[{"text":"State of the PGManager","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/connectsdk\/pgmanager\/init","title":"init","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/init","kind":"symbol","abstract":[]},"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"PGCentralManager","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"title":"PGCentralManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGManager"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PGManager","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanager","title":"PGManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","kind":"symbol","abstract":[{"type":"text","text":"PGManager"}]},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"PGManager","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PGManager"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PGManager","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/state"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/init"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"],"title":"Inherited By"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGManager"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"state","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager~1state\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager~1state\/fragments","value":[{"text":"state","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager","op":"replace"},{"value":[{"text":"PGCentralManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/title","op":"replace","value":"PGManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/fragments","op":"replace","value":[{"text":"PGManager","kind":"identifier"}]}]}]}