{"abstract":[{"type":"text","text":"The delegate of a {@link PGManager} object must adopt the "},{"type":"text","text":"PGManagerDelegate"},{"type":"text","text":" protocol. The"},{"type":"text","text":" "},{"text":"single required method indicates the availability of the manager.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmanagerdelegate"]},{"paths":["\/documentation\/connectsdk\/pgmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate\/managerDidUpdateState(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate"},"metadata":{"symbolKind":"protocol","externalID":"c:@M@ConnectSDK@objc(pl)PGManagerDelegate","navigatorTitle":[{"text":"PGManagerDelegate","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGManagerDelegate"}],"title":"PGManagerDelegate","role":"symbol","roleHeading":"Protocol"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherited By","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate"],"kind":"relationships","type":"inheritedBy"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGManagerDelegate"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerDelegate/managerDidUpdateState(_:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate\/managerDidUpdateState(_:)","url":"\/documentation\/connectsdk\/pgmanagerdelegate\/managerdidupdatestate(_:)","navigatorTitle":[{"text":"managerDidUpdateState:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"managerDidUpdateState(_:)","abstract":[{"text":"centralManagerDidUpdateState:","type":"text"}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"managerDidUpdateState"},{"text":"(","kind":"text"},{"text":"PGManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGManager"},{"text":")","kind":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerDelegate":{"abstract":[{"type":"text","text":"The delegate of a {@link PGManager} object must adopt the "},{"text":"PGManagerDelegate","type":"text"},{"type":"text","text":" protocol. The"},{"type":"text","text":" "},{"type":"text","text":"single required method indicates the availability of the manager."}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","navigatorTitle":[{"text":"PGManagerDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGManagerDelegate","kind":"identifier"}],"title":"PGManagerDelegate","role":"symbol","url":"\/documentation\/connectsdk\/pgmanagerdelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","abstract":[{"text":"PGCentralManagerDelegate","type":"text"}],"role":"symbol","title":"PGCentralManagerDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"PGCentralManagerDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PGManagerDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"PGManagerDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"PGManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate\/managerDidUpdateState(_:)"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherited By","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate"],"kind":"relationships","type":"inheritedBy"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGManagerDelegate"}]}]}},{"op":"replace","value":"managerDidUpdateState:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate~1managerDidUpdateState(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"managerDidUpdateState:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate~1managerDidUpdateState(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/title","value":"PGManagerDelegate"},{"value":[{"kind":"identifier","text":"PGManagerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/fragments"},{"value":"PGCentralManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title"},{"op":"replace","value":[{"text":"PGCentralManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}