{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGOrientation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Definition of the valid display orientations."}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/east","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/invalid","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/north","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/south","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/west"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"metadata":{"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGOrientation","role":"symbol","title":"PGOrientation","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGOrientation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"symbolKind":"enum"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgorientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgorientation"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/north":{"title":"PGOrientation.north","url":"\/documentation\/connectsdk\/pgorientation\/north","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/north","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PGOrientationNorth"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"north"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/Equatable-Implementations":{"kind":"article","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/Equatable-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/connectsdk\/pgorientation\/equatable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/RawRepresentable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/RawRepresentable-Implementations","url":"\/documentation\/connectsdk\/pgorientation\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/east":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/east","url":"\/documentation\/connectsdk\/pgorientation\/east","role":"symbol","kind":"symbol","title":"PGOrientation.east","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"east"}],"navigatorTitle":[{"text":"PGOrientationEast","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/west":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"west"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGOrientationWest"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/west","url":"\/documentation\/connectsdk\/pgorientation\/west","title":"PGOrientation.west","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation":{"role":"symbol","url":"\/documentation\/connectsdk\/pgorientation","navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"kind":"symbol","title":"PGOrientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGOrientation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","abstract":[{"type":"text","text":"Definition of the valid display orientations."}]},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/init(rawValue:)":{"role":"symbol","url":"\/documentation\/connectsdk\/pgorientation\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/init(rawValue:)","abstract":[]},"doc://com.proglove.Mark2SDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/south":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/south","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"south"}],"title":"PGOrientation.south","url":"\/documentation\/connectsdk\/pgorientation\/south","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGOrientationSouth"}],"kind":"symbol","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/invalid":{"url":"\/documentation\/connectsdk\/pgorientation\/invalid","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/invalid","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalid"}],"kind":"symbol","abstract":[],"title":"PGOrientation.invalid","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGOrientationInvalid"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"PGOrientation","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"PGOrientation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PGOrientation","kind":"identifier"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/east","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/invalid","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/north","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/south","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/west"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGOrientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1north\/title","value":"PGOrientationNorth","op":"replace"},{"value":[{"text":"PGOrientationNorth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1north\/fragments"},{"op":"replace","value":"PGOrientationEast","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1east\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGOrientationEast"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1east\/fragments"},{"value":"PGOrientationWest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1west\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1west\/fragments","value":[{"kind":"identifier","text":"PGOrientationWest"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/title","value":"PGOrientation","op":"replace"},{"op":"replace","value":[{"text":"PGOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1south\/title","value":"PGOrientationSouth"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1south\/fragments","value":[{"text":"PGOrientationSouth","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1invalid\/title","value":"PGOrientationInvalid","op":"replace"},{"op":"replace","value":[{"text":"PGOrientationInvalid","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1invalid\/fragments"}]}]}