{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgpairingqr"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgpairingqr"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPairingQR"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"title":"PGPairingQR","roleHeading":"Class","symbolKind":"class","externalID":"c:@M@ConnectSDK@objc(cs)PGPairingQR","role":"symbol","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGPairingQR"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPairingQR"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR\/generate(_:_:_:_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR\/generate(withIndicator:options:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQR/generate(withIndicator:options:)":{"title":"generate(withIndicator:options:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"generateWithIndicator:options:error:"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR\/generate(withIndicator:options:)","role":"symbol","url":"\/documentation\/connectsdk\/pgpairingqr\/generate(withindicator:options:)","abstract":[{"text":"The util method for generating connection barcode with additional connection options.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPairingQRGeneratorOptions","text":"PGPairingQRGeneratorOptions"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQR/generate(_:_:_:_:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR\/generate(_:_:_:_:)","abstract":[{"text":"Generates a QR code with the given identifier and error correction level at the given size","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel","text":"PGPairingQRGeneratorErrorCorrectionLevel"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"title":"generate(_:_:_:_:)","navigatorTitle":[{"text":"generate::::","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgpairingqr\/generate(_:_:_:_:)"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQR":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR","abstract":[],"navigatorTitle":[{"text":"PGPairingQR","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgpairingqr","title":"PGPairingQR","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPairingQR"}]},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PGPairingQR"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPairingQR"}],"op":"replace"},{"value":[{"text":"PGPairingQR","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR\/generate(_:_:_:_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR\/generate(withIndicator:options:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQR"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR~1generate(withIndicator:options:)\/title","value":"generateWithIndicator:options:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR~1generate(withIndicator:options:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"generateWithIndicator:options:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR~1generate(_:_:_:_:)\/title","op":"replace","value":"generate::::"},{"value":[{"kind":"text","text":"+ "},{"text":"generate::::","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR~1generate(_:_:_:_:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR\/title","op":"replace","value":"PGPairingQR"},{"op":"replace","value":[{"text":"PGPairingQR","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}