{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorapierror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorapierror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"PG pairing barcode generator error codes"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}],"title":"PGPairingQRGeneratorApiError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorApiError","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicator","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicatorLength"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError/invalidIndicatorLength":{"role":"symbol","title":"PGPairingQRGeneratorApiError.invalidIndicatorLength","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidIndicatorLength"}],"abstract":[{"type":"text","text":"Invalid indicator length."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicatorLength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicatorlength"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/rawrepresentable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError":{"role":"symbol","title":"PGPairingQRGeneratorApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}],"abstract":[{"type":"text","text":"PG pairing barcode generator error codes"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError/invalidIndicator":{"role":"symbol","title":"PGPairingQRGeneratorApiError.invalidIndicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidIndicator"}],"abstract":[{"type":"text","text":"Invalid indicator length."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicator"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicator"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/init(rawvalue:)"},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"PGPairingQRGeneratorApiError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicator","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicatorLength"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorApiError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicatorLength\/title","value":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicatorLength\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/title","value":"PGPairingQRGeneratorApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicator\/title","value":"PGPairingQRGeneratorApiErrorInvalidIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicator\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}