{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"role":"symbol","externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel","symbolKind":"enum","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"title":"PGPairingQRGeneratorErrorCorrectionLevel"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"PGPairingQRGeneratorErrorCorrectionLevelL: Level L, 7% error correction capability"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPairingQRGeneratorErrorCorrectionLevelM: Level M, 15% error correction capability"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelQ: Level Q, 25% error correction capability","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPairingQRGeneratorErrorCorrectionLevelH: Level H, 30% error correction capability"}]}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel"]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/H","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/L","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/M","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/Q"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel","title":"PGPairingQRGeneratorErrorCorrectionLevel","abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/H":{"abstract":[{"text":"Level H, 30% error correction capability","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelH"}],"type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/h","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"H"}],"kind":"symbol","title":"PGPairingQRGeneratorErrorCorrectionLevel.H","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/H"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/Q":{"abstract":[{"text":"Level Q, 25% error correction capability","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/Q","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/q","title":"PGPairingQRGeneratorErrorCorrectionLevel.Q","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Q"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelQ"}]},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/Equatable-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/Equatable-Implementations","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/equatable-implementations","title":"Equatable Implementations","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/RawRepresentable-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/rawrepresentable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/L":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/L","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"L"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/l","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelL"}],"type":"topic","abstract":[{"type":"text","text":"Level L, 7% error correction capability"}],"title":"PGPairingQRGeneratorErrorCorrectionLevel.L"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/init(rawValue:)":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/init(rawvalue:)","kind":"symbol"},"doc://com.proglove.Mark2SDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/M":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/m","type":"topic","kind":"symbol","abstract":[{"text":"Level M, 15% error correction capability","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/M","title":"PGPairingQRGeneratorErrorCorrectionLevel.M","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelM"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"M"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"PGPairingQRGeneratorErrorCorrectionLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/H","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/L","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/M","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/Q"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"PGPairingQRGeneratorErrorCorrectionLevel","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments","op":"replace","value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}]},{"value":"PGPairingQRGeneratorErrorCorrectionLevelH","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1H\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1H\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelH"}]},{"op":"replace","value":"PGPairingQRGeneratorErrorCorrectionLevelQ","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1Q\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1Q\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelQ"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1L\/title","value":"PGPairingQRGeneratorErrorCorrectionLevelL","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1L\/fragments","op":"replace","value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelL","kind":"identifier"}]},{"op":"replace","value":"PGPairingQRGeneratorErrorCorrectionLevelM","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1M\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1M\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelM"}],"op":"replace"}]}]}