{"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/errorCorrectionLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/fullDiscoveryHandshakeEnabled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageScale","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageSize"],"title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratoroptions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Class","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGPairingQRGeneratorOptions","role":"symbol","title":"PGPairingQRGeneratorOptions","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"symbolKind":"class"},"abstract":[{"type":"text","text":"Options for generating QR pairing image"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions","title":"PGPairingQRGeneratorOptions","abstract":[{"type":"text","text":"Options for generating QR pairing image"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/imageScale":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageScale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/imagescale","abstract":[{"type":"text","text":"The PG Pairing QR image scale"}],"type":"topic","title":"imageScale","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageScale","kind":"symbol","navigatorTitle":[{"text":"imageScale","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/errorCorrectionLevel":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/errorCorrectionLevel","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/errorcorrectionlevel","title":"errorCorrectionLevel","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCorrectionLevel"},{"text":": ","kind":"text"},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel"}],"navigatorTitle":[{"text":"errorCorrectionLevel","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}]},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/fullDiscoveryHandshakeEnabled":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/fullDiscoveryHandshakeEnabled","url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/fulldiscoveryhandshakeenabled","title":"fullDiscoveryHandshakeEnabled","abstract":[{"type":"text","text":"Enable full discover handshake"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fullDiscoveryHandshakeEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fullDiscoveryHandshakeEnabled"}]},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/init":{"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/init","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions/imageSize":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageSize","abstract":[{"type":"text","text":"The PG Pairing QR image size"}],"navigatorTitle":[{"kind":"identifier","text":"imageSize"}],"kind":"symbol","role":"symbol","title":"imageSize","url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions\/imagesize","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGPairingQRGeneratorOptions","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}]},{"value":[{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/errorCorrectionLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/fullDiscoveryHandshakeEnabled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageScale","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/imageSize"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions\/init"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPairingQRGeneratorOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGPairingQRGeneratorOptions","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/title"},{"value":[{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1imageScale\/title","op":"replace","value":"imageScale"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1imageScale\/fragments","value":[{"kind":"identifier","text":"imageScale"}],"op":"replace"},{"op":"replace","value":"errorCorrectionLevel","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1errorCorrectionLevel\/title"},{"value":[{"text":"errorCorrectionLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1errorCorrectionLevel\/fragments"},{"op":"replace","value":"fullDiscoveryHandshakeEnabled","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1fullDiscoveryHandshakeEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"fullDiscoveryHandshakeEnabled"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1fullDiscoveryHandshakeEnabled\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1imageSize\/title","value":"imageSize","op":"replace"},{"value":[{"kind":"identifier","text":"imageSize"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions~1imageSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}