{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@PGPeripheralErrorCentralHasRetriedConnectingKey","roleHeading":"Global Variable","symbolKind":"var","title":"PGPeripheralErrorCentralHasRetriedConnectingKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheralErrorCentralHasRetriedConnectingKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorCentralHasRetriedConnectingKey"}],"role":"symbol","modules":[{"name":"ConnectSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralErrorCentralHasRetriedConnectingKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorCentralHasRetriedConnectingKey","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerrorcentralhasretriedconnectingkey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerrorcentralhasretriedconnectingkey"]}],"abstract":[{"type":"text","text":"A NSNumber Boolean value indicating if the central has retried connection to this peripheral"}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralErrorCentralHasRetriedConnectingKey":{"url":"\/documentation\/connectsdk\/pgperipheralerrorcentralhasretriedconnectingkey","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorCentralHasRetriedConnectingKey","navigatorTitle":[{"text":"PGPeripheralErrorCentralHasRetriedConnectingKey","kind":"identifier"}],"kind":"symbol","title":"PGPeripheralErrorCentralHasRetriedConnectingKey","role":"symbol","abstract":[{"type":"text","text":"A NSNumber Boolean value indicating if the central has retried connection to this peripheral"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"PGPeripheralErrorCentralHasRetriedConnectingKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorCentralHasRetriedConnectingKey"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorCentralHasRetriedConnectingKey"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"PGPeripheralErrorCentralHasRetriedConnectingKey","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorCentralHasRetriedConnectingKey\/title","value":"PGPeripheralErrorCentralHasRetriedConnectingKey"},{"value":[{"text":"PGPeripheralErrorCentralHasRetriedConnectingKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorCentralHasRetriedConnectingKey\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}