{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralErrorDomain"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"title":"PGPeripheralErrorDomain","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralErrorDomain"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable","role":"symbol","symbolKind":"var","modules":[{"name":"ConnectSDK"}],"externalID":"c:@PGPeripheralErrorDomain","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorDomain"}]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorDomain","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The peripheral error domain"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerrordomain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerrordomain"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralErrorDomain":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorDomain","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"PGPeripheralErrorDomain","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheralerrordomain","title":"PGPeripheralErrorDomain","abstract":[{"type":"text","text":"The peripheral error domain"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PGPeripheralErrorDomain"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPeripheralErrorDomain","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"PGPeripheralErrorDomain","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"PGPeripheralErrorDomain","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorDomain\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorDomain\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorDomain"}]}]}]}