{"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheral","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/batteryLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/delegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/identifier","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/lockState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/name","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/state"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/requestDeviceInformation(withDeviceInfoCommand:completionHandler:)"],"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"]}],"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheral"}],"navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"title":"PGPeripheral","role":"symbol","roleHeading":"Class","externalID":"c:@M@ConnectSDK@objc(cs)PGPeripheral","modules":[{"name":"ConnectSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheral"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheral"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/name":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/name","title":"name","navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheral\/name","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral":{"url":"\/documentation\/connectsdk\/pgmockperipheral","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGMockPeripheral","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGMockPeripheral"}],"title":"PGMockPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A mock peripheral for use in testing"}]},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/delegate":{"url":"\/documentation\/connectsdk\/pgperipheral\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/delegate","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate","text":"PGPeripheralDelegate"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/lockState":{"url":"\/documentation\/connectsdk\/pgperipheral\/lockstate","navigatorTitle":[{"text":"lockState","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/lockState","title":"lockState","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lockState","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","text":"PGPeripheralLockState","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/requestDeviceInformation(withDeviceInfoCommand:completionHandler:)":{"url":"\/documentation\/connectsdk\/pgperipheral\/requestdeviceinformation(withdeviceinfocommand:completionhandler:)","navigatorTitle":[{"text":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/requestDeviceInformation(withDeviceInfoCommand:completionHandler:)","title":"requestDeviceInformation(withDeviceInfoCommand:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestDeviceInformation","kind":"identifier"},{"kind":"text","text":"("},{"text":"withDeviceInfoCommand","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","kind":"typeIdentifier","text":"PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformation","text":"PGDeviceInformation"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/identifier":{"url":"\/documentation\/connectsdk\/pgperipheral\/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/identifier","kind":"symbol","title":"identifier","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.proglove.Mark2SDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/state":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGPeripheralState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralState"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/state","url":"\/documentation\/connectsdk\/pgperipheral\/state","kind":"symbol","type":"topic","navigatorTitle":[{"text":"state","kind":"identifier"}],"title":"state","abstract":[],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/batteryLevel":{"url":"\/documentation\/connectsdk\/pgperipheral\/batterylevel","navigatorTitle":[{"kind":"identifier","text":"batteryLevel"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/batteryLevel","title":"batteryLevel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"batteryLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","title":"PGPeripheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheral"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheral"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PGPeripheral","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PGPeripheral"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/batteryLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/delegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/identifier","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/lockState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/name","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/state"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/requestDeviceInformation(withDeviceInfoCommand:completionHandler:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"inheritedBy","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral"],"kind":"relationships","title":"Inherited By"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PGPeripheral","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1name\/title","value":"name","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"value":"PGMockPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/title","op":"replace"},{"value":[{"text":"PGMockPeripheral","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1delegate\/title","op":"replace","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1lockState\/title","op":"replace","value":"lockState"},{"value":[{"text":"lockState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1lockState\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1requestDeviceInformation(withDeviceInfoCommand:completionHandler:)\/title","value":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1requestDeviceInformation(withDeviceInfoCommand:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:","kind":"identifier"}]},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1identifier\/title"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1identifier\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1state\/title","op":"replace","value":"state"},{"value":[{"kind":"identifier","text":"state"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1state\/fragments"},{"op":"replace","value":"batteryLevel","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1batteryLevel\/title"},{"value":[{"kind":"identifier","text":"batteryLevel"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1batteryLevel\/fragments"},{"op":"replace","value":"PGPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheral"}]}]}]}