{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringCharacteristics","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringServices","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteFailedTryLater","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteTooLarge","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/bluetoothNotAvailable","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectingTimedOut","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectionTimedOut","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/discoveryTimedOut","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/incompatibleModel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidData","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingCharacteristics","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingServices","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notConnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notReady","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/operationCancelled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralDisconnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralNotPaired","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unexpectedUnresolvable","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unhandled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unsupportedFeature"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/RawRepresentable-Implementations"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"All PG peripheral error codes"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","title":"PGPeripheralError","externalID":"c:@M@ConnectSDK@E@PGPeripheralError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralError"}],"navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"symbolKind":"enum"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attErrorDiscoveringServices":{"abstract":[{"type":"text","text":"An ATT error occurred discovering services"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorAttErrorDiscoveringServices"}],"type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringservices","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringServices","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attErrorDiscoveringServices","kind":"identifier"}],"title":"PGPeripheralError.attErrorDiscoveringServices","kind":"symbol"},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","title":"Swift.RawRepresentable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/unsupportedFeature":{"title":"PGPeripheralError.unsupportedFeature","url":"\/documentation\/connectsdk\/pgperipheralerror\/unsupportedfeature","abstract":[{"text":"Peripheral feature is unsupported","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unsupportedFeature","type":"topic","navigatorTitle":[{"text":"PGPeripheralErrorUnsupportedFeature","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsupportedFeature","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"title":"PGPeripheralError","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/RawRepresentable-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/connectsdk\/pgperipheralerror\/rawrepresentable-implementations","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/RawRepresentable-Implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/connectsdk\/pgperipheralerror\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/Equatable-Implementations","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/incompatibleModel":{"url":"\/documentation\/connectsdk\/pgperipheralerror\/incompatiblemodel","abstract":[{"type":"text","text":"The device is not compatible with this App based on its model number. See PGPeripheralErrorIncompatibleModelNumberKey for the model number"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/incompatibleModel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incompatibleModel"}],"navigatorTitle":[{"text":"PGPeripheralErrorIncompatibleModel","kind":"identifier"}],"title":"PGPeripheralError.incompatibleModel","kind":"symbol","role":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/operationCancelled":{"title":"PGPeripheralError.operationCancelled","url":"\/documentation\/connectsdk\/pgperipheralerror\/operationcancelled","abstract":[{"text":"The operation was cancelled","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/operationCancelled","type":"topic","navigatorTitle":[{"text":"PGPeripheralErrorOperationCancelled","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"operationCancelled","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/discoveryTimedOut":{"url":"\/documentation\/connectsdk\/pgperipheralerror\/discoverytimedout","kind":"symbol","title":"PGPeripheralError.discoveryTimedOut","type":"topic","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/discoveryTimedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"discoveryTimedOut","kind":"identifier"}],"navigatorTitle":[{"text":"PGPeripheralErrorDiscoveryTimedOut","kind":"identifier"}],"abstract":[{"type":"text","text":"Peripheral discovery timed out"}]},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/peripheralNotPaired":{"title":"PGPeripheralError.peripheralNotPaired","url":"\/documentation\/connectsdk\/pgperipheralerror\/peripheralnotpaired","abstract":[{"text":"The device was not paired, or pairing was cancelled","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralNotPaired","type":"topic","navigatorTitle":[{"text":"PGPeripheralErrorPeripheralNotPaired","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"peripheralNotPaired","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attributeWriteFailedTryLater":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteFailedTryLater","url":"\/documentation\/connectsdk\/pgperipheralerror\/attributewritefailedtrylater","title":"PGPeripheralError.attributeWriteFailedTryLater","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"attributeWriteFailedTryLater","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Writing to the attribute failed but can be retried later","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PGPeripheralErrorAttributeWriteFailedTryLater","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/missingCharacteristics":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"missingCharacteristics","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Required characteristics were missing"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/missingcharacteristics","title":"PGPeripheralError.missingCharacteristics","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingCharacteristics","navigatorTitle":[{"text":"PGPeripheralErrorMissingCharacteristics","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/invalidData":{"abstract":[{"type":"text","text":"Data read from the device was invalid. Could suggest the GATT cache is invalid, requiring a Bluetooth toggle."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidData","navigatorTitle":[{"text":"PGPeripheralErrorInvalidData","kind":"identifier"}],"kind":"symbol","title":"PGPeripheralError.invalidData","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror\/invaliddata","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidData","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/peripheralDisconnected":{"navigatorTitle":[{"text":"PGPeripheralErrorPeripheralDisconnected","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The peripheral closed the connection or went out of range","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralDisconnected","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheralDisconnected","kind":"identifier"}],"type":"topic","title":"PGPeripheralError.peripheralDisconnected","url":"\/documentation\/connectsdk\/pgperipheralerror\/peripheraldisconnected"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attErrorDiscoveringCharacteristics":{"navigatorTitle":[{"text":"PGPeripheralErrorAttErrorDiscoveringCharacteristics","kind":"identifier"}],"abstract":[{"type":"text","text":"An ATT error occurred discovering characteristics, see PGPeripheralErrorServiceKey for the NSUUID of the service"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringCharacteristics","title":"PGPeripheralError.attErrorDiscoveringCharacteristics","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attErrorDiscoveringCharacteristics"}],"type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringcharacteristics"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/notConnected":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notConnected"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notConnected","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorNotConnected"}],"title":"PGPeripheralError.notConnected","url":"\/documentation\/connectsdk\/pgperipheralerror\/notconnected","abstract":[{"type":"text","text":"Not connected to the peripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/init(rawValue:)":{"url":"\/documentation\/connectsdk\/pgperipheralerror\/init(rawvalue:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/invalidState":{"title":"PGPeripheralError.invalidState","url":"\/documentation\/connectsdk\/pgperipheralerror\/invalidstate","abstract":[{"type":"text","text":"Peripheral was in an invalid state for performing this operation"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidState","type":"topic","navigatorTitle":[{"text":"PGPeripheralErrorInvalidState","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidState"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attributeWriteTooLarge":{"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteTooLarge"}],"title":"PGPeripheralError.attributeWriteTooLarge","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteTooLarge","abstract":[{"text":"The write to the attribute went beyond the bounds of the attribute’s size","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/attributewritetoolarge","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attributeWriteTooLarge","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/connectionTimedOut":{"title":"PGPeripheralError.connectionTimedOut","url":"\/documentation\/connectsdk\/pgperipheralerror\/connectiontimedout","abstract":[{"type":"text","text":"Connection timed out"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectionTimedOut","type":"topic","navigatorTitle":[{"text":"PGPeripheralErrorConnectionTimedOut","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionTimedOut"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/notReady":{"title":"PGPeripheralError.notReady","abstract":[{"text":"Device is not ready to perform this action (usually when connecting)","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notReady","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/notready","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notReady","navigatorTitle":[{"text":"PGPeripheralErrorNotReady","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/missingServices":{"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorMissingServices"}],"role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/missingservices","abstract":[{"type":"text","text":"Required services were missing"}],"type":"topic","title":"PGPeripheralError.missingServices","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingServices"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingServices"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/connectingTimedOut":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectingTimedOut","role":"symbol","navigatorTitle":[{"text":"PGPeripheralErrorConnectingTimedOut","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectingTimedOut","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Connecting timed out"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/connectingtimedout","title":"PGPeripheralError.connectingTimedOut"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/bluetoothNotAvailable":{"navigatorTitle":[{"text":"PGPeripheralErrorBluetoothNotAvailable","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/bluetoothNotAvailable","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror\/bluetoothnotavailable","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bluetoothNotAvailable","kind":"identifier"}],"abstract":[{"text":"Bluetooth not available.","type":"text"}],"role":"symbol","title":"PGPeripheralError.bluetoothNotAvailable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/unexpectedUnresolvable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unexpectedUnresolvable","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unexpectedUnresolvable","role":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/unexpectedunresolvable","abstract":[{"type":"text","text":"Unexpected error that cannot be resolved."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"PGPeripheralErrorUnexpectedUnresolvable","kind":"identifier"}],"title":"PGPeripheralError.unexpectedUnresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/unhandled":{"title":"PGPeripheralError.unhandled","url":"\/documentation\/connectsdk\/pgperipheralerror\/unhandled","abstract":[{"text":"Unhandled error.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unhandled","type":"topic","navigatorTitle":[{"text":"PGPeripheralErrorUnhandled","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unhandled"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralError"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PGPeripheralError","kind":"identifier"}]},{"value":[{"text":"PGPeripheralError","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringCharacteristics","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringServices","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteFailedTryLater","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteTooLarge","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/bluetoothNotAvailable","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectingTimedOut","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectionTimedOut","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/discoveryTimedOut","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/incompatibleModel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidData","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingCharacteristics","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingServices","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notConnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notReady","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/operationCancelled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralDisconnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralNotPaired","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unexpectedUnresolvable","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unhandled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unsupportedFeature"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringServices\/title","value":"PGPeripheralErrorAttErrorDiscoveringServices"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringServices\/fragments","value":[{"text":"PGPeripheralErrorAttErrorDiscoveringServices","kind":"identifier"}]},{"op":"replace","value":"PGPeripheralErrorUnsupportedFeature","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unsupportedFeature\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unsupportedFeature\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorUnsupportedFeature"}]},{"value":"PGPeripheralError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title"},{"value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1incompatibleModel\/title","value":"PGPeripheralErrorIncompatibleModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1incompatibleModel\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorIncompatibleModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1operationCancelled\/title","value":"PGPeripheralErrorOperationCancelled"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1operationCancelled\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorOperationCancelled"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1discoveryTimedOut\/title","op":"replace","value":"PGPeripheralErrorDiscoveryTimedOut"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1discoveryTimedOut\/fragments","op":"replace","value":[{"text":"PGPeripheralErrorDiscoveryTimedOut","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralNotPaired\/title","value":"PGPeripheralErrorPeripheralNotPaired","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralNotPaired\/fragments","value":[{"text":"PGPeripheralErrorPeripheralNotPaired","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteFailedTryLater\/title","value":"PGPeripheralErrorAttributeWriteFailedTryLater","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteFailedTryLater\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteFailedTryLater"}]},{"value":"PGPeripheralErrorMissingCharacteristics","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1missingCharacteristics\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1missingCharacteristics\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorMissingCharacteristics"}]},{"value":"PGPeripheralErrorInvalidData","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidData\/title","op":"replace"},{"value":[{"text":"PGPeripheralErrorInvalidData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidData\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralDisconnected\/title","value":"PGPeripheralErrorPeripheralDisconnected"},{"value":[{"text":"PGPeripheralErrorPeripheralDisconnected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralDisconnected\/fragments"},{"value":"PGPeripheralErrorAttErrorDiscoveringCharacteristics","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringCharacteristics\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringCharacteristics\/fragments","value":[{"text":"PGPeripheralErrorAttErrorDiscoveringCharacteristics","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1notConnected\/title","value":"PGPeripheralErrorNotConnected"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1notConnected\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorNotConnected"}]},{"value":"PGPeripheralErrorInvalidState","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidState\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidState\/fragments","value":[{"text":"PGPeripheralErrorInvalidState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteTooLarge\/title","value":"PGPeripheralErrorAttributeWriteTooLarge","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteTooLarge\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteTooLarge"}],"op":"replace"},{"op":"replace","value":"PGPeripheralErrorConnectionTimedOut","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectionTimedOut\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectionTimedOut\/fragments","value":[{"text":"PGPeripheralErrorConnectionTimedOut","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1notReady\/title","value":"PGPeripheralErrorNotReady","op":"replace"},{"value":[{"kind":"identifier","text":"PGPeripheralErrorNotReady"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1notReady\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1missingServices\/title","value":"PGPeripheralErrorMissingServices"},{"value":[{"kind":"identifier","text":"PGPeripheralErrorMissingServices"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1missingServices\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectingTimedOut\/title","value":"PGPeripheralErrorConnectingTimedOut"},{"op":"replace","value":[{"text":"PGPeripheralErrorConnectingTimedOut","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectingTimedOut\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1bluetoothNotAvailable\/title","value":"PGPeripheralErrorBluetoothNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1bluetoothNotAvailable\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorBluetoothNotAvailable"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unexpectedUnresolvable\/title","op":"replace","value":"PGPeripheralErrorUnexpectedUnresolvable"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unexpectedUnresolvable\/fragments","value":[{"text":"PGPeripheralErrorUnexpectedUnresolvable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unhandled\/title","op":"replace","value":"PGPeripheralErrorUnhandled"},{"value":[{"kind":"identifier","text":"PGPeripheralErrorUnhandled"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unhandled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}