{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralState"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPeripheralStateDisconnected: The peripheral is currently not connected to the central manager."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPeripheralStateConnecting: The peripheral is currently in the process of connecting to the central manager."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPeripheralStateDisconnecting: The peripheral is currently in the process of disconnecting from the central manager."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPeripheralStateSystemConnected: The peripheral is currently connected to the system, but not the App’s central manager."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPeripheralStateDiscovering: The peripheral is currently being interrogated by the central manager"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGPeripheralStateReady: The peripheral is ready to be used"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheralstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Values representing the current connection state of the peripheral"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralState"}],"title":"PGPeripheralState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ConnectSDK@E@PGPeripheralState","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralState"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/connecting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnecting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/discovering","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/ready","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/systemConnected"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/systemConnected":{"role":"symbol","title":"PGPeripheralState.systemConnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemConnected"}],"abstract":[{"type":"text","text":"The peripheral is currently connected to the system, but not the App’s central manager."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/systemConnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateSystemConnected"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/systemconnected"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralstate\/equatable-implementations"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/disconnected":{"role":"symbol","title":"PGPeripheralState.disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"abstract":[{"type":"text","text":"The peripheral is currently not connected to the central manager."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateDisconnected"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/disconnected"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState":{"role":"symbol","title":"PGPeripheralState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralState"}],"abstract":[{"type":"text","text":"Values representing the current connection state of the peripheral"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralState"}],"url":"\/documentation\/connectsdk\/pgperipheralstate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/ready":{"role":"symbol","title":"PGPeripheralState.ready","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ready"}],"abstract":[{"type":"text","text":"The peripheral is ready to be used"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/ready","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateReady"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/ready"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralstate\/init(rawvalue:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/discovering":{"role":"symbol","title":"PGPeripheralState.discovering","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"discovering"}],"abstract":[{"type":"text","text":"The peripheral is currently being interrogated by the central manager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/discovering","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateDiscovering"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/discovering"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralstate\/rawrepresentable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/disconnecting":{"role":"symbol","title":"PGPeripheralState.disconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnecting"}],"abstract":[{"type":"text","text":"The peripheral is currently in the process of connecting to the central manager."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateDisconnecting"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/disconnecting"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState/connecting":{"role":"symbol","title":"PGPeripheralState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"The peripheral is currently in the process of disconnecting from the central manager."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralStateConnecting"}],"url":"\/documentation\/connectsdk\/pgperipheralstate\/connecting"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPeripheralState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGPeripheralState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/connecting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnected","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/disconnecting","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/discovering","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/ready","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState\/systemConnected"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1systemConnected\/title","value":"PGPeripheralStateSystemConnected"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1systemConnected\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateSystemConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1disconnected\/title","value":"PGPeripheralStateDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1disconnected\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateDisconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/title","value":"PGPeripheralState"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/fragments","value":[{"kind":"identifier","text":"PGPeripheralState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1ready\/title","value":"PGPeripheralStateReady"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1ready\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateReady"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1discovering\/title","value":"PGPeripheralStateDiscovering"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1discovering\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateDiscovering"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1disconnecting\/title","value":"PGPeripheralStateDisconnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1disconnecting\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateDisconnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1connecting\/title","value":"PGPeripheralStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState~1connecting\/fragments","value":[{"kind":"identifier","text":"PGPeripheralStateConnecting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}