{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralLockState"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipherallockstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipherallockstate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState"},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/disabled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/locked","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/unlocked"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/RawRepresentable-Implementations"]}],"metadata":{"symbolKind":"enum","navigatorTitle":[{"text":"PGPeripheralLockState","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@ConnectSDK@E@PGPeripheralLockState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralLockState"}],"title":"PGPeripheralLockState","modules":[{"name":"ConnectSDK"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"text":"The lock status of the scanner","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/disabled":{"navigatorTitle":[{"text":"PGPeripheralLockStateDisabled","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates that the scanner locking is disabled"}],"url":"\/documentation\/connectsdk\/pgperipherallockstate\/disabled","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/disabled","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"title":"PGPeripheralLockState.disabled","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState":{"type":"topic","abstract":[{"text":"The lock status of the scanner","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgperipherallockstate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPeripheralLockState","kind":"identifier"}],"title":"PGPeripheralLockState","navigatorTitle":[{"text":"PGPeripheralLockState","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/unlocked":{"navigatorTitle":[{"text":"PGPeripheralLockStateUnlocked","kind":"identifier"}],"abstract":[{"text":"Indicates that the scanner has been unlocked with validation barcode","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipherallockstate\/unlocked","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/unlocked","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unlocked","kind":"identifier"}],"title":"PGPeripheralLockState.unlocked","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/connectsdk\/pgperipherallockstate\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/connectsdk\/pgperipherallockstate\/equatable-implementations","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","type":"topic"},"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","title":"Swift.RawRepresentable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/init(rawValue:)":{"abstract":[],"url":"\/documentation\/connectsdk\/pgperipherallockstate\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState/locked":{"navigatorTitle":[{"text":"PGPeripheralLockStateLocked","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates that the scanner is locked and expecting the validation barcode to be scanned."},{"text":" ","type":"text"},{"text":"All scanner functions are suspended until the scanner gets unlocked, or changes to a configuration","type":"text"},{"type":"text","text":" "},{"type":"text","text":"which has authentication disabled"}],"url":"\/documentation\/connectsdk\/pgperipherallockstate\/locked","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/locked","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locked","kind":"identifier"}],"title":"PGPeripheralLockState.locked","type":"topic"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralLockState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"PGPeripheralLockState"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"PGPeripheralLockState","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/disabled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/locked","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState\/unlocked"],"title":"Enumeration Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralLockState","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"PGPeripheralLockStateDisabled","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1disabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralLockStateDisabled"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1disabled\/fragments"},{"op":"replace","value":"PGPeripheralLockState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/fragments","value":[{"kind":"identifier","text":"PGPeripheralLockState"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1unlocked\/title","op":"replace","value":"PGPeripheralLockStateUnlocked"},{"value":[{"kind":"identifier","text":"PGPeripheralLockStateUnlocked"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1unlocked\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1locked\/title","value":"PGPeripheralLockStateLocked","op":"replace"},{"value":[{"text":"PGPeripheralLockStateLocked","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState~1locked\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}