{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate"]}],"kind":"symbol","metadata":{"title":"PGPeripheralDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate","symbolKind":"protocol","role":"symbol","roleHeading":"Protocol"},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didChangeLockState:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didReadRSSI:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanBarcodeWith:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didSendButtonTriggerEvent:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:errorScanningBarcode:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateBatteryLevel(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateName(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateState(_:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheralDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"},"abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheralDidUpdateName(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheralDidUpdateName"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"peripheralDidUpdateName(_:)","abstract":[{"type":"text","text":"The PG peripheral updated its name"}],"kind":"symbol","navigatorTitle":[{"text":"peripheralDidUpdateName:","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatename(_:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateName(_:)","type":"topic","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didChangeLockState:error:)":{"title":"peripheral(_:didChangeLockState:error:)","kind":"symbol","abstract":[{"type":"text","text":"The PG peripheral lock state did change"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didChangeLockState:error:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeLockState","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","kind":"typeIdentifier","text":"PGPeripheralLockState"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"peripheral:didChangeLockState:error:","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didchangelockstate:error:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didScanAuthenticationBarocodeWith:isValid:)":{"title":"peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","kind":"symbol","abstract":[{"type":"text","text":"The PG peripheral has scanned a barcode while locked"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didScanAuthenticationBarocodeWith"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult","kind":"typeIdentifier","text":"PGScannedBarcodeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isValid"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"peripheral:didScanAuthenticationBarocodeWith:isValid:","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanauthenticationbarocodewith:isvalid:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didScanBarcodeWith:)":{"title":"peripheral(_:didScanBarcodeWith:)","kind":"symbol","abstract":[{"type":"text","text":"The PG peripheral scanned a barcode"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanBarcodeWith:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didScanBarcodeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult","kind":"typeIdentifier","text":"PGScannedBarcodeResult"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"peripheral:didScanBarcodeWith:"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanbarcodewith:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheralDidUpdateBatteryLevel(_:)":{"required":true,"title":"peripheralDidUpdateBatteryLevel(_:)","kind":"symbol","abstract":[{"type":"text","text":"The Scanner peripheral updated its battery level"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateBatteryLevel(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheralDidUpdateBatteryLevel"},{"kind":"text","text":"("},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"peripheralDidUpdateBatteryLevel:","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatebatterylevel(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didSendButtonTriggerEvent:)":{"title":"peripheral(_:didSendButtonTriggerEvent:)","kind":"symbol","abstract":[{"type":"text","text":"The Scanner peripheral sent a button trigger event"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didSendButtonTriggerEvent:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSendButtonTriggerEvent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGButtonTriggerEventType","text":"PGButtonTriggerEventType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"peripheral:didSendButtonTriggerEvent:","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didsendbuttontriggerevent:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheralDidUpdateState(_:)":{"abstract":[{"type":"text","text":"The PG peripheral updated its connection state"}],"url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatestate(_:)","required":true,"navigatorTitle":[{"text":"peripheralDidUpdateState:","kind":"identifier"}],"title":"peripheralDidUpdateState(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheralDidUpdateState"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateState(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:errorScanningBarcode:)":{"required":true,"title":"peripheral(_:errorScanningBarcode:)","kind":"symbol","abstract":[{"text":"The PG peripheral encountered an error when scanning a barcode","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:errorScanningBarcode:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":", ","kind":"text"},{"text":"errorScanningBarcode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"peripheral:errorScanningBarcode:"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:errorscanningbarcode:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}],"url":"\/documentation\/connectsdk\/pgperipheraldelegate","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"title":"PGPeripheralDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralDelegate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didReadRSSI:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"text":", ","kind":"text"},{"text":"didReadRSSI","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"title":"peripheral(_:didReadRSSI:)","abstract":[{"text":"The RSSI of the device was read","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"peripheral:didReadRSSI:","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didreadrssi:)","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didReadRSSI:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PGPeripheralDelegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didChangeLockState:error:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didReadRSSI:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanBarcodeWith:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didSendButtonTriggerEvent:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:errorScanningBarcode:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateBatteryLevel(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateName(_:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateState(_:)"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralDelegate"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"peripheralDidUpdateName:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateName(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheralDidUpdateName:"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateName(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didChangeLockState:error:)\/title","value":"peripheral:didChangeLockState:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didChangeLockState:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"peripheral:didChangeLockState:error:","kind":"identifier"}]},{"value":"peripheral:didScanAuthenticationBarocodeWith:isValid:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanAuthenticationBarocodeWith:isValid:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"peripheral:didScanAuthenticationBarocodeWith:isValid:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanAuthenticationBarocodeWith:isValid:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanBarcodeWith:)\/title","value":"peripheral:didScanBarcodeWith:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didScanBarcodeWith:"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanBarcodeWith:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateBatteryLevel(_:)\/title","value":"peripheralDidUpdateBatteryLevel:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"peripheralDidUpdateBatteryLevel:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateBatteryLevel(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didSendButtonTriggerEvent:)\/title","op":"replace","value":"peripheral:didSendButtonTriggerEvent:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didSendButtonTriggerEvent:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didSendButtonTriggerEvent:"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateState(_:)\/title","value":"peripheralDidUpdateState:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheralDidUpdateState:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateState(_:)\/fragments","op":"replace"},{"op":"replace","value":"peripheral:errorScanningBarcode:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:errorScanningBarcode:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:errorScanningBarcode:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:errorScanningBarcode:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title","value":"PGPeripheralDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didReadRSSI:)\/title","value":"peripheral:didReadRSSI:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didReadRSSI:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"peripheral:didReadRSSI:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}