{"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","abstract":[{"type":"text","text":"Feedback enum"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPredefinedFeedback"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgpredefinedfeedback"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/error","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special1","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special2","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special3","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/success"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPredefinedFeedback"}],"externalID":"c:@M@ConnectSDK@E@PGPredefinedFeedback","title":"PGPredefinedFeedback"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/RawRepresentable-Implementations","kind":"article","abstract":[],"url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/rawrepresentable-implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/Equatable-Implementations","role":"collectionGroup","type":"topic","title":"Equatable Implementations","url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/equatable-implementations","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/success":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/success","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedbackSuccess"}],"abstract":[{"type":"text","text":"A positive Feedback."}],"title":"PGPredefinedFeedback.success","url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/success","role":"symbol","kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/special1":{"abstract":[{"text":"Special Feedback (Yellow).","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special1","role":"symbol","url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/special1","title":"PGPredefinedFeedback.special1","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"special1"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial1"}]},"doc://com.proglove.Mark2SDK/SY":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/init(rawValue:)":{"url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/init(rawvalue:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/error":{"abstract":[{"text":"A negative Feedback.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/error","url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/error","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"role":"symbol","title":"PGPredefinedFeedback.error","navigatorTitle":[{"text":"PGPredefinedFeedbackError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/special3":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial3"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"special3","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/special3","kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special3","abstract":[{"type":"text","text":"Special Feedback (Cyan)."}],"title":"PGPredefinedFeedback.special3"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback/special2":{"url":"\/documentation\/connectsdk\/pgpredefinedfeedback\/special2","abstract":[{"type":"text","text":"Special Feedback (Purple)."}],"type":"topic","title":"PGPredefinedFeedback.special2","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial2"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"special2"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special2"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPredefinedFeedback"}],"navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","role":"symbol","type":"topic","title":"PGPredefinedFeedback","url":"\/documentation\/connectsdk\/pgpredefinedfeedback","abstract":[{"text":"Feedback enum","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"PGPredefinedFeedback","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPredefinedFeedback","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PGPredefinedFeedback","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/error","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special1","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special2","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/special3","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback\/success"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPredefinedFeedback"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"PGPredefinedFeedbackSuccess","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1success\/title"},{"op":"replace","value":[{"text":"PGPredefinedFeedbackSuccess","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1success\/fragments"},{"value":"PGPredefinedFeedbackSpecial1","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special1\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial1"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special1\/fragments","op":"replace"},{"value":"PGPredefinedFeedbackError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1error\/title"},{"value":[{"text":"PGPredefinedFeedbackError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1error\/fragments","op":"replace"},{"value":"PGPredefinedFeedbackSpecial3","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special3\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special3\/fragments","value":[{"text":"PGPredefinedFeedbackSpecial3","kind":"identifier"}],"op":"replace"},{"value":"PGPredefinedFeedbackSpecial2","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special2\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback~1special2\/fragments","value":[{"kind":"identifier","text":"PGPredefinedFeedbackSpecial2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title","value":"PGPredefinedFeedback"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments","op":"replace","value":[{"text":"PGPredefinedFeedback","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}