{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGRefreshType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PGDefault: Uses the default refresh strategy defined by ProGlove. Partial or full refresh might be used."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PGFullRefresh: Uses a full refresh for this screen setting. This will take a bit longer, but removes artifacts from previous screens. Full-refresh will definitely be used.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"PGPartialRefresh: Uses a partial refresh for this screen setting. This will be faster than a full refresh, but may produce artifacts of the current screen on the display. Partial-refresh will definitely be used.","type":"text"}],"type":"paragraph"}]}]}]}],"abstract":[{"type":"text","text":"The refresh type, the display should be using when setting a screen."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Enumeration","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGRefreshType"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGRefreshType"}],"externalID":"c:@M@ConnectSDK@E@PGRefreshType","title":"PGRefreshType","symbolKind":"enum"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"]}],"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/default","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/fullRefresh","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/partialRefresh"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgrefreshtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgrefreshtype"]}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType/fullRefresh":{"role":"symbol","url":"\/documentation\/connectsdk\/pgrefreshtype\/fullrefresh","title":"PGRefreshType.fullRefresh","kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/fullRefresh","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullRefresh"}],"navigatorTitle":[{"text":"PGRefreshTypeFullRefresh","kind":"identifier"}],"abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType/default":{"url":"\/documentation\/connectsdk\/pgrefreshtype\/default","navigatorTitle":[{"kind":"identifier","text":"PGRefreshTypeDefault"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"`default`","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"PGRefreshType.default","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/default"},"doc://com.proglove.Mark2SDK/SY":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType/partialRefresh":{"url":"\/documentation\/connectsdk\/pgrefreshtype\/partialrefresh","navigatorTitle":[{"kind":"identifier","text":"PGRefreshTypePartialRefresh"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"partialRefresh"}],"abstract":[],"kind":"symbol","type":"topic","title":"PGRefreshType.partialRefresh","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/partialRefresh"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType/init(rawValue:)":{"url":"\/documentation\/connectsdk\/pgrefreshtype\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"title":"init(rawValue:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/init(rawValue:)"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType/Equatable-Implementations":{"url":"\/documentation\/connectsdk\/pgrefreshtype\/equatable-implementations","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/Equatable-Implementations"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGRefreshType","kind":"identifier"}],"navigatorTitle":[{"text":"PGRefreshType","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgrefreshtype","title":"PGRefreshType","abstract":[{"type":"text","text":"The refresh type, the display should be using when setting a screen."}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/connectsdk\/pgrefreshtype\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PGRefreshType","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGRefreshType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGRefreshType"}]},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/default","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/fullRefresh","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType\/partialRefresh"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGRefreshType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1fullRefresh\/title","value":"PGRefreshTypeFullRefresh","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1fullRefresh\/fragments","value":[{"kind":"identifier","text":"PGRefreshTypeFullRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1default\/title","value":"PGRefreshTypeDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1default\/fragments","value":[{"text":"PGRefreshTypeDefault","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1partialRefresh\/title","value":"PGRefreshTypePartialRefresh"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType~1partialRefresh\/fragments","value":[{"kind":"identifier","text":"PGRefreshTypePartialRefresh"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/title","value":"PGRefreshType","op":"replace"},{"value":[{"kind":"identifier","text":"PGRefreshType"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/fragments","op":"replace"}]}]}