{"variants":[{"paths":["\/documentation\/connectsdk\/pgscannedbarcoderesult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgscannedbarcoderesult"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGScannedBarcodeResult","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"PGScannedBarcodeResult"}],"symbolKind":"class","role":"symbol","title":"PGScannedBarcodeResult","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"abstract":[{"type":"text","text":"PGScannedBarcodeResult"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeContent","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeSymbology"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGScannedBarcodeResult","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Scanned barcode data.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult":{"abstract":[{"text":"PGScannedBarcodeResult","type":"text"}],"url":"\/documentation\/connectsdk\/pgscannedbarcoderesult","kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScannedBarcodeResult"}],"navigatorTitle":[{"kind":"identifier","text":"PGScannedBarcodeResult"}],"title":"PGScannedBarcodeResult","role":"symbol"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult/barcodeSymbology":{"kind":"symbol","navigatorTitle":[{"text":"barcodeSymbology","kind":"identifier"}],"title":"barcodeSymbology","url":"\/documentation\/connectsdk\/pgscannedbarcoderesult\/barcodesymbology","abstract":[{"type":"text","text":"The scanned barcode symbology, if available."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeSymbology","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"barcodeSymbology","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult/barcodeContent":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeContent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeContent"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeContent","abstract":[{"text":"The scanned barcode string.","type":"text"}],"role":"symbol","title":"barcodeContent","url":"\/documentation\/connectsdk\/pgscannedbarcoderesult\/barcodecontent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"PGScannedBarcodeResult","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGScannedBarcodeResult"}]},{"value":[{"text":"PGScannedBarcodeResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeContent","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeSymbology"]}]},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScannedBarcodeResult"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"PGScannedBarcodeResult","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/fragments","value":[{"kind":"identifier","text":"PGScannedBarcodeResult"}]},{"value":"barcodeSymbology","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult~1barcodeSymbology\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult~1barcodeSymbology\/fragments","value":[{"kind":"identifier","text":"barcodeSymbology"}],"op":"replace"},{"op":"replace","value":"barcodeContent","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult~1barcodeContent\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult~1barcodeContent\/fragments","value":[{"text":"barcodeContent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}