{"seeAlsoSections":[{"title":"Models","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScreenData"}],"title":"PGScreenData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ConnectSDK@objc(cs)PGScreenData","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGScreenData"}]},"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}],"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:refreshType:duration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/durationMs","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/refreshType","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateFields","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateId"]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgscreendata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgscreendata"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScreenData"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformation":{"role":"symbol","title":"PGDeviceInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDeviceInformation"}],"abstract":[{"type":"text","text":"Model representing device information"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDeviceInformation"}],"url":"\/documentation\/connectsdk\/pgdeviceinformation"},"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/durationMs":{"role":"symbol","title":"durationMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"abstract":[{"type":"text","text":"The duration for how long the notification should be displayed."},{"type":"text","text":" "},{"type":"text","text":"Only used when sent with NotificationScreen, must be >0 in that case."},{"type":"text","text":" "},{"type":"text","text":"An automatic transition back to the previous screen will take place after this time. A notification can be replaced by any other notification and by a new screen."},{"type":"text","text":" "},{"type":"text","text":"Depending on your implementation, this is thus only an upper limit on the time this notification will be shown."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/durationMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"durationMs"}],"url":"\/documentation\/connectsdk\/pgscreendata\/durationms"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/templateFields":{"role":"symbol","title":"templateFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PGTemplateField","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A list of PGTemplateField which hold the data for header and content for each field in the template."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateFields"}],"url":"\/documentation\/connectsdk\/pgscreendata\/templatefields"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/refreshType":{"role":"symbol","title":"refreshType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGRefreshType","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType"}],"abstract":[{"type":"text","text":"The PGRefreshType type to be used while setting this screen."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/refreshType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshType"}],"url":"\/documentation\/connectsdk\/pgscreendata\/refreshtype"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/init(templateId:templateFields:refreshType:duration:)":{"role":"symbol","title":"init(templateId:templateFields:refreshType:duration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PGTemplateField","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"refreshType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGRefreshType","preciseIdentifier":"c:@M@ConnectSDK@E@PGRefreshType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Designated initializer for creating PGScreenData model class."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:refreshType:duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTemplateId:templateFields:refreshType:duration:"}],"url":"\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:refreshtype:duration:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/init(templateId:templateFields:)":{"role":"symbol","title":"init(templateId:templateFields:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PGTemplateField","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGTemplateField"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Convenience initializer for creating PGScreenData model class. Refresh type will default to PGDefault and durationMs will default to 0."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTemplateId:templateFields:"}],"url":"\/documentation\/connectsdk\/pgscreendata\/init(templateid:templatefields:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"role":"symbol","title":"PGScreenData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScreenData"}],"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGScreenData"}],"url":"\/documentation\/connectsdk\/pgscreendata"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData/templateId":{"role":"symbol","title":"templateId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The id of the template to be used to construct the screen."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateId"}],"url":"\/documentation\/connectsdk\/pgscreendata\/templateid"},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PGScreenData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGScreenData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PGScreenData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/durationMs","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/refreshType","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateFields","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/templateId"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:)","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData\/init(templateId:templateFields:refreshType:duration:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Models","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScreenData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/title","value":"PGDeviceInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/fragments","value":[{"kind":"identifier","text":"PGDeviceInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1durationMs\/title","value":"durationMs"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1durationMs\/fragments","value":[{"kind":"identifier","text":"durationMs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1templateFields\/title","value":"templateFields"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1templateFields\/fragments","value":[{"kind":"identifier","text":"templateFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1refreshType\/title","value":"refreshType"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1refreshType\/fragments","value":[{"kind":"identifier","text":"refreshType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:refreshType:duration:)\/title","value":"initWithTemplateId:templateFields:refreshType:duration:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:refreshType:duration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTemplateId:templateFields:refreshType:duration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:)\/title","value":"initWithTemplateId:templateFields:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1init(templateId:templateFields:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTemplateId:templateFields:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title","value":"PGScreenData"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","value":[{"kind":"identifier","text":"PGScreenData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1templateId\/title","value":"templateId"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData~1templateId\/fragments","value":[{"kind":"identifier","text":"templateId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}