{"variants":[{"paths":["\/documentation\/connectsdk\/pgsetdisplayorientationrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgsetdisplayorientationrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"metadata":{"navigatorTitle":[{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"title":"PGSetDisplayOrientationRequest","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest"},"abstract":[{"text":"This object holds the data for updating a screen orientation on a ProGlove display device.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/init(orientation:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/orientation"],"title":"Instance Properties"}],"references":{"doc://com.proglove.Mark2SDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.proglove.Mark2SDK/SH":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest/init(orientation:)":{"type":"topic","abstract":[{"type":"text","text":"Convenience init used to initiate PGSetDisplayOrientationRequest with a selected orientation."}],"role":"symbol","navigatorTitle":[{"text":"initWithOrientation:","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/init(orientation:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation","kind":"typeIdentifier","text":"PGOrientation"},{"text":")","kind":"text"}],"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/init(orientation:)","title":"init(orientation:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest":{"type":"topic","abstract":[{"text":"This object holds the data for updating a screen orientation on a ProGlove display device.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest","title":"PGSetDisplayOrientationRequest"},"doc://com.proglove.Mark2SDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.proglove.Mark2SDK/s7CVarArgP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest/orientation":{"type":"topic","abstract":[{"text":"The orientation to be set on a connected device.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"orientation","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/orientation","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"text":": ","kind":"text"},{"text":"PGOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation"}],"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/orientation","title":"orientation"},"doc://com.proglove.Mark2SDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.proglove.Mark2SDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.proglove.Mark2SDK/SQ":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"PGSetDisplayOrientationRequest","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/orientation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/init(orientation:)"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGSetDisplayOrientationRequest","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithOrientation:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1init(orientation:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1init(orientation:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOrientation:"}],"op":"replace"},{"value":"PGSetDisplayOrientationRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/fragments","value":[{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1orientation\/title","value":"orientation"},{"op":"replace","value":[{"text":"orientation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1orientation\/fragments"}]}]}