{"sections":[],"kind":"symbol","abstract":[{"text":"PG Wearable API error codes","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/capabilityNotSupported","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/invalidPayload","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestCanceled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestDenied","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestTimeout"]},{"title":"Initializers","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/Equatable-Implementations","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGWearableApiError","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/connectsdk\/pgwearableapierror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgwearableapierror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/SQ","doc:\/\/com.proglove.Mark2SDK\/SH","doc:\/\/com.proglove.Mark2SDK\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"metadata":{"title":"PGWearableApiError","role":"symbol","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGWearableApiError","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGWearableApiError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGWearableApiError"}],"symbolKind":"enum"},"references":{"doc://com.proglove.Mark2SDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SY","title":"Swift.RawRepresentable"},"doc://com.proglove.Mark2SDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SH","title":"Swift.Hashable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/requestTimeout":{"url":"\/documentation\/connectsdk\/pgwearableapierror\/requesttimeout","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestTimeout","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestTimeout","kind":"identifier"}],"navigatorTitle":[{"text":"PGWearableApiErrorRequestTimeout","kind":"identifier"}],"title":"PGWearableApiError.requestTimeout","abstract":[{"type":"text","text":"Wapi request timed out."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/capabilityNotSupported":{"type":"topic","title":"PGWearableApiError.capabilityNotSupported","url":"\/documentation\/connectsdk\/pgwearableapierror\/capabilitynotsupported","abstract":[{"text":"The capability is not supported.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capabilityNotSupported"}],"kind":"symbol","navigatorTitle":[{"text":"PGWearableApiErrorCapabilityNotSupported","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/capabilityNotSupported"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/requestCanceled":{"abstract":[{"type":"text","text":"Wapi request was canceled."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCanceled"}],"url":"\/documentation\/connectsdk\/pgwearableapierror\/requestcanceled","title":"PGWearableApiError.requestCanceled","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PGWearableApiErrorRequestCanceled","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestCanceled","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/Equatable-Implementations":{"type":"topic","url":"\/documentation\/connectsdk\/pgwearableapierror\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/RawRepresentable-Implementations":{"type":"topic","kind":"article","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/RawRepresentable-Implementations","url":"\/documentation\/connectsdk\/pgwearableapierror\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError":{"abstract":[{"text":"PG Wearable API error codes","type":"text"}],"title":"PGWearableApiError","navigatorTitle":[{"text":"PGWearableApiError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError","url":"\/documentation\/connectsdk\/pgwearableapierror","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGWearableApiError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/invalidPayload":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidPayload"}],"navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorInvalidPayload"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/invalidPayload","url":"\/documentation\/connectsdk\/pgwearableapierror\/invalidpayload","type":"topic","kind":"symbol","title":"PGWearableApiError.invalidPayload","abstract":[{"type":"text","text":"Wrong wapi payload received."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/requestDenied":{"type":"topic","url":"\/documentation\/connectsdk\/pgwearableapierror\/requestdenied","kind":"symbol","title":"PGWearableApiError.requestDenied","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestDenied","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestDenied","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorRequestDenied"}],"role":"symbol","abstract":[{"text":"Wapi request was denied. Queue limit reached.","type":"text"}]},"doc://com.proglove.Mark2SDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.proglove.Mark2SDK\/SQ","title":"Swift.Equatable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/connectsdk\/pgwearableapierror\/init(rawvalue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGWearableApiError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"text":"PGWearableApiError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PGWearableApiError"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/capabilityNotSupported","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/invalidPayload","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestCanceled","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestDenied","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestTimeout"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGWearableApiError"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"PGWearableApiErrorRequestTimeout","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestTimeout\/title"},{"value":[{"text":"PGWearableApiErrorRequestTimeout","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestTimeout\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1capabilityNotSupported\/title","op":"replace","value":"PGWearableApiErrorCapabilityNotSupported"},{"value":[{"text":"PGWearableApiErrorCapabilityNotSupported","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1capabilityNotSupported\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestCanceled\/title","value":"PGWearableApiErrorRequestCanceled","op":"replace"},{"value":[{"kind":"identifier","text":"PGWearableApiErrorRequestCanceled"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestCanceled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/title","value":"PGWearableApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/fragments","value":[{"text":"PGWearableApiError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1invalidPayload\/title","value":"PGWearableApiErrorInvalidPayload"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1invalidPayload\/fragments","value":[{"text":"PGWearableApiErrorInvalidPayload","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestDenied\/title","value":"PGWearableApiErrorRequestDenied"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestDenied\/fragments","op":"replace","value":[{"text":"PGWearableApiErrorRequestDenied","kind":"identifier"}]}]}]}