{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/init(_:resolution:timeout:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"resolution","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PGImageResolution","preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"init:resolution:timeout:","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGCaptureImageRequest(im)init:resolution:timeout:","title":"init(_:resolution:timeout:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcaptureimagerequest\/init(_:resolution:timeout:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcaptureimagerequest\/init(_:resolution:timeout:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"jpegQuality","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"resolution"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGImageResolution","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution"},{"text":", ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest":{"abstract":[{"type":"text","text":"PGCaptureImageRequest"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCaptureImageRequest"}],"url":"\/documentation\/connectsdk\/pgcaptureimagerequest","navigatorTitle":[{"text":"PGCaptureImageRequest","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PGCaptureImageRequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest/init(_:resolution:timeout:)":{"navigatorTitle":[{"text":"init:resolution:timeout:","kind":"identifier"}],"title":"init(_:resolution:timeout:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"resolution","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution","text":"PGImageResolution","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/init(_:resolution:timeout:)","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgcaptureimagerequest\/init(_:resolution:timeout:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PGImageResolution"}],"url":"\/documentation\/connectsdk\/pgimageresolution","role":"symbol","title":"PGImageResolution","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGImageResolution","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"init:resolution:timeout:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init:resolution:timeout:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"jpegQuality"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resolution:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","text":"PGImageResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"resolution"},{"text":" ","kind":"text"},{"text":"timeout:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"timeout","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"PGCaptureImageRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGCaptureImageRequest"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1init(_:resolution:timeout:)\/title","value":"init:resolution:timeout:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1init(_:resolution:timeout:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init:resolution:timeout:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/title","value":"PGImageResolution"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/fragments","op":"replace","value":[{"text":"PGImageResolution","kind":"identifier"}]}]}]}