{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resolution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGImageResolution","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"resolution","role":"symbol","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"resolution"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGCaptureImageRequest(py)resolution","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resolution","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution","text":"PGImageResolution"}]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/resolution","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcaptureimagerequest\/resolution"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcaptureimagerequest\/resolution"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Resolution of the image","type":"text"}],"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution":{"navigatorTitle":[{"kind":"identifier","text":"PGImageResolution"}],"url":"\/documentation\/connectsdk\/pgimageresolution","abstract":[],"title":"PGImageResolution","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImageResolution"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest":{"kind":"symbol","role":"symbol","url":"\/documentation\/connectsdk\/pgcaptureimagerequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","abstract":[{"text":"PGCaptureImageRequest","type":"text"}],"navigatorTitle":[{"text":"PGCaptureImageRequest","kind":"identifier"}],"type":"topic","title":"PGCaptureImageRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCaptureImageRequest"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest/resolution":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest\/resolution","navigatorTitle":[{"kind":"identifier","text":"resolution"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgcaptureimagerequest\/resolution","title":"resolution","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution","text":"PGImageResolution"}],"abstract":[{"type":"text","text":"Resolution of the image"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"resolution","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"resolution","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGImageResolution","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","kind":"typeIdentifier","text":"PGImageResolution"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"PGImageResolution","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/fragments","value":[{"text":"PGImageResolution","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/title","value":"PGCaptureImageRequest"},{"op":"replace","value":[{"text":"PGCaptureImageRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/fragments"},{"value":"resolution","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1resolution\/title"},{"op":"replace","value":[{"text":"resolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest~1resolution\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}