{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgscannedbarcoderesult\/barcodecontent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgscannedbarcoderesult\/barcodecontent"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeContent","interfaceLanguage":"swift"},"abstract":[{"text":"The scanned barcode string.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeContent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"barcodeContent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeContent"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult(py)barcodeContent","role":"symbol","title":"barcodeContent","roleHeading":"Instance Property"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult":{"abstract":[{"text":"PGScannedBarcodeResult","type":"text"}],"url":"\/documentation\/connectsdk\/pgscannedbarcoderesult","kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScannedBarcodeResult"}],"navigatorTitle":[{"kind":"identifier","text":"PGScannedBarcodeResult"}],"title":"PGScannedBarcodeResult","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult/barcodeContent":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeContent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeContent"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult\/barcodeContent","abstract":[{"text":"The scanned barcode string.","type":"text"}],"role":"symbol","title":"barcodeContent","url":"\/documentation\/connectsdk\/pgscannedbarcoderesult\/barcodecontent"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"barcodeContent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"barcodeContent"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"barcodeContent","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/title","value":"PGScannedBarcodeResult","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGScannedBarcodeResult"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult~1barcodeContent\/title","value":"barcodeContent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult~1barcodeContent\/fragments","value":[{"kind":"identifier","text":"barcodeContent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}