{"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/sequenceNotFound","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgfeedbackapierror\/sequencenotfound"]},{"paths":["\/documentation\/connectsdk\/pgfeedbackapierror\/sequencenotfound"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"PGFeedbackApiErrorSequenceNotFound","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGFeedbackApiError@PGFeedbackApiErrorSequenceNotFound","title":"PGFeedbackApiError.sequenceNotFound","symbolKind":"case","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sequenceNotFound"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sequenceNotFound"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Feedback for sequence id not found."}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError/sequenceNotFound":{"abstract":[{"type":"text","text":"Feedback for sequence id not found."}],"title":"PGFeedbackApiError.sequenceNotFound","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError\/sequenceNotFound","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sequenceNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"PGFeedbackApiErrorSequenceNotFound"}],"url":"\/documentation\/connectsdk\/pgfeedbackapierror\/sequencenotfound","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError","type":"topic","kind":"symbol","title":"PGFeedbackApiError","url":"\/documentation\/connectsdk\/pgfeedbackapierror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGFeedbackApiError","kind":"identifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"PGFeedbackApiError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PGFeedbackApiErrorSequenceNotFound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"PGFeedbackApiErrorSequenceNotFound"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGFeedbackApiErrorSequenceNotFound"}]}],"kind":"declarations"}},{"op":"replace","value":"PGFeedbackApiErrorSequenceNotFound","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError~1sequenceNotFound\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError~1sequenceNotFound\/fragments","value":[{"kind":"identifier","text":"PGFeedbackApiErrorSequenceNotFound"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError\/title","value":"PGFeedbackApiError","op":"replace"},{"op":"replace","value":[{"text":"PGFeedbackApiError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}