{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation"]]},"metadata":{"externalID":"c:@M@ConnectSDK@E@PGOrientation@PGOrientationEast","modules":[{"name":"ConnectSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"east","kind":"identifier"}],"symbolKind":"case","title":"PGOrientation.east","roleHeading":"Case","navigatorTitle":[{"text":"PGOrientationEast","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"east"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/east"},"variants":[{"paths":["\/documentation\/connectsdk\/pgorientation\/east"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgorientation\/east"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/east":{"title":"PGOrientation.east","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/east","url":"\/documentation\/connectsdk\/pgorientation\/east","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGOrientationEast"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"east","kind":"identifier"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation":{"title":"PGOrientation","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"kind":"symbol","type":"topic","abstract":[{"text":"Definition of the valid display orientations.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","url":"\/documentation\/connectsdk\/pgorientation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PGOrientationEast","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGOrientationEast"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PGOrientationEast","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PGOrientationEast","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1east\/title"},{"value":[{"text":"PGOrientationEast","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1east\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/title","value":"PGOrientation","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/fragments","value":[{"kind":"identifier","text":"PGOrientation"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}