{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/invalid"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/connectsdk\/pgorientation\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgorientation\/invalid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ConnectSDK@E@PGOrientation@PGOrientationInvalid","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalid"}],"role":"symbol","modules":[{"name":"ConnectSDK"}],"roleHeading":"Case","title":"PGOrientation.invalid","navigatorTitle":[{"text":"PGOrientationInvalid","kind":"identifier"}],"symbolKind":"case"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation":{"abstract":[{"type":"text","text":"Definition of the valid display orientations."}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"title":"PGOrientation","url":"\/documentation\/connectsdk\/pgorientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGOrientation"}],"type":"topic","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/invalid":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/invalid","url":"\/documentation\/connectsdk\/pgorientation\/invalid","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGOrientationInvalid"}],"title":"PGOrientation.invalid"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"PGOrientationInvalid","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PGOrientationInvalid"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"PGOrientationInvalid"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGOrientation","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGOrientation"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1invalid\/title","value":"PGOrientationInvalid"},{"op":"replace","value":[{"text":"PGOrientationInvalid","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1invalid\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}