{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/north"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"north"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation"]]},"metadata":{"symbolKind":"case","title":"PGOrientation.north","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"north","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"role":"symbol","externalID":"c:@M@ConnectSDK@E@PGOrientation@PGOrientationNorth","navigatorTitle":[{"text":"PGOrientationNorth","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgorientation\/north"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgorientation\/north"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation":{"title":"PGOrientation","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"kind":"symbol","type":"topic","abstract":[{"text":"Definition of the valid display orientations.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","url":"\/documentation\/connectsdk\/pgorientation"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation/north":{"url":"\/documentation\/connectsdk\/pgorientation\/north","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"north"}],"navigatorTitle":[{"kind":"identifier","text":"PGOrientationNorth"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation\/north","title":"PGOrientation.north"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PGOrientationNorth","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGOrientationNorth"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGOrientationNorth"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/title","op":"replace","value":"PGOrientation"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/fragments","op":"replace","value":[{"text":"PGOrientation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1north\/title","value":"PGOrientationNorth"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation~1north\/fragments","op":"replace","value":[{"text":"PGOrientationNorth","kind":"identifier"}]}]}]}