{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/contenttoolong"]},{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/contenttoolong"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The content value is too long."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorContentTooLong","symbolKind":"case","modules":[{"name":"ConnectSDK"}],"title":"PGDisplayApiError.contentTooLong","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentTooLong"}],"navigatorTitle":[{"text":"PGDisplayApiErrorContentTooLong","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentTooLong"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/contentTooLong","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/contentTooLong":{"abstract":[{"text":"The content value is too long.","type":"text"}],"url":"\/documentation\/connectsdk\/pgdisplayapierror\/contenttoolong","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorContentTooLong"}],"title":"PGDisplayApiError.contentTooLong","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"contentTooLong","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/contentTooLong"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"title":"PGDisplayApiError","navigatorTitle":[{"text":"PGDisplayApiError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"PG Display API error codes."}],"url":"\/documentation\/connectsdk\/pgdisplayapierror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDisplayApiError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGDisplayApiErrorContentTooLong"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PGDisplayApiErrorContentTooLong"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PGDisplayApiErrorContentTooLong","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"PGDisplayApiErrorContentTooLong","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1contentTooLong\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1contentTooLong\/fragments","value":[{"text":"PGDisplayApiErrorContentTooLong","kind":"identifier"}],"op":"replace"},{"value":"PGDisplayApiError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGDisplayApiError"}]}]}]}