{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/duplicateFieldId"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"abstract":[{"type":"text","text":"The provided list of fields contain duplicate field id."}],"metadata":{"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"PGDisplayApiErrorDuplicateFieldId","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"title":"PGDisplayApiError.duplicateFieldId","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorDuplicateFieldId","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"duplicateFieldId","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"duplicateFieldId","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/duplicatefieldid"]},{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/duplicatefieldid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/duplicateFieldId":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"duplicateFieldId"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/duplicateFieldId","title":"PGDisplayApiError.duplicateFieldId","abstract":[{"type":"text","text":"The provided list of fields contain duplicate field id."}],"type":"topic","url":"\/documentation\/connectsdk\/pgdisplayapierror\/duplicatefieldid","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PGDisplayApiErrorDuplicateFieldId","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","abstract":[{"text":"PG Display API error codes.","type":"text"}],"url":"\/documentation\/connectsdk\/pgdisplayapierror","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiError"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGDisplayApiError","kind":"identifier"}],"title":"PGDisplayApiError","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGDisplayApiErrorDuplicateFieldId"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"PGDisplayApiErrorDuplicateFieldId","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGDisplayApiErrorDuplicateFieldId"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1duplicateFieldId\/title","op":"replace","value":"PGDisplayApiErrorDuplicateFieldId"},{"op":"replace","value":[{"text":"PGDisplayApiErrorDuplicateFieldId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1duplicateFieldId\/fragments"},{"op":"replace","value":"PGDisplayApiError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title"},{"op":"replace","value":[{"text":"PGDisplayApiError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments"}]}]}