{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/emptyTemplateId"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/emptytemplateid"]},{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/emptytemplateid"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The provided Template id is nil or empty."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"emptyTemplateId","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"PGDisplayApiErrorEmptyTemplateId","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorEmptyTemplateId","role":"symbol","title":"PGDisplayApiError.emptyTemplateId","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"emptyTemplateId","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/emptyTemplateId":{"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/emptyTemplateId","kind":"symbol","navigatorTitle":[{"text":"PGDisplayApiErrorEmptyTemplateId","kind":"identifier"}],"title":"PGDisplayApiError.emptyTemplateId","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"emptyTemplateId","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgdisplayapierror\/emptytemplateid","abstract":[{"type":"text","text":"The provided Template id is nil or empty."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","abstract":[{"text":"PG Display API error codes.","type":"text"}],"url":"\/documentation\/connectsdk\/pgdisplayapierror","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiError"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGDisplayApiError","kind":"identifier"}],"title":"PGDisplayApiError","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"PGDisplayApiErrorEmptyTemplateId","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGDisplayApiErrorEmptyTemplateId","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PGDisplayApiErrorEmptyTemplateId","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"PGDisplayApiErrorEmptyTemplateId","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1emptyTemplateId\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1emptyTemplateId\/fragments","value":[{"kind":"identifier","text":"PGDisplayApiErrorEmptyTemplateId"}]},{"value":"PGDisplayApiError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title"},{"value":[{"kind":"identifier","text":"PGDisplayApiError"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}