{"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorFieldIdNotInTemplate","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fieldIdNotInTemplate","kind":"identifier"}],"title":"PGDisplayApiError.fieldIdNotInTemplate","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorFieldIdNotInTemplate"}],"role":"symbol","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/fieldIdNotInTemplate"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldIdNotInTemplate"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The provided field id is not in the list of supported ids. The field id is number beetween 1 and number of supported fields."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/fieldidnotintemplate"]},{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/fieldidnotintemplate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/fieldIdNotInTemplate":{"title":"PGDisplayApiError.fieldIdNotInTemplate","kind":"symbol","navigatorTitle":[{"text":"PGDisplayApiErrorFieldIdNotInTemplate","kind":"identifier"}],"type":"topic","abstract":[{"text":"The provided field id is not in the list of supported ids. The field id is number beetween 1 and number of supported fields.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/fieldIdNotInTemplate","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldIdNotInTemplate"}],"url":"\/documentation\/connectsdk\/pgdisplayapierror\/fieldidnotintemplate","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"title":"PGDisplayApiError","navigatorTitle":[{"text":"PGDisplayApiError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"PG Display API error codes."}],"url":"\/documentation\/connectsdk\/pgdisplayapierror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDisplayApiError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PGDisplayApiErrorFieldIdNotInTemplate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGDisplayApiErrorFieldIdNotInTemplate","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGDisplayApiErrorFieldIdNotInTemplate"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1fieldIdNotInTemplate\/title","value":"PGDisplayApiErrorFieldIdNotInTemplate","op":"replace"},{"value":[{"text":"PGDisplayApiErrorFieldIdNotInTemplate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1fieldIdNotInTemplate\/fragments","op":"replace"},{"op":"replace","value":"PGDisplayApiError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments","value":[{"text":"PGDisplayApiError","kind":"identifier"}]}]}]}