{"variants":[{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/headertoolong"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/headertoolong"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"headerTooLong","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"PGDisplayApiError.headerTooLong","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorHeaderTooLong","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorHeaderTooLong"}]},"abstract":[{"type":"text","text":"The header value is too long."}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/headerTooLong","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerTooLong"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/headerTooLong":{"url":"\/documentation\/connectsdk\/pgdisplayapierror\/headertoolong","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headerTooLong"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorHeaderTooLong"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/headerTooLong","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The header value is too long."}],"title":"PGDisplayApiError.headerTooLong"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"role":"symbol","abstract":[{"type":"text","text":"PG Display API error codes."}],"title":"PGDisplayApiError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGDisplayApiError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PGDisplayApiError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgdisplayapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"PGDisplayApiErrorHeaderTooLong","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGDisplayApiErrorHeaderTooLong"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGDisplayApiErrorHeaderTooLong"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1headerTooLong\/title","value":"PGDisplayApiErrorHeaderTooLong"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1headerTooLong\/fragments","value":[{"kind":"identifier","text":"PGDisplayApiErrorHeaderTooLong"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title","op":"replace","value":"PGDisplayApiError"},{"value":[{"text":"PGDisplayApiError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments"}]}]}