{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidNumberOfFieldsInTemplate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/invalidnumberoffieldsintemplate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/invalidnumberoffieldsintemplate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/invalidNumberOfFieldsInTemplate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"There is mismatch in number of fields provided and supported by selected template."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidNumberOfFieldsInTemplate"}],"title":"PGDisplayApiError.invalidNumberOfFieldsInTemplate","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorInvalidNumberOfFieldsInTemplate","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"role":"symbol","title":"PGDisplayApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDisplayApiError"}],"abstract":[{"type":"text","text":"PG Display API error codes."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiError"}],"url":"\/documentation\/connectsdk\/pgdisplayapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/invalidNumberOfFieldsInTemplate":{"role":"symbol","title":"PGDisplayApiError.invalidNumberOfFieldsInTemplate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidNumberOfFieldsInTemplate"}],"abstract":[{"type":"text","text":"There is mismatch in number of fields provided and supported by selected template."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/invalidNumberOfFieldsInTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"}],"url":"\/documentation\/connectsdk\/pgdisplayapierror\/invalidnumberoffieldsintemplate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title","value":"PGDisplayApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments","value":[{"kind":"identifier","text":"PGDisplayApiError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1invalidNumberOfFieldsInTemplate\/title","value":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1invalidNumberOfFieldsInTemplate\/fragments","value":[{"kind":"identifier","text":"PGDisplayApiErrorInvalidNumberOfFieldsInTemplate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}