{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/negativeduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/negativeduration"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/negativeDuration"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","abstract":[{"text":"The provided duration is negative value.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"negativeDuration","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"negativeDuration","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"PGDisplayApiErrorNegativeDuration","kind":"identifier"}],"title":"PGDisplayApiError.negativeDuration","externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorNegativeDuration"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/negativeDuration":{"title":"PGDisplayApiError.negativeDuration","url":"\/documentation\/connectsdk\/pgdisplayapierror\/negativeduration","abstract":[{"type":"text","text":"The provided duration is negative value."}],"navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorNegativeDuration"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/negativeDuration","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"negativeDuration","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"title":"PGDisplayApiError","navigatorTitle":[{"text":"PGDisplayApiError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"PG Display API error codes."}],"url":"\/documentation\/connectsdk\/pgdisplayapierror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDisplayApiError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGDisplayApiErrorNegativeDuration","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"PGDisplayApiErrorNegativeDuration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"PGDisplayApiErrorNegativeDuration","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1negativeDuration\/title","value":"PGDisplayApiErrorNegativeDuration"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1negativeDuration\/fragments","op":"replace","value":[{"text":"PGDisplayApiErrorNegativeDuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title","op":"replace","value":"PGDisplayApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments","value":[{"text":"PGDisplayApiError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}