{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateIdNotFound"}]}]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/templateidnotfound"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdisplayapierror\/templateidnotfound"]}],"sections":[],"abstract":[{"type":"text","text":"The provided Template id not found in the list of supported ids."}],"metadata":{"role":"symbol","externalID":"c:@M@ConnectSDK@E@PGDisplayApiError@PGDisplayApiErrorTemplateIdNotFound","roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templateIdNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorTemplateIdNotFound"}],"title":"PGDisplayApiError.templateIdNotFound"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/templateIdNotFound"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError/templateIdNotFound":{"navigatorTitle":[{"text":"PGDisplayApiErrorTemplateIdNotFound","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The provided Template id not found in the list of supported ids.","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError\/templateIdNotFound","url":"\/documentation\/connectsdk\/pgdisplayapierror\/templateidnotfound","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templateIdNotFound"}],"title":"PGDisplayApiError.templateIdNotFound"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"title":"PGDisplayApiError","navigatorTitle":[{"text":"PGDisplayApiError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"PG Display API error codes."}],"url":"\/documentation\/connectsdk\/pgdisplayapierror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDisplayApiError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PGDisplayApiErrorTemplateIdNotFound","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PGDisplayApiErrorTemplateIdNotFound","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"PGDisplayApiErrorTemplateIdNotFound"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1templateIdNotFound\/title","value":"PGDisplayApiErrorTemplateIdNotFound","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError~1templateIdNotFound\/fragments","value":[{"text":"PGDisplayApiErrorTemplateIdNotFound","kind":"identifier"}]},{"value":"PGDisplayApiError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments","value":[{"kind":"identifier","text":"PGDisplayApiError"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}