{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/cloudconnectiondelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/cloudconnectiondelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)cloudConnectionDelegate","roleHeading":"Instance Property","symbolKind":"property","title":"cloudConnectionDelegate","navigatorTitle":[{"kind":"identifier","text":"cloudConnectionDelegate"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudConnectionDelegate"},{"text":": ","kind":"text"},{"text":"PGCloudConnectionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCloudConnectionDelegate"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudConnectionDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGCloudConnectionDelegate","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCloudConnectionDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cloudConnectionDelegate"},"abstract":[{"type":"text","text":"A delegate used for insight updates"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionDelegate":{"url":"\/documentation\/connectsdk\/pgcloudconnectiondelegate","type":"topic","title":"PGCloudConnectionDelegate","navigatorTitle":[{"text":"PGCloudConnectionDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudConnectionDelegate","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager","role":"symbol","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}],"title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/cloudConnectionDelegate":{"abstract":[{"type":"text","text":"A delegate used for insight updates"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/cloudConnectionDelegate","url":"\/documentation\/connectsdk\/pgcentralmanager\/cloudconnectiondelegate","title":"cloudConnectionDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudConnectionDelegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCloudConnectionDelegate","text":"PGCloudConnectionDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cloudConnectionDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"cloudConnectionDelegate","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cloudConnectionDelegate","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<PGCloudConnectionDelegate>","preciseIdentifier":"c:Qo@M@ConnectSDK@objc(pl)PGCloudConnectionDelegate"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cloudConnectionDelegate"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/title","value":"PGCloudConnectionDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/fragments","value":[{"kind":"identifier","text":"PGCloudConnectionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"text":"PGCentralManager","kind":"identifier"}]},{"value":"cloudConnectionDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1cloudConnectionDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1cloudConnectionDelegate\/fragments","value":[{"text":"cloudConnectionDelegate","kind":"identifier"}]}]}]}