{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager","text":"PGConfigurationManager","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The configuration manager.","type":"text"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/configurationmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/configurationmanager"]}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configurationManager","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager","text":"PGConfigurationManager","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)configurationManager","navigatorTitle":[{"kind":"identifier","text":"configurationManager"}],"modules":[{"name":"ConnectSDK"}],"role":"symbol","roleHeading":"Instance Property","title":"configurationManager","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/configurationManager"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager":{"role":"symbol","title":"PGConfigurationManager","kind":"symbol","navigatorTitle":[{"text":"PGConfigurationManager","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationManager"}],"type":"topic","url":"\/documentation\/connectsdk\/pgconfigurationmanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/configurationManager":{"type":"topic","navigatorTitle":[{"text":"configurationManager","kind":"identifier"}],"title":"configurationManager","role":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanager\/configurationmanager","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"configurationManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGConfigurationManager","text":"PGConfigurationManager","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The configuration manager."}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/configurationManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"PGCentralManager","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"title":"PGCentralManager"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"configurationManager","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"configurationManager","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"id<PGConfigurationManager>","preciseIdentifier":"c:Qo@M@ConnectSDK@objc(pl)PGConfigurationManager","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"configurationManager","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PGConfigurationManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/title"},{"value":[{"text":"PGConfigurationManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/fragments"},{"op":"replace","value":"configurationManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1configurationManager\/title"},{"value":[{"text":"configurationManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1configurationManager\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"text":"PGCentralManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}