{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The connected scanner, if one is connected"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"metadata":{"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)connectedScanner","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectedScanner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"connectedScanner","navigatorTitle":[{"kind":"identifier","text":"connectedScanner"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/connectedscanner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/connectedscanner"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedScanner"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectedScanner","kind":"identifier"},{"kind":"text","text":": "},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/connectedScanner":{"role":"symbol","title":"connectedScanner","url":"\/documentation\/connectsdk\/pgcentralmanager\/connectedscanner","abstract":[{"type":"text","text":"The connected scanner, if one is connected"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/connectedScanner","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectedScanner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"connectedScanner"}],"kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","role":"symbol","title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"connectedScanner","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"connectedScanner","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"kind":"text","text":" * "},{"text":"connectedScanner","kind":"identifier"}]}]}},{"value":"PGPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"text":"PGPeripheral","kind":"identifier"}]},{"op":"replace","value":"connectedScanner","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectedScanner\/title"},{"value":[{"kind":"identifier","text":"connectedScanner"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1connectedScanner\/fragments"},{"value":"PGCentralManager","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"text":"PGCentralManager","kind":"identifier"}]}]}]}