{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/delegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"text":"PGCentralManagerDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/delegate"]}],"abstract":[{"type":"text","text":"The central delegate"}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate","text":"PGCentralManagerDelegate"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"delegate","modules":[{"name":"ConnectSDK"}],"role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCentralManagerDelegate"}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","title":"PGCentralManagerDelegate","abstract":[{"text":"PGCentralManagerDelegate","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/delegate":{"abstract":[{"text":"The central delegate","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/delegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/delegate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGCentralManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate"},{"text":"?","kind":"text"}],"title":"delegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","role":"symbol","title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"delegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ConnectSDK@objc(pl)PGCentralManagerDelegate","text":"id<PGCentralManagerDelegate>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title","value":"PGCentralManagerDelegate"},{"value":[{"text":"PGCentralManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","op":"replace","value":[{"text":"PGCentralManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}