{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"feedbackManager"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFeedbackManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager","text":"PGFeedbackManager"},{"text":"? { get }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/feedbackmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/feedbackmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"abstract":[{"type":"text","text":"The feedback manager. Use this manager to play feedback sequences on a connected device."}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/feedbackManager","interfaceLanguage":"swift"},"metadata":{"title":"feedbackManager","role":"symbol","symbolKind":"property","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)feedbackManager","navigatorTitle":[{"text":"feedbackManager","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"feedbackManager","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGFeedbackManager","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFeedbackManager"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGFeedbackManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Protocol contains all the feedback related methods."}],"title":"PGFeedbackManager","role":"symbol","navigatorTitle":[{"text":"PGFeedbackManager","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgfeedbackmanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"PGCentralManager","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"title":"PGCentralManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/feedbackManager":{"navigatorTitle":[{"text":"feedbackManager","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/feedbackManager","type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager\/feedbackmanager","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"feedbackManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFeedbackManager","text":"PGFeedbackManager","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"feedbackManager","kind":"symbol","abstract":[{"type":"text","text":"The feedback manager. Use this manager to play feedback sequences on a connected device."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"feedbackManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"feedbackManager","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ConnectSDK@objc(pl)PGFeedbackManager","text":"id<PGFeedbackManager>"},{"kind":"text","text":" * "},{"text":"feedbackManager","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/title","op":"replace","value":"PGFeedbackManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/fragments","value":[{"text":"PGFeedbackManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","value":[{"kind":"identifier","text":"PGCentralManager"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1feedbackManager\/title","op":"replace","value":"feedbackManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1feedbackManager\/fragments","value":[{"text":"feedbackManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}