{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/firmwareupdatemanager"]},{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/firmwareupdatemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"firmwareUpdateManager","navigatorTitle":[{"text":"firmwareUpdateManager","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"firmwareUpdateManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManager","text":"PGFirmwareUpdateManager"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)firmwareUpdateManager","modules":[{"name":"ConnectSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/firmwareUpdateManager","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firmwareUpdateManager","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager","kind":"typeIdentifier","text":"PGFirmwareUpdateManager","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManager"},{"kind":"text","text":"? { get }"}]}]}],"abstract":[{"type":"text","text":"The firmware update manager."}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManager":{"navigatorTitle":[{"text":"PGFirmwareUpdateManager","kind":"identifier"}],"abstract":[{"type":"text","text":"The protocol for the PGFirmwareUpdateManager."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGFirmwareUpdateManager","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgfirmwareupdatemanager","role":"symbol","title":"PGFirmwareUpdateManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/firmwareUpdateManager":{"type":"topic","title":"firmwareUpdateManager","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firmwareUpdateManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGFirmwareUpdateManager","text":"PGFirmwareUpdateManager","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"firmwareUpdateManager","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/firmwareupdatemanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/firmwareUpdateManager","kind":"symbol","abstract":[{"text":"The firmware update manager.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanager","abstract":[{"type":"text","text":"PGCentralManager"}],"role":"symbol","title":"PGCentralManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"firmwareUpdateManager"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"firmwareUpdateManager","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@ConnectSDK@objc(pl)PGFirmwareUpdateManager","text":"id<PGFirmwareUpdateManager>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"firmwareUpdateManager","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager\/title","op":"replace","value":"PGFirmwareUpdateManager"},{"value":[{"text":"PGFirmwareUpdateManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager\/fragments"},{"value":"firmwareUpdateManager","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1firmwareUpdateManager\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1firmwareUpdateManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"firmwareUpdateManager"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","op":"replace","value":"PGCentralManager"},{"op":"replace","value":[{"kind":"identifier","text":"PGCentralManager"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments"}]}]}