{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageManager","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager","text":"PGImageManager","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGImageManager"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/imagemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/imagemanager"]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/imageManager","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)imageManager","navigatorTitle":[{"text":"imageManager","kind":"identifier"}],"symbolKind":"property","title":"imageManager","role":"symbol","modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"imageManager","kind":"identifier"},{"kind":"text","text":": "},{"text":"PGImageManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGImageManager"},{"text":"?","kind":"text"}]},"abstract":[{"text":"The image manager. Use this manager to capture a photo using the connected device.","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageManager":{"navigatorTitle":[{"text":"PGImageManager","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager","type":"topic","role":"symbol","title":"PGImageManager","kind":"symbol","abstract":[{"text":"PGImageManager protocol containg the methods and properties for retrieving an image using photo feature","type":"text"}],"url":"\/documentation\/connectsdk\/pgimagemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGImageManager"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/imageManager":{"abstract":[{"type":"text","text":"The image manager. Use this manager to capture a photo using the connected device."}],"role":"symbol","type":"topic","title":"imageManager","url":"\/documentation\/connectsdk\/pgcentralmanager\/imagemanager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/imageManager","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(pl)PGImageManager","text":"PGImageManager","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageManager"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager","role":"symbol","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}],"title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"imageManager","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"imageManager","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@ConnectSDK@objc(pl)PGImageManager","kind":"typeIdentifier","text":"id<PGImageManager>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageManager"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/title","value":"PGImageManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/fragments","value":[{"text":"PGImageManager","kind":"identifier"}]},{"value":"imageManager","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1imageManager\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1imageManager\/fragments","value":[{"text":"imageManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PGCentralManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title"},{"value":[{"kind":"identifier","text":"PGCentralManager"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","op":"replace"}]}]}