{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initiateScannerConnection"},{"kind":"text","text":"("},{"text":"withImageSize","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"size","content":[{"type":"paragraph","inlineContent":[{"text":"The image size","type":"text"}]}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The generated QR code"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnection(withimagesize:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnection(withimagesize:)"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnection(withImageSize:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"This method generates an identifier which is embedded in a QR code for the Scanner to Scan, which the Scanner will advertise with."},{"text":" ","type":"text"},{"type":"text","text":"The central begins scanning for a Scanner advertising the generated identifier, and on discovering will connect to the Scanner."},{"type":"text","text":" "},{"text":"After Scanner interrogation, the scanner will become ready and ","type":"text"},{"type":"codeVoice","code":"-centralManager:scannerDidBecomeReady:"},{"text":" will be called.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method is a convenience method which calls "},{"type":"codeVoice","code":"-initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale"},{"type":"text","text":" "},{"type":"text","text":"with correction level Q (appropriate for dirty environments such as a warehouse) and the scale factor of the main screen"}],"metadata":{"symbolKind":"method","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initiateScannerConnection"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withImageSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(im)initiateScannerConnectionWithImageSize:","navigatorTitle":[{"kind":"identifier","text":"initiateScannerConnectionWithImageSize:"}],"title":"initiateScannerConnection(withImageSize:)"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/initiateScannerConnection(withImageSize:)":{"abstract":[{"type":"text","text":"This method generates an identifier which is embedded in a QR code for the Scanner to Scan, which the Scanner will advertise with."},{"text":" ","type":"text"},{"type":"text","text":"The central begins scanning for a Scanner advertising the generated identifier, and on discovering will connect to the Scanner."},{"type":"text","text":" "},{"type":"text","text":"After Scanner interrogation, the scanner will become ready and "},{"type":"codeVoice","code":"-centralManager:scannerDidBecomeReady:"},{"text":" will be called.","type":"text"},{"text":" ","type":"text"},{"text":"This method is a convenience method which calls ","type":"text"},{"type":"codeVoice","code":"-initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale"},{"type":"text","text":" "},{"type":"text","text":"with correction level Q (appropriate for dirty environments such as a warehouse) and the scale factor of the main screen"}],"title":"initiateScannerConnection(withImageSize:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"initiateScannerConnectionWithImageSize:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnection(withimagesize:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnection(withImageSize:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initiateScannerConnection","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager","role":"symbol","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}],"title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initiateScannerConnectionWithImageSize:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initiateScannerConnectionWithImageSize:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"initiateScannerConnectionWithImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnection(withImageSize:)\/title","op":"replace","value":"initiateScannerConnectionWithImageSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnection(withImageSize:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initiateScannerConnectionWithImageSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"text":"PGCentralManager","kind":"identifier"}]}]}]}