{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel","text":"PGPairingQRGeneratorErrorCorrectionLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"level","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The QR code correction level"}]}]},{"name":"imageSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image size"}]}]},{"name":"scale","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The destination screen points to pixels scale"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The generated QR code"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnectionwithqrcorrectionlevel(_:imagesize:scale:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnectionwithqrcorrectionlevel(_:imagesize:scale:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method generates an identifier which is embedded in a QR code for the Scanner to Scan, which the Scanner will advertise with."},{"type":"text","text":" "},{"type":"text","text":"The central begins scanning for a Scanner advertising the generated identifier, and on discovering will connect to the Scanner."},{"type":"text","text":" "},{"type":"text","text":"After Scanner interrogation, the scanner will become ready and "},{"type":"codeVoice","code":"-centralManager:scannerDidBecomeReady:"},{"type":"text","text":" will be called"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGPairingQRGeneratorErrorCorrectionLevel","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"title":"initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(im)initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"role":"symbol","title":"PGCentralManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCentralManager"}],"abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)":{"role":"symbol","title":"initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGPairingQRGeneratorErrorCorrectionLevel","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[{"type":"text","text":"This method generates an identifier which is embedded in a QR code for the Scanner to Scan, which the Scanner will advertise with."},{"type":"text","text":" "},{"type":"text","text":"The central begins scanning for a Scanner advertising the generated identifier, and on discovering will connect to the Scanner."},{"type":"text","text":" "},{"type":"text","text":"After Scanner interrogation, the scanner will become ready and "},{"type":"codeVoice","code":"-centralManager:scannerDidBecomeReady:"},{"type":"text","text":" will be called"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/initiatescannerconnectionwithqrcorrectionlevel(_:imagesize:scale:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"role":"symbol","title":"PGPairingQRGeneratorErrorCorrectionLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","preciseIdentifier":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel","text":"PGPairingQRGeneratorErrorCorrectionLevel"},{"kind":"text","text":") "},{"kind":"internalParam","text":"level"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scale"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"kind":"identifier","text":"PGCentralManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)\/title","value":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1initiateScannerConnectionWithQRCorrectionLevel(_:imageSize:scale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initiateScannerConnectionWithQRCorrectionLevel:imageSize:scale:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title","value":"PGPairingQRGeneratorErrorCorrectionLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}