{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/issearching"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/issearching"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearching"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"ConnectSDK"}],"title":"isSearching","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)isSearching","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"isSearching","kind":"identifier"}]},"abstract":[{"type":"text","text":"A Boolean indicating whether the search for a scanner is currently in progress."},{"type":"text","text":" "},{"text":"The value of this property is set to YES when a search is initiated and remains in that state until the search results (or an appropriate error) are delivered, at which time the property is set to NO.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearching"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { get }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/isSearching","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"PGCentralManager","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"title":"PGCentralManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/isSearching":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isSearching","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanager\/issearching","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/isSearching","abstract":[{"type":"text","text":"A Boolean indicating whether the search for a scanner is currently in progress."},{"type":"text","text":" "},{"type":"text","text":"The value of this property is set to YES when a search is initiated and remains in that state until the search results (or an appropriate error) are delivered, at which time the property is set to NO."}],"title":"isSearching","navigatorTitle":[{"text":"isSearching","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isSearching","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isSearching"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isSearching","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"text":"PGCentralManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1isSearching\/title","op":"replace","value":"isSearching"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1isSearching\/fragments","value":[{"text":"isSearching","kind":"identifier"}],"op":"replace"}]}]}