{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"scanningForIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(py)scanningForIndicator","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"scanningForIndicator"}],"symbolKind":"property","modules":[{"name":"ConnectSDK"}],"title":"scanningForIndicator"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/scanningForIndicator"},"abstract":[{"text":"The indicator the central is scanning for. This is a random string which is included in the QR code generated","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningForIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? { get }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/scanningforindicator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/scanningforindicator"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/scanningForIndicator":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/scanningForIndicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"scanningForIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"scanningForIndicator","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcentralmanager\/scanningforindicator","abstract":[{"type":"text","text":"The indicator the central is scanning for. This is a random string which is included in the QR code generated"}],"role":"symbol","title":"scanningForIndicator"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"PGCentralManager","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"title":"PGCentralManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"scanningForIndicator"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"scanningForIndicator"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"scanningForIndicator","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1scanningForIndicator\/title","value":"scanningForIndicator","op":"replace"},{"value":[{"text":"scanningForIndicator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1scanningForIndicator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"kind":"identifier","text":"PGCentralManager"}],"op":"replace"}]}]}