{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/stopScan()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanager\/stopscan()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanager\/stopscan()"]}],"abstract":[{"type":"text","text":"Use this method to stop scanning process after initiateScannerConnectionWithImageSize is invoked and before pairing QR code is scanned."},{"text":" ","type":"text"},{"type":"text","text":"If connection with Scanner is established use cancelScannerConnection: to cancel the connection."}],"metadata":{"symbolKind":"method","externalID":"c:@M@ConnectSDK@objc(cs)PGCentralManager(im)stopScan","modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Method","title":"stopScan()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopScan","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stopScan"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopScan","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager/stopScan()":{"abstract":[{"type":"text","text":"Use this method to stop scanning process after initiateScannerConnectionWithImageSize is invoked and before pairing QR code is scanned."},{"type":"text","text":" "},{"type":"text","text":"If connection with Scanner is established use cancelScannerConnection: to cancel the connection."}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"stopScan","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager\/stopScan()","url":"\/documentation\/connectsdk\/pgcentralmanager\/stopscan()","title":"stopScan()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopScan"},{"text":"()","kind":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","role":"symbol","title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"stopScan"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopScan","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopScan"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"stopScan","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1stopScan()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager~1stopScan()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopScan"}]},{"op":"replace","value":"PGCentralManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title"},{"value":[{"text":"PGCentralManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","op":"replace"}]}]}