{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playFeedbackSequence","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withFeedbackCommand","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"command"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","text":"PGCommand","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"command","content":[{"inlineContent":[{"type":"text","text":""},{"code":"PGCommand","type":"codeVoice"},{"text":" to use with ","type":"text"},{"code":"PGFeedbackRequest","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler containing error if encountered"}]}],"name":"completionHandler"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgfeedbackmanager\/playfeedbacksequence(withfeedbackcommand:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgfeedbackmanager\/playfeedbacksequence(withfeedbackcommand:completionhandler:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager\/playFeedbackSequence(withFeedbackCommand:completionHandler:)"},"sections":[],"abstract":[{"type":"text","text":"Plays sequence on a connected scanner based on a provided id."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGFeedbackManager(im)playFeedbackSequenceWithFeedbackCommand:completionHandler:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playFeedbackSequence","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withFeedbackCommand"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","text":"PGCommand","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"required":true,"roleHeading":"Instance Method","navigatorTitle":[{"text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:","kind":"identifier"}],"role":"symbol","title":"playFeedbackSequence(withFeedbackCommand:completionHandler:)"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager":{"navigatorTitle":[{"text":"PGFeedbackManager","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol contains all the feedback related methods."}],"title":"PGFeedbackManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackManager"}],"type":"topic","url":"\/documentation\/connectsdk\/pgfeedbackmanager","role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager/playFeedbackSequence(withFeedbackCommand:completionHandler:)":{"type":"topic","required":true,"role":"symbol","abstract":[{"type":"text","text":"Plays sequence on a connected scanner based on a provided id."}],"navigatorTitle":[{"text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playFeedbackSequence"},{"text":"(","kind":"text"},{"text":"withFeedbackCommand","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager\/playFeedbackSequence(withFeedbackCommand:completionHandler:)","url":"\/documentation\/connectsdk\/pgfeedbackmanager\/playfeedbacksequence(withfeedbackcommand:completionhandler:)","title":"playFeedbackSequence(withFeedbackCommand:completionHandler:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"type":"topic","title":"PGCommand","abstract":[{"type":"text","text":"A PGCommand is used to send a command to a connected device through Connect SDK."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"playFeedbackSequenceWithFeedbackCommand:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"playFeedbackSequenceWithFeedbackCommand:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","text":"PGCommand"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"command"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"PGFeedbackManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/title","op":"replace"},{"value":[{"text":"PGFeedbackManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/fragments"},{"value":"playFeedbackSequenceWithFeedbackCommand:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager~1playFeedbackSequence(withFeedbackCommand:completionHandler:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager~1playFeedbackSequence(withFeedbackCommand:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","value":"PGCommand","op":"replace"},{"value":[{"text":"PGCommand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments"}]}]}