{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didstartsearchingforindicator:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didstartsearchingforindicator:)"]}],"metadata":{"externalID":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate(im)centralManager:didStartSearchingForIndicator:","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didStartSearchingForIndicator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ConnectSDK"}],"title":"centralManager(_:didStartSearchingForIndicator:)","navigatorTitle":[{"kind":"identifier","text":"centralManager:didStartSearchingForIndicator:"}]},"abstract":[{"type":"text","text":"The central is searching for a peripheral scanner with an indicator."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"centralManager"},{"text":": ","kind":"text"},{"text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"},{"text":", ","kind":"text"},{"text":"didStartSearchingForIndicator","kind":"externalParam"},{"kind":"text","text":" "},{"text":"indicator","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"name":"centralManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The PG central"}]}]},{"name":"indicator","content":[{"inlineContent":[{"type":"text","text":"The indicator the central is searching for."}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didStartSearchingForIndicator:)","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"role":"symbol","title":"PGCentralManagerDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","navigatorTitle":[{"text":"PGCentralManagerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"PGCentralManagerDelegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager","role":"symbol","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}],"title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:didStartSearchingForIndicator:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","text":"PGCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didStartSearchingForIndicator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didstartsearchingforindicator:)","role":"symbol","navigatorTitle":[{"text":"centralManager:didStartSearchingForIndicator:","kind":"identifier"}],"title":"centralManager(_:didStartSearchingForIndicator:)","abstract":[{"type":"text","text":"The central is searching for a peripheral scanner with an indicator."}],"required":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didStartSearchingForIndicator:)","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"centralManager:didStartSearchingForIndicator:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:didStartSearchingForIndicator:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"centralManager:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","text":"PGCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"kind":"text","text":" *) "},{"text":"centralManager","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartSearchingForIndicator:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"indicator","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title","value":"PGCentralManagerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments","op":"replace","value":[{"text":"PGCentralManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGCentralManager"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didStartSearchingForIndicator:)\/title","op":"replace","value":"centralManager:didStartSearchingForIndicator:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didStartSearchingForIndicator:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"centralManager:didStartSearchingForIndicator:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}