{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didLostConnectionAndReconnectingToScanner:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","text":"PGCentralManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLostConnectionAndReconnectingToScanner"},{"kind":"text","text":" "},{"text":"scanner","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"centralManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The central"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The Scanner"}],"type":"paragraph"}],"name":"scanner"}]}],"metadata":{"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","text":"PGCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLostConnectionAndReconnectingToScanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":")","kind":"text"}],"role":"symbol","required":true,"externalID":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate(im)centralManager:didLostConnectionAndReconnectingToScanner:","title":"centralManager(_:didLostConnectionAndReconnectingToScanner:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"centralManager:didLostConnectionAndReconnectingToScanner:","kind":"identifier"}]},"sections":[],"abstract":[{"text":"The central manager did lost connection to Scanner and trying to reconnect.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didlostconnectionandreconnectingtoscanner:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didlostconnectionandreconnectingtoscanner:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","abstract":[{"text":"PGCentralManagerDelegate","type":"text"}],"role":"symbol","title":"PGCentralManagerDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"PGCentralManagerDelegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanager","abstract":[{"type":"text","text":"PGCentralManager"}],"role":"symbol","title":"PGCentralManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:didLostConnectionAndReconnectingToScanner:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:didLostConnectionAndReconnectingToScanner:)","type":"topic","required":true,"role":"symbol","title":"centralManager(_:didLostConnectionAndReconnectingToScanner:)","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:didlostconnectionandreconnectingtoscanner:)","kind":"symbol","abstract":[{"text":"The central manager did lost connection to Scanner and trying to reconnect.","type":"text"}],"navigatorTitle":[{"text":"centralManager:didLostConnectionAndReconnectingToScanner:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didLostConnectionAndReconnectingToScanner"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","title":"PGPeripheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheral"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"centralManager:didLostConnectionAndReconnectingToScanner:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"centralManager:didLostConnectionAndReconnectingToScanner:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"centralManager:"},{"text":"(","kind":"text"},{"text":"PGCentralManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"kind":"text","text":" *) "},{"text":"centralManager","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLostConnectionAndReconnectingToScanner:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scanner"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"PGCentralManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title"},{"value":[{"text":"PGCentralManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"text":"PGCentralManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didLostConnectionAndReconnectingToScanner:)\/title","value":"centralManager:didLostConnectionAndReconnectingToScanner:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:didLostConnectionAndReconnectingToScanner:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:didLostConnectionAndReconnectingToScanner:"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","value":"PGPeripheral","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"kind":"identifier","text":"PGPeripheral"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}