{"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate(im)centralManager:connectingToScanner:","symbolKind":"method","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","kind":"typeIdentifier","text":"PGCentralManager"},{"kind":"text","text":", "},{"text":"connectingToScanner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"centralManager:connectingToScanner:","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"title":"centralManager(_:connectingToScanner:)"},"variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:connectingtoscanner:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:connectingtoscanner:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:connectingToScanner:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"centralManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","text":"PGCentralManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"connectingToScanner"},{"text":" ","kind":"text"},{"text":"scanner","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"centralManager","content":[{"type":"paragraph","inlineContent":[{"text":"The PG central","type":"text"}]}]},{"name":"scanner","content":[{"inlineContent":[{"text":"The scanner which is now connecting","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate"]]},"abstract":[{"text":"Now connecting to a Scanner","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManager","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"PGCentralManager","type":"text"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"title":"PGCentralManager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"kind":"identifier","text":"PGPeripheral"}],"title":"PGPeripheral","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheral","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:connectingToScanner:)":{"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:connectingtoscanner:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:connectingToScanner:)","role":"symbol","title":"centralManager(_:connectingToScanner:)","required":true,"abstract":[{"text":"Now connecting to a Scanner","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","kind":"typeIdentifier","text":"PGCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectingToScanner"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"centralManager:connectingToScanner:"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","type":"topic","abstract":[{"type":"text","text":"PGCentralManagerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCentralManagerDelegate"}],"title":"PGCentralManagerDelegate","role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"centralManager:connectingToScanner:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"centralManager:connectingToScanner:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"centralManager:"},{"kind":"text","text":"("},{"text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"centralManager"},{"kind":"text","text":" "},{"text":"connectingToScanner:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":" *) "},{"text":"scanner","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"text":"PGCentralManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","value":"PGPeripheral","op":"replace"},{"value":[{"kind":"identifier","text":"PGPeripheral"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments"},{"op":"replace","value":"centralManager:connectingToScanner:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:connectingToScanner:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:connectingToScanner:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:connectingToScanner:"}]},{"value":"PGCentralManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments","op":"replace","value":[{"text":"PGCentralManagerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}