{"abstract":[{"text":"The Scanner became ready","type":"text"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidbecomeready:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidbecomeready:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate(im)centralManager:scannerDidBecomeReady:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scannerDidBecomeReady"},{"text":": ","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"centralManager:scannerDidBecomeReady:"}],"role":"symbol","modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"centralManager(_:scannerDidBecomeReady:)","required":true},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"centralManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCentralManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scannerDidBecomeReady"},{"text":" ","kind":"text"},{"text":"scanner","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The PG central","type":"text"}]}],"name":"centralManager"},{"content":[{"inlineContent":[{"text":"The scanner which became ready","type":"text"}],"type":"paragraph"}],"name":"scanner"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidBecomeReady:)","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCentralManagerDelegate"}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","title":"PGCentralManagerDelegate","abstract":[{"text":"PGCentralManagerDelegate","type":"text"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","role":"symbol","title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:scannerDidBecomeReady:)":{"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidbecomeready:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"PGCentralManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scannerDidBecomeReady"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"centralManager:scannerDidBecomeReady:","kind":"identifier"}],"abstract":[{"type":"text","text":"The Scanner became ready"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidBecomeReady:)","kind":"symbol","title":"centralManager(_:scannerDidBecomeReady:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"centralManager:scannerDidBecomeReady:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"centralManager:scannerDidBecomeReady:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"centralManager:"},{"kind":"text","text":"("},{"text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"centralManager"},{"text":" ","kind":"text"},{"text":"scannerDidBecomeReady:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral"},{"text":" *) ","kind":"text"},{"text":"scanner","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title","value":"PGCentralManagerDelegate"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGCentralManagerDelegate"}],"op":"replace"},{"value":"PGCentralManager","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title"},{"value":[{"text":"PGCentralManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidBecomeReady:)\/title","value":"centralManager:scannerDidBecomeReady:","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidBecomeReady:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"centralManager:scannerDidBecomeReady:"}],"op":"replace"},{"value":"PGPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","op":"replace","value":[{"text":"PGPeripheral","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}