{"sections":[],"abstract":[{"type":"text","text":"Scanner is connected but still not ready for use."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidconnect:)"]},{"paths":["\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidconnect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"centralManager:scannerDidConnect:"}],"title":"centralManager(_:scannerDidConnect:)","externalID":"c:@M@ConnectSDK@objc(pl)PGCentralManagerDelegate(im)centralManager:scannerDidConnect:","roleHeading":"Instance Method","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","text":"PGCentralManager"},{"text":", ","kind":"text"},{"text":"scannerDidConnect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":")","kind":"text"}],"modules":[{"name":"ConnectSDK"}]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidConnect:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scannerDidConnect"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"scanner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The PG central.","type":"text"}]}],"name":"centralManager"},{"name":"scanner","content":[{"type":"paragraph","inlineContent":[{"text":"The scanner which is now connected.","type":"text"}]}]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"role":"symbol","title":"PGCentralManagerDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","navigatorTitle":[{"text":"PGCentralManagerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"PGCentralManagerDelegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager","role":"symbol","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}],"title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate/centralManager(_:scannerDidConnect:)":{"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate\/centralManager(_:scannerDidConnect:)","title":"centralManager(_:scannerDidConnect:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"centralManager:scannerDidConnect:"}],"abstract":[{"type":"text","text":"Scanner is connected but still not ready for use."}],"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"text":", ","kind":"text"},{"text":"scannerDidConnect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":")"}],"url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate\/centralmanager(_:scannerdidconnect:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"kind":"symbol","title":"PGPeripheral","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}],"url":"\/documentation\/connectsdk\/pgperipheral"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"centralManager:scannerDidConnect:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"centralManager:scannerDidConnect:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"centralManager:"},{"kind":"text","text":"("},{"text":"PGCentralManager","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCentralManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"centralManager"},{"text":" ","kind":"text"},{"text":"scannerDidConnect:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},{"kind":"text","text":" *) "},{"text":"scanner","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGCentralManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGCentralManagerDelegate"}]},{"op":"replace","value":"PGCentralManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","op":"replace","value":[{"text":"PGCentralManager","kind":"identifier"}]},{"value":"centralManager:scannerDidConnect:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidConnect:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate~1centralManager(_:scannerDidConnect:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"centralManager:scannerDidConnect:"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","op":"replace","value":"PGPeripheral"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"kind":"identifier","text":"PGPeripheral"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}