{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attErrorDiscoveringServices","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringServices","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringservices"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringservices"]}],"metadata":{"title":"PGPeripheralError.attErrorDiscoveringServices","navigatorTitle":[{"text":"PGPeripheralErrorAttErrorDiscoveringServices","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorAttErrorDiscoveringServices","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"attErrorDiscoveringServices","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"symbolKind":"case","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"An ATT error occurred discovering services"}],"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attErrorDiscoveringServices":{"abstract":[{"type":"text","text":"An ATT error occurred discovering services"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorAttErrorDiscoveringServices"}],"type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringservices","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringServices","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attErrorDiscoveringServices","kind":"identifier"}],"title":"PGPeripheralError.attErrorDiscoveringServices","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"title":"PGPeripheralError","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorAttErrorDiscoveringServices"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorAttErrorDiscoveringServices"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"PGPeripheralErrorAttErrorDiscoveringServices"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringServices\/title","value":"PGPeripheralErrorAttErrorDiscoveringServices","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringServices\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorAttErrorDiscoveringServices"}],"op":"replace"},{"value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace","value":[{"text":"PGPeripheralError","kind":"identifier"}]}]}]}