{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attErrorDiscoveringCharacteristics","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorAttErrorDiscoveringCharacteristics","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorAttErrorDiscoveringCharacteristics"}],"symbolKind":"case","modules":[{"name":"ConnectSDK"}],"title":"PGPeripheralError.attErrorDiscoveringCharacteristics"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attErrorDiscoveringCharacteristics"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringcharacteristics"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringcharacteristics"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringCharacteristics"},"abstract":[{"type":"text","text":"An ATT error occurred discovering characteristics, see PGPeripheralErrorServiceKey for the NSUUID of the service"}],"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"kind":"symbol","abstract":[{"type":"text","text":"All PG peripheral error codes"}],"url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","title":"PGPeripheralError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attErrorDiscoveringCharacteristics":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"attErrorDiscoveringCharacteristics","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/atterrordiscoveringcharacteristics","abstract":[{"text":"An ATT error occurred discovering characteristics, see PGPeripheralErrorServiceKey for the NSUUID of the service","type":"text"}],"title":"PGPeripheralError.attErrorDiscoveringCharacteristics","navigatorTitle":[{"text":"PGPeripheralErrorAttErrorDiscoveringCharacteristics","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attErrorDiscoveringCharacteristics","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorAttErrorDiscoveringCharacteristics"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPeripheralErrorAttErrorDiscoveringCharacteristics","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"PGPeripheralErrorAttErrorDiscoveringCharacteristics"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace","value":"PGPeripheralError"},{"value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringCharacteristics\/title","value":"PGPeripheralErrorAttErrorDiscoveringCharacteristics"},{"value":[{"text":"PGPeripheralErrorAttErrorDiscoveringCharacteristics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attErrorDiscoveringCharacteristics\/fragments"}]}]}