{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"abstract":[{"text":"The write to the attribute went beyond the bounds of the attribute’s size","type":"text"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/attributewritetoolarge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/attributewritetoolarge"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"PGPeripheralError.attributeWriteTooLarge","role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteTooLarge"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attributeWriteTooLarge","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorAttributeWriteTooLarge","symbolKind":"case"},"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteTooLarge","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributeWriteTooLarge"}]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralError"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","role":"symbol","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"title":"PGPeripheralError"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attributeWriteTooLarge":{"title":"PGPeripheralError.attributeWriteTooLarge","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributeWriteTooLarge","kind":"identifier"}],"abstract":[{"type":"text","text":"The write to the attribute went beyond the bounds of the attribute’s size"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/attributewritetoolarge","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteTooLarge"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteTooLarge"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"PGPeripheralErrorAttributeWriteTooLarge"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PGPeripheralErrorAttributeWriteTooLarge","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteTooLarge"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","value":"PGPeripheralError","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteTooLarge\/title","value":"PGPeripheralErrorAttributeWriteTooLarge"},{"op":"replace","value":[{"text":"PGPeripheralErrorAttributeWriteTooLarge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteTooLarge\/fragments"}]}]}