{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteFailedTryLater"}],"modules":[{"name":"ConnectSDK"}],"title":"PGPeripheralError.attributeWriteFailedTryLater","role":"symbol","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorAttributeWriteFailedTryLater","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributeWriteFailedTryLater","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteFailedTryLater","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributeWriteFailedTryLater","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/attributewritefailedtrylater"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/attributewritefailedtrylater"]}],"kind":"symbol","abstract":[{"type":"text","text":"Writing to the attribute failed but can be retried later"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"title":"PGPeripheralError","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/attributeWriteFailedTryLater":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/attributeWriteFailedTryLater","url":"\/documentation\/connectsdk\/pgperipheralerror\/attributewritefailedtrylater","title":"PGPeripheralError.attributeWriteFailedTryLater","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"attributeWriteFailedTryLater","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Writing to the attribute failed but can be retried later","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PGPeripheralErrorAttributeWriteFailedTryLater","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorAttributeWriteFailedTryLater"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"PGPeripheralErrorAttributeWriteFailedTryLater","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteFailedTryLater"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace","value":"PGPeripheralError"},{"value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteFailedTryLater\/title","op":"replace","value":"PGPeripheralErrorAttributeWriteFailedTryLater"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1attributeWriteFailedTryLater\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorAttributeWriteFailedTryLater"}]}]}]}