{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"connectingTimedOut","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/connectingtimedout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/connectingtimedout"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Connecting timed out"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectingTimedOut","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"PGPeripheralErrorConnectingTimedOut","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectingTimedOut"}],"externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorConnectingTimedOut","symbolKind":"case","title":"PGPeripheralError.connectingTimedOut","roleHeading":"Case"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror","title":"PGPeripheralError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","abstract":[{"type":"text","text":"All PG peripheral error codes"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/connectingTimedOut":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectingTimedOut","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PGPeripheralErrorConnectingTimedOut","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectingTimedOut","abstract":[{"text":"Connecting timed out","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/connectingtimedout","kind":"symbol","title":"PGPeripheralError.connectingTimedOut","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PGPeripheralErrorConnectingTimedOut","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"PGPeripheralErrorConnectingTimedOut","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGPeripheralErrorConnectingTimedOut"}],"languages":["occ"]}]}},{"op":"replace","value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title"},{"op":"replace","value":[{"text":"PGPeripheralError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectingTimedOut\/title","op":"replace","value":"PGPeripheralErrorConnectingTimedOut"},{"op":"replace","value":[{"text":"PGPeripheralErrorConnectingTimedOut","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectingTimedOut\/fragments"}]}]}