{"metadata":{"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionTimedOut"}],"role":"symbol","roleHeading":"Case","title":"PGPeripheralError.connectionTimedOut","navigatorTitle":[{"text":"PGPeripheralErrorConnectionTimedOut","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorConnectionTimedOut"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/connectiontimedout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/connectiontimedout"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Connection timed out","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectionTimedOut"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connectionTimedOut","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralError"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","role":"symbol","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"title":"PGPeripheralError"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/connectionTimedOut":{"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorConnectionTimedOut"}],"title":"PGPeripheralError.connectionTimedOut","kind":"symbol","abstract":[{"type":"text","text":"Connection timed out"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/connectiontimedout","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionTimedOut"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/connectionTimedOut"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PGPeripheralErrorConnectionTimedOut","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorConnectionTimedOut"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PGPeripheralErrorConnectionTimedOut","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace"},{"value":[{"text":"PGPeripheralError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectionTimedOut\/title","value":"PGPeripheralErrorConnectionTimedOut"},{"op":"replace","value":[{"text":"PGPeripheralErrorConnectionTimedOut","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1connectionTimedOut\/fragments"}]}]}