{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"abstract":[{"type":"text","text":"Peripheral discovery timed out"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"discoveryTimedOut","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/discoveryTimedOut"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/discoverytimedout"]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/discoverytimedout"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"PGPeripheralErrorDiscoveryTimedOut","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"discoveryTimedOut"}],"symbolKind":"case","modules":[{"name":"ConnectSDK"}],"role":"symbol","roleHeading":"Case","title":"PGPeripheralError.discoveryTimedOut","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorDiscoveryTimedOut"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/discoveryTimedOut":{"navigatorTitle":[{"text":"PGPeripheralErrorDiscoveryTimedOut","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/discoverytimedout","title":"PGPeripheralError.discoveryTimedOut","type":"topic","abstract":[{"text":"Peripheral discovery timed out","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoveryTimedOut"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/discoveryTimedOut"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror","title":"PGPeripheralError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","abstract":[{"type":"text","text":"All PG peripheral error codes"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PGPeripheralErrorDiscoveryTimedOut"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorDiscoveryTimedOut"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PGPeripheralErrorDiscoveryTimedOut","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"PGPeripheralErrorDiscoveryTimedOut","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1discoveryTimedOut\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1discoveryTimedOut\/fragments","value":[{"text":"PGPeripheralErrorDiscoveryTimedOut","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","value":"PGPeripheralError","op":"replace"},{"value":[{"text":"PGPeripheralError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}