{"metadata":{"externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorIncompatibleModel","roleHeading":"Case","symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorIncompatibleModel"}],"modules":[{"name":"ConnectSDK"}],"title":"PGPeripheralError.incompatibleModel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"incompatibleModel","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incompatibleModel"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The device is not compatible with this App based on its model number. See PGPeripheralErrorIncompatibleModelNumberKey for the model number"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/incompatiblemodel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/incompatiblemodel"]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/incompatibleModel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/incompatibleModel":{"url":"\/documentation\/connectsdk\/pgperipheralerror\/incompatiblemodel","abstract":[{"type":"text","text":"The device is not compatible with this App based on its model number. See PGPeripheralErrorIncompatibleModelNumberKey for the model number"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/incompatibleModel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incompatibleModel"}],"navigatorTitle":[{"text":"PGPeripheralErrorIncompatibleModel","kind":"identifier"}],"title":"PGPeripheralError.incompatibleModel","kind":"symbol","role":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"title":"PGPeripheralError","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"PGPeripheralErrorIncompatibleModel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPeripheralErrorIncompatibleModel","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PGPeripheralErrorIncompatibleModel","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1incompatibleModel\/title","value":"PGPeripheralErrorIncompatibleModel","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1incompatibleModel\/fragments","value":[{"text":"PGPeripheralErrorIncompatibleModel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace","value":[{"text":"PGPeripheralError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}