{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/invaliddata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/invaliddata"]}],"abstract":[{"type":"text","text":"Data read from the device was invalid. Could suggest the GATT cache is invalid, requiring a Bluetooth toggle."}],"metadata":{"modules":[{"name":"ConnectSDK"}],"role":"symbol","title":"PGPeripheralError.invalidData","roleHeading":"Case","navigatorTitle":[{"text":"PGPeripheralErrorInvalidData","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidData"}],"symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorInvalidData"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidData","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidData","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror","title":"PGPeripheralError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","abstract":[{"type":"text","text":"All PG peripheral error codes"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/invalidData":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidData","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidData","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data read from the device was invalid. Could suggest the GATT cache is invalid, requiring a Bluetooth toggle."}],"title":"PGPeripheralError.invalidData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorInvalidData"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/invaliddata","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorInvalidData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"PGPeripheralErrorInvalidData","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"PGPeripheralErrorInvalidData","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","value":"PGPeripheralError"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","value":[{"kind":"identifier","text":"PGPeripheralError"}],"op":"replace"},{"value":"PGPeripheralErrorInvalidData","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidData\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidData\/fragments","value":[{"text":"PGPeripheralErrorInvalidData","kind":"identifier"}],"op":"replace"}]}]}