{"metadata":{"title":"PGPeripheralError.invalidState","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorInvalidState"}],"symbolKind":"case","roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"role":"symbol","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorInvalidState","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidState"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidState"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidState"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"abstract":[{"type":"text","text":"Peripheral was in an invalid state for performing this operation"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/invalidstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/invalidstate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/invalidState":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidState"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorInvalidState"}],"type":"topic","title":"PGPeripheralError.invalidState","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/invalidState","abstract":[{"type":"text","text":"Peripheral was in an invalid state for performing this operation"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/invalidstate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"kind":"symbol","abstract":[{"type":"text","text":"All PG peripheral error codes"}],"url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","title":"PGPeripheralError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PGPeripheralErrorInvalidState","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorInvalidState"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGPeripheralErrorInvalidState"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PGPeripheralErrorInvalidState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidState\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1invalidState\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorInvalidState"}]},{"value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","value":[{"kind":"identifier","text":"PGPeripheralError"}]}]}]}