{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingCharacteristics"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/missingcharacteristics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/missingcharacteristics"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingCharacteristics","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Required characteristics were missing"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingCharacteristics"}],"title":"PGPeripheralError.missingCharacteristics","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorMissingCharacteristics","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorMissingCharacteristics"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/missingCharacteristics":{"role":"symbol","title":"PGPeripheralError.missingCharacteristics","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingCharacteristics"}],"abstract":[{"type":"text","text":"Required characteristics were missing"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/missingCharacteristics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorMissingCharacteristics"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/missingcharacteristics"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"role":"symbol","title":"PGPeripheralError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPeripheralError"}],"abstract":[{"type":"text","text":"All PG peripheral error codes"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralError"}],"url":"\/documentation\/connectsdk\/pgperipheralerror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorMissingCharacteristics"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorMissingCharacteristics"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGPeripheralErrorMissingCharacteristics"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1missingCharacteristics\/title","value":"PGPeripheralErrorMissingCharacteristics"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1missingCharacteristics\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorMissingCharacteristics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","value":"PGPeripheralError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","value":[{"kind":"identifier","text":"PGPeripheralError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}