{"abstract":[{"type":"text","text":"Device is not ready to perform this action (usually when connecting)"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/notready"]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/notready"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"PGPeripheralErrorNotReady","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReady"}],"externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorNotReady","symbolKind":"case","role":"symbol","title":"PGPeripheralError.notReady","roleHeading":"Case","modules":[{"name":"ConnectSDK"}]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notReady","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notReady"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/notReady":{"title":"PGPeripheralError.notReady","abstract":[{"text":"Device is not ready to perform this action (usually when connecting)","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notReady","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/notready","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/notReady","navigatorTitle":[{"text":"PGPeripheralErrorNotReady","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"title":"PGPeripheralError","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"PGPeripheralErrorNotReady","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"PGPeripheralErrorNotReady","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PGPeripheralErrorNotReady","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1notReady\/title","value":"PGPeripheralErrorNotReady"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1notReady\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorNotReady"}]},{"op":"replace","value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace","value":[{"text":"PGPeripheralError","kind":"identifier"}]}]}]}