{"metadata":{"title":"PGPeripheralError.operationCancelled","role":"symbol","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operationCancelled"}],"roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorOperationCancelled","navigatorTitle":[{"text":"PGPeripheralErrorOperationCancelled","kind":"identifier"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/operationCancelled","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"sections":[],"kind":"symbol","abstract":[{"text":"The operation was cancelled","type":"text"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/operationcancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/operationcancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"operationCancelled","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralError"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","role":"symbol","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"title":"PGPeripheralError"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/operationCancelled":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/operationCancelled","abstract":[{"text":"The operation was cancelled","type":"text"}],"navigatorTitle":[{"text":"PGPeripheralErrorOperationCancelled","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operationCancelled"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror\/operationcancelled","kind":"symbol","title":"PGPeripheralError.operationCancelled"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PGPeripheralErrorOperationCancelled","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPeripheralErrorOperationCancelled","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"PGPeripheralErrorOperationCancelled","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace","value":"PGPeripheralError"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1operationCancelled\/title","value":"PGPeripheralErrorOperationCancelled","op":"replace"},{"value":[{"text":"PGPeripheralErrorOperationCancelled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1operationCancelled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}