{"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorPeripheralNotPaired","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheralNotPaired","kind":"identifier"}],"title":"PGPeripheralError.peripheralNotPaired","navigatorTitle":[{"text":"PGPeripheralErrorPeripheralNotPaired","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/peripheralnotpaired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/peripheralnotpaired"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralNotPaired","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The device was not paired, or pairing was cancelled"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheralNotPaired"}]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"kind":"symbol","abstract":[{"type":"text","text":"All PG peripheral error codes"}],"url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","title":"PGPeripheralError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/peripheralNotPaired":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheralNotPaired"}],"navigatorTitle":[{"text":"PGPeripheralErrorPeripheralNotPaired","kind":"identifier"}],"title":"PGPeripheralError.peripheralNotPaired","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralNotPaired","url":"\/documentation\/connectsdk\/pgperipheralerror\/peripheralnotpaired","abstract":[{"type":"text","text":"The device was not paired, or pairing was cancelled"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorPeripheralNotPaired"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorPeripheralNotPaired"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"PGPeripheralErrorPeripheralNotPaired","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","value":"PGPeripheralError"},{"value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace"},{"value":"PGPeripheralErrorPeripheralNotPaired","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralNotPaired\/title"},{"value":[{"kind":"identifier","text":"PGPeripheralErrorPeripheralNotPaired"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralNotPaired\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}