{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheralDisconnected"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralDisconnected"},"abstract":[{"type":"text","text":"The peripheral closed the connection or went out of range"}],"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheralDisconnected"}],"navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorPeripheralDisconnected"}],"symbolKind":"case","title":"PGPeripheralError.peripheralDisconnected","modules":[{"name":"ConnectSDK"}],"role":"symbol","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorPeripheralDisconnected"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/peripheraldisconnected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/peripheraldisconnected"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror","title":"PGPeripheralError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","abstract":[{"type":"text","text":"All PG peripheral error codes"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/peripheralDisconnected":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"peripheralDisconnected","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorPeripheralDisconnected"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/peripheralDisconnected","abstract":[{"text":"The peripheral closed the connection or went out of range","type":"text"}],"url":"\/documentation\/connectsdk\/pgperipheralerror\/peripheraldisconnected","kind":"symbol","title":"PGPeripheralError.peripheralDisconnected","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PGPeripheralErrorPeripheralDisconnected"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"PGPeripheralErrorPeripheralDisconnected"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"PGPeripheralErrorPeripheralDisconnected","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","value":"PGPeripheralError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","value":[{"kind":"identifier","text":"PGPeripheralError"}]},{"op":"replace","value":"PGPeripheralErrorPeripheralDisconnected","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralDisconnected\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1peripheralDisconnected\/fragments","value":[{"text":"PGPeripheralErrorPeripheralDisconnected","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}