{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unexpectedUnresolvable","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/unexpectedunresolvable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/unexpectedunresolvable"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unexpectedUnresolvable","kind":"identifier"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorUnexpectedUnresolvable","navigatorTitle":[{"text":"PGPeripheralErrorUnexpectedUnresolvable","kind":"identifier"}],"title":"PGPeripheralError.unexpectedUnresolvable"},"abstract":[{"type":"text","text":"Unexpected error that cannot be resolved."}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unexpectedUnresolvable","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/unexpectedUnresolvable":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unexpectedUnresolvable","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorUnexpectedUnresolvable"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror\/unexpectedunresolvable","type":"topic","title":"PGPeripheralError.unexpectedUnresolvable","abstract":[{"type":"text","text":"Unexpected error that cannot be resolved."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unexpectedUnresolvable"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror","title":"PGPeripheralError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","abstract":[{"type":"text","text":"All PG peripheral error codes"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"PGPeripheralErrorUnexpectedUnresolvable"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPeripheralErrorUnexpectedUnresolvable","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGPeripheralErrorUnexpectedUnresolvable"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unexpectedUnresolvable\/title","value":"PGPeripheralErrorUnexpectedUnresolvable"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unexpectedUnresolvable\/fragments","value":[{"text":"PGPeripheralErrorUnexpectedUnresolvable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","value":"PGPeripheralError"},{"value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","op":"replace"}]}]}