{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheralerror\/unhandled"]},{"paths":["\/documentation\/connectsdk\/pgperipheralerror\/unhandled"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"PGPeripheralError.unhandled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unhandled","kind":"identifier"}],"role":"symbol","modules":[{"name":"ConnectSDK"}],"roleHeading":"Case","navigatorTitle":[{"text":"PGPeripheralErrorUnhandled","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGPeripheralError@PGPeripheralErrorUnhandled","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhandled"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Unhandled error."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unhandled","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError/unhandled":{"title":"PGPeripheralError.unhandled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unhandled"}],"abstract":[{"type":"text","text":"Unhandled error."}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerror\/unhandled","role":"symbol","navigatorTitle":[{"text":"PGPeripheralErrorUnhandled","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError\/unhandled","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralError"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","role":"symbol","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"title":"PGPeripheralError"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"PGPeripheralErrorUnhandled","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"PGPeripheralErrorUnhandled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"PGPeripheralErrorUnhandled","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGPeripheralErrorUnhandled","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unhandled\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError~1unhandled\/fragments","value":[{"text":"PGPeripheralErrorUnhandled","kind":"identifier"}],"op":"replace"},{"value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGPeripheralError"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments"}]}]}