{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capabilityNotSupported"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"ConnectSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"capabilityNotSupported","kind":"identifier"}],"title":"PGWearableApiError.capabilityNotSupported","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorCapabilityNotSupported"}],"externalID":"c:@M@ConnectSDK@E@PGWearableApiError@PGWearableApiErrorCapabilityNotSupported"},"abstract":[{"type":"text","text":"The capability is not supported."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgwearableapierror\/capabilitynotsupported"]},{"paths":["\/documentation\/connectsdk\/pgwearableapierror\/capabilitynotsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/capabilityNotSupported","interfaceLanguage":"swift"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/capabilityNotSupported":{"title":"PGWearableApiError.capabilityNotSupported","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/capabilityNotSupported","kind":"symbol","abstract":[{"type":"text","text":"The capability is not supported."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"capabilityNotSupported","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgwearableapierror\/capabilitynotsupported","navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorCapabilityNotSupported"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError":{"role":"symbol","navigatorTitle":[{"text":"PGWearableApiError","kind":"identifier"}],"abstract":[{"type":"text","text":"PG Wearable API error codes"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgwearableapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError","title":"PGWearableApiError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGWearableApiError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PGWearableApiErrorCapabilityNotSupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGWearableApiErrorCapabilityNotSupported"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGWearableApiErrorCapabilityNotSupported"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1capabilityNotSupported\/title","value":"PGWearableApiErrorCapabilityNotSupported","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1capabilityNotSupported\/fragments","value":[{"text":"PGWearableApiErrorCapabilityNotSupported","kind":"identifier"}],"op":"replace"},{"value":"PGWearableApiError","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/fragments","value":[{"kind":"identifier","text":"PGWearableApiError"}]}]}]}