{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidPayload"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgwearableapierror\/invalidpayload"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgwearableapierror\/invalidpayload"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/invalidPayload","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrong wapi payload received."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidPayload"}],"title":"PGWearableApiError.invalidPayload","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGWearableApiError@PGWearableApiErrorInvalidPayload","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorInvalidPayload"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError":{"role":"symbol","title":"PGWearableApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGWearableApiError"}],"abstract":[{"type":"text","text":"PG Wearable API error codes"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGWearableApiError"}],"url":"\/documentation\/connectsdk\/pgwearableapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/invalidPayload":{"role":"symbol","title":"PGWearableApiError.invalidPayload","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidPayload"}],"abstract":[{"type":"text","text":"Wrong wapi payload received."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/invalidPayload","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorInvalidPayload"}],"url":"\/documentation\/connectsdk\/pgwearableapierror\/invalidpayload"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGWearableApiErrorInvalidPayload"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGWearableApiErrorInvalidPayload"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGWearableApiErrorInvalidPayload"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/title","value":"PGWearableApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/fragments","value":[{"kind":"identifier","text":"PGWearableApiError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1invalidPayload\/title","value":"PGWearableApiErrorInvalidPayload"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1invalidPayload\/fragments","value":[{"kind":"identifier","text":"PGWearableApiErrorInvalidPayload"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}