{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimeout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgwearableapierror\/requesttimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgwearableapierror\/requesttimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestTimeout","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wapi request timed out."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimeout"}],"title":"PGWearableApiError.requestTimeout","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGWearableApiError@PGWearableApiErrorRequestTimeout","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorRequestTimeout"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/requestTimeout":{"role":"symbol","title":"PGWearableApiError.requestTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimeout"}],"abstract":[{"type":"text","text":"Wapi request timed out."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorRequestTimeout"}],"url":"\/documentation\/connectsdk\/pgwearableapierror\/requesttimeout"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError":{"role":"symbol","title":"PGWearableApiError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGWearableApiError"}],"abstract":[{"type":"text","text":"PG Wearable API error codes"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGWearableApiError"}],"url":"\/documentation\/connectsdk\/pgwearableapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGWearableApiErrorRequestTimeout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGWearableApiErrorRequestTimeout"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGWearableApiErrorRequestTimeout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestTimeout\/title","value":"PGWearableApiErrorRequestTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestTimeout\/fragments","value":[{"kind":"identifier","text":"PGWearableApiErrorRequestTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/title","value":"PGWearableApiError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/fragments","value":[{"kind":"identifier","text":"PGWearableApiError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}