{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestDenied","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wapi request was denied. Queue limit reached."}],"metadata":{"navigatorTitle":[{"text":"PGWearableApiErrorRequestDenied","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"role":"symbol","externalID":"c:@M@ConnectSDK@E@PGWearableApiError@PGWearableApiErrorRequestDenied","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestDenied","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"PGWearableApiError.requestDenied"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgwearableapierror\/requestdenied"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgwearableapierror\/requestdenied"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestDenied","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError/requestDenied":{"navigatorTitle":[{"kind":"identifier","text":"PGWearableApiErrorRequestDenied"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestDenied"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError\/requestDenied","role":"symbol","abstract":[{"type":"text","text":"Wapi request was denied. Queue limit reached."}],"url":"\/documentation\/connectsdk\/pgwearableapierror\/requestdenied","type":"topic","title":"PGWearableApiError.requestDenied"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError":{"role":"symbol","navigatorTitle":[{"text":"PGWearableApiError","kind":"identifier"}],"abstract":[{"type":"text","text":"PG Wearable API error codes"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgwearableapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError","title":"PGWearableApiError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGWearableApiError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"PGWearableApiErrorRequestDenied","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PGWearableApiErrorRequestDenied","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"PGWearableApiErrorRequestDenied","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestDenied\/title","value":"PGWearableApiErrorRequestDenied"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError~1requestDenied\/fragments","value":[{"kind":"identifier","text":"PGWearableApiErrorRequestDenied"}]},{"op":"replace","value":"PGWearableApiError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/fragments","value":[{"kind":"identifier","text":"PGWearableApiError"}],"op":"replace"}]}]}