{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/invalidAuthenticationBarcode","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","title":"PGDeviceLockError.invalidAuthenticationBarcode","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGDeviceLockError@PGDeviceLockErrorInvalidAuthenticationBarcode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidAuthenticationBarcode","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"PGDeviceLockErrorInvalidAuthenticationBarcode","kind":"identifier"}]},"abstract":[{"type":"text","text":"Authentication barcode is invalid"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidAuthenticationBarcode","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdevicelockerror\/invalidauthenticationbarcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdevicelockerror\/invalidauthenticationbarcode"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError/invalidAuthenticationBarcode":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidAuthenticationBarcode","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgdevicelockerror\/invalidauthenticationbarcode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockErrorInvalidAuthenticationBarcode"}],"role":"symbol","title":"PGDeviceLockError.invalidAuthenticationBarcode","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/invalidAuthenticationBarcode","abstract":[{"type":"text","text":"Authentication barcode is invalid"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockError"}],"role":"symbol","title":"PGDeviceLockError","type":"topic","abstract":[{"text":"Scanner lock\/unlock error codes","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGDeviceLockError"}],"url":"\/documentation\/connectsdk\/pgdevicelockerror"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PGDeviceLockErrorInvalidAuthenticationBarcode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"PGDeviceLockErrorInvalidAuthenticationBarcode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGDeviceLockErrorInvalidAuthenticationBarcode"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1invalidAuthenticationBarcode\/title","value":"PGDeviceLockErrorInvalidAuthenticationBarcode","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1invalidAuthenticationBarcode\/fragments","value":[{"kind":"identifier","text":"PGDeviceLockErrorInvalidAuthenticationBarcode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/title","op":"replace","value":"PGDeviceLockError"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/fragments","op":"replace","value":[{"text":"PGDeviceLockError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}