{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgdevicelockerror\/unlockfailed"]},{"paths":["\/documentation\/connectsdk\/pgdevicelockerror\/unlockfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unlockFailed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/unlockFailed","interfaceLanguage":"swift"},"metadata":{"title":"PGDeviceLockError.unlockFailed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlockFailed"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGDeviceLockError@PGDeviceLockErrorUnlockFailed","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockErrorUnlockFailed"}],"symbolKind":"case","role":"symbol"},"abstract":[{"type":"text","text":"Device unlock failed"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError/unlockFailed":{"url":"\/documentation\/connectsdk\/pgdevicelockerror\/unlockfailed","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError\/unlockFailed","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockErrorUnlockFailed"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unlockFailed","kind":"identifier"}],"title":"PGDeviceLockError.unlockFailed","type":"topic","abstract":[{"text":"Device unlock failed","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError":{"type":"topic","navigatorTitle":[{"text":"PGDeviceLockError","kind":"identifier"}],"title":"PGDeviceLockError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError","kind":"symbol","url":"\/documentation\/connectsdk\/pgdevicelockerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDeviceLockError","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Scanner lock\/unlock error codes"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"PGDeviceLockErrorUnlockFailed","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGDeviceLockErrorUnlockFailed"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"PGDeviceLockErrorUnlockFailed","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"PGDeviceLockErrorUnlockFailed","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1unlockFailed\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError~1unlockFailed\/fragments","value":[{"kind":"identifier","text":"PGDeviceLockErrorUnlockFailed"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/title","op":"replace","value":"PGDeviceLockError"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/fragments","value":[{"kind":"identifier","text":"PGDeviceLockError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}