{"metadata":{"role":"collection","roleHeading":"Framework","externalID":"ConnectSDK","modules":[{"name":"ConnectSDK"}],"title":"ConnectSDK","symbolKind":"module"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/initate-connection"],"title":"Essentials"},{"title":"Models","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]},{"title":"Classes","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogging","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField"]},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"],"title":"Protocols"},{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudBulkErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudFleetErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorCentralHasRetriedConnectingKey","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorIncompatibleModelNumberKey","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorServiceKey","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGURLErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiErrorDomain"],"title":"Variables"},{"title":"Enumerations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError"]}],"sections":[],"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ConnectSDK","type":"text"}]},{"type":"text","text":" provides a set of APIs that allow your apps to scan for ProGlove devices, connect to them, and interact with them."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"introduction-graph.png"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/connectsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk"]}],"hierarchy":{"paths":[[]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralState":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralState"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","role":"symbol","abstract":[{"type":"text","text":"Values representing the current connection state of the peripheral"}],"title":"PGPeripheralState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralState","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgperipheralstate","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError":{"abstract":[{"type":"text","text":"PG pairing barcode generator error codes"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorApiError","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror","navigatorTitle":[{"text":"PGPairingQRGeneratorApiError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError","title":"PGPairingQRGeneratorApiError","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiErrorDomain":{"url":"\/documentation\/connectsdk\/pgfeedbackapierrordomain","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiErrorDomain","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackApiErrorDomain"}],"kind":"symbol","title":"PGFeedbackApiErrorDomain","role":"symbol","abstract":[{"type":"text","text":"The scanner feedback api error domain."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGFeedbackApiErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformation":{"abstract":[{"type":"text","text":"Model representing device information"}],"kind":"symbol","navigatorTitle":[{"text":"PGDeviceInformation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgdeviceinformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDeviceInformation"}],"title":"PGDeviceInformation","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/ConnectSDKVersionStringPtr":{"url":"\/documentation\/connectsdk\/connectsdkversionstringptr","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionStringPtr","kind":"symbol","title":"ConnectSDKVersionStringPtr","role":"symbol","abstract":[{"type":"text","text":"Project version string for ConnectSDK."}],"fragments":[{"kind":"identifier","text":"ConnectSDKVersionStringPtr"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiError":{"role":"symbol","navigatorTitle":[{"text":"PGWearableApiError","kind":"identifier"}],"abstract":[{"type":"text","text":"PG Wearable API error codes"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgwearableapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError","title":"PGWearableApiError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGWearableApiError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManagerDelegate","kind":"identifier"}],"role":"symbol","title":"PGCentralManagerDelegate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","type":"topic","kind":"symbol","url":"\/documentation\/connectsdk\/pgcentralmanagerdelegate","navigatorTitle":[{"text":"PGCentralManagerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"PGCentralManagerDelegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudBulkErrorDomain":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGCloudBulkErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"PGCloudBulkErrorDomain","kind":"identifier"}],"abstract":[{"type":"text","text":"The Bulk Provisioning Error Domain"}],"role":"symbol","title":"PGCloudBulkErrorDomain","url":"\/documentation\/connectsdk\/pgcloudbulkerrordomain","type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudBulkErrorDomain"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGWearableApiErrorDomain":{"url":"\/documentation\/connectsdk\/pgwearableapierrordomain","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiErrorDomain","navigatorTitle":[{"text":"PGWearableApiErrorDomain","kind":"identifier"}],"kind":"symbol","title":"PGWearableApiErrorDomain","role":"symbol","abstract":[{"type":"text","text":"The WearableApi error domain"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGWearableApiErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralErrorCentralHasRetriedConnectingKey":{"url":"\/documentation\/connectsdk\/pgperipheralerrorcentralhasretriedconnectingkey","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorCentralHasRetriedConnectingKey","navigatorTitle":[{"text":"PGPeripheralErrorCentralHasRetriedConnectingKey","kind":"identifier"}],"kind":"symbol","title":"PGPeripheralErrorCentralHasRetriedConnectingKey","role":"symbol","abstract":[{"type":"text","text":"A NSNumber Boolean value indicating if the central has retried connection to this peripheral"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"PGPeripheralErrorCentralHasRetriedConnectingKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"kind":"symbol","title":"PGPeripheral","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}],"url":"\/documentation\/connectsdk\/pgperipheral"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockErrorDomain":{"url":"\/documentation\/connectsdk\/pgdevicelockerrordomain","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockErrorDomain","navigatorTitle":[{"kind":"identifier","text":"PGDeviceLockErrorDomain"}],"kind":"symbol","title":"PGDeviceLockErrorDomain","role":"symbol","abstract":[{"type":"text","text":"Device Lock Error Domain"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGDeviceLockErrorDomain"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLoggingDelegate":{"url":"\/documentation\/connectsdk\/pgloggingdelegate","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate","navigatorTitle":[{"kind":"identifier","text":"PGLoggingDelegate"}],"kind":"symbol","title":"PGLoggingDelegate","role":"symbol","abstract":[{"type":"text","text":"The logging class delegate protocol"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGLoggingDelegate"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGURLErrorDomain":{"url":"\/documentation\/connectsdk\/pgurlerrordomain","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGURLErrorDomain","navigatorTitle":[{"kind":"identifier","text":"PGURLErrorDomain"}],"kind":"symbol","title":"PGURLErrorDomain","role":"symbol","abstract":[{"type":"text","text":"The URL Request Error Domain"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGURLErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel","title":"PGPairingQRGeneratorErrorCorrectionLevel","abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralErrorServiceKey":{"url":"\/documentation\/connectsdk\/pgperipheralerrorservicekey","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorServiceKey","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralErrorServiceKey"}],"kind":"symbol","title":"PGPeripheralErrorServiceKey","role":"symbol","abstract":[{"text":"The UUID string of the service the error occurred on","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"PGPeripheralErrorServiceKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGManagerState"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","abstract":[{"type":"text","text":"Represents the current state of a PGManager."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"title":"PGManagerState","kind":"symbol","url":"\/documentation\/connectsdk\/pgmanagerstate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"title":"PGCommandParams","abstract":[{"type":"text","text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PGCommandParams","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgcommandparams","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"navigatorTitle":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgperipheraldelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate","title":"PGPeripheralDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","type":"topic","role":"symbol","title":"PGConfigurationManager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationManager"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationManager"}],"kind":"symbol","abstract":[],"url":"\/documentation\/connectsdk\/pgconfigurationmanager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest":{"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","navigatorTitle":[{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}],"kind":"symbol","title":"PGSetDisplayOrientationRequest","role":"symbol","abstract":[{"type":"text","text":"This object holds the data for updating a screen orientation on a ProGlove display device."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralError":{"title":"PGPeripheralError","abstract":[{"text":"All PG peripheral error codes","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheralerror","role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","navigatorTitle":[{"text":"PGPeripheralError","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManager":{"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanager","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager","navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateManager"}],"kind":"symbol","title":"PGFirmwareUpdateManager","role":"symbol","abstract":[{"type":"text","text":"The protocol for the PGFirmwareUpdateManager."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFirmwareUpdateManager"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionDelegate":{"url":"\/documentation\/connectsdk\/pgcloudconnectiondelegate","type":"topic","title":"PGCloudConnectionDelegate","navigatorTitle":[{"text":"PGCloudConnectionDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudConnectionDelegate","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorDomain":{"navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorDomain"}],"kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrordomain","title":"PGPairingQRGeneratorErrorDomain","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorDomain","abstract":[{"text":"The ParingQRGenerator Error Domain","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGPairingQRGeneratorErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorOptions":{"title":"PGPairingQRGeneratorOptions","abstract":[{"text":"Options for generating QR pairing image","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPairingQRGeneratorOptions"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratoroptions"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult":{"navigatorTitle":[{"text":"PGScannedBarcodeResult","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgscannedbarcoderesult","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"PGScannedBarcodeResult"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","title":"PGScannedBarcodeResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGScannedBarcodeResult","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQR":{"url":"\/documentation\/connectsdk\/pgpairingqr","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR","navigatorTitle":[{"text":"PGPairingQR","kind":"identifier"}],"kind":"symbol","title":"PGPairingQR","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPairingQR","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceLockError":{"type":"topic","navigatorTitle":[{"text":"PGDeviceLockError","kind":"identifier"}],"title":"PGDeviceLockError","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError","kind":"symbol","url":"\/documentation\/connectsdk\/pgdevicelockerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDeviceLockError","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Scanner lock\/unlock error codes"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGTemplateField":{"url":"\/documentation\/connectsdk\/pgtemplatefield","navigatorTitle":[{"text":"PGTemplateField","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class represents the data, that should be displayed in a template field."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField","title":"PGTemplateField","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGTemplateField","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackApiError":{"kind":"symbol","navigatorTitle":[{"text":"PGFeedbackApiError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGFeedbackApiError","kind":"identifier"}],"title":"PGFeedbackApiError","abstract":[],"url":"\/documentation\/connectsdk\/pgfeedbackapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError","role":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackManager"}],"url":"\/documentation\/connectsdk\/pgfeedbackmanager","abstract":[{"text":"Protocol contains all the feedback related methods.","type":"text"}],"title":"PGFeedbackManager","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFeedbackManager"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest":{"type":"topic","title":"PGCaptureImageRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGCaptureImageRequest","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","kind":"symbol","url":"\/documentation\/connectsdk\/pgcaptureimagerequest","abstract":[{"text":"PGCaptureImageRequest","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PGCaptureImageRequest"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus":{"abstract":[{"text":"Connection status to Insight portal","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatus"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus","title":"PGCloudConnectionStatus","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudConnectionStatus","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogFlag":{"navigatorTitle":[{"kind":"identifier","text":"PGLogFlag"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGLogFlag","kind":"identifier"}],"kind":"symbol","title":"PGLogFlag","abstract":[{"type":"text","text":"Log flags, used to determine the severity of a log message"}],"url":"\/documentation\/connectsdk\/pglogflag","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformationRequest":{"title":"PGDeviceInformationRequest","abstract":[{"type":"text","text":"Request used for retreiving Device information"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGDeviceInformationRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGDeviceInformationRequest"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgdeviceinformationrequest","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/ConnectSDKVersionStringObject":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionStringObject","type":"topic","url":"\/documentation\/connectsdk\/connectsdkversionstringobject","kind":"symbol","title":"ConnectSDKVersionStringObject","role":"symbol","abstract":[{"type":"text","text":"Project version string for ConnectSDK."}],"fragments":[{"text":"ConnectSDKVersionStringObject","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateErrorDomain":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"PGFirmwareUpdateErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateErrorDomain","navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateErrorDomain"}],"url":"\/documentation\/connectsdk\/pgfirmwareupdateerrordomain","title":"PGFirmwareUpdateErrorDomain","abstract":[{"text":"Firmware Update Error Domain","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageResolution":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGImageResolution","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGImageResolution"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","type":"topic","title":"PGImageResolution","abstract":[],"url":"\/documentation\/connectsdk\/pgimageresolution","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiError":{"title":"PGDisplayApiError","navigatorTitle":[{"text":"PGDisplayApiError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"PG Display API error codes."}],"url":"\/documentation\/connectsdk\/pgdisplayapierror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDisplayApiError","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","type":"topic","role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"title":"PGPredefinedFeedback","url":"\/documentation\/connectsdk\/pgpredefinedfeedback","abstract":[{"text":"Feedback enum","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPredefinedFeedback","kind":"identifier"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImage":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"PGImage","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGImage","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","url":"\/documentation\/connectsdk\/pgimage","abstract":[{"type":"text","text":"Object containing image data and image options"}],"title":"PGImage"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation":{"role":"symbol","url":"\/documentation\/connectsdk\/pgorientation","navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"kind":"symbol","title":"PGOrientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGOrientation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","abstract":[{"type":"text","text":"Definition of the valid display orientations."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudFleetErrorDomain":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudFleetErrorDomain","url":"\/documentation\/connectsdk\/pgcloudfleeterrordomain","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCloudFleetErrorDomain"}],"kind":"symbol","title":"PGCloudFleetErrorDomain","role":"symbol","abstract":[{"type":"text","text":"The Fleet Provisioning Error Domain"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudFleetErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralErrorIncompatibleModelNumberKey":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorIncompatibleModelNumberKey","type":"topic","url":"\/documentation\/connectsdk\/pgperipheralerrorincompatiblemodelnumberkey","navigatorTitle":[{"text":"PGPeripheralErrorIncompatibleModelNumberKey","kind":"identifier"}],"kind":"symbol","title":"PGPeripheralErrorIncompatibleModelNumberKey","role":"symbol","abstract":[{"text":"The incompatible model number NSString that was discovered for this device","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralErrorIncompatibleModelNumberKey","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayManager":{"abstract":[{"text":"Protocol contains all the display configuration related methods.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDisplayManager"}],"title":"PGDisplayManager","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager","type":"topic","url":"\/documentation\/connectsdk\/pgdisplaymanager","navigatorTitle":[{"text":"PGDisplayManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState":{"url":"\/documentation\/connectsdk\/pgperipherallockstate","type":"topic","abstract":[{"text":"The lock status of the scanner","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","navigatorTitle":[{"text":"PGPeripheralLockState","kind":"identifier"}],"role":"symbol","title":"PGPeripheralLockState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralLockState"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudErrorDomain":{"url":"\/documentation\/connectsdk\/pgclouderrordomain","title":"PGCloudErrorDomain","abstract":[{"text":"The Cloud Error Domain","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PGCloudErrorDomain"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudErrorDomain","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCloudErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScreenData":{"abstract":[{"type":"text","text":"This object holds the data for updating a screen on a ProGlove display device."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGScreenData"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgscreendata","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGScreenData","kind":"identifier"}],"title":"PGScreenData","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/ConnectSDKVersionString":{"url":"\/documentation\/connectsdk\/connectsdkversionstring","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Project version string for ConnectSDK."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionString","type":"topic","title":"ConnectSDKVersionString","fragments":[{"kind":"identifier","text":"ConnectSDKVersionString"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationApiError":{"title":"PGConfigurationApiError","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGConfigurationApiError"}],"abstract":[{"type":"text","text":"PG configuration api error codes"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationapierror","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationApiError"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogLevel":{"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGLogLevel","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/connectsdk\/pgloglevel","title":"PGLogLevel","abstract":[{"type":"text","text":"Log levels, used for filtering log messages"}],"navigatorTitle":[{"text":"PGLogLevel","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/ConnectSDKVersionNumber":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionNumber","type":"topic","url":"\/documentation\/connectsdk\/connectsdkversionnumber","kind":"symbol","title":"ConnectSDKVersionNumber","role":"symbol","abstract":[{"type":"text","text":"Project version number for ConnectSDK."}],"fragments":[{"text":"ConnectSDKVersionNumber","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGLogging":{"title":"PGLogging","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGLogging","kind":"identifier"}],"navigatorTitle":[{"text":"PGLogging","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The logging class for the library"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogging","type":"topic","url":"\/documentation\/connectsdk\/pglogging"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFirmwareUpdateManagerDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"PGFirmwareUpdateManagerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"title":"PGFirmwareUpdateManagerDelegate","kind":"symbol","abstract":[{"type":"text","text":"PGFirmwareUpdateManagerDelegate"},{"type":"text","text":" "},{"text":"The delegate protocol for the PGFirmwareUpdateManager. The delegate must adopt the PGFirmwareUpdateManagerDelegate protocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The methods will provide the firmware update state information."}],"url":"\/documentation\/connectsdk\/pgfirmwareupdatemanagerdelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGManagerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgmanagerdelegate","navigatorTitle":[{"kind":"identifier","text":"PGManagerDelegate"}],"abstract":[{"type":"text","text":"The delegate of a {@link PGManager} object must adopt the "},{"text":"PGManagerDelegate","type":"text"},{"type":"text","text":" protocol. The"},{"type":"text","text":" "},{"text":"single required method indicates the availability of the manager.","type":"text"}],"title":"PGManagerDelegate","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationProfile":{"type":"topic","kind":"symbol","title":"PGConfigurationProfile","role":"symbol","navigatorTitle":[{"text":"PGConfigurationProfile","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgconfigurationprofile","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","abstract":[{"text":"Configuration profile model class.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGConfigurationProfile"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"title":"PGCommand","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"url":"\/documentation\/connectsdk\/pgcommand","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","type":"topic","url":"\/documentation\/connectsdk\/pgmanager","navigatorTitle":[{"kind":"identifier","text":"PGManager"}],"kind":"symbol","title":"PGManager","role":"symbol","abstract":[{"text":"PGManager","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGCentralManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgcentralmanager","role":"symbol","navigatorTitle":[{"text":"PGCentralManager","kind":"identifier"}],"title":"PGCentralManager","abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest":{"type":"topic","abstract":[{"text":"Model representing PGFeedback Request","type":"text"}],"title":"PGFeedbackRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGFeedbackRequest"}],"navigatorTitle":[{"kind":"identifier","text":"PGFeedbackRequest"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","role":"symbol","url":"\/documentation\/connectsdk\/pgfeedbackrequest","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral":{"type":"topic","navigatorTitle":[{"text":"PGMockPeripheral","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","kind":"symbol","url":"\/documentation\/connectsdk\/pgmockperipheral","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGMockPeripheral","kind":"identifier"}],"title":"PGMockPeripheral","abstract":[{"type":"text","text":"A mock peripheral for use in testing"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralErrorDomain":{"abstract":[{"type":"text","text":"The peripheral error domain"}],"role":"symbol","type":"topic","title":"PGPeripheralErrorDomain","url":"\/documentation\/connectsdk\/pgperipheralerrordomain","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGPeripheralErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"PGPeripheralErrorDomain","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorDomain","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayApiErrorDomain":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PGDisplayApiErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","abstract":[{"type":"text","text":"The scanner display api error domain."}],"url":"\/documentation\/connectsdk\/pgdisplayapierrordomain","role":"symbol","title":"PGDisplayApiErrorDomain","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiErrorDomain","navigatorTitle":[{"kind":"identifier","text":"PGDisplayApiErrorDomain"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGRefreshType":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGRefreshType","kind":"identifier"}],"abstract":[{"type":"text","text":"The refresh type, the display should be using when setting a screen."}],"title":"PGRefreshType","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","url":"\/documentation\/connectsdk\/pgrefreshtype","navigatorTitle":[{"text":"PGRefreshType","kind":"identifier"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate":{"kind":"symbol","title":"PGConfigurationManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","role":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate","abstract":[],"type":"topic"},"introduction-graph.png":{"alt":"Introduction","identifier":"introduction-graph.png","type":"image","variants":[{"url":"\/images\/introduction-graph.png","traits":["1x","light"]}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageManager":{"navigatorTitle":[{"text":"PGImageManager","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager","type":"topic","role":"symbol","title":"PGImageManager","kind":"symbol","abstract":[{"text":"PGImageManager protocol containg the methods and properties for retrieving an image using photo feature","type":"text"}],"url":"\/documentation\/connectsdk\/pgimagemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGImageManager"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType","abstract":[{"text":"The button trigger event types","type":"text"}],"title":"PGButtonTriggerEventType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGButtonTriggerEventType","kind":"identifier"}],"navigatorTitle":[{"text":"PGButtonTriggerEventType","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/initate-connection":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/initate-connection","type":"topic","url":"\/documentation\/connectsdk\/initate-connection","kind":"article","title":"Initiate Connection","role":"article","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationErrorDomain":{"type":"topic","title":"PGConfigurationErrorDomain","abstract":[{"type":"text","text":"The ConfigurationApi error domain"}],"url":"\/documentation\/connectsdk\/pgconfigurationerrordomain","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGConfigurationErrorDomain"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGConfigurationErrorDomain"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationErrorDomain"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/initate-connection"],"title":"Essentials"},{"title":"Models","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScreenData"]},{"title":"Classes","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformationRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogging","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQR","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorOptions","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField"]},{"title":"Protocols","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLoggingDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]},{"title":"Variables","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionNumber","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionString","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionStringObject","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/ConnectSDKVersionStringPtr","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudBulkErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudFleetErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFirmwareUpdateErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorCentralHasRetriedConnectingKey","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorIncompatibleModelNumberKey","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralErrorServiceKey","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGURLErrorDomain","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiErrorDomain"]},{"title":"Enumerations","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceLockError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageResolution","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogFlag","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGLogLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralError","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralState","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGRefreshType","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGWearableApiError"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/title","value":"PGPeripheralState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralState\/fragments","value":[{"kind":"identifier","text":"PGPeripheralState"}]},{"op":"replace","value":"PGPairingQRGeneratorApiError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiErrorDomain\/title","value":"PGFeedbackApiErrorDomain","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiErrorDomain\/fragments","value":[{"kind":"identifier","text":"PGFeedbackApiErrorDomain"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/title","value":"PGDeviceInformation"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/fragments","value":[{"kind":"identifier","text":"PGDeviceInformation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/title","value":"PGWearableApiError","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiError\/fragments","value":[{"text":"PGWearableApiError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/title","value":"PGCentralManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGCentralManagerDelegate"}]},{"value":"PGCloudBulkErrorDomain","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudBulkErrorDomain\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PGCloudBulkErrorDomain"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudBulkErrorDomain\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiErrorDomain\/title","value":"PGWearableApiErrorDomain","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGWearableApiErrorDomain\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGWearableApiErrorDomain"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorCentralHasRetriedConnectingKey\/title","op":"replace","value":"PGPeripheralErrorCentralHasRetriedConnectingKey"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorCentralHasRetriedConnectingKey\/fragments","value":[{"kind":"identifier","text":"PGPeripheralErrorCentralHasRetriedConnectingKey"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","value":"PGPeripheral","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"text":"PGPeripheral","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockErrorDomain\/title","value":"PGDeviceLockErrorDomain","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockErrorDomain\/fragments","value":[{"kind":"identifier","text":"PGDeviceLockErrorDomain"}],"op":"replace"},{"op":"replace","value":"PGLoggingDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate\/title"},{"op":"replace","value":[{"text":"PGLoggingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLoggingDelegate\/fragments"},{"value":"PGURLErrorDomain","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGURLErrorDomain\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGURLErrorDomain\/fragments","value":[{"kind":"identifier","text":"PGURLErrorDomain"}],"op":"replace"},{"op":"replace","value":"PGPairingQRGeneratorErrorCorrectionLevel","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments"},{"value":"PGPeripheralErrorServiceKey","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorServiceKey\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorServiceKey\/fragments","op":"replace","value":[{"text":"PGPeripheralErrorServiceKey","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title","op":"replace","value":"PGManagerState"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments","value":[{"text":"PGManagerState","kind":"identifier"}]},{"op":"replace","value":"PGCommandParams","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title"},{"value":[{"kind":"identifier","text":"PGCommandParams"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","op":"replace"},{"value":"PGPeripheralDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/title","op":"replace","value":"PGConfigurationManager"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManager\/fragments","op":"replace","value":[{"text":"PGConfigurationManager","kind":"identifier"}]},{"value":"PGSetDisplayOrientationRequest","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}]},{"value":"PGPeripheralError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralError\/fragments","value":[{"text":"PGPeripheralError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager\/title","value":"PGFirmwareUpdateManager","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManager\/fragments","value":[{"kind":"identifier","text":"PGFirmwareUpdateManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/title","op":"replace","value":"PGCloudConnectionDelegate"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/fragments","op":"replace","value":[{"text":"PGCloudConnectionDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorDomain\/title","value":"PGPairingQRGeneratorErrorDomain"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorDomain\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorDomain"}]},{"value":"PGPairingQRGeneratorOptions","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/title","op":"replace"},{"value":[{"text":"PGPairingQRGeneratorOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorOptions\/fragments","op":"replace"},{"op":"replace","value":"PGScannedBarcodeResult","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PGScannedBarcodeResult"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/fragments"},{"op":"replace","value":"PGPairingQR","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQR\/fragments","value":[{"text":"PGPairingQR","kind":"identifier"}],"op":"replace"},{"value":"PGDeviceLockError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/title","op":"replace"},{"op":"replace","value":[{"text":"PGDeviceLockError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceLockError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/title","value":"PGTemplateField"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/fragments","value":[{"kind":"identifier","text":"PGTemplateField"}]},{"op":"replace","value":"PGFeedbackApiError","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError\/title"},{"value":[{"text":"PGFeedbackApiError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackApiError\/fragments","op":"replace"},{"value":"PGFeedbackManager","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/fragments","value":[{"text":"PGFeedbackManager","kind":"identifier"}]},{"value":"PGCaptureImageRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PGCaptureImageRequest"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/title","value":"PGCloudConnectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGCloudConnectionStatus"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/title","value":"PGLogFlag","op":"replace"},{"value":[{"kind":"identifier","text":"PGLogFlag"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogFlag\/fragments","op":"replace"},{"value":"PGDeviceInformationRequest","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformationRequest\/fragments","value":[{"kind":"identifier","text":"PGDeviceInformationRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateErrorDomain\/title","value":"PGFirmwareUpdateErrorDomain"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateErrorDomain\/fragments","op":"replace","value":[{"text":"PGFirmwareUpdateErrorDomain","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/title","value":"PGImageResolution","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageResolution\/fragments","value":[{"kind":"identifier","text":"PGImageResolution"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/title","op":"replace","value":"PGDisplayApiError"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiError\/fragments","op":"replace","value":[{"text":"PGDisplayApiError","kind":"identifier"}]},{"value":"PGPredefinedFeedback","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments","op":"replace","value":[{"text":"PGPredefinedFeedback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/title","value":"PGImage"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/fragments","value":[{"kind":"identifier","text":"PGImage"}],"op":"replace"},{"value":"PGOrientation","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/fragments","value":[{"text":"PGOrientation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudFleetErrorDomain\/title","value":"PGCloudFleetErrorDomain"},{"op":"replace","value":[{"text":"PGCloudFleetErrorDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudFleetErrorDomain\/fragments"},{"value":"PGPeripheralErrorIncompatibleModelNumberKey","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorIncompatibleModelNumberKey\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorIncompatibleModelNumberKey\/fragments","op":"replace","value":[{"kind":"identifier","text":"PGPeripheralErrorIncompatibleModelNumberKey"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager\/title","value":"PGDisplayManager","op":"replace"},{"op":"replace","value":[{"text":"PGDisplayManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager\/fragments"},{"value":"PGPeripheralLockState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/fragments","value":[{"kind":"identifier","text":"PGPeripheralLockState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudErrorDomain\/title","value":"PGCloudErrorDomain","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudErrorDomain\/fragments","op":"replace","value":[{"text":"PGCloudErrorDomain","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/title","value":"PGScreenData","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScreenData\/fragments","value":[{"kind":"identifier","text":"PGScreenData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/title","value":"PGConfigurationApiError"},{"value":[{"kind":"identifier","text":"PGConfigurationApiError"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationApiError\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/title","value":"PGLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogLevel\/fragments","value":[{"kind":"identifier","text":"PGLogLevel"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogging\/title","value":"PGLogging","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGLogging\/fragments","value":[{"kind":"identifier","text":"PGLogging"}]},{"value":"PGFirmwareUpdateManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"PGFirmwareUpdateManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFirmwareUpdateManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/title","value":"PGManagerDelegate"},{"value":[{"kind":"identifier","text":"PGManagerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/title","op":"replace","value":"PGConfigurationProfile"},{"value":[{"kind":"identifier","text":"PGConfigurationProfile"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/fragments"},{"value":"PGCommand","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments","op":"replace","value":[{"text":"PGCommand","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/title","op":"replace","value":"PGManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/fragments","value":[{"text":"PGManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","op":"replace","value":"PGCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"kind":"identifier","text":"PGCentralManager"}]},{"op":"replace","value":"PGFeedbackRequest","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/title"},{"value":[{"kind":"identifier","text":"PGFeedbackRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/fragments"},{"op":"replace","value":"PGMockPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/fragments","value":[{"kind":"identifier","text":"PGMockPeripheral"}]},{"value":"PGPeripheralErrorDomain","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorDomain\/title"},{"value":[{"kind":"identifier","text":"PGPeripheralErrorDomain"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralErrorDomain\/fragments"},{"value":"PGDisplayApiErrorDomain","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiErrorDomain\/title"},{"op":"replace","value":[{"text":"PGDisplayApiErrorDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayApiErrorDomain\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/title","value":"PGRefreshType"},{"value":[{"kind":"identifier","text":"PGRefreshType"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGRefreshType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/title","value":"PGConfigurationManagerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/title","value":"PGImageManager","op":"replace"},{"value":[{"kind":"identifier","text":"PGImageManager"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/title","value":"PGButtonTriggerEventType"},{"op":"replace","value":[{"text":"PGButtonTriggerEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationErrorDomain\/title","value":"PGConfigurationErrorDomain"},{"value":[{"text":"PGConfigurationErrorDomain","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationErrorDomain\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}