{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGOrientation","preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"PGSetDisplayOrientationRequest object","type":"text"}]}],"name":"orientation"}]}],"metadata":{"title":"init(orientation:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation","text":"PGOrientation","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest(im)initWithOrientation:","role":"symbol","symbolKind":"init","navigatorTitle":[{"text":"initWithOrientation:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Convenience init used to initiate PGSetDisplayOrientationRequest with a selected orientation."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/init(orientation:)"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/init(orientation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/init(orientation:)"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest":{"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest","navigatorTitle":[{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}],"kind":"symbol","title":"PGSetDisplayOrientationRequest","role":"symbol","abstract":[{"type":"text","text":"This object holds the data for updating a screen orientation on a ProGlove display device."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGSetDisplayOrientationRequest","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest/init(orientation:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PGOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation"},{"kind":"text","text":")"}],"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/init(orientation:)","navigatorTitle":[{"kind":"identifier","text":"initWithOrientation:"}],"abstract":[{"type":"text","text":"Convenience init used to initiate PGSetDisplayOrientationRequest with a selected orientation."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/init(orientation:)","type":"topic","title":"init(orientation:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation":{"role":"symbol","url":"\/documentation\/connectsdk\/pgorientation","navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"kind":"symbol","title":"PGOrientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGOrientation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","abstract":[{"type":"text","text":"Definition of the valid display orientations."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithOrientation:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOrientation:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","text":"PGOrientation"},{"text":") ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/title","op":"replace","value":"PGSetDisplayOrientationRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/fragments","value":[{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1init(orientation:)\/title","value":"initWithOrientation:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1init(orientation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOrientation:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/title","value":"PGOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/fragments","value":[{"text":"PGOrientation","kind":"identifier"}]}]}]}