{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/orientation","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/orientation"]},{"paths":["\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/orientation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The orientation to be set on a connected device.","type":"text"}],"metadata":{"modules":[{"name":"ConnectSDK"}],"title":"orientation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation","text":"PGOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"orientation"}],"roleHeading":"Instance Property","externalID":"c:@M@ConnectSDK@objc(cs)PGSetDisplayOrientationRequest(py)orientation","role":"symbol","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation"},{"text":": ","kind":"text"},{"text":"PGOrientation","preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest"]]},"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest/orientation":{"abstract":[{"text":"The orientation to be set on a connected device.","type":"text"}],"navigatorTitle":[{"text":"orientation","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation","text":"PGOrientation","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest\/orientation","title":"orientation","kind":"symbol","url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest\/orientation","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGSetDisplayOrientationRequest":{"url":"\/documentation\/connectsdk\/pgsetdisplayorientationrequest","kind":"symbol","abstract":[{"type":"text","text":"This object holds the data for updating a screen orientation on a ProGlove display device."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"navigatorTitle":[{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"type":"topic","title":"PGSetDisplayOrientationRequest","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGSetDisplayOrientationRequest"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGOrientation":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","url":"\/documentation\/connectsdk\/pgorientation","navigatorTitle":[{"kind":"identifier","text":"PGOrientation"}],"type":"topic","kind":"symbol","title":"PGOrientation","role":"symbol","abstract":[{"type":"text","text":"Definition of the valid display orientations."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGOrientation","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"orientation"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"orientation"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGOrientation","text":"PGOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGOrientation"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"orientation","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1orientation\/title"},{"value":[{"text":"orientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest~1orientation\/fragments"},{"value":"PGSetDisplayOrientationRequest","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGSetDisplayOrientationRequest\/fragments","value":[{"kind":"identifier","text":"PGSetDisplayOrientationRequest"}],"op":"replace"},{"value":"PGOrientation","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGOrientation\/fragments","value":[{"kind":"identifier","text":"PGOrientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}