{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/state","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"State of the PGManager"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"state","navigatorTitle":[{"kind":"identifier","text":"state"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ConnectSDK"}],"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGManager(py)state","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGManagerState","text":"PGManagerState"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmanager\/state"]},{"paths":["\/documentation\/connectsdk\/pgmanager\/state"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"text":"PGManagerState","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","preciseIdentifier":"c:@M@ConnectSDK@E@PGManagerState"},{"text":" { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"The current state of the manager, initially set to ","type":"text"},{"text":"PGManagerStateUnknown","type":"text"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Updates are provided by required delegate method ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate\/managerDidUpdateState(_:)"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager","kind":"symbol","role":"symbol","abstract":[{"text":"PGManager","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGManager","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgmanager","title":"PGManager","type":"topic","navigatorTitle":[{"text":"PGManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerState":{"kind":"symbol","type":"topic","role":"symbol","title":"PGManagerState","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","abstract":[{"type":"text","text":"Represents the current state of a PGManager."}],"navigatorTitle":[{"text":"PGManagerState","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGManagerState"}],"url":"\/documentation\/connectsdk\/pgmanagerstate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManager/state":{"url":"\/documentation\/connectsdk\/pgmanager\/state","navigatorTitle":[{"kind":"identifier","text":"state"}],"abstract":[{"text":"State of the PGManager","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PGManagerState","preciseIdentifier":"c:@M@ConnectSDK@E@PGManagerState","kind":"typeIdentifier"}],"title":"state","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManager\/state"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGManagerDelegate/managerDidUpdateState(_:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerDelegate\/managerDidUpdateState(_:)","url":"\/documentation\/connectsdk\/pgmanagerdelegate\/managerdidupdatestate(_:)","navigatorTitle":[{"text":"managerDidUpdateState:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"managerDidUpdateState(_:)","abstract":[{"text":"centralManagerDidUpdateState:","type":"text"}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"managerDidUpdateState"},{"text":"(","kind":"text"},{"text":"PGManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGManager"},{"text":")","kind":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"state"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"state","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGManagerState","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGManagerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGManagerState"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/title","value":"PGManager","op":"replace"},{"value":[{"kind":"identifier","text":"PGManager"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager\/fragments"},{"value":"PGManagerState","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerState\/fragments","value":[{"kind":"identifier","text":"PGManagerState"}],"op":"replace"},{"value":"state","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager~1state\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"state"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManager~1state\/fragments"},{"value":"managerDidUpdateState:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate~1managerDidUpdateState(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGManagerDelegate~1managerDidUpdateState(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"managerDidUpdateState:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}