{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/h"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/h"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/H"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel"]]},"metadata":{"externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel@PGPairingQRGeneratorErrorCorrectionLevelH","role":"symbol","roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelH","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"H"}],"title":"PGPairingQRGeneratorErrorCorrectionLevel.H","symbolKind":"case"},"abstract":[{"type":"text","text":"Level H, 30% error correction capability"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"H"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"abstract":[{"text":"The PG Pairing QR error correction level","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","title":"PGPairingQRGeneratorErrorCorrectionLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/H":{"abstract":[{"type":"text","text":"Level H, 30% error correction capability"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/H","title":"PGPairingQRGeneratorErrorCorrectionLevel.H","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"H"}],"navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelH","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/h"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PGPairingQRGeneratorErrorCorrectionLevelH","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelH","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelH"}],"languages":["occ"]}]},"op":"replace"},{"value":"PGPairingQRGeneratorErrorCorrectionLevel","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title"},{"value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments","op":"replace"},{"value":"PGPairingQRGeneratorErrorCorrectionLevelH","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1H\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1H\/fragments","value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelH","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}