{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"L"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/l"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/l"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/L","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Level L, 7% error correction capability"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"L"}],"title":"PGPairingQRGeneratorErrorCorrectionLevel.L","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel@PGPairingQRGeneratorErrorCorrectionLevelL","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelL"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"role":"symbol","title":"PGPairingQRGeneratorErrorCorrectionLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/L":{"role":"symbol","title":"PGPairingQRGeneratorErrorCorrectionLevel.L","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"L"}],"abstract":[{"type":"text","text":"Level L, 7% error correction capability"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/L","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelL"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/l"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PGPairingQRGeneratorErrorCorrectionLevelL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelL"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelL"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title","value":"PGPairingQRGeneratorErrorCorrectionLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1L\/title","value":"PGPairingQRGeneratorErrorCorrectionLevelL"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1L\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelL"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}