{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/M","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel"]]},"variants":[{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/m"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/m"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","modules":[{"name":"ConnectSDK"}],"roleHeading":"Case","externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel@PGPairingQRGeneratorErrorCorrectionLevelM","title":"PGPairingQRGeneratorErrorCorrectionLevel.M","navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelM","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"M"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"M"}]}],"kind":"declarations"}],"abstract":[{"text":"Level M, 15% error correction capability","type":"text"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/M":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/m","type":"topic","kind":"symbol","abstract":[{"text":"Level M, 15% error correction capability","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/M","title":"PGPairingQRGeneratorErrorCorrectionLevel.M","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelM"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"M"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel","title":"PGPairingQRGeneratorErrorCorrectionLevel","abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGPairingQRGeneratorErrorCorrectionLevelM","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelM","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelM"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1M\/title","op":"replace","value":"PGPairingQRGeneratorErrorCorrectionLevelM"},{"value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelM","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1M\/fragments"},{"value":"PGPairingQRGeneratorErrorCorrectionLevel","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title","op":"replace"},{"value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}