{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/Q","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel"]]},"abstract":[{"text":"Level Q, 25% error correction capability","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Q","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorErrorCorrectionLevel@PGPairingQRGeneratorErrorCorrectionLevelQ","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelQ","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Q"}],"modules":[{"name":"ConnectSDK"}],"title":"PGPairingQRGeneratorErrorCorrectionLevel.Q"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/q"]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/q"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel","title":"PGPairingQRGeneratorErrorCorrectionLevel","abstract":[{"type":"text","text":"The PG Pairing QR error correction level"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel","navigatorTitle":[{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorErrorCorrectionLevel","kind":"identifier"}],"type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorErrorCorrectionLevel/Q":{"abstract":[{"text":"Level Q, 25% error correction capability","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorErrorCorrectionLevel\/Q","url":"\/documentation\/connectsdk\/pgpairingqrgeneratorerrorcorrectionlevel\/q","title":"PGPairingQRGeneratorErrorCorrectionLevel.Q","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Q"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelQ"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PGPairingQRGeneratorErrorCorrectionLevelQ","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelQ","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"PGPairingQRGeneratorErrorCorrectionLevelQ","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/title","value":"PGPairingQRGeneratorErrorCorrectionLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1Q\/title","value":"PGPairingQRGeneratorErrorCorrectionLevelQ"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorErrorCorrectionLevel~1Q\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorErrorCorrectionLevelQ"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}