{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateBatteryLevel(_:)"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]]},"kind":"symbol","metadata":{"title":"peripheralDidUpdateBatteryLevel(_:)","modules":[{"name":"ConnectSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheralDidUpdateBatteryLevel"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate(im)peripheralDidUpdateBatteryLevel:","navigatorTitle":[{"kind":"identifier","text":"peripheralDidUpdateBatteryLevel:"}],"required":true,"role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatebatterylevel(_:)"]},{"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatebatterylevel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The Scanner peripheral updated its battery level"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheralDidUpdateBatteryLevel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The Scanner peripheral"}],"type":"paragraph"}],"name":"peripheral"}]}],"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheralDidUpdateBatteryLevel(_:)":{"required":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateBatteryLevel(_:)","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatebatterylevel(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheralDidUpdateBatteryLevel"},{"kind":"text","text":"("},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The Scanner peripheral updated its battery level"}],"title":"peripheralDidUpdateBatteryLevel(_:)","type":"topic","navigatorTitle":[{"text":"peripheralDidUpdateBatteryLevel:","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"url":"\/documentation\/connectsdk\/pgperipheraldelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate","title":"PGPeripheralDelegate","abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"peripheralDidUpdateBatteryLevel:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"peripheralDidUpdateBatteryLevel:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"peripheralDidUpdateBatteryLevel:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateBatteryLevel(_:)\/title","op":"replace","value":"peripheralDidUpdateBatteryLevel:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateBatteryLevel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheralDidUpdateBatteryLevel:"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title","op":"replace","value":"PGPeripheralDelegate"},{"value":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments"},{"op":"replace","value":"PGPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"text":"PGPeripheral","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}