{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheralDidUpdateName","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanner peripheral"}]}],"name":"peripheral"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateName(_:)"},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","title":"peripheralDidUpdateName(_:)","externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate(im)peripheralDidUpdateName:","modules":[{"name":"ConnectSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"peripheralDidUpdateName:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheralDidUpdateName"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"The PG peripheral updated its name"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatename(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatename(_:)"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"url":"\/documentation\/connectsdk\/pgperipheraldelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate","title":"PGPeripheralDelegate","abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheralDidUpdateName(_:)":{"abstract":[{"text":"The PG peripheral updated its name","type":"text"}],"title":"peripheralDidUpdateName(_:)","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheraldidupdatename(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheralDidUpdateName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheralDidUpdateName(_:)","navigatorTitle":[{"kind":"identifier","text":"peripheralDidUpdateName:"}],"kind":"symbol","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"peripheralDidUpdateName:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"peripheralDidUpdateName:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"peripheralDidUpdateName:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title","value":"PGPeripheralDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateName(_:)\/title","value":"peripheralDidUpdateName:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheralDidUpdateName(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"peripheralDidUpdateName:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","op":"replace","value":"PGPeripheral"},{"value":[{"kind":"identifier","text":"PGPeripheral"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","op":"replace"}]}]}