{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanBarcodeWith:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanbarcodewith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanbarcodewith:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The PG peripheral scanned a barcode"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"text":"didScanBarcodeWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGScannedBarcodeResult","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"peripheral","content":[{"inlineContent":[{"text":"The PG peripheral","type":"text"}],"type":"paragraph"}]},{"name":"data","content":[{"inlineContent":[{"text":"The scanned data","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"navigatorTitle":[{"text":"peripheral:didScanBarcodeWith:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanBarcodeWith"},{"kind":"text","text":": "},{"text":"PGScannedBarcodeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult"},{"text":")","kind":"text"}],"title":"peripheral(_:didScanBarcodeWith:)","externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate(im)peripheral:didScanBarcodeWith:","symbolKind":"method","role":"symbol","modules":[{"name":"ConnectSDK"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"url":"\/documentation\/connectsdk\/pgperipheraldelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate","title":"PGPeripheralDelegate","abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didScanBarcodeWith:)":{"url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanbarcodewith:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanBarcodeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGScannedBarcodeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"peripheral:didScanBarcodeWith:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanBarcodeWith:)","abstract":[{"type":"text","text":"The PG peripheral scanned a barcode"}],"kind":"symbol","title":"peripheral(_:didScanBarcodeWith:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGScannedBarcodeResult"}],"navigatorTitle":[{"text":"PGScannedBarcodeResult","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgscannedbarcoderesult","title":"PGScannedBarcodeResult","abstract":[{"type":"text","text":"PGScannedBarcodeResult"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"peripheral:didScanBarcodeWith:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"peripheral:didScanBarcodeWith:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"peripheral:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didScanBarcodeWith:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","text":"PGScannedBarcodeResult"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"PGPeripheralDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PGPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"text":"PGPeripheral","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanBarcodeWith:)\/title","value":"peripheral:didScanBarcodeWith:"},{"value":[{"text":"- ","kind":"text"},{"text":"peripheral:didScanBarcodeWith:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanBarcodeWith:)\/fragments"},{"value":"PGScannedBarcodeResult","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/title"},{"value":[{"kind":"identifier","text":"PGScannedBarcodeResult"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/fragments","op":"replace"}]}]}