{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"errorScanningBarcode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"peripheral","content":[{"inlineContent":[{"text":"The Scanner peripheral","type":"text"}],"type":"paragraph"}]},{"name":"errorScanningBarcode","content":[{"inlineContent":[{"type":"text","text":"The error encountered, in the "},{"type":"codeVoice","code":"PGPeripheralErrorDomain"},{"type":"text","text":" domain"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:errorscanningbarcode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:errorscanningbarcode:)"]}],"abstract":[{"text":"The PG peripheral encountered an error when scanning a barcode","type":"text"}],"metadata":{"roleHeading":"Instance Method","title":"peripheral(_:errorScanningBarcode:)","externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate(im)peripheral:errorScanningBarcode:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"peripheral:errorScanningBarcode:"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral"},{"text":", ","kind":"text"},{"text":"errorScanningBarcode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"modules":[{"name":"ConnectSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:errorScanningBarcode:)"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"url":"\/documentation\/connectsdk\/pgperipheraldelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate","title":"PGPeripheralDelegate","abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:errorScanningBarcode:)":{"url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:errorscanningbarcode:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"peripheral:errorScanningBarcode:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorScanningBarcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"role":"symbol","title":"peripheral(_:errorScanningBarcode:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:errorScanningBarcode:)","abstract":[{"text":"The PG peripheral encountered an error when scanning a barcode","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"peripheral:errorScanningBarcode:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:errorScanningBarcode:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"peripheral:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorScanningBarcode:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"errorScanningBarcode"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"PGPeripheral","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title"},{"value":[{"kind":"identifier","text":"PGPeripheral"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments"},{"op":"replace","value":"PGPeripheralDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title"},{"value":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:errorScanningBarcode:)\/title","value":"peripheral:errorScanningBarcode:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:errorScanningBarcode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:errorScanningBarcode:"}],"op":"replace"}]}]}