{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]]},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanauthenticationbarocodewith:isvalid:)"]},{"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanauthenticationbarocodewith:isvalid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The PG peripheral has scanned a barcode while locked","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"peripheral:didScanAuthenticationBarocodeWith:isValid:"}],"symbolKind":"method","modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Method","role":"symbol","title":"peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate(im)peripheral:didScanAuthenticationBarocodeWith:isValid:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanAuthenticationBarocodeWith"},{"kind":"text","text":": "},{"text":"PGScannedBarcodeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isValid"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PGPeripheral","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanAuthenticationBarocodeWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","text":"PGScannedBarcodeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult"},{"kind":"text","text":", "},{"text":"isValid","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"peripheral","content":[{"type":"paragraph","inlineContent":[{"text":"The PG peripheral","type":"text"}]}]},{"name":"didScanAuthenticationBarocodeWith","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanned barcode"}]}]},{"name":"isValid","content":[{"inlineContent":[{"type":"text","text":"Is the scanned barcode valid"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"kind":"identifier","text":"PGPeripheral"}],"title":"PGPeripheral","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheral","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didScanAuthenticationBarocodeWith:isValid:)":{"title":"peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","kind":"symbol","abstract":[{"type":"text","text":"The PG peripheral has scanned a barcode while locked"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didScanAuthenticationBarocodeWith:isValid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didScanAuthenticationBarocodeWith"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult","kind":"typeIdentifier","text":"PGScannedBarcodeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isValid"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"peripheral:didScanAuthenticationBarocodeWith:isValid:","kind":"identifier"}],"type":"topic","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didscanauthenticationbarocodewith:isvalid:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}],"url":"\/documentation\/connectsdk\/pgperipheraldelegate","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"title":"PGPeripheralDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheralDelegate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGScannedBarcodeResult":{"abstract":[{"text":"PGScannedBarcodeResult","type":"text"}],"url":"\/documentation\/connectsdk\/pgscannedbarcoderesult","kind":"symbol","type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGScannedBarcodeResult"}],"navigatorTitle":[{"kind":"identifier","text":"PGScannedBarcodeResult"}],"title":"PGScannedBarcodeResult","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"peripheral:didScanAuthenticationBarocodeWith:isValid:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"peripheral:didScanAuthenticationBarocodeWith:isValid:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"peripheral:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral"},{"kind":"text","text":" *) "},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didScanAuthenticationBarocodeWith:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGScannedBarcodeResult","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGScannedBarcodeResult","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGScannedBarcodeResult"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isValid","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","value":"PGPeripheral"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"kind":"identifier","text":"PGPeripheral"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanAuthenticationBarocodeWith:isValid:)\/title","value":"peripheral:didScanAuthenticationBarocodeWith:isValid:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"peripheral:didScanAuthenticationBarocodeWith:isValid:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didScanAuthenticationBarocodeWith:isValid:)\/fragments"},{"value":"PGPeripheralDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}]},{"value":"PGScannedBarcodeResult","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGScannedBarcodeResult\/fragments","value":[{"text":"PGScannedBarcodeResult","kind":"identifier"}]}]}]}