{"abstract":[{"type":"text","text":"The PG peripheral lock state did change"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didChangeLockState:error:)","interfaceLanguage":"swift"},"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":", ","kind":"text"},{"text":"didChangeLockState","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","text":"PGPeripheralLockState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"peripheral:didChangeLockState:error:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"ConnectSDK"}],"title":"peripheral(_:didChangeLockState:error:)","externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate(im)peripheral:didChangeLockState:error:","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didchangelockstate:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didchangelockstate:error:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeLockState"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"lockState"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","text":"PGPeripheralLockState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"peripheral","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The PG peripheral"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The peripheral lock state"}]}],"name":"lockState"},{"content":[{"inlineContent":[{"type":"text","text":"The peripheral state change error"}],"type":"paragraph"}],"name":"error"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState":{"type":"topic","abstract":[{"text":"The lock status of the scanner","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgperipherallockstate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPeripheralLockState","kind":"identifier"}],"title":"PGPeripheralLockState","navigatorTitle":[{"text":"PGPeripheralLockState","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"url":"\/documentation\/connectsdk\/pgperipheraldelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate","title":"PGPeripheralDelegate","abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didChangeLockState:error:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeLockState"},{"kind":"text","text":": "},{"text":"PGPeripheralLockState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"peripheral:didChangeLockState:error:"}],"abstract":[{"text":"The PG peripheral lock state did change","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didChangeLockState:error:)","kind":"symbol","title":"peripheral(_:didChangeLockState:error:)","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didchangelockstate:error:)","type":"topic","required":true,"role":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"peripheral:didChangeLockState:error:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didChangeLockState:error:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"peripheral:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},{"kind":"text","text":" *) "},{"text":"peripheral","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChangeLockState:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","text":"PGPeripheralLockState"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"lockState"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PGPeripheral","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","op":"replace","value":[{"text":"PGPeripheral","kind":"identifier"}]},{"value":"PGPeripheralLockState","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/fragments","value":[{"text":"PGPeripheralLockState","kind":"identifier"}]},{"value":"PGPeripheralDelegate","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments","op":"replace","value":[{"text":"PGPeripheralDelegate","kind":"identifier"}]},{"value":"peripheral:didChangeLockState:error:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didChangeLockState:error:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didChangeLockState:error:"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didChangeLockState:error:)\/fragments"}]}]}