{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didSendButtonTriggerEvent:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didsendbuttontriggerevent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didsendbuttontriggerevent:)"]}],"abstract":[{"type":"text","text":"The Scanner peripheral sent a button trigger event"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSendButtonTriggerEvent"},{"kind":"text","text":" "},{"text":"buttonTriggerEvent","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PGButtonTriggerEventType","preciseIdentifier":"c:@M@ConnectSDK@E@PGButtonTriggerEventType","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The Scanner peripheral","type":"text"}],"type":"paragraph"}],"name":"peripheral"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The button trigger event type","type":"text"}]}],"name":"buttonTriggerEvent"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"ConnectSDK"}],"required":true,"title":"peripheral(_:didSendButtonTriggerEvent:)","externalID":"c:@M@ConnectSDK@objc(pl)PGPeripheralDelegate(im)peripheral:didSendButtonTriggerEvent:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSendButtonTriggerEvent"},{"kind":"text","text":": "},{"text":"PGButtonTriggerEventType","preciseIdentifier":"c:@M@ConnectSDK@E@PGButtonTriggerEventType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"peripheral:didSendButtonTriggerEvent:","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate":{"navigatorTitle":[{"text":"PGPeripheralDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/connectsdk\/pgperipheraldelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The delegate protocol for the PG peripheral"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate","title":"PGPeripheralDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPeripheralDelegate","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"kind":"symbol","title":"PGPeripheral","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}],"url":"\/documentation\/connectsdk\/pgperipheral"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGButtonTriggerEventType":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgbuttontriggereventtype","role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType","abstract":[{"text":"The button trigger event types","type":"text"}],"title":"PGButtonTriggerEventType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGButtonTriggerEventType","kind":"identifier"}],"navigatorTitle":[{"text":"PGButtonTriggerEventType","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralDelegate/peripheral(_:didSendButtonTriggerEvent:)":{"kind":"symbol","url":"\/documentation\/connectsdk\/pgperipheraldelegate\/peripheral(_:didsendbuttontriggerevent:)","required":true,"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralDelegate\/peripheral(_:didSendButtonTriggerEvent:)","abstract":[{"type":"text","text":"The Scanner peripheral sent a button trigger event"}],"title":"peripheral(_:didSendButtonTriggerEvent:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didSendButtonTriggerEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PGButtonTriggerEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGButtonTriggerEventType"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"peripheral:didSendButtonTriggerEvent:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"peripheral:didSendButtonTriggerEvent:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"peripheral:didSendButtonTriggerEvent:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"peripheral:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","text":"PGPeripheral","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSendButtonTriggerEvent:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"PGButtonTriggerEventType","preciseIdentifier":"c:@M@ConnectSDK@E@PGButtonTriggerEventType","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGButtonTriggerEventType"},{"kind":"text","text":") "},{"text":"buttonTriggerEvent","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/title","value":"PGPeripheralDelegate"},{"value":[{"kind":"identifier","text":"PGPeripheralDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","value":"PGPeripheral","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"kind":"identifier","text":"PGPeripheral"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/title","value":"PGButtonTriggerEventType","op":"replace"},{"value":[{"text":"PGButtonTriggerEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGButtonTriggerEventType\/fragments"},{"op":"replace","value":"peripheral:didSendButtonTriggerEvent:","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didSendButtonTriggerEvent:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralDelegate~1peripheral(_:didSendButtonTriggerEvent:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"peripheral:didSendButtonTriggerEvent:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}