{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didFailToLoadNewConfiguration(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"New configuration has failed to load"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didfailtoloadnewconfiguration(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didfailtoloadnewconfiguration(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didFailToLoadNewConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Error that has occurred during the loading process","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManagerDelegate(im)didFailToLoadNewConfiguration:","title":"didFailToLoadNewConfiguration(_:)","symbolKind":"method","navigatorTitle":[{"text":"didFailToLoadNewConfiguration:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didFailToLoadNewConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"modules":[{"name":"ConnectSDK"}]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate/didFailToLoadNewConfiguration(_:)":{"type":"topic","abstract":[{"text":"New configuration has failed to load","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didFailToLoadNewConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"didFailToLoadNewConfiguration:"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didFailToLoadNewConfiguration(_:)","title":"didFailToLoadNewConfiguration(_:)","kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didfailtoloadnewconfiguration(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate":{"abstract":[],"navigatorTitle":[{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"title":"PGConfigurationManagerDelegate","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate","role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"didFailToLoadNewConfiguration:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFailToLoadNewConfiguration:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didFailToLoadNewConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didFailToLoadNewConfiguration(_:)\/title","op":"replace","value":"didFailToLoadNewConfiguration:"},{"value":[{"text":"- ","kind":"text"},{"text":"didFailToLoadNewConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didFailToLoadNewConfiguration(_:)\/fragments"},{"op":"replace","value":"PGConfigurationManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}]}]}]}