{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didLoadNewConfiguration(_:)"},"sections":[],"kind":"symbol","metadata":{"title":"didLoadNewConfiguration(_:)","required":true,"externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManagerDelegate(im)didLoadNewConfiguration:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didLoadNewConfiguration"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didLoadNewConfiguration:"}]},"variants":[{"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didloadnewconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didloadnewconfiguration(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didLoadNewConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"configurationId","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"configurationId","content":[{"type":"paragraph","inlineContent":[{"text":"Configuration ID for the new configuration that has been loaded","type":"text"}]}]}],"kind":"parameters"}],"abstract":[{"text":"New configuration has been loaded","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate":{"abstract":[],"navigatorTitle":[{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"title":"PGConfigurationManagerDelegate","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate","role":"symbol","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate/didLoadNewConfiguration(_:)":{"type":"topic","abstract":[{"text":"New configuration has been loaded","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didLoadNewConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"didLoadNewConfiguration:"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/didLoadNewConfiguration(_:)","title":"didLoadNewConfiguration(_:)","kind":"symbol","url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/didloadnewconfiguration(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"didLoadNewConfiguration:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"didLoadNewConfiguration:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"didLoadNewConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configurationId"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"PGConfigurationManagerDelegate","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/title"},{"value":[{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didLoadNewConfiguration(_:)\/title","value":"didLoadNewConfiguration:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1didLoadNewConfiguration(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didLoadNewConfiguration:","kind":"identifier"}]}]}]}