{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate"]]},"abstract":[{"type":"text","text":"The request to set a profile to a device failed."}],"metadata":{"externalID":"c:@M@ConnectSDK@objc(pl)PGConfigurationManagerDelegate(im)peripheral:didFailToSetConfigurationProfile:error:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"kind":"text","text":"?, "},{"text":"didFailToSetConfigurationProfile","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Method","role":"symbol","required":true,"navigatorTitle":[{"text":"peripheral:didFailToSetConfigurationProfile:error:","kind":"identifier"}],"symbolKind":"method","title":"peripheral(_:didFailToSetConfigurationProfile:error:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didFailToSetConfigurationProfile:error:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/peripheral(_:didfailtosetconfigurationprofile:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/peripheral(_:didfailtosetconfigurationprofile:error:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"peripheral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","text":"PGPeripheral"},{"text":"?, ","kind":"text"},{"text":"didFailToSetConfigurationProfile","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"profile","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The Scanner peripheral if available ","type":"text"},{"type":"codeVoice","code":"PGPeripheral"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"peripheral"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"he profile that is tried to be set to a connected device."}]}],"name":"profile"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error occurred during the request."}]}],"name":"error"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate/peripheral(_:didFailToSetConfigurationProfile:error:)":{"required":true,"url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate\/peripheral(_:didfailtosetconfigurationprofile:error:)","title":"peripheral(_:didFailToSetConfigurationProfile:error:)","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate\/peripheral(_:didFailToSetConfigurationProfile:error:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"didFailToSetConfigurationProfile","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile","text":"PGConfigurationProfile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"peripheral:didFailToSetConfigurationProfile:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"The request to set a profile to a device failed."}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationManagerDelegate":{"role":"symbol","navigatorTitle":[{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGConfigurationManagerDelegate","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgconfigurationmanagerdelegate","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationManagerDelegate","type":"topic","title":"PGConfigurationManagerDelegate"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"kind":"identifier","text":"PGPeripheral"}],"title":"PGPeripheral","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheral","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGConfigurationProfile":{"url":"\/documentation\/connectsdk\/pgconfigurationprofile","navigatorTitle":[{"text":"PGConfigurationProfile","kind":"identifier"}],"title":"PGConfigurationProfile","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGConfigurationProfile","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration profile model class."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"peripheral:didFailToSetConfigurationProfile:error:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"peripheral:didFailToSetConfigurationProfile:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"peripheral:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"typeIdentifier","text":"PGPeripheral","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGPeripheral"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":" "},{"text":"didFailToSetConfigurationProfile:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGConfigurationProfile","kind":"typeIdentifier","text":"PGConfigurationProfile","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGConfigurationProfile"},{"text":" *) ","kind":"text"},{"text":"profile","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1peripheral(_:didFailToSetConfigurationProfile:error:)\/title","op":"replace","value":"peripheral:didFailToSetConfigurationProfile:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate~1peripheral(_:didFailToSetConfigurationProfile:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"peripheral:didFailToSetConfigurationProfile:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/title","value":"PGConfigurationManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationManagerDelegate\/fragments","value":[{"kind":"identifier","text":"PGConfigurationManagerDelegate"}]},{"op":"replace","value":"PGPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"text":"PGPeripheral","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/title","value":"PGConfigurationProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGConfigurationProfile\/fragments","value":[{"text":"PGConfigurationProfile","kind":"identifier"}]}]}]}