{"abstract":[{"type":"text","text":"When set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" this command will clear all queued commands and then queue itself."}],"metadata":{"roleHeading":"Instance Property","title":"replaceQueue","externalID":"c:@M@ConnectSDK@objc(cs)PGCommandParams(py)replaceQueue","role":"symbol","symbolKind":"property","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"replaceQueue"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"replaceQueue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/replaceQueue"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Commands that are already started will not be canceled by this flag.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"This command will be first-in-queue afterwards but that does not guarantee execution of the command."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"It can be canceled by a different command with [replaceQueue] set to YES, too.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(defaults to NO)"}]}]}],"type":"unorderedList"}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/connectsdk\/pgcommandparams\/replacequeue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgcommandparams\/replacequeue"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams/replaceQueue":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams\/replaceQueue","abstract":[{"type":"text","text":"When set to "},{"code":"true","type":"codeVoice"},{"text":" this command will clear all queued commands and then queue itself.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replaceQueue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"replaceQueue","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcommandparams\/replacequeue","title":"replaceQueue","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommandParams":{"type":"topic","abstract":[{"type":"text","text":"Holder for parameter that affect the execution of commands. For example the queueing behaviour."}],"title":"PGCommandParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PGCommandParams","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgcommandparams","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGCommandParams"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommandParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"replaceQueue"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"replaceQueue","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"replaceQueue","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"replaceQueue","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams~1replaceQueue\/title","op":"replace"},{"value":[{"kind":"identifier","text":"replaceQueue"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams~1replaceQueue\/fragments"},{"value":"PGCommandParams","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommandParams\/fragments","op":"replace","value":[{"text":"PGCommandParams","kind":"identifier"}]}]}]}