{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"This method can be used to change the orientation on a connected device."}],"variants":[{"paths":["\/documentation\/connectsdk\/pgdisplaymanager\/setdisplayorientation(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgdisplaymanager\/setdisplayorientation(_:completionhandler:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDisplayOrientation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ConnectSDK@objc(pl)PGDisplayManager(im)setDisplayOrientation:completionHandler:","required":true,"title":"setDisplayOrientation(_:completionHandler:)","symbolKind":"method","navigatorTitle":[{"text":"setDisplayOrientation:completionHandler:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setDisplayOrientation(_:completionHandler:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDisplayOrientation","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"orientationCommand","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","text":"PGCommand","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PGCommand"},{"type":"text","text":" containing "},{"code":"PGSetDisplayOrientationRequest","type":"codeVoice"},{"type":"text","text":" with a concrete orientation."}]}],"name":"orientationCommand"},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler returning an error in case the  request failed.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayManager":{"abstract":[{"text":"Protocol contains all the display configuration related methods.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGDisplayManager"}],"title":"PGDisplayManager","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager","type":"topic","url":"\/documentation\/connectsdk\/pgdisplaymanager","navigatorTitle":[{"text":"PGDisplayManager","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDisplayManager/setDisplayOrientation(_:completionHandler:)":{"type":"topic","url":"\/documentation\/connectsdk\/pgdisplaymanager\/setdisplayorientation(_:completionhandler:)","kind":"symbol","navigatorTitle":[{"text":"setDisplayOrientation:completionHandler:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDisplayOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PGCommand","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"setDisplayOrientation(_:completionHandler:)","abstract":[{"type":"text","text":"This method can be used to change the orientation on a connected device."}],"role":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDisplayManager\/setDisplayOrientation(_:completionHandler:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"title":"PGCommand","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"url":"\/documentation\/connectsdk\/pgcommand","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setDisplayOrientation:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setDisplayOrientation:completionHandler:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setDisplayOrientation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","text":"PGCommand"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"orientationCommand"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager\/title","value":"PGDisplayManager","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager\/fragments","value":[{"kind":"identifier","text":"PGDisplayManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager~1setDisplayOrientation(_:completionHandler:)\/title","op":"replace","value":"setDisplayOrientation:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"setDisplayOrientation:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDisplayManager~1setDisplayOrientation(_:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","op":"replace","value":"PGCommand"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments","value":[{"kind":"identifier","text":"PGCommand"}]}]}]}