{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate\/cloudConnectionStatusDidUpdate(_:error:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudConnectionStatusDidUpdate"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","preciseIdentifier":"c:@M@ConnectSDK@E@PGCloudConnectionStatus","text":"PGCloudConnectionStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Connection status ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","type":"reference"}]}],"name":"status"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"Error that might happend if there is no successfull connection","type":"text"}]}]}],"kind":"parameters"}],"sections":[],"abstract":[{"text":"Cloud connection status for Insight updated","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgcloudconnectiondelegate\/cloudconnectionstatusdidupdate(_:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgcloudconnectiondelegate\/cloudconnectionstatusdidupdate(_:error:)"]}],"metadata":{"navigatorTitle":[{"text":"cloudConnectionStatusDidUpdate:error:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ConnectSDK@objc(pl)PGCloudConnectionDelegate(im)cloudConnectionStatusDidUpdate:error:","modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Method","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudConnectionStatusDidUpdate"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGCloudConnectionStatus","kind":"typeIdentifier","text":"PGCloudConnectionStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"title":"cloudConnectionStatusDidUpdate(_:error:)"},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionDelegate/cloudConnectionStatusDidUpdate(_:error:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudConnectionStatusDidUpdate"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGCloudConnectionStatus","text":"PGCloudConnectionStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"cloudConnectionStatusDidUpdate(_:error:)","role":"symbol","url":"\/documentation\/connectsdk\/pgcloudconnectiondelegate\/cloudconnectionstatusdidupdate(_:error:)","navigatorTitle":[{"text":"cloudConnectionStatusDidUpdate:error:","kind":"identifier"}],"abstract":[{"text":"Cloud connection status for Insight updated","type":"text"}],"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate\/cloudConnectionStatusDidUpdate(_:error:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionStatus":{"abstract":[{"text":"Connection status to Insight portal","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PGCloudConnectionStatus"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgcloudconnectionstatus","title":"PGCloudConnectionStatus","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudConnectionStatus","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCloudConnectionDelegate":{"url":"\/documentation\/connectsdk\/pgcloudconnectiondelegate","type":"topic","title":"PGCloudConnectionDelegate","navigatorTitle":[{"text":"PGCloudConnectionDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCloudConnectionDelegate","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"text":"ProGlove ConnectSDK","type":"text"}]},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","url":"\/documentation\/connectsdk","title":"ConnectSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"cloudConnectionStatusDidUpdate:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cloudConnectionStatusDidUpdate:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"cloudConnectionStatusDidUpdate:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGCloudConnectionStatus","kind":"typeIdentifier","text":"PGCloudConnectionStatus","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCloudConnectionStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate~1cloudConnectionStatusDidUpdate(_:error:)\/title","value":"cloudConnectionStatusDidUpdate:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"cloudConnectionStatusDidUpdate:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate~1cloudConnectionStatusDidUpdate(_:error:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/title","value":"PGCloudConnectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionStatus\/fragments","value":[{"text":"PGCloudConnectionStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/title","value":"PGCloudConnectionDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"PGCloudConnectionDelegate"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCloudConnectionDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}