{"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager\/takeImage(_:completionHandler:)"},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgimagemanager\/takeimage(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgimagemanager\/takeimage(_:completionhandler:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"captureImageCommand","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","text":"PGCommand","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"PGImage","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGImage","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","type":"reference","isActive":true},{"type":"text","text":" to use with "},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","type":"reference","isActive":true}]}],"name":"captureImageCommand"},{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Completion handler that returns "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage"},{"type":"text","text":" or Error"}],"type":"paragraph"}]}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(pl)PGImageManager(im)takeImage:completionHandler:","title":"takeImage(_:completionHandler:)","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"takeImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"PGCommand","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGImage","text":"PGImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"text":"takeImage:completionHandler:","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Take image function that is used to retrieve the image"}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageManager":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager","title":"PGImageManager","navigatorTitle":[{"kind":"identifier","text":"PGImageManager"}],"type":"topic","url":"\/documentation\/connectsdk\/pgimagemanager","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGImageManager"}],"kind":"symbol","abstract":[{"text":"PGImageManager protocol containg the methods and properties for retrieving an image using photo feature","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCaptureImageRequest":{"kind":"symbol","role":"symbol","url":"\/documentation\/connectsdk\/pgcaptureimagerequest","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCaptureImageRequest","abstract":[{"text":"PGCaptureImageRequest","type":"text"}],"navigatorTitle":[{"text":"PGCaptureImageRequest","kind":"identifier"}],"type":"topic","title":"PGCaptureImageRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGCaptureImageRequest"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImage":{"type":"topic","title":"PGImage","abstract":[{"type":"text","text":"Object containing image data and image options"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImage","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PGImage","kind":"identifier"}],"url":"\/documentation\/connectsdk\/pgimage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGImage"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGImageManager/takeImage(_:completionHandler:)":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGImageManager\/takeImage(_:completionHandler:)","title":"takeImage(_:completionHandler:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"takeImage:completionHandler:"}],"type":"topic","url":"\/documentation\/connectsdk\/pgimagemanager\/takeimage(_:completionhandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"takeImage"},{"text":"(","kind":"text"},{"text":"PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"PGImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGImage"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Take image function that is used to retrieve the image"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"symbol","role":"symbol","abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"title":"PGCommand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"takeImage:completionHandler:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"takeImage:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"takeImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","text":"PGCommand"},{"text":" *) ","kind":"text"},{"text":"captureImageCommand","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@ConnectSDK@objc(cs)PGImage#*$objc(cs)NSError)","text":"void (^)(PGImage *, NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/title","value":"PGImageManager"},{"value":[{"kind":"identifier","text":"PGImageManager"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/title","value":"PGCaptureImageRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCaptureImageRequest\/fragments","value":[{"text":"PGCaptureImageRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/title","op":"replace","value":"PGImage"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImage\/fragments","value":[{"text":"PGImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager~1takeImage(_:completionHandler:)\/title","op":"replace","value":"takeImage:completionHandler:"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGImageManager~1takeImage(_:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"takeImage:completionHandler:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","value":"PGCommand"},{"op":"replace","value":[{"kind":"identifier","text":"PGCommand"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}