{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgtemplatefield\/fieldid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgtemplatefield\/fieldid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField\/fieldId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The id of the field that should be filled with [header] and [content]."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"title":"fieldId","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ConnectSDK@objc(cs)PGTemplateField(py)fieldId","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fieldId"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGTemplateField":{"role":"symbol","title":"PGTemplateField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGTemplateField"}],"abstract":[{"type":"text","text":"This class represents the data, that should be displayed in a template field."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGTemplateField"}],"url":"\/documentation\/connectsdk\/pgtemplatefield"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGTemplateField/fieldId":{"role":"symbol","title":"fieldId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"abstract":[{"type":"text","text":"The id of the field that should be filled with [header] and [content]."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGTemplateField\/fieldId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fieldId"}],"url":"\/documentation\/connectsdk\/pgtemplatefield\/fieldid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fieldId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fieldId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"uint32_t","preciseIdentifier":"c:@T@uint32_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldId"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/title","value":"PGTemplateField"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField\/fragments","value":[{"kind":"identifier","text":"PGTemplateField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField~1fieldId\/title","value":"fieldId"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGTemplateField~1fieldId\/fragments","value":[{"kind":"identifier","text":"fieldId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}