{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","text":"PGPeripheralLockState","preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"title":"lockState","navigatorTitle":[{"text":"lockState","kind":"identifier"}],"modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockState"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","kind":"typeIdentifier","text":"PGPeripheralLockState"}],"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGPeripheral(py)lockState","symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/lockState","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"]]},"variants":[{"paths":["\/documentation\/connectsdk\/pgperipheral\/lockstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgperipheral\/lockstate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/lockState":{"abstract":[],"type":"topic","title":"lockState","url":"\/documentation\/connectsdk\/pgperipheral\/lockstate","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/lockState","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","text":"PGPeripheralLockState","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lockState"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheralLockState":{"type":"topic","abstract":[{"text":"The lock status of the scanner","type":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState","role":"symbol","kind":"symbol","url":"\/documentation\/connectsdk\/pgperipherallockstate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PGPeripheralLockState","kind":"identifier"}],"title":"PGPeripheralLockState","navigatorTitle":[{"text":"PGPeripheralLockState","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral","kind":"symbol","role":"symbol","title":"PGPeripheral","abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"text":"PGPeripheral","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGPeripheral"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"lockState","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"lockState"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PGPeripheralLockState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@E@PGPeripheralLockState","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheralLockState"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockState"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1lockState\/title","value":"lockState","op":"replace"},{"value":[{"text":"lockState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1lockState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/title","value":"PGPeripheralLockState"},{"op":"replace","value":[{"text":"PGPeripheralLockState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheralLockState\/fragments"},{"value":"PGPeripheral","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","op":"replace","value":[{"text":"PGPeripheral","kind":"identifier"}]}]}]}