{"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/requestDeviceInformation(withDeviceInfoCommand:completionHandler:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgperipheral\/requestdeviceinformation(withdeviceinfocommand:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgperipheral\/requestdeviceinformation(withdeviceinfocommand:completionhandler:)"]}],"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestDeviceInformation"},{"text":"(","kind":"text"},{"text":"withDeviceInfoCommand","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","kind":"typeIdentifier","text":"PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"PGDeviceInformation","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformation"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","title":"requestDeviceInformation(withDeviceInfoCommand:completionHandler:)","externalID":"c:@M@ConnectSDK@objc(cs)PGPeripheral(im)requestDeviceInformationWithDeviceInfoCommand:completionHandler:","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestDeviceInformation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withDeviceInfoCommand","kind":"externalParam"},{"kind":"text","text":" "},{"text":"deviceInfoRequest","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PGCommand","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","text":"PGDeviceInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformation"},{"kind":"text","text":"?, "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"symbol","role":"symbol","abstract":[{"text":"A PGCommand is used to send a command to a connected device through Connect SDK.","type":"text"}],"title":"PGCommand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGCommand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral/requestDeviceInformation(withDeviceInfoCommand:completionHandler:)":{"url":"\/documentation\/connectsdk\/pgperipheral\/requestdeviceinformation(withdeviceinfocommand:completionhandler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestDeviceInformation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDeviceInfoCommand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"PGDeviceInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGDeviceInformation"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral\/requestDeviceInformation(withDeviceInfoCommand:completionHandler:)","navigatorTitle":[{"text":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:","kind":"identifier"}],"role":"symbol","title":"requestDeviceInformation(withDeviceInfoCommand:completionHandler:)","kind":"symbol"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGDeviceInformation":{"abstract":[{"type":"text","text":"Model representing device information"}],"url":"\/documentation\/connectsdk\/pgdeviceinformation","navigatorTitle":[{"text":"PGDeviceInformation","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGDeviceInformation","role":"symbol","title":"PGDeviceInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGDeviceInformation","kind":"identifier"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"kind":"symbol","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"url":"\/documentation\/connectsdk","role":"collection","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","type":"topic"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPeripheral":{"abstract":[],"url":"\/documentation\/connectsdk\/pgperipheral","navigatorTitle":[{"kind":"identifier","text":"PGPeripheral"}],"title":"PGPeripheral","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGPeripheral","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPeripheral"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"requestDeviceInformationWithDeviceInfoCommand:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand","text":"PGCommand","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deviceInfoRequest"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@ConnectSDK@objc(cs)PGDeviceInformation#*$objc(cs)NSError)","text":"void (^)(PGDeviceInformation *, NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"PGCommand","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title"},{"value":[{"text":"PGCommand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments"},{"value":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1requestDeviceInformation(withDeviceInfoCommand:completionHandler:)\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral~1requestDeviceInformation(withDeviceInfoCommand:completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestDeviceInformationWithDeviceInfoCommand:completionHandler:"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/title","op":"replace","value":"PGDeviceInformation"},{"value":[{"text":"PGDeviceInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGDeviceInformation\/fragments"},{"value":"PGPeripheral","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPeripheral\/fragments","value":[{"kind":"identifier","text":"PGPeripheral"}]}]}]}