{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIndicator"},{"text":" ","kind":"text"},{"text":"indicator","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"indicator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The indicator to advertise with"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral"]]},"kind":"symbol","abstract":[{"text":"Advertise the Scanner with the given indicator, equivalent to scanning the pairing QR with the Scanner","type":"text"}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/advertise(withIndicator:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGMockPeripheral(im)advertiseWithIndicator:","modules":[{"name":"ConnectSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"advertise(withIndicator:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"advertise"},{"text":"(","kind":"text"},{"text":"withIndicator","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"advertiseWithIndicator:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgmockperipheral\/advertise(withindicator:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgmockperipheral\/advertise(withindicator:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral/advertise(withIndicator:)":{"abstract":[{"type":"text","text":"Advertise the Scanner with the given indicator, equivalent to scanning the pairing QR with the Scanner"}],"navigatorTitle":[{"text":"advertiseWithIndicator:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgmockperipheral\/advertise(withindicator:)","title":"advertise(withIndicator:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"advertise"},{"text":"(","kind":"text"},{"text":"withIndicator","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/advertise(withIndicator:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral":{"url":"\/documentation\/connectsdk\/pgmockperipheral","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGMockPeripheral","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGMockPeripheral"}],"title":"PGMockPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A mock peripheral for use in testing"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"advertiseWithIndicator:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"advertiseWithIndicator:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"advertiseWithIndicator:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"indicator","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1advertise(withIndicator:)\/title","value":"advertiseWithIndicator:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1advertise(withIndicator:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"advertiseWithIndicator:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/title","value":"PGMockPeripheral","op":"replace"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/fragments","value":[{"text":"PGMockPeripheral","kind":"identifier"}],"op":"replace"}]}]}