{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/advertisementData"},"variants":[{"paths":["\/documentation\/connectsdk\/pgmockperipheral\/advertisementdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgmockperipheral\/advertisementdata"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral"]]},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"advertisementData","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"advertisementData","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ConnectSDK@objc(cs)PGMockPeripheral(py)advertisementData","modules":[{"name":"ConnectSDK"}],"symbolKind":"property","roleHeading":"Instance Property","title":"advertisementData"},"abstract":[{"type":"text","text":"The advertisement data to use. A collection of keys and values"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"advertisementData","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] { get }"}],"languages":["swift"]}]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral":{"url":"\/documentation\/connectsdk\/pgmockperipheral","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PGMockPeripheral","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PGMockPeripheral"}],"title":"PGMockPeripheral","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A mock peripheral for use in testing"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral/advertisementData":{"abstract":[{"text":"The advertisement data to use. A collection of keys and values","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"advertisementData"}],"kind":"symbol","url":"\/documentation\/connectsdk\/pgmockperipheral\/advertisementdata","title":"advertisementData","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"advertisementData","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/advertisementData"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"advertisementData"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"advertisementData"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"advertisementData"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/title","op":"replace","value":"PGMockPeripheral"},{"value":[{"text":"PGMockPeripheral","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/fragments","op":"replace"},{"value":"advertisementData","op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1advertisementData\/title"},{"value":[{"text":"advertisementData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1advertisementData\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}