{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBarcode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"barcode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The barcode string to send"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/pgmockperipheral\/sendbarcode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/pgmockperipheral\/sendbarcode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/sendBarcode(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Send a barcode to the central"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBarcode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"sendBarcode(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ConnectSDK@objc(cs)PGMockPeripheral(im)sendBarcode:","modules":[{"name":"ConnectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sendBarcode:"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral/sendBarcode(_:)":{"role":"symbol","title":"sendBarcode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBarcode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Send a barcode to the central"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/sendBarcode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendBarcode:"}],"url":"\/documentation\/connectsdk\/pgmockperipheral\/sendbarcode(_:)"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral":{"role":"symbol","title":"PGMockPeripheral","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGMockPeripheral"}],"abstract":[{"type":"text","text":"A mock peripheral for use in testing"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGMockPeripheral"}],"url":"\/documentation\/connectsdk\/pgmockperipheral"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendBarcode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendBarcode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendBarcode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1sendBarcode(_:)\/title","value":"sendBarcode:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1sendBarcode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendBarcode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/title","value":"PGMockPeripheral"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/fragments","value":[{"kind":"identifier","text":"PGMockPeripheral"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}