{"kind":"symbol","identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/setBatteryLevel(batteryLevel:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Set the battery level of the Mock","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBatteryLevel"},{"kind":"text","text":"("},{"text":"batteryLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The battery level"}]}],"name":"batteryLevel"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setBatteryLevel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"batteryLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@objc(cs)PGMockPeripheral(im)setBatteryLevelWithBatteryLevel:","role":"symbol","title":"setBatteryLevel(batteryLevel:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setBatteryLevelWithBatteryLevel:"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/connectsdk\/pgmockperipheral\/setbatterylevel(batterylevel:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgmockperipheral\/setbatterylevel(batterylevel:)"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral"]]},"sections":[],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral/setBatteryLevel(batteryLevel:)":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral\/setBatteryLevel(batteryLevel:)","kind":"symbol","role":"symbol","title":"setBatteryLevel(batteryLevel:)","abstract":[{"type":"text","text":"Set the battery level of the Mock"}],"url":"\/documentation\/connectsdk\/pgmockperipheral\/setbatterylevel(batterylevel:)","navigatorTitle":[{"kind":"identifier","text":"setBatteryLevelWithBatteryLevel:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setBatteryLevel","kind":"identifier"},{"kind":"text","text":"("},{"text":"batteryLevel","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":")","kind":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","role":"collection","url":"\/documentation\/connectsdk","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}]},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGMockPeripheral":{"type":"topic","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGMockPeripheral","kind":"symbol","role":"symbol","title":"PGMockPeripheral","abstract":[{"text":"A mock peripheral for use in testing","type":"text"}],"url":"\/documentation\/connectsdk\/pgmockperipheral","navigatorTitle":[{"text":"PGMockPeripheral","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PGMockPeripheral"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setBatteryLevelWithBatteryLevel:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setBatteryLevelWithBatteryLevel:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setBatteryLevelWithBatteryLevel:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"batteryLevel"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1setBatteryLevel(batteryLevel:)\/title","value":"setBatteryLevelWithBatteryLevel:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBatteryLevelWithBatteryLevel:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral~1setBatteryLevel(batteryLevel:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/title","value":"PGMockPeripheral"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGMockPeripheral\/fragments","value":[{"text":"PGMockPeripheral","kind":"identifier"}]}]}]}