{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"PGPairingQRGeneratorApiError.invalidIndicatorLength","navigatorTitle":[{"text":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength","kind":"identifier"}],"externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorApiError@PGPairingQRGeneratorApiErrorInvalidIndicatorLength","symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"ConnectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidIndicatorLength"}]},"abstract":[{"text":"Invalid indicator length.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicatorLength"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidIndicatorLength","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicatorlength"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicatorlength"]}],"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError/invalidIndicatorLength":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicatorlength","role":"symbol","kind":"symbol","title":"PGPairingQRGeneratorApiError.invalidIndicatorLength","abstract":[{"type":"text","text":"Invalid indicator length."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidIndicatorLength","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicatorLength"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError","role":"symbol","title":"PGPairingQRGeneratorApiError","abstract":[{"text":"PG pairing barcode generator error codes","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorApiError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicatorLength\/title"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicatorLength\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicatorLength"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/title","value":"PGPairingQRGeneratorApiError"},{"value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/fragments"}]}]}