{"sections":[],"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicator"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidIndicator","kind":"identifier"}],"roleHeading":"Case","title":"PGPairingQRGeneratorApiError.invalidIndicator","modules":[{"name":"ConnectSDK"}],"externalID":"c:@M@ConnectSDK@E@PGPairingQRGeneratorApiError@PGPairingQRGeneratorApiErrorInvalidIndicator"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidIndicator","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invalid indicator length."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicator"]},{"paths":["\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError/invalidIndicator":{"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror\/invalidindicator","role":"symbol","kind":"symbol","title":"PGPairingQRGeneratorApiError.invalidIndicator","abstract":[{"text":"Invalid indicator length.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidIndicator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PGPairingQRGeneratorApiErrorInvalidIndicator","kind":"identifier"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError\/invalidIndicator"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPairingQRGeneratorApiError":{"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPairingQRGeneratorApiError","role":"symbol","title":"PGPairingQRGeneratorApiError","abstract":[{"text":"PG pairing barcode generator error codes","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PGPairingQRGeneratorApiError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPairingQRGeneratorApiError"}],"url":"\/documentation\/connectsdk\/pgpairingqrgeneratorapierror"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/connectsdk","identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","abstract":[{"type":"text","text":"The "},{"inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}],"type":"strong"},{"text":" is a software development kit that enables integration between your iOS apps and the ProGlove system.","type":"text"}],"title":"ConnectSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"PGPairingQRGeneratorApiErrorInvalidIndicator","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicator"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicator"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PGPairingQRGeneratorApiErrorInvalidIndicator","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicator\/title"},{"value":[{"kind":"identifier","text":"PGPairingQRGeneratorApiErrorInvalidIndicator"}],"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError~1invalidIndicator\/fragments"},{"path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/title","value":"PGPairingQRGeneratorApiError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPairingQRGeneratorApiError\/fragments","value":[{"text":"PGPairingQRGeneratorApiError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}